apache/incubator-kie-optaplanner

optaplanner-docs/src/main/docbook/en-US/Chapter-Benchmarking_and_tweaking/Chapter-Benchmarking_and_tweaking.xml
Geoffrey - could you review this first chapter to make sure that this is how you wanted the changes to titles to happen? Once confirmed, I will make the changes in the rest of the chapters and then send another pull request. I have:
* changed all titles to Titlecase, including chapter, sections and figures.
* Changed All Titles So Every Word Is Capitalized
=> Changed all titles to titlecase in Chapter Benchmarking and Tweaking

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/common/nearby/BetaDistributionNearbyRandom.java
see https://en.wikipedia.org/wiki/Beta_distribution
=> BetaDistribution: parameters alpha and beta need to be positive. 

optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/common/nearby/BetaDistributionNearbyRandomTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/common/nearby/BlockDistributionNearbyRandomTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/common/nearby/LinearDistributionNearbyRandomTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/common/nearby/ParabolicDistributionNearbyRandomTest.java
You may not going to like the cycle over all values which we want to pick.
=> DistributioTests: added corner cases, more tested values

optaplanner-docs/src/main/docbook/en-US/Chapter-Integration/Chapter-Integration.xml
As I promised - short instructions how to use OptaPlanner on the Android platform. Also I send you an email.
=> optaplanner on android doc

optaplanner-docs/src/main/docbook/en-US/Chapter-Quick_start/Chapter-Quick_start.xml
Partially complete review of this chapter with some changes made.
=> made some basic changes to Quick Start chapter. Not complete review.

optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoft/HardMediumSoftScore.java
Added "hard" to score to clarify when the medium score value is irrelevant.
=> Clarification in docs of getMediumScore()

optaplanner-docs/src/main/docbook/en-US/Chapter-Quick_start/Chapter-Quick_start.xml
Completed docs review of this chapter.
=> Completed QuickStart chapter review

optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/util/listeners/PhaseTestListener.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/integration/SolverConfigCombinationsTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nqueens/solver/tracking/NQueensConstructionHeuristicTrackingTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nqueens/solver/tracking/NQueensLocalSearchTrackingTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nqueens/solver/tracking/NQueensSolutionInitializer.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nqueens/solver/tracking/NQueensStepTracker.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nqueens/solver/tracking/NQueensTrackingTest.java
There is one commented test. Check it out please
=> Solver config combinations

optaplanner-webexamples/src/main/webapp/vehiclerouting/WEB-INF/beans.xml
Quick fix for PLANNER-302 on JBoss EAP
=> PLANNER-302-fix: Added beans.xml to enable CDI

optaplanner-core/src/main/java/org/optaplanner/core/api/domain/valuerange/ValueRangeFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/valuerange/buildin/biginteger/BigIntegerValueRange.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/valuerange/buildin/biginteger/BigIntegerValueRangeTest.java, optaplanner-docs/src/main/docbook/en-US/Chapter-Planner_configuration/Chapter-Planner_configuration.xml
Refactor:
* reordering the methods in `ValueRangeFactory` to match the docs order (seemed to make more sense than the order in `ValueRangeFactory` originally)
* small javadoc fix
=> PLANNER-360: BigIntegerValueRange

optaplanner-benchmark/src/main/resources/org/optaplanner/benchmark/impl/report/benchmarkReport.html.ftl
This should be more understandable and logical.
=> PLANNER-334: Fixed hiding of other badges when a benchmark fails

optaplanner-docs/src/main/docbook/en-US/Chapter-Planner_configuration/Chapter-Planner_configuration.xml
Conflicts:
optaplanner-docs/src/main/docbook/en-US/Chapter-Planner_configuration/Chapter-Planner_configuration.xml
=> Completed review of Chapter-Planner_configuration.xml

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/PlannerBenchmarkRunner.java
=> PLANNER-48: Code Style fix

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SolverBenchmarkResult.java, optaplanner-benchmark/src/main/resources/org/optaplanner/benchmark/impl/report/benchmarkReport.html.ftl
* Not quite sure on the wording of the pop-ups in the template
=> PLANNER-390: Added badges to solver configs

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/SingleBenchmarkRunner.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/aggregator/swingui/BenchmarkAggregatorFrame.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ranking/SingleBenchmarkRankingComparator.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ranking/TotalRankSolverRankingWeightFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ranking/TotalScoreSolverRankingComparator.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ranking/WorstScoreSolverRankingComparator.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SingleBenchmarkResult.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SolverBenchmarkResult.java, optaplanner-benchmark/src/main/resources/org/optaplanner/benchmark/impl/report/benchmarkReport.html.ftl, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/ranking/AbstractSolverRankingComparatorTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/ranking/TotalRankSolverRankingWeightFactoryTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/ranking/TotalScoreSolverRankingComparatorTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/ranking/WorstScoreSolverRankingComparatorTest.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/ScoreUtils.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/scope/DefaultSolverScope.java, optaplanner-docs/src/main/docbook/en-US/Chapter-Benchmarking_and_tweaking/Chapter-Benchmarking_and_tweaking.xml
* **NOTE**: Merge only after PLANNER-390 PR #119
=> PLANNER-391: Fixed ranking of solver configs with uninitialized solutions

pom.xml
=> Added modules to the maven-checkstyle-plugin

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SolverBenchmarkResult.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/ScoreUtils.java
=> Fixes uninitialized variable count averaging

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SolverBenchmarkResult.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/result/SolverBenchmarkResultTest.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/ScoreUtils.java
Round up, more is worse.
Sorry for creating 2 PRs, but I had this idea later and found it way better than the first one. Added a test as compensation.
=> Fixes uninitialized variable count averaging without floating point arithmetic

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/PlannerBenchmarkRunner.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SolverBenchmarkResult.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/bestsolutionmutation/BestSolutionMutationSingleStatistic.java, optaplanner-benchmark/src/main/resources/org/optaplanner/benchmark/impl/report/benchmarkReport.html.ftl, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/result/SolverBenchmarkResultTest.java, optaplanner-core/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/mutation/MutationCounter.java, optaplanner-core/src/test/java/org/optaplanner/core/config/util/ConfigUtilsTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nqueens/app/NQueensBenchmarkTest.java
(Mostly) 1 fix per commit. See commit messages.
**Merge only after** #141.
**Ready to merge after build passes.**
=> Small fixes

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SolverBenchmarkResult.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/result/SolverBenchmarkResultTest.java
=> SolverBenchmarkResult Correct failed singles handling in average score with uninitialized prefix

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/api/PlannerBenchmarkFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/FreemarkerXmlPlannerBenchmarkFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/PlannerBenchmarkRunner.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/SubSingleBenchmarkRunner.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/XStreamXmlPlannerBenchmarkFactory.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/api/PlannerBenchmarkFactoryTest.java, optaplanner-benchmark/src/test/resources/org/optaplanner/benchmark/api/classloaderTestdataPlannerBenchmarkConfig.xml, optaplanner-benchmark/src/test/resources/org/optaplanner/benchmark/api/testdataInputSolutionFile.xml, optaplanner-benchmark/src/test/resources/org/optaplanner/benchmark/api/testdataPlannerBenchmarkConfig.xml, optaplanner-core/src/test/java/org/optaplanner/core/api/solver/ClassLoaderTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/solver/SolverFactoryTest.java, optaplanner-core/src/test/resources/org/optaplanner/core/api/solver/classloaderTestdataSolverConfig.xml
* PLANNER-440: ClassLoader refactoring in benchmark
* *rebased, waiting to be finished*
* TODOs (still left):
* Why can't scoreDrl in classloader...Config.xml be prefixed with `diverted.../` prefix?
* Move these tests to `-examples` too?
* Add the Freemarker test
=> PLANNER-440: Unfinished

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/accessor/BeanPropertyMemberAccessor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/accessor/MethodMemberAccessor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java
getDeclaringClass() already includes "class" in the name, so it currently becomes "class class ClassName".
PlanningEntityCollection should be PlanningEntityCollectionProperty
=> Update exception messages

optaplanner-docs/src/main/docbook/en-US/Chapter-Score_calculation/Chapter-Score_calculation.xml
Fixes made for:
-apostrophe placements
-Removed extra ":"(colons)
-Spelled out single digit numbers
=> Made minor grammar fixes

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/SmallScalingOrderedSet.java
I benchmarked it at home, it really seems to be best option for now. I bet we will deiscuss it agian when there will be enabled duplicities in notifications
=> smallScaleOrderedSet with threshold 128

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/StatisticUtils.java
`DecimalFormat` replaces the dot with a comma
=> Fixed getStandardDeviationString for localized systems

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java
While doing research for PLANNER-356, i found out this one TODO that was easy enough to solve.
This PR removes fixes the TODO and also moves the list sorting out of the loop, since the list is never modified other than by removing the first item.
=> Small optimization in the SolutionDescriptor

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/valuerange/buildin/temporal/TemporalValueRange.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/valuerange/buildin/temporal/TemporalValueRangeTest.java
The `contains` method should be improved when possible.
=> Ticket #549 TemporalValueRange added with tests

optaplanner-benchmark/pom.xml, optaplanner-core/pom.xml, optaplanner-persistence/optaplanner-persistence-common/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml, optaplanner-persistence/optaplanner-persistence-xstream/pom.xml
Depends on:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/183
=> [DROOLS-1129] consistent OSGi Bundle-SymbolicName for all jars

pom.xml
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/207
=> kie-parent now brings all 3rd party deps

optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/AbstractPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolver.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/phase/PhaseLifecyleTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/util/PlannerTestUtils.java
I started learning to use [PIT](http://pitest.org/) for mutation testing. I picked the first line with missing code coverage and find a few bugs related to solver, phases and steps lifecycle. I have fixed the bugs and added code coverage.
=> Add code coverage for phase lifecycle and fix a few bugs

optaplanner-core/src/main/java/org/optaplanner/core/config/score/trend/InitializingScoreTrendLevel.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/node/comparator/BreadthFirstNodeComparator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/node/comparator/DepthFirstNodeComparator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/node/comparator/OptimisticBoundFirstNodeComparator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/node/comparator/OriginalOrderNodeComparator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/node/comparator/ScoreFirstNodeComparator.java, optaplanner-docs/src/main/docbook/en-US/Chapter-Exhaustive_search/Chapter-Exhaustive_search.xml
The picture was changed without updating the text description. This makes the description consistent. I also fixed a few typos in comments.
=> Update description of Branch And Bound example

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/report/BenchmarkReport.java, optaplanner-benchmark/src/main/resources/org/optaplanner/benchmark/impl/report/benchmarkReport.html.ftl
Score "calculation" count summary is used in the navigation button and in documentation.
=> Benchmark report consistency fix

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfig.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfigTest.java
I want to contribute a few tests that I created while exploring capabilities of Pitest (mutation testing tool).
=> Add test coverage for PlannerBenchmarkConfig

optaplanner-docs/src/main/asciidoc/Chapter-Optimization_algorithms/Chapter-Optimization_algorithms.adoc
Docs review of Chapter 6 - Optimization Algorithms.
=> Review optimization algorithms chapter

optaplanner-examples/src/main/resources/org/optaplanner/examples/nqueens/solver/nqueensSolverConfig.xml
Looked at this so many times its starting to bug me...
=> Trivial update to n-queens example

optaplanner-persistence/optaplanner-persistence-jpa/pom.xml
Please don't merge yet. All the IP BOM 7.0.0.CR5 PRs need to be merged together.
=> Upgrade JPA from 2.0 to 2.1 + Hibernate libs from 4.x to 5.x

optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendable/BendableScoreTest.java, optaplanner-docs/src/main/asciidoc/Chapter-Score_calculation/Chapter-Score_calculation.adoc
I found this a bit confusing, so added docs and a unit test that helped me to understand it.
Also included some other minor doc fixes.
=> Update documentation for BendableScore.

optaplanner-examples/src/main/java/org/optaplanner/examples/cheaptime/app/CheapTimeApp.java, optaplanner-examples/src/main/java/org/optaplanner/examples/cloudbalancing/optional/move/CloudComputerChangeMoveFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/cloudbalancing/optional/move/CloudProcessSwapMoveFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/persistence/StringDataGenerator.java, optaplanner-examples/src/main/java/org/optaplanner/examples/scrabble/domain/ScrabbleCell.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/app/TaskAssigningApp.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/domain/Affinity.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/domain/Task.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/domain/solver/TaskDifficultyComparator.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/persistence/TaskAssigningGenerator.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/swingui/TaskAssigningPanel.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/swingui/TaskOverviewPanel.java
Mostly to silence build-time noise, but some other simplifications.
=> Minor cleanups in examples.

optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoft/HardMediumSoftScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreHolder.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftbigdecimal/package-info.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftlong/HardMediumSoftLongScore.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreDefinition.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreHolderTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreDefinitionTest.java, optaplanner-docs/src/main/asciidoc/Chapter-Score_calculation/Chapter-Score_calculation.adoc, optaplanner-persistence/optaplanner-persistence-jackson/src/main/java/org/optaplanner/persistence/jackson/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreJacksonJsonDeserializer.java, optaplanner-persistence/optaplanner-persistence-jackson/src/test/java/org/optaplanner/persistence/jackson/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreJacksonJsonSerializerAndDeserializerTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/main/java/org/optaplanner/persistence/jaxb/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreJaxbXmlAdapter.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/main/java/org/optaplanner/persistence/jpa/impl/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreHibernateType.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/filtered-resources/META-INF/persistence.xml, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-xstream/src/main/java/org/optaplanner/persistence/xstream/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreXStreamConverter.java, optaplanner-persistence/optaplanner-persistence-xstream/src/test/java/org/optaplanner/persistence/xstream/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreXStreamConverterTest.java
See https://issues.jboss.org/browse/PLANNER-635
Broken into multiple commits to make review easier - will squash if required.
=> PLANNER-635 Implement HardMediumSoftBigDecimalScore

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenDroolsScoreDirector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenTestWriter.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenFactField.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenListValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenMapValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenSetValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueFact.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/operation/TestGenKieSessionDelete.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/operation/TestGenKieSessionFireAllRules.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/operation/TestGenKieSessionInsert.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/operation/TestGenKieSessionUpdate.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenTestWriterTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueFactTest.java, optaplanner-core/src/test/resources/org/optaplanner/core/impl/score/director/drools/testgen/TestGenWriterOutput.java
This should fix failing test on Windows as was pointed out in #251. On this occasion I added a test for TestGenTestWriter.
=> Add TestGenWriterTest, use LF line endings

optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenTestWriterTest.java, optaplanner-core/src/test/resources/org/optaplanner/core/impl/score/director/drools/testgen/TestGenWriterOutput.java
The test now passes on Windows.
=> PLANNER-726 Fix TestGenTestWriterTest for Windows

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ranking/SingleBenchmarkRankingComparator.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ranking/SubSingleBenchmarkRankingScoreComparator.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ranking/TotalRankSolverRankingWeightFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ranking/TotalScoreSolverRankingComparator.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SingleBenchmarkResult.java
This also contributes to removal of commons.lang3 (https://issues.jboss.org/browse/PLANNER-539)
=> PLANNER-609 Replace CompareToBuilder with Comparator in optaplanner-benchmark

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/SwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainReversingSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/TailChainSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/scope/PartitionChangeMove.java
Polishing a few inconsistencies related to https://issues.jboss.org/browse/PLANNER-731.
=> PLANNER-731 Clean-up

optaplanner-docs/src/main/asciidoc/Chapter-Planner_introduction/Chapter-Planner_introduction.adoc
Introduction modularization draft. Very little actual content change, mostly moving chunks of the content around to improve flow and structure.
=> Review optaplanner introduction

optaplanner-docs/src/main/asciidoc/Chapter-Planner_introduction/Chapter-Planner_introduction.adoc
Hi Geoffrey,
I didn't add this change to the previous pull request properly. Sorry!
=> Restructured section about Running Examples in an IDE for clarity.

optaplanner-persistence/optaplanner-persistence-jackson/pom.xml
It's the name of the library so it should start with a capital letter.
=> Capitalize Jackson name

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/DroolsScoreDirector.java
This will fail because of 
https://issues.jboss.org/browse/DROOLS-1368 - Resolved
https://issues.jboss.org/browse/DROOLS-1369
=> PLANNER-697 Enable property reactive on DroolsScoreDirector

optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhase.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseTest.java
The `threadPoolShutdown` test was based on the incorrect assumption that
all created threads are in `TERMINATED` state after `awaitTermination()`
successfully finishes.
Also improved PS thread pool termination. It is good idea to first wait
for PS solvers to terminate voluntarily. Thread pool's `shutdownNow()` is
used as a last resort.
=> Remove incorrect test and improve thread pool termination

optaplanner-core/src/build/revapi-config.json
Fixes build issues introduced in https://github.com/kiegroup/optaplanner/commit/5c38cf725485500a5240df41fcf125f5b25c3f0d
=> Include Solver.addProblemFactChanges in revapi config

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/src/build/revapi-config.json
Hi, @ge0ffrey,
same as #306, but for 7.0.x.
Marian
=> [7.0.x] Change revapi-config.json comment to be more general

optaplanner-benchmark/pom.xml, optaplanner-examples/pom.xml, optaplanner-persistence/optaplanner-persistence-common/pom.xml, optaplanner-persistence/optaplanner-persistence-jackson/pom.xml, optaplanner-persistence/optaplanner-persistence-jaxb/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml, optaplanner-persistence/optaplanner-persistence-xstream/pom.xml, optaplanner-test/pom.xml
Removed unused dependencies, adjusted some scopes from `compile` to `runtime`.
=> Clean up dependencies

optaplanner-integration/.gitignore, optaplanner-integration/optaplanner-core-gwt/.gitignore, optaplanner-integration/optaplanner-core-gwt/pom.xml, optaplanner-integration/optaplanner-core-gwt/src/main/module.gwt.xml, optaplanner-integration/pom.xml, pom.xml
Together with https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/444
=> PLANNER-807 optaplanner-core-gwt

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/src/build/revapi-config.json
Hi, @ge0ffrey,
same as #315, but for 7.0.x.
Marian
=> [7.0.x] Revapi: filter only public fields and getters/setters

optaplanner-benchmark/pom.xml, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/decider/LocalSearchDecider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/scope/LocalSearchMoveScope.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/scope/LocalSearchStepScope.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendable/BendableScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendablebigdecimal/BendableBigDecimalScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendablelong/BendableLongScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/AbstractAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/hillclimbing/HillClimbingAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/lateacceptance/LateAcceptanceAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/simulatedannealing/SimulatedAnnealingAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/stepcountinghillclimbing/StepCountingHillClimbingAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/tabu/EntityTabuAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/tabu/ValueTabuAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/forager/AcceptedForagerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/forager/finalist/StrategicOscillationByLevelFinalistPodiumTest.java, optaplanner-examples/pom.xml, optaplanner-persistence/optaplanner-persistence-common/pom.xml, optaplanner-persistence/optaplanner-persistence-jackson/pom.xml, optaplanner-persistence/optaplanner-persistence-jaxb/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml, optaplanner-persistence/optaplanner-persistence-xstream/pom.xml, optaplanner-test/pom.xml
I misunderstood the purpose of the 7.0.x branch so I made a few PRs that were actually meant for master. (I thought 7.0.x is for all 7.x releases and master will be inactive until the start of 8.x development.)
The included commits are from:
- #300 
- #297 
- #299
=> Forward port commits from 7.0.x

optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/kie/KieSolverAssemblerService.java, optaplanner-core/src/main/resources/META-INF/kie.conf
(cherry picked from commit 5ba1a2922522758db0d0726aabe9b1019a6e6f35)
=> [DROOLS-1649] ServiceRegistry refactor (#327)

optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/XStreamXmlSolverFactory.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/util/PlannerTestUtils.java, optaplanner-persistence/optaplanner-persistence-xstream/src/main/java/org/optaplanner/persistence/xstream/impl/domain/solution/XStreamSolutionFileIO.java
(cherry picked from commit ac94ded0deab40bf3f50be324feaa30dd6eee35e)
=> RHBRMS-2784 - XStream: DoS when unmarshalling void type (#328)

optaplanner-persistence/optaplanner-persistence-jpa/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/src/test/filtered-resources/META-INF/persistence.xml, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/AbstractScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/util/OptaplannerPersistenceUtil.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/resources/jndi.properties
Replace bitronix with narayana
Introduce new class contaning properties for optaplanner
persistence tests.
Depends on #https://github.com/kiegroup/drools/pull/1455
@baldimir
=> DROOLS-1692: Align optaplanner-peristence-jpa with Narayana

optaplanner-docs/src/main/asciidoc/BenchmarkingAndTweaking/BenchmarkingAndTweaking-chapter.adoc, optaplanner-docs/src/main/asciidoc/MoveAndNeighborhoodSelection/MoveAndNeighborhoodSelection-chapter.adoc, optaplanner-docs/src/main/asciidoc/ScoreCalculation/ScoreCalculation-chapter.adoc
These are 3 small fixes for errors I found mostly while copy&pasting code from the optaplanner-docs (which are really great, thanks for them!)
=> Small fixes for errors in optaplanner-doc

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/src/build/revapi-config.json
Hi, @psiroky,
see kiegroup/droolsjbpm-build-bootstrap#595 for more information.
=> Revapi checks against 7.0.0.Final now

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/report/BenchmarkReport.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/ProblemBenchmarkResult.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SubSingleBenchmarkResult.java, optaplanner-core/src/main/java/org/optaplanner/core/config/domain/ReflectionsWorkaroundClasspathHelper.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/chained/KOptMoveSelectorConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/solver/EnvironmentMode.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/mutation/MutationCounter.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/composite/CartesianProductMoveSelector.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/value/decorator/InitializedValueSelectorTest.java, optaplanner-examples/src/main/java/org/optaplanner/examples/cheaptime/domain/Machine.java, optaplanner-examples/src/main/java/org/optaplanner/examples/cheaptime/solver/score/CheapTimeIncrementalScoreCalculator.java, optaplanner-examples/src/main/java/org/optaplanner/examples/investment/domain/AssetClass.java, optaplanner-examples/src/main/java/org/optaplanner/examples/investment/domain/AssetClassAllocation.java, optaplanner-examples/src/main/java/org/optaplanner/examples/investment/domain/InvestmentParametrization.java, optaplanner-examples/src/main/java/org/optaplanner/examples/investment/domain/Region.java, optaplanner-examples/src/main/java/org/optaplanner/examples/investment/domain/Sector.java
(or the possessive form of "it")
=> Remove apostrophe from 's where the meaning is plural

optaplanner-core/src/test/resources/logback-test.xml, optaplanner-docs/src/main/asciidoc/LocalSearch/LocalSearch-chapter.adoc, optaplanner-examples/src/main/resources/logback.xml, optaplanner-examples/src/test/resources/logback-test.xml, optaplanner-persistence/optaplanner-persistence-common/src/test/resources/logback-test.xml, optaplanner-persistence/optaplanner-persistence-jackson/src/test/resources/logback-test.xml, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/resources/logback-test.xml, optaplanner-persistence/optaplanner-persistence-jpa/src/test/resources/logback-test.xml, optaplanner-persistence/optaplanner-persistence-xstream/src/test/resources/logback-test.xml
Actually, the word 'therefor' exists, but it has a different meaning: https://english.stackexchange.com/questions/58616/is-there-a-difference-between-therefor-and-therefore/58617#58617. Didn't know that...
=> Fix a few typos

optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/domain/ConferenceParametrization.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/domain/ConferenceSolution.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/domain/Room.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/domain/Speaker.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/domain/Talk.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/domain/Timeslot.java, optaplanner-examples/src/test/java/org/optaplanner/examples/conferencescheduling/solver/ConferenceSchedulingScoreHardConstraintTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/conferencescheduling/solver/ConferenceSchedulingScoreSoftConstraintTest.java
Unit tests for conference scheduling example rules.
=> conference scheduling: unit tests

optaplanner-docs/src/main/asciidoc/BenchmarkingAndTweaking/BenchmarkingAndTweaking-chapter.adoc, optaplanner-docs/src/main/asciidoc/ConstructionHeuristics/ConstructionHeuristics-chapter.adoc, optaplanner-docs/src/main/asciidoc/DesignPatterns/DesignPatterns-chapter.adoc, optaplanner-docs/src/main/asciidoc/LocalSearch/LocalSearch-chapter.adoc, optaplanner-docs/src/main/asciidoc/MoveAndNeighborhoodSelection/MoveAndNeighborhoodSelection-chapter.adoc, optaplanner-docs/src/main/asciidoc/OptimizationAlgorithms/OptimizationAlgorithms-chapter.adoc, optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc, optaplanner-docs/src/main/asciidoc/RepeatedPlanning/RepeatedPlanning-chapter.adoc, optaplanner-docs/src/main/asciidoc/ScoreCalculation/ScoreCalculation-chapter.adoc
Thank you for such a wonderful documentation!
=> Fix typos in the OptaPlanner user guide

optaplanner-webexamples/pom.xml
repeated effort of https://github.com/kiegroup/optaplanner/pull/369
=> RHDM-251 - wildfly 11 upgrade

README.adoc
@ge0ffrey @yurloc @Christopher-Chianelli @tiagobento Guys, this is the proposal of Definition of Done. Feel free to comment, hopefully we will have a version we can agree on till this week's meeting.
Thanks!
=> Introduce Definition of Done into readme

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/src/build/revapi-config.json
depends on kiegroup/droolsjbpm-build-bootstrap#775
See parent commit for more info.
=> Change revapi to check against 7.5.0.Final

optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc, optaplanner-docs/src/main/asciidoc/QuickStart/CloudBalancingDomainModel/CloudBalancingDomainModel-section.adoc
Documentation was badly formatted in sections 2.2.2.3 and 4.3.1 .
=> Made small fixes to documentation formatting.

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/nearby/NearEntityNearbyEntitySelector.java
=> Add logic to prevent arithmetic overflow of nearby entity count limit

optaplanner-examples/src/test/java/org/optaplanner/examples/vehiclerouting/app/VehicleRoutingMultiThreadedReproducibilityTest.java
@ge0ffrey (marking you here instead of requesting a review)
=> Mark VehicleRoutingMultiThreadedReproducibilityTest as a turtle test

optaplanner-core/src/main/java/org/optaplanner/core/api/score/AbstractScore.java, optaplanner-core/src/main/java/org/optaplanner/core/config/solver/SolverConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/solver/termination/TerminationConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/valuerange/descriptor/AbstractFromPropertyValueRangeDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/valuerange/descriptor/FromEntityPropertyValueRangeDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/PartitionSolver.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/AbstractSolver.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolver.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/termination/PhaseToSolverTerminationBridge.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendable/BendableScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendablelong/BendableLongScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardmediumsoft/HardMediumSoftScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardmediumsoftlong/HardMediumSoftLongScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardsoft/HardSoftScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardsoftdouble/HardSoftDoubleScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardsoftlong/HardSoftLongScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/simple/SimpleScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/simpledouble/SimpleDoubleScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/simplelong/SimpleLongScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/TestdataSleepingEntity.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/TestdataSolutionPartitioner.java, optaplanner-docs/src/main/asciidoc/OptimizationAlgorithms/OptimizationAlgorithms-chapter.adoc, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/persistence/ConferenceSchedulingXlsxFileIO.java, optaplanner-examples/src/main/java/org/optaplanner/examples/meetingscheduling/persistence/MeetingSchedulingXlsxFileIO.java, optaplanner-examples/src/test/java/org/optaplanner/examples/conferencescheduling/solver/ConferenceSchedulingScoreRulesXlsxTest.java
Docs coming soon, as well as support for 
`
<unimprovedScoreDifferenceThreshold>1hard/MIN_VALUEsoft</unimprovedScoreDifferenceThreshold>`
Tests coming soon too hopefully, the use of System.currentMillis() makes this a pain, but we need it...
=> Unimproved time millis spent score difference threshold termination

optaplanner-docs/src/main/asciidoc/UseCasesAndExamples/ExamplesOverview/ExamplesOverview-section.adoc
These are all the substantial changes made in Chapter 3 for GSG, actually. (There will also be modularization and download link changes; we need to work out conditioning before link changes can be anywhere close to upstream repo)
=> replaced competition with contest, slight rephrases around it

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenDroolsScoreDirector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueFact.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueFactTest.java
- supports LocalDate fields
- better exception messages
@yurloc changes from yesterday's debug session, please review
=> Make minor improvements to Drools test generator

optaplanner-examples/src/main/java/org/optaplanner/examples/rocktour/domain/RockTourParametrization.java, optaplanner-examples/src/main/java/org/optaplanner/examples/rocktour/domain/solver/RockShowVariableListener.java
@ge0ffrey comments to RockTour - please review and merge.
=> Add clarifying comments to RockTour example

optaplanner-benchmark/src/main/java/org/optaplanner/swing/impl/TangoColorFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/persistence/AbstractXlsxSolutionFileIO.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/persistence/ConferenceSchedulingXlsxFileIO.java
Color scheduled cells if they're different than published ones
=> PLANNER-1301-ColorPublishedTimeslot

optaplanner-docs/src/main/asciidoc/QuickStart/CloudBalancingBeyondThisTutorial/CloudBalancingBeyondThisTutorial-section.adoc, optaplanner-docs/src/main/asciidoc/QuickStart/CloudBalancingDomainModel/CloudBalancingDomainModel-section.adoc, optaplanner-docs/src/main/asciidoc/QuickStart/CloudBalancingSolverConfiguration/CloudBalancingSolverConfiguration-section.adoc
These changes are here for your review. This started from my chapter3 branch, but chapter2 changes are more extensive. I would very much appreciate if you could comment on the changes ASAP. The principal changes are:
* I added some explanation of the domain model, closing off places where I spent quite some time figuring things out and had to search the rest of the document.
* I added clear locations of files in the example structure we have. (This was from productized zip but I assume it's not changed from upstream structure).
* I explained that the config is part of the code. 
* I made some style changes
I think this needs more discussion before an upstream merge, so I marged the PR as "do not merge".
At this point I am creating, temporarily, an independent product version. But the …
=> chapter 2 changes

optaplanner-webexamples/pom.xml
Upgrate to Wildfly 14
@ge0ffrey Would you mind to review it?
* https://github.com/jboss-integration/jboss-integration-platform-bom/pull/427
* https://github.com/errai/errai/pull/363
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/843
* https://github.com/kiegroup/appformer/pull/483
* https://github.com/kiegroup/kie-wb-common/pull/2147
* https://github.com/kiegroup/jbpm/pull/1336
* https://github.com/kiegroup/jbpm-wb/pull/1206
* https://github.com/kiegroup/drools/pull/2086
* https://github.com/kiegroup/droolsjbpm-integration/pull/1583
* https://github.com/kiegroup/kie-wb-distributions/pull/821 
* https://github.com/kiegroup/kie-docs/pull/1108
*https://github.com/kiegroup/optaplanner/pull/437
*https://github.com/kiegroup/optaplanner-wb/pull/304
=> [AF-1555]: Upgraded WF11 to WF14

optaplanner-examples/src/main/java/org/optaplanner/examples/common/app/CommonApp.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/swingui/SolverAndPersistenceFrame.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/app/ConferenceSchedulingApp.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/persistence/ConferenceSchedulingCfpDevoxxImporter.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/swingui/ConferenceCFPImportAction.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/swingui/ConferenceSchedulingPanel.java
It's likely that other devoxx/voxxed conference will now try to import their cfp-devoxx instance.
These changes make that more user friendly to do that:
- import cfp button in toolbar, immediately visible before opening a file
- show "please wait" dialog while importing
It still doesn't just work for any random cfp-devoxx instance, but it does give a hint where find the code that hardcodes some Devoxx Belgium specific assumptions.
=> Conf scheduling devoxx: import improvements

optaplanner-persistence/optaplanner-persistence-jaxb/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml
PR set:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/900 (Please comment on this PR if you have any questions)
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/352
* https://github.com/kiegroup/drools/pull/2191
* https://github.com/kiegroup/jbpm/pull/1394
* https://github.com/kiegroup/optaplanner/pull/469
* https://github.com/kiegroup/droolsjbpm-integration/pull/1667
* https://github.com/kiegroup/appformer/pull/574
* https://github.com/kiegroup/optaplanner-wb/pull/319
* https://github.com/kiegroup/jbpm-wb/pull/1257
* https://github.com/kiegroup/kie-wb-distributions/pull/858
* https://github.com/kiegroup/optaweb-employee-rostering/pull/215
=> Align JAXB and JAXWS APIs with Wildfly

.travis.yml, travis-sonarcloud.sh
Based on `TRAVIS_EVENT_TYPE` environment variable, we supply additional parameter for either PR or master branch analysis.
=> Enable regular SonarCloud analysis for a master branch

optaplanner-benchmark/pom.xml, optaplanner-examples/pom.xml
Should fix test failures in the full downstream build. Please see https://github.com/kiegroup/jbpm-designer/pull/835 for more details.
=> Enable AWT headless mode to prevent test failures

optaplanner-core/src/main/java/org/optaplanner/core/config/constructionheuristic/ConstructionHeuristicPhaseConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/move/MoveSelectorConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/localsearch/LocalSearchPhaseConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/localsearch/decider/acceptor/AcceptorConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/solver/SolverConfig.java, optaplanner-examples/src/main/java/org/optaplanner/examples/cloudbalancing/persistence/CloudBalancingGenerator.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nqueens/app/NQueensHelloWorld.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nqueens/persistence/NQueensGenerator.java
These makes Graal experiments far less painful, because Graal doesn't like XStream.
=> Add with methods on the important Config classes

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/measurement/ScoreDifferencePercentage.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/Score.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/bendable/BendableScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/bendablebigdecimal/BendableBigDecimalScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/bendablelong/BendableLongScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoft/HardMediumSoftScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftlong/HardMediumSoftLongScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoft/HardSoftScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftdouble/HardSoftDoubleScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftlong/HardSoftLongScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/simple/SimpleScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/simplebigdecimal/SimpleBigDecimalScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/simpledouble/SimpleDoubleScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/simplelong/SimpleLongScore.java
https://en.wikipedia.org/wiki/Addition
=> Fix methematical terminology (addend)

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/chained/DefaultSubChainSelector.java
https://issues.jboss.org/browse/PLANNER-1347?_sscc=t
=> Fixing ArithmeticException

optaplanner-docs/src/main/asciidoc/PlannerIntroduction/DownloadAndRunTheExamples/DownloadAndRunTheExamples-section.adoc
Due to https://stackoverflow.com/questions/55717865/optaplanner-dependencies-via-gradle-within-intellij-idea
=> Gradle docs

optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/move/factory/MoveIteratorFactoryConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/move/factory/MoveListFactoryConfig.java, optaplanner-docs/src/main/asciidoc/MoveAndNeighborhoodSelection/MoveAndNeighborhoodSelection-chapter.adoc
@rsynek It's lacking a few simple unit tests currently. Would that be something that Ivan can take on?
=> PLANNER-1453 Custom properties for MoveList/IteratorFactory

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/StatisticUtils.java, optaplanner-examples/src/main/java/org/optaplanner/examples/coachshuttlegathering/domain/solver/TransportTimeToHubUpdatingVariableListener.java, optaplanner-examples/src/main/java/org/optaplanner/examples/flightcrewscheduling/persistence/FlightCrewSchedulingXlsxFileIO.java, optaplanner-examples/src/main/java/org/optaplanner/examples/travelingtournament/persistence/TravelingTournamentExporter.java, optaplanner-webexamples/src/main/java/org/optaplanner/webexamples/cloudbalancing/CloudBalancingWebAction.java, optaplanner-webexamples/src/main/webapp/cloudbalancing/solve.jsp, optaplanner-webexamples/src/main/webapp/cloudbalancing/terminateEarly.jsp, optaplanner-webexamples/src/main/webapp/vehiclerouting/index.jsp
Some issues fixed, some marked as false positives/won't fix on SonarCloud. This should bring us down to no major issues.
=> PLANNER-1540 Fix critical and major issues identified by SonarCloud

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenDateValueProvider.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenTestWriterTest.java
Addressing the leftovers from https://github.com/kiegroup/optaplanner/pull/518
=> Fix TestGenValueProvider and provide a unit test

pom.xml
Depends on https://github.com/kiegroup/kie-jenkins-scripts/pull/492 and https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/979
=> BAQE-1001 Unify reporting to SonarCloud under KIE parent

optaplanner-benchmark/src/build/revapi-config.json
depends on kiegroup/droolsjbpm-build-bootstrap#1002
=> BAQE-1039 - Change revapi to check against 7.23.0.Final

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/pillar/DefaultPillarSelector.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/entity/pillar/DefaultPillarSelectorTest.java
This PR brings an observed 25 - 50 % score calculation speed increase on Machine Reassignment and 2 - 5 % improvement on Cloud Balancing.
=> PLANNER-1565 Optimize subpillar selection

optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
Until [PLANNER-226](https://issues.jboss.org/browse/PLANNER-226) is not resolved, this warning could save a few minutes for others.
=> Add warning to docs about nullable chained variables

optaplanner-examples/src/main/java/org/optaplanner/examples/tsp/swingui/TspWorldPanel.java
Replaces #536 
The old code also used to react on middle button. (And that action was the same as right button.) In the interest of clarity, and because we do not know how middle buttons work on Mac, I have removed the middle button functionality.
The resulting code was tested on Linux. Left and right buttons' behavior remains unchanged.
=> PLANNER-1954 TSP example support for right-click emulation on Mac OS X

optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/solver/score/TaskAssigningConstraintProvider.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/taskassigning/benchmark/taskAssigningBenchmarkConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/taskassigning/benchmark/taskAssigningScoreDirectorBenchmarkConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/taskassigning/solver/taskAssigningSolverConfig.xml
The following results were achieved in a 5-minute run on `500tasks-20employees` with `FULL_ASSERT`:
- DRL score: 0hard/-49205soft/... with 15701 steps.
- Constraint streams score: 0hard/-48844soft/... with 33313 steps.
**Constraint streams appears to be a clear winner here.** However, I am leaving a couple comments in the code where **we could still improve the API** for even better results.
@ge0ffrey @rsynek Please review.
=> PLANNER-1595 Constraint stream implementation for Task Assignment

optaplanner-core/src/build/revapi-config.json
@ge0ffrey Please merge ASAP, we broke the build.
=> PLANNER-1597 Fix the build post-merge

optaplanner-docs/src/main/asciidoc/MoveAndNeighborhoodSelection/MoveAndNeighborhoodSelection-chapter.adoc
=> PLANNER-1599 Documentation for sequential subpillars

optaplanner-examples/src/main/java/org/optaplanner/examples/flightcrewscheduling/optional/score/FlightCrewSchedulingConstraintProvider.java, optaplanner-examples/src/main/java/org/optaplanner/examples/rocktour/optional/score/RockTourConstraintProvider.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/flightcrewscheduling/solver/flightCrewSchedulingSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/rocktour/solver/rockTourSolverConfig.xml
I ran this with assertion score director and the results are 1:1 equivalent. I did not run any benchmarks.
=> Add ConstraintProviders for Flight Crew Scheduling and Rock Tour

optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/entity/pillar/PillarSelectorConfig.java
Fix to the issue caught by internal test suite.
https://issues.jboss.org/browse/PLANNER-1665
=> PLANNER-1665 Fix backward incompatibility of pillar selector config

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/BavetConstraintSession.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/AbstractConstraintStreamTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/bi/BiConstraintStreamTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/tri/TriConstraintStreamTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/uni/UniConstraintStreamTest.java
@ge0ffrey Please squash when merging.
=> PLANNER-1668 Remove facts from the session properly

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/ConstraintCollectorsTest.java
This PR introduces some code sharing and a lot of test coverage.
=> PLANNER-1667 Add code coverage for more ConstraintCollectors

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/src/build/revapi-config.json
depends on kiegroup/droolsjbpm-build-bootstrap#1070
=> BAQE-1114 - Change revapi to check against 7.26.0.Final

optaplanner-benchmark/pom.xml, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/report/BenchmarkReport.java, optaplanner-examples/pom.xml, optaplanner-examples/src/main/java/org/optaplanner/examples/cheaptime/swingui/CheapTimePanel.java
Requires: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1077
=> Remove dependency to jcommon and fix code due to JFreeChart upgrade 

optaplanner-docs/src/main/asciidoc/LocalSearch/LocalSearch-chapter.adoc
Fixed links to Late Acceptance and Step Counting Hill Climbing which were broken
=> Fixed broken external links

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/report/BenchmarkReport.java
=> Add missing finite check for JFreeChart regression

optaplanner-docs/src/main/asciidoc/DesignPatterns/DesignPatterns-chapter.adoc
[Rendered draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-4653/#designPatterns)
[BXMSDOC-4653](https://issues.jboss.org/browse/BXMSDOC-4653)
Copy edited Design Patterns Introduction
`
=> BXMSDOC-4615 Optaplanner: Edit Design Patterns Introduction

optaplanner-persistence/optaplanner-persistence-jackson/src/test/java/org/optaplanner/persistence/jackson/api/OptaPlannerJacksonModuleTest.java
Recreated #573 with my comment resolved.
=> PLANNER-1704 Make OptaPlannerJacksonModuleTest more reliable

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/DroolsConstraint.java
Follow-up to https://github.com/kiegroup/drools/pull/2632
=> PLANNER-1689 Add Drools rule creation debugging

optaplanner-core/pom.xml, optaplanner-examples/pom.xml
@ge0ffrey Was easier than you would think. :-)
=> PLANNER-1703 Remove unused dependency on Guava

optaplanner-docs/src/main/asciidoc/LocalSearch/LocalSearch-chapter.adoc, optaplanner-docs/src/main/asciidoc/OptimizationAlgorithms/OptimizationAlgorithms-chapter.adoc
The main documentation for the Great Deluge algorithm.
=> Primary documentation for Great Deluge algorhitm

pom.xml
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1116
=> PLANNER-1716 Switch OptaPlanner to junit-vintage-engine

optaplanner-docs/src/main/asciidoc/BenchmarkingAndTweaking/letTheBestScoreStatisticGuideYou.svg, optaplanner-docs/src/main/asciidoc/DesignPatterns/DesignPatterns-chapter.adoc, optaplanner-docs/src/main/asciidoc/Development/Development-chapter.adoc, optaplanner-docs/src/main/asciidoc/DroolsScoreCalculation/DroolsScoreCalculation-chapter.adoc, optaplanner-docs/src/main/asciidoc/Integration/Integration-chapter.adoc, optaplanner-docs/src/main/asciidoc/LocalSearch/LocalSearch-chapter.adoc, optaplanner-docs/src/main/asciidoc/MoveAndNeighborhoodSelection/MoveAndNeighborhoodSelection-chapter.adoc, optaplanner-docs/src/main/asciidoc/OptimizationAlgorithms/OptimizationAlgorithms-chapter.adoc, optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc, optaplanner-docs/src/main/asciidoc/PlannerIntroduction/Governance/Governance-section.adoc, optaplanner-docs/src/main/asciidoc/QuickStart/CloudBalancingDomainModel/CloudBalancingDomainModel-section.adoc, optaplanner-docs/src/main/asciidoc/RepeatedPlanning/RepeatedPlanning-chapter.adoc, optaplanner-docs/src/main/asciidoc/ScoreCalculation/ScoreCalculation-chapter.adoc, optaplanner-docs/src/main/asciidoc/ShadowVariable/ShadowVariable-chapter.adoc, optaplanner-docs/src/main/asciidoc/UseCasesAndExamples/ConferenceScheduling/ConferenceScheduling-section.adoc, optaplanner-docs/src/main/asciidoc/UseCasesAndExamples/ProjectJobScheduling/ProjectJobScheduling-section.adoc, optaplanner-docs/src/main/asciidoc/UseCasesAndExamples/TaskAssigning/TaskAssigning-section.adoc
Hello people,
This is my first pull request to this repository and I am hoping to make more contributions in the near future.
This pull request fixes various typos and grammatical mistakes that exists in the project's docs.
It would be great if someone offers me feedback so I can make changes accordingly.
Thanks,
Jafer
=> Clean-up docs

optaplanner-docs/src/main/asciidoc/ConstraintStreams/ConstraintStreams-chapter.adoc
This is the first draft. Looking for your comments, @ge0ffrey @emmurphy1. (Others welcome too, of course.)
FYI I intentionally did not list every override of every function on every stream type. The docs are to be read by people, and these overrides read as well as a phonebook.
=> PLANNER-1712 Constraint Streams documentation

optaplanner-integration/pom.xml
Jira: https://issues.redhat.com/browse/PLANNER-1753
Merge with: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1147
=> [PLANNER-1753] Remove Spring Boot dependency management for kie-parent to manage

optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/decider/forager/finalist/StrategicOscillationByLevelFinalistPodium.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/forager/finalist/StrategicOscillationByLevelFinalistPodiumTest.java
@ge0ffrey, I took the liberty of refreshing Jordan's PR, adding a test and cleaning up the code. This is ready for review and merge now.
=> PLANNER-1219 Fix strategic oscillation bug

optaplanner-core/src/main/java/org/optaplanner/core/api/solver/event/SolverEventListener.java
Since Optaplanner 7.x+ requires `Java 8 or higher`
See https://www.optaplanner.org/download/releaseNotes/releaseNotes7.html
=> Added java.lang.FunctionalInterface

optaplanner-core/src/main/java/org/optaplanner/core/api/solver/SolverJob.java, optaplanner-core/src/main/java/org/optaplanner/core/api/solver/SolverManager.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverJob.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverManager.java
As Jiri pointed out. This solves this problem:
```
// Cat extends Animal
public Cat read(Long id) {...}
public void save(Object o) {...}
SolverManager<Long, Animal> solverManager;
solverManager.solve(1L, this::read, this::save); // Now compiles
```
=> SolverManager PECS (Producer Extends, Consumer Super)

optaplanner-docs/src/main/asciidoc/PlannerIntroduction/Requirements/Requirements-section.adoc
http://www.apache.org/foundation/license-faq.html#License
=> Fix Apache License name

optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java
As discussed with Radovan to increase test coverage upstream.
=> Spring Boot test that actually calls solve()

optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenTestWriter.java, optaplanner-core/src/test/resources/org/optaplanner/core/impl/score/director/drools/testgen/TestGenWriterOutput.java
https://github.com/kiegroup/droolsjbpm-integration/pull/1864
https://github.com/kiegroup/drools/pull/2636
https://github.com/kiegroup/openshift-drools-hacep/pull/68
https://github.com/kiegroup/kie-wb-playground/pull/78
https://github.com/kiegroup/droolsjbpm-knowledge/pull/397
=> [DROOLS-4092] Avoid using Drools' executable model

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java
A tiny little PR adding a useful feature.
Many of our collectors can actually be reimplemented using it, getting rid of some code duplication.
=> PLANNER-1832 Add generic ConstraintCollectors.sum()

optaplanner-docs/src/main/asciidoc/BenchmarkingAndTweaking/BenchmarkingAndTweaking-chapter.adoc, optaplanner-docs/src/main/asciidoc/Development/Development-chapter.adoc, optaplanner-docs/src/main/asciidoc/Integration/Integration-chapter.adoc, optaplanner-docs/src/main/asciidoc/MoveAndNeighborhoodSelection/MoveAndNeighborhoodSelection-chapter.adoc, optaplanner-docs/src/main/asciidoc/OptimizationAlgorithms/OptimizationAlgorithms-chapter.adoc, optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc, optaplanner-docs/src/main/asciidoc/QuickStart/CloudBalancingScoreConfiguration/CloudBalancingScoreConfiguration-section.adoc, optaplanner-docs/src/main/asciidoc/RepeatedPlanning/RepeatedPlanning-chapter.adoc, optaplanner-docs/src/main/asciidoc/ScoreCalculation/ScoreCalculation-chapter.adoc, optaplanner-docs/src/main/asciidoc/UseCasesAndExamples/NQueens/NQueens-section.adoc
All feedback welcome, but "Suggestion" github comments extra welcome (easier to apply :))
=> Solver manager docs

optaplanner-examples/src/main/java/org/optaplanner/examples/travelingtournament/optional/score/TravelingTournamentConstraintProvider.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/travelingtournament/solver/travelingTournamentScoreRules.drl, optaplanner-examples/src/main/resources/org/optaplanner/examples/travelingtournament/solver/travelingTournamentSolverConfig.xml
Verified correct with assertion score director.
Surprisingly, the performance of CS-D is significantly better than DRL.
=> PLANNER-1824 Add constraint provider for Traveling Tournament

optaplanner-core/src/test/java/org/optaplanner/core/api/solver/SolverManagerTest.java
This PR incorporates #665 + addresses a majority of review comments.
@michaltomco please go over the original comments from #665 and open a new PR to address the remaining ones of them.
=> PLANNER-1791 Add SolverManager tests

optaplanner-docs/src/main/asciidoc/ConstraintStreams/ConstraintStreams-chapter.adoc
I found two minor issues while going through the documentation and amended them.
=> docs: Address constraint streams doc issues

optaplanner-docs/pom.xml
https://issues.redhat.com/browse/PLANNER-1839
- kiegroup/droolsjbpm-build-bootstrap/pull/1192
- kiegroup/kie-docs/pull/2200 (optional)
- kiegroup/optaplanner/pull/696
- kiegroup/optaweb-employee-rostering/pull/395
- kiegroup/optaweb-vehicle-routing/pull/268
=> PLANNER-1839 Have Asciidoctor managed by kie-parent

optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java
Merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1196
https://github.com/kiegroup/jbpm-work-items/pull/124
https://github.com/kiegroup/optaweb-employee-rostering/pull/397
https://github.com/kiegroup/optaweb-vehicle-routing/pull/270
=> [7.33.x] RHPAM-2734: Fix for compatibility with Spring Boot 2.1

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/FieldAccessingSolutionCloner.java
Might be needed for Graal (Quarkus native mode). Performance enhancement in any case.
=> PLANNER-1883 default SolutionCloner should not reflect inside enums

optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenTestWriter.java, optaplanner-core/src/test/resources/org/optaplanner/core/impl/score/director/drools/testgen/TestGenWriterOutput.java
=> Revert [DROOLS-4092] 

optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverJob.java, optaplanner-core/src/test/java/org/optaplanner/core/api/solver/SolverManagerTest.java
https://issues.redhat.com/browse/PLANNER-1894
=> PLANNER-1894 SolverManager.terminateEarly() fix

optaplanner-docs/src/main/asciidoc/Integration/Integration-chapter.adoc, optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java, optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/SolverProperties.java, optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java
This allows to set daemon mode through application.properties or system
properties.
Example application.properties:
```
optaplanner.solver.daemon=true
```
=> PLANNER-1907 Add daemon to SolverProperties

optaplanner-distribution/pom.xml, optaplanner-docs/src/main/asciidoc/Integration/Integration-chapter.adoc, optaplanner-examples/pom.xml, optaplanner-persistence/optaplanner-persistence-jsonb/src/main/java/org/optaplanner/persistence/jsonb/api/score/AbstractScoreJsonbAdapter.java
Merge with: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1246
=> Add JSON-B integration to distribution and examples + integration docs

optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerProperties.java, optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/SolverManagerProperties.java, optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/SolverProperties.java, optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/TerminationProperties.java
https://issues.redhat.com/browse/PLANNER-1908
=> PLANNER-1908 Don't use Javadoc tags in Spring Boot configuration keys

optaplanner-persistence/optaplanner-persistence-jsonb/src/main/java/org/optaplanner/persistence/jsonb/api/OptaPlannerJsonbConfig.java
Jira: https://issues.redhat.com/browse/PLANNER-1922
=> [PLANNER-1922] Add getScoreJsonbAdapters() to OptaPlannerJsonbConfig class

README.adoc, ide-configuration/eclipse-format.xml, ide-configuration/eclipse.importorder, ide-configuration/ide-configuration.adoc, optaplanner-integration/pom.xml, optaplanner-persistence/pom.xml, pom.xml
This PR introduces the Quarkus code style into the OptaPlanner project. By default, the codebase is automatically formatted during a build. In a CI environment, a validation takes place instead.
=> PLANNER-1876 Create a code style for OptaPlanner project

optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java, optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/SolverProperties.java, optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java
Missing some tests that are available on the quarkus variant:
https://github.com/quarkusio/quarkus/pull/8667
Due to this problem:
https://stackoverflow.com/questions/61287244/applicationcontextrunner-for-testing-our-spring-boot-starter-is-there-a-way-to
=> Spring Boot: support constraints.drl

optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/domain/MrBalancePenalty.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/domain/MrLocation.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/domain/MrMachine.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/domain/MrMachineCapacity.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/domain/MrNeighborhood.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/domain/MrProcess.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/domain/MrProcessAssignment.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/domain/MrProcessRequirement.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/domain/MrResource.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/domain/MrService.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/domain/solver/MrServiceDependency.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/solver/score/MachineReassignmentConstraintProvider.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/machinereassignment/solver/machineReassignmentScoreRules.drl, optaplanner-examples/src/test/java/org/optaplanner/examples/machinereassignment/solver/score/MachineReassignmentConstraintProviderTest.java
Does NOT fully fix the CS provider - see the constraints throwing `UnsupportedOperationException`.
=> PLANNER-1953 Cover machine reassignment CSP by tests

optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/solver/score/MachineReassignmentConstraintProvider.java, optaplanner-examples/src/test/java/org/optaplanner/examples/machinereassignment/solver/score/MachineReassignmentConstraintProviderTest.java
I rewrote the test because it was testing at overcapacity. Also wanted to use the "different digits" trick so it was easier to follow what's going on. The test still failed after I refactored it, now it succeeds.
@rsynek I am not 100% sure that the refactored test counts as much as the previous one, please validate and point out if it's not :)
=> Fix balanceCost constraint

optaplanner-examples/src/test/java/org/optaplanner/examples/machinereassignment/solver/score/MachineReassignmentConstraintProviderTest.java, optaplanner-examples/src/test/resources/org/optaplanner/examples/machinereassignment/solver/score/model-a1-1-0hard-44306501soft.xml
Also removes insertion of unnecessary facts from the balanceCost tests.
=> Machine reassignment snapshot test

optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftdouble/HardSoftDoubleScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftdouble/HardSoftDoubleScoreHolder.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftdouble/package-info.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/simpledouble/SimpleDoubleScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/simpledouble/SimpleDoubleScoreHolder.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/simpledouble/package-info.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardsoftdouble/HardSoftDoubleScoreDefinition.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/simpledouble/SimpleDoubleScoreDefinition.java, optaplanner-docs/src/main/asciidoc/ScoreCalculation/ScoreCalculation-chapter.adoc, optaplanner-examples/pom.xml, optaplanner-persistence/optaplanner-persistence-jackson/src/main/java/org/optaplanner/persistence/jackson/api/score/buildin/hardsoftdouble/HardSoftDoubleScoreJacksonJsonDeserializer.java, optaplanner-persistence/optaplanner-persistence-jackson/src/main/java/org/optaplanner/persistence/jackson/api/score/buildin/hardsoftdouble/HardSoftDoubleScoreJacksonJsonSerializer.java, optaplanner-persistence/optaplanner-persistence-jackson/src/main/java/org/optaplanner/persistence/jackson/api/score/buildin/simpledouble/SimpleDoubleScoreJacksonJsonDeserializer.java, optaplanner-persistence/optaplanner-persistence-jackson/src/main/java/org/optaplanner/persistence/jackson/api/score/buildin/simpledouble/SimpleDoubleScoreJacksonJsonSerializer.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/main/java/org/optaplanner/persistence/jaxb/api/score/buildin/hardsoftdouble/HardSoftDoubleScoreJaxbXmlAdapter.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/main/java/org/optaplanner/persistence/jaxb/api/score/buildin/simpledouble/SimpleDoubleScoreJaxbXmlAdapter.java, optaplanner-persistence/optaplanner-persistence-jpa/src/main/java/org/optaplanner/persistence/jpa/impl/score/buildin/hardsoftdouble/HardSoftDoubleScoreHibernateType.java, optaplanner-persistence/optaplanner-persistence-jpa/src/main/java/org/optaplanner/persistence/jpa/impl/score/buildin/simpledouble/SimpleDoubleScoreHibernateType.java, optaplanner-persistence/optaplanner-persistence-jsonb/src/main/java/org/optaplanner/persistence/jsonb/api/score/buildin/hardsoftdouble/HardSoftDoubleScoreJsonbAdapter.java, optaplanner-persistence/optaplanner-persistence-jsonb/src/main/java/org/optaplanner/persistence/jsonb/api/score/buildin/simpledouble/SimpleDoubleScoreJsonbAdapter.java, optaplanner-persistence/optaplanner-persistence-xstream/src/main/java/org/optaplanner/persistence/xstream/api/score/buildin/hardsoftdouble/HardSoftDoubleScoreXStreamConverter.java, optaplanner-persistence/optaplanner-persistence-xstream/src/main/java/org/optaplanner/persistence/xstream/api/score/buildin/simpledouble/SimpleDoubleScoreXStreamConverter.java
Also see https://github.com/kiegroup/optaplanner-website/pull/232
=> PLANNER-1579 Deprecate double-based score types

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/constraintweight/descriptor/ConstraintConfigurationDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/constraintweight/descriptor/ConstraintWeightDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/entity/descriptor/EntityDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/BavetConstraintFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/DroolsConstraintFactory.java
Relates to https://stackoverflow.com/questions/61572757/optaplanner-throws-nullpointerexception-while-building-solver
=> Class.getPackage() might return null

optaplanner-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java
Relates to
https://stackoverflow.com/questions/61761407/optaplanner-caused-by-java-lang-illegalstateexception-no-classes-found (question got deleted but the feedback was valid...)
=> Spring Boot starter: improve error messages around class scanning

optaplanner-docs/src/main/asciidoc/UseCasesAndExamples/ExamplesOverview/ExamplesOverview-section.adoc, optaplanner-docs/src/main/asciidoc/UseCasesAndExamples/NurseRostering/NurseRostering-section.adoc
https://www.kuleuven-kulak.be/nrpcompetition - outdated
To define example of rostering problem there was
a reference to kuleuven-kulak.be resource that now returns 503 Service unavailable.
However they do have an academic paper with the
full description of the competition in 2010.
=> Change 2 broken links to Rostering competition

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/ConstraintCollectorsTest.java
Response to a SO question.
Brings the API back in line with what the docs say.
=> PLANNER-1984 Add no-arg countDistinct() constraint collector

.github/workflows/jpa_integration_ci.yml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml
Jira: https://issues.redhat.com/browse/PLANNER-1979
=> Add JPA Persistence CI workflow

optaplanner-persistence/optaplanner-persistence-jpa/pom.xml
Merge with: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1350
=> Let postgresql version be managed by kie-parent

optaplanner-examples/src/main/java/org/optaplanner/examples/examination/domain/ExaminationConstraintConfiguration.java, optaplanner-examples/src/main/java/org/optaplanner/examples/examination/domain/FollowingExam.java, optaplanner-examples/src/main/java/org/optaplanner/examples/examination/domain/LeadingExam.java, optaplanner-examples/src/main/java/org/optaplanner/examples/examination/domain/Period.java, optaplanner-examples/src/main/java/org/optaplanner/examples/examination/domain/PeriodPenalty.java, optaplanner-examples/src/main/java/org/optaplanner/examples/examination/domain/Room.java, optaplanner-examples/src/main/java/org/optaplanner/examples/examination/domain/RoomPenalty.java, optaplanner-examples/src/main/java/org/optaplanner/examples/examination/domain/Student.java, optaplanner-examples/src/main/java/org/optaplanner/examples/examination/domain/Topic.java, optaplanner-examples/src/main/java/org/optaplanner/examples/examination/solver/score/ExaminationConstraintProvider.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/examination/solver/examinationConstraints.drl, optaplanner-examples/src/main/resources/org/optaplanner/examples/examination/solver/examinationSolverConfig.xml, optaplanner-examples/src/test/java/org/optaplanner/examples/examination/solver/score/ExaminationConstraintProviderTest.java
Add a constraint stream provider for the Examination example.
=> PLANNER-1819 Add Examination CSProvider

.github/workflows/jpa_integration_ci.yml, .github/workflows/os_java_ci.yml
Should fix the connection reset issues with transferring dependencies.
=> Fix issues with artifact transfer in CI

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java
OptaPlannerProcessor - orElse approach for solverConfigXML
Port of https://github.com/quarkusio/quarkus/pull/9574#issuecomment-645404725
`Repeated condition` removal was already fixed by @ge0ffrey in https://github.com/kiegroup/optaplanner/commit/3d445020f8e058ca73be395bbcb8c3a18768f54e#diff-b73e4fc58d0c81c2375ba2e5463a7125
=> OptaPlannerProcessor - orElse approach for solverConfigXML

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bi/CompositeBiJoiner.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bi/SingleBiJoiner.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/common/AbstractJoiner.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/penta/CompositePentaJoiner.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/penta/SinglePentaJoiner.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/quad/CompositeQuadJoiner.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/quad/SingleQuadJoiner.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/tri/CompositeTriJoiner.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/tri/SingleTriJoiner.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/JoinersTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/stream/bi/AbstractBiJoinerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/stream/penta/AbstractPentaJoinerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/stream/quad/AbstractQuadJoinerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/stream/tri/AbstractTriJoinerTest.java, optaplanner-examples/src/main/java/org/optaplanner/examples/examination/solver/score/ExaminationConstraintProvider.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/solver/score/MachineReassignmentConstraintProvider.java, optaplanner-examples/src/main/java/org/optaplanner/examples/scrabble/optional/score/ScrabbleConstraintProvider.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/examination/solver/examinationConstraints.drl
Minor improvements in index performance. Also re-implements parts of the constraint provider to do the same thing as DRL does.
This speeds up Examination from 6 to ~140. So still bad, but not apocalyptic anymore.
=> PLANNER-2011 Somewhat improve Examination Constraint Provider performance

optaplanner-docs/src/main/asciidoc/QuickStart/SpringBoot/SpringBootQuickStart-chapter.adoc
=> Fix import in docs for ProblemFactCollectionProperty that still uses drools

pom.xml
@yurloc thanks for spotting this.
=> Replace deprecated maven properties

optaplanner-quickstarts/quarkus-school-timetabling/build.gradle, optaplanner-quickstarts/quarkus-school-timetabling/pom.xml, optaplanner-quickstarts/spring-boot-school-timetabling/build.gradle, optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml, pom.xml
This reverts commit 092b2cf5af8327319ad435d3388c9edfad398212.
=> Revert "upgraded to 7.41.0-SNAPSHOT"

optaplanner-examples/src/main/java/org/optaplanner/examples/meetingscheduling/app/MeetingSchedulingApp.java, optaplanner-examples/src/main/java/org/optaplanner/examples/meetingscheduling/domain/MeetingAssignment.java, optaplanner-examples/src/main/java/org/optaplanner/examples/meetingscheduling/optional/score/MeetingSchedulingConstraintProvider.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/meetingscheduling/solver/meetingSchedulingSolverConfig.xml, optaplanner-examples/src/test/java/org/optaplanner/examples/meetingscheduling/optional/score/MeetingSchedulingConstraintProviderTest.java
Jira: https://issues.redhat.com/browse/PLANNER-1820
=> WIP: Convert MeetingScheduling example to ConstraintStreams

.github/workflows/jpa_integration_ci.yml, .github/workflows/os_java_ci.yml, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/loader/InstanceProblemProvider.java
Tested with the benchmark aggregator on VRP benchmark config.
=> PLANNER-2061 Remove solution and a cloner from benchmark results

optaplanner-benchmark/pom.xml, optaplanner-build-parent/pom.xml, optaplanner-core/pom.xml, optaplanner-persistence/optaplanner-persistence-jaxb/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/pom.xml
- switches to jakarta.xml.bind:jakarta.xml.bind-api
- ecxludes any dependency that brings duplicate classes (ban-duplicated-classes enforce check must pass)
=> PLANNER-2034 Use jakarta EE API for JAXB

optaplanner-quickstarts/quarkus-school-timetabling/pom.xml, optaplanner-quickstarts/quarkus-school-timetabling/src/main/java/org/acme/schooltimetabling/domain/Lesson.java, optaplanner-quickstarts/quarkus-school-timetabling/src/main/java/org/acme/schooltimetabling/domain/Room.java, optaplanner-quickstarts/quarkus-school-timetabling/src/main/java/org/acme/schooltimetabling/domain/Timeslot.java, optaplanner-quickstarts/quarkus-school-timetabling/src/main/java/org/acme/schooltimetabling/solver/TimeTableConstraintProvider.java, optaplanner-quickstarts/quarkus-school-timetabling/src/test/java/org/acme/schooltimetabling/solver/TimeTableConstraintProviderTest.java, optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml, optaplanner-quickstarts/spring-boot-school-timetabling/src/main/java/com/example/schooltimetabling/domain/Lesson.java, optaplanner-quickstarts/spring-boot-school-timetabling/src/main/java/com/example/schooltimetabling/domain/Room.java, optaplanner-quickstarts/spring-boot-school-timetabling/src/main/java/com/example/schooltimetabling/domain/Timeslot.java, optaplanner-quickstarts/spring-boot-school-timetabling/src/main/java/com/example/schooltimetabling/solver/TimeTableConstraintProvider.java, optaplanner-quickstarts/spring-boot-school-timetabling/src/test/java/com/example/schooltimetabling/solver/TimeTableConstraintProviderTest.java
Identical domains for both quickstarts = identical constraint provider tests.
Essentially, this is one code twice. Perfect code duplication.
=> PLANNER-1950 ConstraintProvider tests for School Timetabling quickstarts

optaplanner-core/src/main/java/org/optaplanner/core/impl/io/jaxb/JaxbIO.java
Fixes a security vulnerability found by SonarCloud, see:
https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A4-XML_External_Entities_(XXE)
=> Secure XML transformation against XXE

optaplanner-core/src/main/java/org/optaplanner/core/impl/io/jaxb/JaxbIO.java
- suppress the XXE vulnerability as a false-positive issue (see the comment in the src file)
- avoid using generic exceptions
=> Resolve issues reported by SonarCloud

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/nearby/NearEntityNearbyEntitySelector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/nearby/NearEntityNearbyValueSelector.java
I'm adding a fail-fast and some comments to explain why the code - although it looks weird - actually works as intended.
=> PLANNER-496 Ensure that nearby selection code is correct

.github/workflows/quarkus-snapshot-readme.md, .github/workflows/quarkus-snapshot.yaml
**JIRA**: 
[PLANNER-2112](https://issues.redhat.com/browse/PLANNER-2112)
https://github.com/quarkusio/quarkus-ecosystem-ci/pull/17
**How to retest or run**:
* a pull request please add comment: regex **[.\*[j|J]enkins,?.\*(retest|test) this.\*]**
* a full downstream build please add comment: regex **[.*\[j|J]enkins,?.\*(execute|run|trigger|start|do) fdb.\*]**
* a compile downstream build please  add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) cdb.\*]**
* a full production downstream please add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) product fdb.\*]**
* an upstream build please add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) upstream.\*]**
i.e for running a full downstream build = …
=> PLANNER-2112 Automate testing with Quarkus snapshots

optaplanner-build-parent/pom.xml
https://github.com/kiegroup/optaplanner-quickstarts/pull/2
<details>
<summary>
</summary>
</details>
=> Upgrade Quarkus to 1.8.0.Final

optaplanner-docs/src/main/asciidoc/RepeatedPlanning/RepeatedPlanning-chapter.adoc
Applying doc review comments that were left out of #913.
=> Apply Emily's comments

Jenkinsfile.deploy
https://issues.redhat.com/browse/PLANNER-2128
https://github.com/kiegroup/kogito-pipelines/pull/58
<details>
<summary>
</summary>
</details>
=> PLANNER-2128 Create Jenkins deploy pipeline

.github/pull_request_template.md
https://issues.redhat.com/browse/BXMSPROD-1003
https://github.com/kiegroup/lienzo-core/pull/132
https://github.com/kiegroup/lienzo-tests/pull/107
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1470
https://github.com/kiegroup/appformer/pull/1052
https://github.com/kiegroup/droolsjbpm-knowledge/pull/463
https://github.com/kiegroup/drools/pull/3109
https://github.com/kiegroup/optaplanner/pull/933
https://github.com/kiegroup/jbpm/pull/1756
https://github.com/kiegroup/kie-jpmml-integration/pull/42
https://github.com/kiegroup/droolsjbpm-integration/pull/2240
https://github.com/kiegroup/openshift-drools-hacep/pull/99
https://github.com/kiegroup/kie-uberfire-extensions/pull/105
https://github.com/kiegroup/kie-wb-playground/pull/96
https://github.com/kiegroup/kie-wb-common/pull/3422 …
=> BXMSPROD-1003 add details section to pull request template

optaplanner-benchmark/pom.xml, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/io/PlannerBenchmarkConfigIO.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/api/PlannerBenchmarkFactoryTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfigTest.java, optaplanner-benchmark/src/test/resources/org/optaplanner/benchmark/api/invalidBenchmarkConfig.xml, optaplanner-benchmark/src/test/resources/org/optaplanner/benchmark/config/testBenchmarkConfigWithNamespace.xml, optaplanner-benchmark/src/test/resources/org/optaplanner/benchmark/config/testBenchmarkConfigWithoutNamespace.xml, optaplanner-benchmark/src/test/resources/org/optaplanner/benchmark/impl/result/testPlannerBenchmarkResult.xml, optaplanner-core/src/main/java/org/optaplanner/core/config/solver/SolverConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/io/jaxb/GenericJaxbIO.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/io/jaxb/SolverConfigIO.java, optaplanner-core/src/main/resources/org/optaplanner/core/impl/io/jaxb/removeNamespaces.xslt, optaplanner-core/src/test/java/org/optaplanner/core/api/solver/SolverFactoryTest.java, optaplanner-core/src/test/java/org/optaplanner/core/config/solver/SolverConfigTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/io/jaxb/GenericJaxbIOTest.java, optaplanner-core/src/test/resources/org/optaplanner/core/api/solver/invalidSolverConfig.xml, optaplanner-core/src/test/resources/org/optaplanner/core/config/solver/testSolverConfigWithNamespace.xml, optaplanner-core/src/test/resources/org/optaplanner/core/config/solver/testSolverConfigWithoutNamespace.xml, optaplanner-docs/src/main/asciidoc/BenchmarkingAndTweaking/BenchmarkingAndTweaking-chapter.adoc, optaplanner-docs/src/main/asciidoc/ConstraintStreams/ConstraintStreams-chapter.adoc, optaplanner-docs/src/main/asciidoc/ExhaustiveSearch/ExhaustiveSearch-chapter.adoc, optaplanner-docs/src/main/asciidoc/LocalSearch/LocalSearch-chapter.adoc, optaplanner-docs/src/main/asciidoc/OptimizationAlgorithms/OptimizationAlgorithms-chapter.adoc, optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc, optaplanner-docs/src/main/asciidoc/QuickStart/PlainJava/CloudBalancingSolverConfiguration/CloudBalancingSolverConfiguration-section.adoc, optaplanner-docs/src/main/asciidoc/RepeatedPlanning/RepeatedPlanning-chapter.adoc
https://issues.redhat.com/browse/PLANNER-2143
https://github.com/kiegroup/optaplanner-website/pull/280
TODO: documentation, upgrade recipe and release notes to wrap up the entire XSD work.
<details>
<summary>
</summary>
</details>
=> PLANNER-2143 Validate config XML with a namespace

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/solver/drools/functions/LoadBalanceByCountAccumulateFunction.java, optaplanner-examples/src/main/java/org/optaplanner/examples/tennis/app/TennisApp.java, optaplanner-examples/src/main/java/org/optaplanner/examples/tennis/optional/score/TennisConstraintProvider.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/tennis/solver/tennisSolverConfig.xml, optaplanner-examples/src/test/java/org/optaplanner/examples/tennis/optional/score/TennisConstraintProviderTest.java
`FULL_ASSERT` against score DRL passed.
=> PLANNER-1830 Add Constraint Provider for Tennis example

optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/domain/Room.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/domain/Talk.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/domain/Timeslot.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/optional/score/ConferenceSchedulingConstraintProvider.java, optaplanner-examples/src/test/java/org/optaplanner/examples/conferencescheduling/optional/score/ConferenceSchedulingConstraintProviderTest.java
`FULL_ASSERT` against score DRL passes.
=> PLANNER-1817 Finish the Conference Scheduling constraint provider

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-build-parent/pom.xml, optaplanner-core/src/build/revapi-config.json
https://issues.redhat.com/browse/PLANNER-2186
<details>
<summary>
</summary>
</details>
=> PLANNER-2186 Exclude dependencies from revapi check

optaplanner-build-parent/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/runtime/graal/MvelSubstitutions.java
Related Pr:
https://github.com/kiegroup/optaplanner-quickstarts/pull/7
=> PLANNER-2171 Fix reflection native warning + fix mvel subs issue + upgrade to quarkus 1.8.1

optaplanner-core/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/InnerConstraintFactory.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptorTest.java
=> PLANNER-2181 Encapsulate reflection operations in SolutionDescriptor

Jenkinsfile
https://issues.redhat.com/browse/PLANNER-2194
<details>
<summary>
</summary>
</details>
=> PLANNER-2194 Create a pipeline for building PRs

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/DotNames.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/OptaPlannerBeanProvider.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/runtime/graal/MvelSubstitutions.java, optaplanner-quarkus-integration/pom.xml, optaplanner-quickstarts/quarkus-school-timetabling/build.gradle, optaplanner-quickstarts/quarkus-school-timetabling/pom.xml
quarkus:dev is still broken, but I need to get this part merged in order to isolate the remaining issue easily and replicate with the quarkus team.
=> [7.x] PLANNER-2171 avoid reflection warnings + fix mvel native + upgrade to quarkus 1.8.2

optaplanner-build-parent/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java
Related https://github.com/kiegroup/optaplanner-quickstarts/pull/11
=> Upgrade to Quarkus 1.8.2.Final

.github/workflows/pull_request.yml
* https://github.com/kiegroup/optaplanner/pull/961
<details>
<summary>
</summary>
</details>
=> Install takari to pull request build flow

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/src/build/revapi-config.json, optaplanner-persistence/optaplanner-persistence-jpa/src/build/revapi-config.json, optaplanner-test/src/build/revapi-config.json
**Thank you for submitting this pull request**
**JIRA**: [BAQE-1567](https://issues.redhat.com/browse/BAQE-1567)
depends on kiegroup/droolsjbpm-build-bootstrap#1485
=> BAQE-1567 - Change revapi to check against 7.44.0.Final

optaplanner-build-parent/pom.xml
Related: https://github.com/kiegroup/optaplanner-quickstarts/pull/16
=> Upgrade Quarkus to 1.9.0.Final

optaplanner-docs/src/main/asciidoc/QuickStart/SpringBoot/SpringBootQuickStart-chapter.adoc
Loose end from changes on the quickstarts some time ago.
=> Spring Quickstart structure changes

pom.xml
Corresponds with https://issues.redhat.com/browse/PLANNER-2142
<details>
<summary>
</summary>
</details>
=> PLANNER-2142 Add distributionManagement

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1025
* https://github.com/kiegroup/lienzo-core/pull/135
* https://github.com/kiegroup/lienzo-tests/pull/110
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1489
* https://github.com/kiegroup/kie-soup/pull/160
* https://github.com/kiegroup/appformer/pull/1063
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/478
* https://github.com/kiegroup/drools/pull/3177
* https://github.com/kiegroup/optaplanner/pull/978
* https://github.com/kiegroup/jbpm/pull/1783
* https://github.com/kiegroup/kie-jpmml-integration/pull/45
* https://github.com/kiegroup/droolsjbpm-integration/pull/2290
* https://github.com/kiegroup/openshift-drools-hacep/pull/101
* https://github.com/kiegroup/droolsjbpm-tools/pull/121
* …
=> BXMSPROD-1025 pull request configuration centralized

optaplanner-build-parent/pom.xml
None.
None. 
<details>
<summary>
</summary>
</details>
=> Remove duplicate declaration of versions-maven-plugin

optaplanner-examples/src/main/java/org/optaplanner/examples/vehiclerouting/domain/location/segmented/RoadSegmentLocation.java
Currently, This project has **+9K** of warnings and code smells.
<a href="https://ibb.co/NpRxdTN"><img src="https://i.ibb.co/Dkd4HrM/image.png" alt="image" border="0"></a>
I'm starting to work on those warnings, If acceptable, and waiting for your review to start.
<details>
<summary>
</summary>
</details>
=> Removing casting

build/optaplanner-build-parent/pom.xml
@Christopher-Chianelli when doing refactors like this, it's recommended to also do a "find in path" search (ctrl-shift-f in intellij) for the removed property (or method name, class name or field name).
=> Clean up for format.directory property

optaplanner-examples/src/test/java/org/optaplanner/examples/coachshuttlegathering/app/CoachShuttleGatheringPerformanceTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/curriculumcourse/app/CurriculumCoursePerformanceTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/dinnerparty/app/DinnerPartyPerformanceTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/investment/app/InvestmentPerformanceTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nqueens/app/NQueensBenchmarkTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/tennis/app/TennisBenchmarkTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/tennis/app/TennisPerformanceTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/travelingtournament/app/TravelingTournamentPerformanceTest.java
Merge after this is merged: https://github.com/kiegroup/kogito-runtimes/pull/858
Before then, this PR will be red.
=> PLANNER-2213 Adjust disabled tests according to latest developments in Drools

.gitignore, build/optaplanner-build-parent/pom.xml, optaplanner-distribution/src/main/assembly/assembly-optaplanner.xml, optaplanner-distribution/src/main/assembly/scripts/runExamples.bat, optaplanner-distribution/src/main/assembly/scripts/runExamples.sh, optaplanner-examples/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/pom.xml, pom.xml
Cherry picks both PR's (normally not done, but I had to merge the first one early to unblock Lukas)
=> [8.0.x] PLANNER-2226 PR + remove kogito-ruleunits PR

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/ScoreDirectorFactoryFactory.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/ScoreDirectorFactoryFactoryTest.java, optaplanner-core/src/test/resources/org/optaplanner/core/impl/score/director/invalidDroolsConstraints.drl
I would argue this does not need to land on 8.0.x.
=> PLANNER-2240 Switch OptaPlanner to KieHelper

.github/workflows/jpa_integration_ci.yml, .github/workflows/os_java_ci.yml, Jenkinsfile
<details>
<summary>
</summary>
</details>
=> Enable github actions on the 8.0.x branch

optaplanner-examples/src/test/java/org/optaplanner/examples/curriculumcourse/app/CurriculumCoursePerformanceTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/tennis/app/TennisBenchmarkTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/tennis/app/TennisPerformanceTest.java
Do not merge yet, as the new Kogito SNAPSHOT is not out yet and therefore these tests are still failing.
=> PLANNER-2213 Reenable the remaining tests

optaplanner-examples/src/test/java/org/optaplanner/examples/curriculumcourse/app/CurriculumCoursePerformanceTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/tennis/app/TennisBenchmarkTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/tennis/app/TennisPerformanceTest.java
(cherry picked from commit 7633e95a15acf3621a29d270551095b919e7d775)
=> [8.0.x] PLANNER-2213 Reenable the remaining tests (#1009)

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java
=> Fix formatting

Jenkinsfile.promote
<details>
<summary>
</summary>
</details>
=> Fix a bug in the OptaPlanner website update stage

build/optaplanner-build-parent/pom.xml
(cherry picked from commit 54658509ea28ede6ad2f3b4d27b6550395fdd367)
Already applied to 8.0.x, now also to master.
=> Change maven.compiler.release from 11 to 8.

build/release/release-procedure.adoc
Relates to https://issues.redhat.com/browse/PLANNER-2215
<details>
<summary>
</summary>
</details>
=> Document a release procedure

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/ConstraintGraph.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/ConstraintSubTree.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/rules/UniGroupBy2Map0CollectMutator.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/AdvancedGroupByConstraintStreamTest.java
(cherry picked from commit 226e0156b13a5000838e10523c222de0b3874704)
=> [8.0.x] PLANNER-2270 Make CS-D GroupBy2Map0Collect return bi rule (#1056)

optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
<details>
<summary>
fixed SolverManager description typo
</summary>
</details>
=> fixed SolverManager.solver() description typo

optaplanner-core/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/ScoreDirectorFactoryFactory.java, optaplanner-core/src/test/java/org/optaplanner/core/config/util/ConfigUtilsTest.java, optaplanner-docs/src/main/asciidoc/Integration/Integration-chapter.adoc, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerBuildTimeConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/SolverBuildTimeConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/constraints/OptaPlannerProcessorConstraintProviderAndDrlTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/constraints/OptaPlannerProcessorConstraintsDrlDefaultTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/constraints/OptaPlannerProcessorConstraintsDrlTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessorTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/resources/org/optaplanner/quarkus/constraints/defaultConstraints.drl, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/pom.xml, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerProperties.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/SolverProperties.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/normal/NoConstraintsSpringTestConfiguration.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/normal/NormalSpringTestConfiguration.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/normal/domain/TestdataSpringSolution.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/resources/constraints.drl, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/resources/org/optaplanner/spring/boot/autoconfigure/customConstraints.drl
https://issues.redhat.com/browse/PLANNER-2265
<details>
<summary>
</summary>
</details>
=> PLANNER-2265 Add constraints-drl property

Jenkinsfile, build/optaplanner-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4068
Dependent PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/952
- https://github.com/kiegroup/kogito-apps/pull/573
- https://github.com/kiegroup/optaplanner/pull/1072
- https://github.com/kiegroup/kogito-examples/pull/491
- https://github.com/kiegroup/kogito-images/pull/290
- https://github.com/kiegroup/kogito-cloud-operator/pull/701
=> [8.1.x] KOGITO-4068 set kogito version 1.1.0-SNAPSHOT

optaplanner-docs/src/main/asciidoc/LocalSearch/LocalSearch-chapter.adoc
=> Docs: Fix the queen moves in the Local Search chapter

README.adoc
https://issues.redhat.com/browse/PLANNER-2290
<details>
<summary>
</summary>
</details>
=> PLANNER-2290 Fix a broken link in readme

Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-3863
Cherry-pick: https://github.com/kiegroup/optaplanner/pull/1071
=> [8.1.x][cherry-pick] KOGITO-3863 Setup timeout to deploy/promote

Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-3863
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/99
- https://github.com/kiegroup/kogito-runtimes/pull/947
- https://github.com/kiegroup/kogito-apps/pull/572
- https://github.com/kiegroup/kogito-examples/pull/490
- https://github.com/kiegroup/optaplanner/pull/1071
- https://github.com/kiegroup/kogito-images/pull/289
- https://github.com/kiegroup/kogito-cloud-operator/pull/698
=> KOGITO-3863 Setup timeout to deploy/promote

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractGroupByAccumulator.java
This will only affect 7.49. 
7.48 and any and all related releases are unaffected.
https://issues.redhat.com/browse/DROOLS-5875
https://github.com/kiegroup/drools/pull/3298
=> [7.x] Fix build after DROOLS-5875 was merged

optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/placer/AbstractEntityPlacer.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/custom/CustomShadowVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/FromSolutionEntitySelector.java, optaplanner-docs/src/main/asciidoc/MoveAndNeighborhoodSelection/MoveAndNeighborhoodSelection-chapter.adoc
Found accidentally when browsing through the code.
<details>
<summary>
</summary>
</details>
=> Various fixes 1

optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/value/ValueSelectorConfig.java, optaplanner-core/src/test/resources/org/optaplanner/core/config/solver/testSolverConfigWithoutNamespace.xml
https://issues.redhat.com/browse/PLANNER-1486
<details>
<summary>
</summary>
</details>
=> PLANNER-1486 Inherit filterClass in ValueSelectorConfig

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractGroupByAccumulator.java
https://issues.redhat.com/browse/DROOLS-5930
https://github.com/kiegroup/drools/pull/3310
=> [7.x] Fix build after DROOLS-5930

optaplanner-core/src/main/java/org/optaplanner/core/impl/io/jaxb/GenericJaxbIO.java
https://issues.redhat.com/browse/PLANNER-2297
<details>
<summary>
</summary>
</details>
=> Improve error message

optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java
<details>
<summary>
</summary>
</details>
=> Fix error message for Spring when a constraint provider cannot be found

optaplanner-docs/src/main/asciidoc/Integration/Integration-chapter.adoc
https://issues.redhat.com/browse/PLANNER-2288
<details>
<summary>
</summary>
</details>
=> PLANNER-2288 Document Quarkus configuration properties

build/optaplanner-build-parent/pom.xml
Fixes the Quarkus ecosystem CI: https://github.com/quarkusio/quarkus/issues/11563
<details>
<summary>
</summary>
</details>
=> Upgrade Jackson to 2.12.1

build/optaplanner-build-parent/pom.xml
<details>
<summary>
</summary>
</details>
=> Upgrade Quarkus to 1.11.0.Final

optaplanner-docs/src/main/asciidoc/RepeatedPlanning/RepeatedPlanning-chapter.adoc
=> Fix typo in ID of repeated planning documentation

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractGroupByAccumulator.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-5953
=> [DROOLS-5953] generalize accumulate function

optaplanner-core/src/main/java/org/optaplanner/core/config/solver/SolverConfig.java, optaplanner-core/src/test/java/org/optaplanner/core/config/solver/SolverConfigTest.java, optaplanner-docs/src/main/asciidoc/QuickStart/PlainJava/CloudBalancingMainMethod/CloudBalancingMainMethod-section.adoc, optaplanner-docs/src/main/asciidoc/QuickStart/PlainJava/CloudBalancingScoreConfiguration/CloudBalancingScoreConfiguration-section.adoc, optaplanner-docs/src/main/asciidoc/QuickStart/PlainJava/CloudBalancingSolverConfiguration/CloudBalancingSolverConfiguration-section.adoc, optaplanner-examples/src/main/java/org/optaplanner/examples/cloudbalancing/app/CloudBalancingHelloWorld.java
These extra methods make it a lot easier to set up an embedded (= non quarkus, not spring-boot) use of OptaPlanner for people who hate XML (or think it's overkill here).
=> SolverConfig: withEasyScoreCalculatorClass, withConstraintProviderClass and withTerminationSpentLimit

optaplanner-examples/src/main/java/org/optaplanner/examples/tsp/persistence/AbstractSvgTspOutputBuilder.java, optaplanner-examples/src/main/java/org/optaplanner/examples/tsp/persistence/SvgTspLineAndCircleExporter.java, optaplanner-examples/src/main/java/org/optaplanner/examples/tsp/persistence/SvgTspPathExporter.java
Update the export code so that the orientation of the generated SVG matches what is visible in the Swing app.
=> Exchange lat/long, flip vertically to match Swing app

optaplanner-core/src/main/java/org/optaplanner/core/api/domain/variable/VariableListener.java, optaplanner-examples/pom.xml
+ align maven-exec to run scripts
=> VariableListener javadoc should clarify its the source var's entity 

Jenkinsfile, build/optaplanner-build-parent/pom.xml
<details>
<summary>
</summary>
</details>
=> [1.2.x] Updated kogito version

Jenkinsfile
<details>
<summary>
</summary>
</details>
=> Correct PR check if on release branch

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/GizmoMemberAccessorEntityEnhancer.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/OptaPlannerBeanProvider.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/nativeimage/Substitute_MemberAccessorFactory.java
<details>
<summary>
</summary>
</details>
=> Fix native image generation for Gizmo

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorGizmoKitchenSinkTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/gizmo/DummyVariableListener.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/gizmo/TestDataKitchenSinkEntity.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/gizmo/annotations/AbstractQuarkusRecordableAnnotation.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/gizmo/annotations/QuarkusRecordableAnnotations.java
<details>
<summary>
</summary>
</details>
=> Fix annotation processing for nested annotation arrays in Gizmo

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorGizmoKitchenSinkTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/gizmo/DummyVariableListener.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/gizmo/TestDataKitchenSinkEntity.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/gizmo/annotations/AbstractQuarkusRecordableAnnotation.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/gizmo/annotations/QuarkusRecordableAnnotations.java
Cherry-pick of https://github.com/kiegroup/optaplanner/pull/1122 .
<details>
<summary>
</summary>
</details>
=> 8.2.x: Fix annotation processing for nested annotation arrays in Gizmo

build/optaplanner-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4319
Due to https://github.com/mojohaus/versions-maven-plugin/issues/312
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1131
=> [8.2.x] KOGITO-4319 Downgrade maven versions plugin

build/optaplanner-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4319
Due to https://github.com/mojohaus/versions-maven-plugin/issues/312
=> KOGITO-4319 Downgrade maven versions plugin

optaplanner-core/src/build/revapi-config.json, optaplanner-core/src/main/java/org/optaplanner/core/api/score/constraint/ConstraintMatch.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/constraint/DefaultConstraintMatchTotal.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/constraint/ConstraintMatchTest.java
Also see https://github.com/kiegroup/optaplanner-website/pull/313
=> PLANNER-2322 Allow duplicate constraint matches to coexist

optaplanner-quarkus-integration/optaplanner-quarkus-jackson/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/pom.xml, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/pom.xml, optaplanner-spring-integration/optaplanner-spring-boot-starter/pom.xml, pom.xml
jboss parent 36 has a maven compiler version (something ending with -jboss-2) that seemed to have disappeared from Maven Central
=> Upgrade JBoss Parent pom from 36 to 37

Jenkinsfile.deploy
<details>
<summary>
</summary>
</details>
=> Use the right branch for quickstarts

optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoft/HardMediumSoftScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftlong/HardMediumSoftLongScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoft/HardSoftScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftlong/HardSoftLongScore.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/bendable/BendableScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/bendablebigdecimal/BendableBigDecimalScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/bendablelong/BendableLongScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardmediumsoft/HardMediumSoftScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardmediumsoftlong/HardMediumSoftLongScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardsoft/HardSoftScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardsoftlong/HardSoftLongScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/simple/SimpleScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/simplebigdecimal/SimpleBigDecimalScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/simplelong/SimpleLongScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/holder/AbstractScoreHolder.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/DroolsConstraintFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/DroolsConstraintSessionFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/AbstractBiConstraintConsequence.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/AbstractConstraintConsequence.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/AbstractQuadConstraintConsequence.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/AbstractTriConstraintConsequence.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/AbstractUniConstraintConsequence.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/UniLeftHandSide.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/buildin/AbstractScoreHolderTest.java
I have measured both increases and drops in CS-D and DRL performance, case by case. 
On average, both CS-D and DRL improved by ~2 %.
From that, I conclude that this has a negligible impact on performance, if any.
=> PLANNER-2324 Make CS-D reuse the justifications which are already known

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/uni/DroolsUniCondition.java
https://issues.redhat.com/browse/DROOLS-5995
https://github.com/kiegroup/drools/pull/3360
=> DROOLS-5995 Adapt to the new signature for beta indexes

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/uni/DroolsUniCondition.java
Mario made more changes, so one more adaptation is needed.
https://issues.redhat.com/browse/DROOLS-5995
https://github.com/kiegroup/drools/pull/3369
=> DROOLS-5995b Adapt to the new signature for beta indexes

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/BiLeftHandSide.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/PatternVariable.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/QuadLeftHandSide.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/TriLeftHandSide.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/UniLeftHandSide.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/optional/score/MachineReassignmentConstraintProvider.java, optaplanner-examples/src/main/java/org/optaplanner/examples/meetingscheduling/optional/score/MeetingSchedulingConstraintProvider.java
Requires https://github.com/kiegroup/kogito-runtimes/pull/1052 and the subsequent Kogito SNAPSHOT.
Otherwise the build breaks.
=> PLANNER-2165, PLANNER-2166, PLANNER-2167 Index higher cardinality joins

optaplanner-core/src/build/revapi-config.json, optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/bi/BiConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/quad/QuadConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/tri/TriConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/uni/UniConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/bi/BavetAbstractBiConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/tri/BavetAbstractTriConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/uni/BavetAbstractUniConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/bi/DroolsAbstractBiConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/bi/DroolsFilterBiConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/bi/DroolsGroupingBiConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/bi/DroolsJoinBiConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/BiLeftHandSide.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/QuadLeftHandSide.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/TriLeftHandSide.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/UniLeftHandSide.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/quad/DroolsAbstractQuadConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/quad/DroolsGroupingQuadConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/tri/DroolsAbstractTriConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/tri/DroolsGroupingTriConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/uni/DroolsAbstractUniConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/uni/DroolsGroupingUniConstraintStream.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/AbstractConstraintStreamTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/ConstraintStreamFunctionalTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/bi/BiConstraintStreamTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/quad/QuadConstraintStreamTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/tri/TriConstraintStreamTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/uni/UniConstraintStreamTest.java
A lot of code, but really just the 1 thing, over and over and over again.
=> PLANNER-2330 groupBy() overloads for 2, 3, 4 collectors

optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
Do not use auto-generated hashCode
https://issues.redhat.com/browse/PLANNER-2333
<details>
<summary>
</summary>
</details>
=> Add docs note on auto-generated hashCode

optaplanner-quarkus-integration/optaplanner-quarkus-jackson/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/pom.xml
https://issues.redhat.com/browse/BXMSPROD-1208
https://github.com/kiegroup/kogito-pipelines/pull/121
https://github.com/kiegroup/kogito-examples/pull/583
https://github.com/kiegroup/optaplanner/pull/1170
https://github.com/kiegroup/kogito-runtimes/pull/1089
<details>
<summary>
</summary>
</details>
=> BXMSPROD-1208 prod profile 1.3.x/8.3.x

optaplanner-quarkus-integration/optaplanner-quarkus-jackson/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/pom.xml
https://issues.redhat.com/browse/BXMSPROD-1208
https://github.com/kiegroup/optaplanner/pull/1165
https://github.com/kiegroup/kogito-examples/pull/568
https://github.com/kiegroup/kogito-runtimes/pull/1078
https://github.com/kiegroup/kogito-pipelines/pull/117
<details>
<summary>
</summary>
</details>
=> BXMSPROD-1208 prod profile

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/loader/InstanceProblemProvider.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/api/PlannerBenchmarkFactoryTest.java
Backport because this hurts a lot.
=> [8.3.x] PLANNER-2343 fix .buildPlannerBenchmark(problems) duplicates problems

optaplanner-core/src/main/java/org/optaplanner/core/config/solver/termination/TerminationConfig.java
The exception message wasn't properly formatted. This PR fixes the problem.
<details>
<summary>
</summary>
</details>
=> Fix exception message construction

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/SubSingleBenchmarkRunner.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ranking/ScoreSubSingleBenchmarkRankingComparator.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SingleBenchmarkResult.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SubSingleBenchmarkResult.java, optaplanner-benchmark/src/main/resources/org/optaplanner/benchmark/impl/report/benchmarkReport.html.ftl
https://issues.redhat.com/browse/PLANNER-2352
=> PLANNER-2352 Benchmarker: show score explanation summary for each single benchmark

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/SolverBuildTimeConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorSolverPropertiesTest.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/SolverProperties.java
https://issues.redhat.com/browse/PLANNER-2354
<details>
<summary>
</summary>
</details>
=> PLANNER-2354 Use Quarkus configuration to set daemon mode

.github/workflows/os_java_ci.yml
<details>
<summary>
</summary>
</details>
=> Run maven in GHA with -fae option

.github/pull_request_template.md, .jenkins/dsl/jobs.groovy, Jenkinsfile
https://issues.redhat.com/browse/KOGITO-4452
In order to test against LTS version of Quarkus.
Command will be `Jenkins run LTS[ tests]`
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/119
- https://github.com/kiegroup/kogito-runtimes/pull/1072
- https://github.com/kiegroup/optaplanner/pull/1201
- https://github.com/kiegroup/kogito-apps/pull/655
- https://github.com/kiegroup/kogito-examples/pull/606
=> KOGITO-4452 Setup LTS PR check

optaplanner-docs/src/main/asciidoc/ConstraintStreams/ConstraintStreams-chapter.adoc
https://issues.redhat.com/browse/PLANNER-2345
<details>
<summary>
</summary>
</details>
=> Add docs for injecting and autowiring ConstraintVerifier

optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java
The Spring Boot auto-configuration fails due to:
ClassNotFoundException: org.optaplanner.test.api.score.stream.ConstraintVerifier
when `optaplanner-test` is not present on the classpath. Breaks a build of the optaweb-employee-rostering.
See https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/condition/ConditionalOnClass.html.
<details>
<summary>
</summary>
* …
=> Fix ConstraintVerifier Spring Boot auto-configuration

Jenkinsfile.promote
<details>
<summary>
</summary>
</details>
=> Map required_pull_request_reviews

.github/pull_request_template.md, .jenkins/dsl/jobs.groovy, Jenkinsfile
https://issues.redhat.com/browse/KOGITO-4158
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/127
- https://github.com/kiegroup/kogito-runtimes/pull/1120
- https://github.com/kiegroup/optaplanner/pull/1204
- https://github.com/kiegroup/kogito-apps/pull/699
- https://github.com/kiegroup/kogito-examples/pull/608
=> KOGITO-4158 Setup native PR checks

.jenkins/dsl/jobs.groovy, Jenkinsfile.deploy
Runs cypress tests on ERP and VRP if SKIP_INTEGRATION_TESTS id is false
For nightly builds only. Got skipped in release build
https://github.com/kiegroup/kogito-pipelines/pull/135
Wait for fix to merge:
https://github.com/kiegroup/optaweb-vehicle-routing/pull/448
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/custom%2Fadupliak%2Fnightly-optaplanner-deploy/detail/nightly-optaplanner-deploy/3/pipeline/
The VRP and ERP builds successfully passed, deploy job fails because it cannot deploy to the nexus repository (it is outdated) 
<details>
<summary>
</summary>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run …
=> Add integration-tests profile

optaplanner-quarkus-integration/optaplanner-quarkus-jackson/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/pom.xml
This reverts commit 124f8556cd1ceede3ce0aa457392e4173cf02e45.
=> Productize integration-test modules so that quarkus-platform which depends on them can also use them productized

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/common/nearby/NearbyDistanceMatrix.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/nearby/NearEntityNearbyEntitySelector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/nearby/NearEntityNearbyValueSelector.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/common/nearby/NearbyDistanceMatrixTest.java
https://issues.redhat.com/browse/PLANNER-2337
<details>
<summary>
</summary>
</details>
=> PLANNER-2337 NPE in NearbyDistanceMatrix

optaplanner-core/pom.xml, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/ScoreDirectorFactoryFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/DroolsConstraintSessionFactory.java
ANC apparently doesn't work in native and broke all sorts of CI in Kogito.
=> Disable Drools Alpha Network Compiler

build/optaplanner-build-parent/pom.xml
https://issues.redhat.com/browse/PLANNER-2366
- https://github.com/kiegroup/optaplanner/pull/1221
- https://github.com/kiegroup/optaplanner-quickstarts/pull/78
- https://github.com/kiegroup/optaweb-employee-rostering/pull/572
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/445
<details>
<summary>
</summary>
* …
=> PLANNER-2366: Upgrade Spring Boot to 2.3.4

build/optaplanner-build-parent/pom.xml, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/mutation/TestGenRemoveRandomBlockMutator.java
<details>
<summary>
</summary>
</details>
=> PLANNER-2371: Replace blacklist with denylist or similar

optaplanner-docs/src/main/asciidoc/QuickStart/SpringBoot/SpringBootQuickStart-chapter.adoc
Basically a copy of https://github.com/quarkusio/quarkus/pull/15611 ; any changes to this should also apply to that.
<details>
<summary>
</summary>
</details>
=> Add ConstraintVerifier section to Spring Boot Quickstart guide

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/lookup/PlanningIdLookUpStrategy.java
related PR for upgrade recipe: https://github.com/kiegroup/optaplanner-website/pull/335
=> Fail fast on null planning ID

build/optaplanner-build-parent/pom.xml, optaplanner-core/src/build/revapi-config.json
https://github.com/kiegroup/kogito-runtimes/pull/1202
<details>
<summary>
</summary>
</details>
=> [8.5.x] Bump kie7 to 7.52.0.Final

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ProblemBenchmarksFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/SolverBenchmarkFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/BenchmarkResultIO.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/DroolsScoreDirectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverFactory.java
=> Delay SolutionCloner creation until EntityDescriptors are created 

Jenkinsfile
<details>
<summary>
</summary>
</details>
=> Use a maven mirror in Jenkins PR check

build/optaplanner-build-parent/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/pom.xml, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java
https://issues.redhat.com/browse/PLANNER-2389
https://github.com/kiegroup/optaplanner/pull/1254
https://github.com/kiegroup/optaplanner-quickstarts/pull/93
https://github.com/kiegroup/optaweb-employee-rostering/pull/602
https://github.com/kiegroup/optaweb-vehicle-routing/pull/471
<details>
<summary>
</summary>
* for a …
=> PLANNER-2389 Upgrade Quarkus to 1.13

Jenkinsfile.deploy
* https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/151
<details>
<summary>
</summary>
</details>
=> create PR with labels

optaplanner-docs/src/main/asciidoc/ConstraintStreams/ConstraintStreams-chapter.adoc
Comes from this Twitter feedback:
https://twitter.com/Eduardo02725273/status/1389686018585120770
=> CS docs improvements: list all Collectors methods + avoid will

build/optaplanner-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-5079
<details>
<summary>
</summary>
</details>
=> [KOGITO-5079] Bump 7.54.0.Beta1

build/optaplanner-build-parent/pom.xml
Related PR
- https://github.com/kiegroup/optaplanner/pull/1326
- https://github.com/kiegroup/kogito-runtimes/pull/1308
<details>
<summary>
</summary>
</details>
=> [master] Bump KIE 7.54.0.Final

build/optaplanner-build-parent/pom.xml
Related PR
- https://github.com/kiegroup/kogito-runtimes/pull/1309
- https://github.com/kiegroup/optaplanner/pull/1327
<details>
<summary>
</summary>
</details>
=> [8.7.x][master] Bump KIE 7.54.0.Final

build/optaplanner-build-parent/pom.xml
<details>
<summary>
</summary>
</details>
=> bump to kie 7.55.0.Beta1

build/optaplanner-build-parent/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java
Upgrades to 1.13.4.Final of Quarkus and fixed the https://github.com/quarkusio/quarkus/issues/11563.
<details>
<summary>
</summary>
</details>
=> Upgrade Quarkus to 1.13.4.Final

optaplanner-core/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/entity/descriptor/EntityDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/score/descriptor/ScoreDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/custom/CustomShadowVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/descriptor/GenuineVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/HeuristicConfigPolicy.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/ScoreDirectorFactoryFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/IncrementalScoreDirectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverFactory.java, optaplanner-core/src/test/java/org/optaplanner/core/config/util/ConfigUtilsTest.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java
The **CustomShadowVariableDescriptor's variableListenerClass** (org.optaplanner.core.impl.testdata.domain.shadow.extended.TestdataExtendedShadowedParentEntity$ThirdShadowUpdatingVariableListener) does not have a public no-arg constructor.
The **TestdataExtendedShadowedParentEntity.thirdShadow shadow's variableListenerClass** (org.optaplanner.core.impl.testdata.domain.shadow.extended.TestdataExtendedShadowedParentEntity$ThirdShadowUpdatingVariableListener) does not have a public no-arg constructor.
The **EntityDescriptor's pinningFilterClass** (org.optaplanner.core.impl.testdata.domain.pinned.TestdataPinningFilter) does not have a public no-arg constructor.
The **EntityDescriptor(org.optaplanner.core.impl.testdata.domain.pinned.TestdataPinnedEntity)'s pinningFilterClass** …
=> Fix usage of ConfigUtils.newInstance()

.github/workflows/os_java_ci.yml
<details>
<summary>
</summary>
</details>
=> Update Github Actions to use the Build Chain

optaplanner-core/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/verifier/OptaPlannerConstraintVerifierBavetStreamImplTest.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/pom.xml, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java, optaplanner-test/pom.xml, optaplanner-test/src/build/revapi-config.json, optaplanner-test/src/main/java/org/optaplanner/test/api/score/stream/ConstraintVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultConstraintVerifier.java
* Adds ConstraintVerifier.create(SolverConfig) for convenience
* Salvages this stale PR https://github.com/kiegroup/optaplanner/pull/812/files (which I 'll now close)
=> add ConstraintVerifier.create(SolverConfig)

build/optaplanner-build-parent/pom.xml
- https://github.com/kiegroup/kogito-runtimes/pull/1274
- https://github.com/kiegroup/kogito-apps/pull/857
- https://github.com/kiegroup/kogito-examples/pull/722
- https://github.com/kiegroup/optaplanner/pull/1379
=> KOGITO-5069 Bump Quarkus 2.0.0.CR3

.github/workflows/os_java_ci.yml
<details>
<summary>
</summary> …
=> Support long paths on Windows

.jenkins/dsl/jobs.groovy
to get the correct default quickstart branch as parameter
=> Small update on DSL

optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/util/TestMeterRegistry.java
<details>
<summary>
</summary> …
=> Do not rely on String formatting in Micrometer tests

build/optaplanner-build-parent/pom.xml
<details>
<summary>
</summary> …
=> Update Quarkus to 2.0.0.Final

build/optaplanner-build-parent/pom.xml
<details>
<summary>
</summary> …
=> [8.8.x] Update Quarkus to 2.0.0.Final

Jenkinsfile.deploy, Jenkinsfile.promote, Jenkinsfile.turtle
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1395
=> [8.8.x] Setup Jenkins timestamps

build/optaplanner-build-parent/pom.xml, optaplanner-core/pom.xml, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/KieRuntimeBuilderWrapper.java, optaplanner-distribution/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/GizmoMemberAccessorEntityEnhancer.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/KieRuntimeBuilderMock.java, optaplanner-quarkus-integration/optaplanner-quarkus/drl-integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/pom.xml
https://issues.redhat.com/browse/KOGITO-5223
PRs
- https://github.com/kiegroup/kogito-runtimes/pull/1347
- https://github.com/kiegroup/optaplanner/pull/1402
- https://github.com/kiegroup/kogito-examples/pull/716
=> [KOGITO-5223] kie v7 legacy API for Kogito

Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-4094
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/962
- https://github.com/kiegroup/optaplanner/pull/1095
- https://github.com/kiegroup/kogito-apps/pull/590
- https://github.com/kiegroup/kogito-examples/pull/515
=> KOGITO-4094 Avoid to deploy artifacts if author is not `kiegroup` and no artifacts repository has been given

optaplanner-quarkus-integration/optaplanner-quarkus/runtime/pom.xml
https://issues.redhat.com/browse/PLANNER-2471
<details>
<summary>
</summary> …
=> PLANNER-2471 Fix the Quarkus native compilation

.jenkins/dsl/jobs.groovy
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1398
https://issues.redhat.com/browse/KOGITO-5408
There will be one PR check job per branch instead of a global one.
This will help with updates of PR checks.
**Depends on: https://github.com/kiegroup/kogito-pipelines/pull/203**
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1404
- https://github.com/kiegroup/optaplanner/pull/1399
- https://github.com/kiegroup/kogito-apps/pull/908
- https://github.com/kiegroup/kogito-examples/pull/748
=> [8.8.x] KOGITO-5408 Branch dependent PR jobs

optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/runtime/src/main/resources/META-INF/quarkus-extension.yaml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/resources/META-INF/quarkus-extension.yaml
Streamline this a bit more to make it clear what is the main module (optaplanner) on code.quarkus.io
=> code.quarkus.io: improve metadata

optaplanner-docs/src/main/asciidoc/ConstraintStreams/ConstraintStreams-chapter.adoc, optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
Fix a few issues discovered while reading the constraint streams chapter.
<details>
<summary>
</summary>
* for a <b>specific …
=> Fix documentation typos

.jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-5480
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1416
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins …
=> [8.5.x] KOGITO-5480 Reorganized seed jobs & trigger automatically

.jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-5480
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1416
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins …
=> [8.8.x] KOGITO-5480 Reorganized seed jobs & trigger automatically

.jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-5480
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1416
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins …
=> [8.9.x] KOGITO-5480 Reorganized seed jobs & trigger automatically

build/optaplanner-build-parent/pom.xml
bundle:
- https://github.com/kiegroup/kogito-runtimes/pull/1422
- https://github.com/kiegroup/optaplanner/pull/1413
- https://github.com/kiegroup/optaplanner-quickstarts/pull/133
=> Bump Quarkus 2.0.1.Final

optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/BestScoreFeasibleTerminationTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/BestScoreTerminationTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/StepCountTerminationTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/TimeMillisSpentTerminationTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/UnimprovedStepCountTerminationTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTerminationTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/UnimprovedTimeMillisSpentTerminationTest.java
=> Termination tests generics

optaplanner-docs/src/main/asciidoc/MoveAndNeighborhoodSelection/MoveAndNeighborhoodSelection-chapter.adoc
https://stackoverflow.com/questions/68432914/optaplanner-pillarswapmoveselector-multiple-variablenameinclude-elements
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> please add comment: …
=> Update documentation of selector config

optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/impl/ConsecutiveIntervalInfoImpl.java
A profile in jboss parent causes IDEA to think we
are using JDK 8, whereas we are using JDK 11.
<details>
<summary>
</summary> …
=> Remove usage of var due to IDEA IDE bug

.github/workflows/os_java_ci.yml
The build chain tool is not properly taken into account for excluded projects. https://github.com/kiegroup/github-action-build-chain/pull/160 solves the problem
related PR
- https://github.com/kiegroup/github-action-build-chain/pull/160
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/527
- https://github.com/kiegroup/optaweb-employee-rostering/pull/654
- https://github.com/kiegroup/optaplanner/pull/1418
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/528
- https://github.com/kiegroup/optaweb-employee-rostering/pull/655
<details>
<summary>
</summary>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run …
=> BXMSPROD-1413 [master] [build-chain upgrade] exclude projects not taken into account

.ci/jenkins/Jenkinsfile
https://issues.redhat.com/browse/KOGITO-5532
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1447
- https://github.com/kiegroup/optaplanner/pull/1432
- https://github.com/kiegroup/kogito-apps/pull/943
- https://github.com/kiegroup/kogito-examples/pull/798
- https://github.com/kiegroup/kogito-images/pull/597
<details>
<summary>
</summary>
* for a <b>full production …
=> KOGITO-5532 Corrected PR check author handling

.jenkins/dsl/jobs.groovy, Jenkinsfile
https://issues.redhat.com/browse/KOGITO-5540
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1442
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins …
=> [8.9.x] KOGITO-5540 Disable Sonarcloud on release branches (#1442)

.ci/jenkins/Jenkinsfile.deploy
<details>
<summary>
</summary> …
=> Fix Gradle version update script

Jenkinsfile.deploy
Cherry-pick of https://github.com/kiegroup/optaplanner/pull/1444
<details>
<summary>
</summary>
* for a <b>specific Quarkus …
=> [8.9.x] Fix Gradle version update script

.ci/jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-5480
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/206
- https://github.com/kiegroup/kogito-runtimes/pull/1429
- https://github.com/kiegroup/optaplanner/pull/1416
- https://github.com/kiegroup/kogito-apps/pull/928
- https://github.com/kiegroup/kogito-examples/pull/778
- https://github.com/kiegroup/kogito-images/pull/575
- https://github.com/kiegroup/kogito-operator/pull/929
- https://github.com/kiegroup/rhpam-kogito-operator/pull/53
<details>
<summary>
</summary>
* for a <b>full …
=> KOGITO-5480 Reorganized seed jobs & trigger automatically

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/ScoreDirectorFactoryFactory.java
@Christopher-Chianelli Can you please check that there is nothing here to do wrt. Quarkus? I only re-enable this functionality outside of Quarkus and I'm not sure if/how we support that with Quarkus.
=> PLANNER-2448 Restore the possibility to configure KieBase options

.ci/jenkins/Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-5567
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1466
- https://github.com/kiegroup/optaplanner/pull/1452
- https://github.com/kiegroup/kogito-examples/pull/808
<details>
<summary>
</summary>
* for an <b>upstream …
=> KOGITO-5567 Skip tests on Maven deploy

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-5326
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/212
- https://github.com/kiegroup/kogito-runtimes/pull/1449
- https://github.com/kiegroup/optaplanner/pull/1436
- https://github.com/kiegroup/kogito-apps/pull/945
- https://github.com/kiegroup/kogito-examples/pull/800
- https://github.com/kiegroup/kogito-images/pull/602
- https://github.com/kiegroup/kogito-operator/pull/944
- https://github.com/kiegroup/rhpam-kogito-operator/pull/56
<details>
<summary>
</summary>
* for a <b>full …
=> KOGITO-5326 Setup deploy/promote notifications on demand

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh, .github/workflows/jpa_integration_ci.yml, .github/workflows/os_java_ci.yml, .github/workflows/quarkus-snapshot-readme.md, .github/workflows/quarkus-snapshot.yaml, .github/workflows/sonarcloud.yml, README.adoc, build/release/release-procedure.adoc, optaplanner-distribution/src/main/assembly/filtered-resources/ReadMeOptaPlanner.txt, optaplanner-docs/src/main/asciidoc/PlannerIntroduction/DownloadAndRunTheExamples/DownloadAndRunTheExamples-section.adoc, pom.xml
**PLEASE DO NOT MERGE. THIS WILL BE DONE WHEN `master` will be renamed as `main`**
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/188
- https://github.com/kiegroup/kogito-runtimes/pull/1365
- https://github.com/kiegroup/optaplanner/pull/1372
- https://github.com/kiegroup/optaweb-employee-rostering/pull/660
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/532
- https://github.com/kiegroup/optaplanner-quickstarts/pull/144
- https://github.com/kiegroup/kogito-apps/pull/882
- https://github.com/kiegroup/kogito-examples/pull/729
- https://github.com/kiegroup/kogito-images/pull/516
- https://github.com/kiegroup/kogito-operator/pull/905
- https://github.com/kiegroup/rhpam-kogito-operator/pull/44
=> BXMSPROD-1265: Conscious language initiative

build/optaplanner-build-parent/pom.xml, optaplanner-distribution/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml, optaplanner-quarkus-integration/pom.xml
The part we agreed on from #1438 , importing the Quarkus BOM without additional changes.
<details>
<summary>
</summary>
* for …
=> Import Quarkus BOM

Jenkinsfile.promote
<details>
<summary>
</summary> …
=> [8.9.x] Correct setup of repository in build.gradle files

.github/workflows/pull_request.yml, README.adoc, optaplanner-core/src/main/java/org/optaplanner/core/api/domain/variable/CustomShadowVariable.java, optaplanner-distribution/src/main/assembly/filtered-resources/ReadMeOptaPlanner.txt, optaplanner-docs/src/main/asciidoc/PlannerIntroduction/DownloadAndRunTheExamples/DownloadAndRunTheExamples-section.adoc
https://github.com/kiegroup/optaplanner/pull/1466
https://github.com/kiegroup/optaweb-employee-rostering/pull/663
https://github.com/kiegroup/optaweb-vehicle-routing/pull/536
<!--
Thank you for submitting this pull request.
<details>
<summary>
</summary>
* for an <b>upstream …
=> BXMSPROD-1265: master to main leftovers

Jenkinsfile.promote
Correct promote pipeline for release
=> 1.9.x correct promote

.ci/jenkins/Jenkinsfile.promote
backport from: https://github.com/kiegroup/optaplanner/pull/1467
<details>
<summary>
</summary>
* for a <b>specific Quarkus …
=> Promote pipeline: Correct setup of repository in build.gradle files (#1467)

build/optaplanner-build-parent/pom.xml
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1465
- https://github.com/kiegroup/optaplanner/pull/1451
- https://github.com/kiegroup/optaplanner-quickstarts/pull/145
- https://github.com/kiegroup/kogito-apps/pull/964
- https://github.com/kiegroup/kogito-examples/pull/810
<details>
<summary>
</summary>
* for a <b>full production downstream build</b> please add …
=> Bump Quarkus 2.1.0.Final

.github/workflows/jpa_integration_ci.yml, .github/workflows/os_java_ci.yml, .github/workflows/sonarcloud.yml
* https://github.com/kiegroup/optaplanner/pull/1481
* https://github.com/kiegroup/optaplanner-quickstarts/pull/151
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/540
* https://github.com/kiegroup/optaweb-employee-rostering/pull/668
=> [main] github actions paths-ignore

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java
=> PLANNER-2406 Make map-based constraint collectors incremental

.ci/jenkins/dsl/jobs.groovy
<details>
<summary>
</summary> …
=> Optaweb PR checks on all branches

.ci/jenkins/dsl/jobs.groovy
<details>
<summary>
</summary> …
=> Optaweb PR checks on release branches

.ci/jenkins/dsl/jobs.groovy
Cherry-picks:
- https://github.com/kiegroup/optaplanner/pull/1499
- https://github.com/kiegroup/optaplanner/pull/1500
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> please add comment: …
=> [8.10.x] optawebs pr checks

build/optaplanner-build-parent/pom.xml
https://github.com/kiegroup/optaplanner-quickstarts/pull/159
<details>
<summary>
</summary>
* for a <b>specific Quarkus LTS …
=> Upgrade Quarkus to 2.1.2.Final

.gitignore, optaplanner-persistence/optaplanner-persistence-jaxb/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml, optaplanner-persistence/optaplanner-persistence-jsonb/pom.xml, optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml
**JIRA**: 
[JBPM-9659](https://issues.redhat.com/browse/JBPM-9659)
**Related PRs*: 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1693
https://github.com/kiegroup/kie-soup/pull/216
https://github.com/kiegroup/droolsjbpm-knowledge/pull/543
https://github.com/kiegroup/drools/pull/3757
https://github.com/kiegroup/optaplanner/pull/1463
https://github.com/kiegroup/lienzo-tests/pull/124
https://github.com/kiegroup/appformer/pull/1163
https://github.com/kiegroup/kie-uberfire-extensions/pull/122
https://github.com/kiegroup/jbpm/pull/1974
https://github.com/kiegroup/kie-jpmml-integration/pull/62
https://github.com/kiegroup/droolsjbpm-integration/pull/2539
https://github.com/kiegroup/kie-wb-playground/pull/115
https://github.com/kiegroup/kie-wb-common/pull/3660 …
=> JBPM-9659: Upgrade deployments to WildFly 23

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/tri/TriConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/accessor/MemberAccessorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/entity/descriptor/EntityDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/anchor/AnchorShadowVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/custom/CustomShadowVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/InverseRelationShadowVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMoveSelector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarSwapMoveSelector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/SwapMoveSelector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/KOptMoveSelector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainSwapMoveSelector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/TailChainSwapMoveSelector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/ValueSelectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/AbstractScoreDirector.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/invalid/TestdataDuplicatePlanningScorePropertySolution.java, optaplanner-docs/src/main/asciidoc/PlannerIntroduction/Governance/Governance-section.adoc, optaplanner-docs/src/main/asciidoc/ScoreCalculation/ScoreCalculation-chapter.adoc, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/nativeimage/Substitute_MemberAccessorFactory.java
<details>
<summary>
</summary> …
=> Various fixes

optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
<details>
<summary>
</summary> …
=> Fix a few documentation typos

build/optaplanner-build-parent/pom.xml
https://github.com/kiegroup/optaplanner/pull/1535
https://github.com/kiegroup/optaplanner-quickstarts/pull/170
<details>
<summary>
</summary>
* for an <b>upstream build</b> please add comment: …
=> [8.11.x] upgrade quarkus 2.2.0.final

.github/workflows/full-downstream.yml, .github/workflows/pull_request.yml
The `concurrency` section should be part of a job.
<details>
<summary>
</summary>
* for a <b>Quarkus LTS …
=> Fix the GHA workflow definition

optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
<details>
<summary>
</summary>
* for …
=> Add Micrometer to docs

.github/workflows/full-downstream.yml, .github/workflows/pull_request.yml
<details>
<summary>
</summary>
* for …
=> Remove Java 8 from GHA

.ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle, build/optaplanner-build-parent/pom.xml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
Propagate change to `main` branch from initial PR: https://github.com/kiegroup/optaplanner/pull/1550
=> Upgrade Jenkinsfile Maven version to 3.6.3

optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
<details>
<summary>
</summary>
* for …
=> BXMSDOC-8107 Updated the Monitoring section with productized changes

build/optaplanner-build-parent/pom.xml
<details>
<summary>
</summary>
* for …
=> [8.11.x] Bump Quarkus 2.2.2.Final

optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/ExperimentalConstraintCollectors.java
<details>
<summary>
</summary>
* for …
=> Improve Javadoc

.github/workflows/full-downstream.yml, .github/workflows/os_java_ci.yml, .github/workflows/pull_request.yml
**Thank you for submitting this pull request**
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1475
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1770
* https://github.com/kiegroup/kie-soup/pull/228
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/549
* https://github.com/kiegroup/drools/pull/3835
* https://github.com/kiegroup/optaplanner/pull/1577
* https://github.com/kiegroup/lienzo-core/pull/152
* https://github.com/kiegroup/lienzo-tests/pull/126
* https://github.com/kiegroup/appformer/pull/1197
* https://github.com/kiegroup/kie-uberfire-extensions/pull/124
* https://github.com/kiegroup/jbpm/pull/2024
* https://github.com/kiegroup/kie-jpmml-integration/pull/65
* https://github.com/kiegroup/droolsjbpm-integration/pull/2607
* …
=> [main] BXMSPROD-1475 force maven to 3.8.1

.github/workflows/os_java_ci.yml, .github/workflows/pull_request.yml
**Thank you for submitting this pull request**
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1475
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1770
* https://github.com/kiegroup/kie-soup/pull/228
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/549
* https://github.com/kiegroup/drools/pull/3835
* https://github.com/kiegroup/optaplanner/pull/1577
* https://github.com/kiegroup/lienzo-core/pull/152
* https://github.com/kiegroup/lienzo-tests/pull/126
* https://github.com/kiegroup/appformer/pull/1197
* https://github.com/kiegroup/kie-uberfire-extensions/pull/124
* https://github.com/kiegroup/jbpm/pull/2024
* https://github.com/kiegroup/kie-jpmml-integration/pull/65
* https://github.com/kiegroup/droolsjbpm-integration/pull/2607
* …
=> BXMSPROD-1475 maven version

optaplanner-persistence/optaplanner-persistence-jpa/pom.xml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)
**referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1768
* https://github.com/kiegroup/jbpm/pull/2016
* https://github.com/kiegroup/drools/pull/3832
* https://github.com/kiegroup/droolsjbpm-integration/pull/2602
* https://github.com/kiegroup/jbpm-work-items/pull/215
* https://github.com/kiegroup/kie-jpmml-integration/pull/64
* https://github.com/kiegroup/kie-soup/pull/227
* https://github.com/jboss-integration/rhba-installers/pull/92
=> RHPAM-3897: switch to jboss-transaction-spi-jakarta

optaplanner-persistence/optaplanner-persistence-jpa/pom.xml
**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)
**referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1775
* https://github.com/kiegroup/jbpm/pull/2028
* https://github.com/kiegroup/drools/pull/3839
* https://github.com/kiegroup/droolsjbpm-integration/pull/2609
* https://github.com/kiegroup/jbpm-work-items/pull/218
* https://github.com/kiegroup/kie-jpmml-integration/pull/67
* https://github.com/kiegroup/kie-soup/pull/230
* https://github.com/jboss-integration/rhba-installers/pull/93
=> [7.59.x] RHPAM-3897: switch to jboss-transaction-spi-jakarta

.ci/jenkins/dsl/jobs.groovy
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1517
https://issues.redhat.com/browse/KOGITO-5730
This will reorganize the different jobs in a specific branch folder and allow automatically deleting jobs when the concerned branch is removed from the [main config](https://github.com/kiegroup/kogito-pipelines/blob/main/dsl/seed/config/main.yaml#L2)
Example: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/kogito-5730/
Here are the new mappings: 
- nightly/{branch}/... => {branch}/nightly/...
- release/{branch}/... => {branch}/release/...
- pullrequest/{branch}/... => {branch}/pullrequest/...
- tools/{branch}/... => {branch}/tools/...
- other/{branch}/... => {branch}/other/...
**All PRs should be merged at the same time !!!!** …
=> [8.11.x] KOGITO-5730 Update DSL folder structure (#1517)

build/optaplanner-build-parent/pom.xml
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1646
- https://github.com/kiegroup/optaplanner/pull/1600
- https://github.com/kiegroup/kogito-examples/pull/917
- https://github.com/kiegroup/optaplanner-quickstarts/pull/195
=> [8.11.x] Bump Quarkus 2.2.3.Final

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-5680
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/233
- https://github.com/kiegroup/kogito-runtimes/pull/1514
- https://github.com/kiegroup/optaplanner/pull/1503
- https://github.com/kiegroup/kogito-examples/pull/908
- https://github.com/kiegroup/optaplanner-quickstarts/pull/188
<details>
<summary>
</summary>
* for a …
=> [KOGITO-5680] Quarkus update Jenkins jobs

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/AbstractAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/BiAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/QuadAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/TriAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/UniAccumulator.java
Related pull request:
https://github.com/kiegroup/drools/pull/3961
https://github.com/kiegroup/kogito-runtimes/pull/1688
https://github.com/kiegroup/optaplanner/pull/1643
=> [KOGITO-2391] introducing ReteEvaluator

optaplanner-docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc
@radtriste @mbiarnes If this PR is in time to make the 8.13.0.Final release (so we fix the broken links SEO influence sooner rather than later), that would be nice, but it is not a necessity.
=> [8.13.x] Fix broken links in quarkus docs

optaplanner-docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc, optaplanner-docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc, optaplanner-docs/src/modules/ROOT/pages/quickstart/spring-boot/spring-boot-quickstart.adoc
Relates to https://github.com/kiegroup/optaplanner-quickstarts/pull/217
=> Clean up gradle and maven quickstart build files

optaplanner-quickstarts/spring-boot-school-timetabling/src/test/java/com/example/schooltimetabling/solver/TimeTableControllerTest.java
https://issues.redhat.com/browse/PLANNER-2571
<details>
<summary>
</summary> …
=> PLANNER-2571 Add a workaround for a race condition in quickstart

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/AbstractAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/BiAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/QuadAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/TriAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/UniAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/ValueExtractor.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/score/ConferenceSchedulingConstraintProvider.java
I ran the reproducer code in a loop several thousand times and the issue did not show.
Before the fix, it would usually show within the first 20 repetitions.
=> PLANNER-2557 Thread-safe groupBy in CS-D

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/stream/DroolsConstraintStreamScoreDirector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/stream/DroolsConstraintStreamScoreDirectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/SessionDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/AbstractRuleContext.java
Depends on https://github.com/kiegroup/optaplanner/pull/1646
=> PLANNER-2569 Improve performance of disabled constraints 

.github/workflows/full-downstream.yml, .github/workflows/pull_request.yml
- https://github.com/kiegroup/kogito-pipelines/pull/313
- https://github.com/kiegroup/kogito-runtimes/pull/1692
- https://github.com/kiegroup/kogito-examples/pull/968
- https://github.com/kiegroup/kogito-apps/pull/1093
- https://github.com/kiegroup/optaplanner/pull/1649
- https://github.com/kiegroup/drools/pull/3984
=> BXMSPROD-1540 composite actions centralized github actions

optaplanner-docs/src/antora.yml
Brings the left-hand side menu if you build docs from the `main` branch of OptaPlanner.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this change you can easily reproduce the same …
=> Include a menu in the default antora docs

optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/verifier/OptaPlannerConstraintVerifierDroolsStreamImplTest.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultConstraintVerifier.java
JIRA: https://issues.redhat.com/browse/DROOLS-6645
Relate pull requests:
https://github.com/kiegroup/drools/pull/4006
https://github.com/kiegroup/kogito-runtimes/pull/1710
https://github.com/kiegroup/optaplanner/pull/1666
=> [DROOLS-6645] remove xml dependencies from drools core and compiler

.github/workflows/full-downstream.yml, .github/workflows/pull_request.yml
https://github.com/kiegroup/optaweb-vehicle-routing/pull/602
=>  BXMSPROD-1542 definition-file eval expression 

.github/workflows/full-downstream.yml, .github/workflows/pull_request.yml
https://github.com/kiegroup/optaweb-vehicle-routing/pull/602
=> [8.14.x] BXMSPROD-1542 definition-file eval expression

.github/workflows/full-downstream.yml, .github/workflows/pull_request.yml
https://github.com/kiegroup/optaweb-vehicle-routing/pull/602
=> [8.11.x] BXMSPROD-1542 definition-file eval expression

build/optaplanner-build-parent/pom.xml
Assembly:
- https://github.com/kiegroup/optaplanner-quickstarts/pull/225
- https://github.com/kiegroup/optaplanner/pull/1675
- https://github.com/kiegroup/kogito-examples/pull/979
- https://github.com/kiegroup/kogito-apps/pull/1113
- https://github.com/kiegroup/kogito-runtimes/pull/1717
=> [1.14.x] KOGITO-6130 Upgrade to Quarkus 2.4.2

build/optaplanner-build-parent/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1695
- https://github.com/kiegroup/kogito-apps/pull/1095
- https://github.com/kiegroup/kogito-examples/pull/940
- https://github.com/kiegroup/optaplanner/pull/1658
- https://github.com/kiegroup/optaplanner-quickstarts/pull/220
=> KOGITO-6130 Upgrade to Quarkus 2.4.2

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/accessor/gizmo/GizmoMemberAccessorImplementor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/gizmo/GizmoSolutionClonerImplementor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/Phase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/AbstractSolver.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/io/jaxb/adapter/JaxbCustomPropertiesAdapterTest.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/api/Break.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/api/IntervalBreak.java
<details>
<summary>
</summary> …
=> Fix a few Javadoc issues

build/optaplanner-build-parent/pom.xml, optaplanner-core/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/pom.xml
**JIRA**: https://issues.redhat.com/browse/DROOLS-6730
Related PRs:
https://github.com/kiegroup/drools/pull/4052
https://github.com/kiegroup/kogito-runtimes/pull/1763
https://github.com/kiegroup/optaplanner/pull/1700
https://github.com/kiegroup/kogito-apps/pull/1138
=> [DROOLS-6730] move drools-static from kogito to drools

build/optaplanner-build-parent/pom.xml
related https://github.com/kiegroup/optaplanner-quickstarts/pull/245
=> [8.15.x] Upgrade Logback from 1.2.3 to 1.2.8

build/optaplanner-build-parent/pom.xml, optaplanner-docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc
related https://github.com/kiegroup/optaplanner-quickstarts/pull/247
=> Upgrade Logback to 1.2.9

build/optaplanner-build-parent/pom.xml, optaplanner-docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc
related https://github.com/kiegroup/optaplanner-quickstarts/pull/249
=> [8.15.x] Upgrade Logback to 1.2.9

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/SmallScalingOrderedSet.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerNotifiable.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerNotification.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerNotificationType.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerSupport.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/SwapMove.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarChangeMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarSwapMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/SwapMoveTest.java
Creates much less objects.
Also while I was there, cleans up some code.
=> Reduce GC pressure in VariableListenerNotificationSupport

build/optaplanner-build-parent/pom.xml
- https://github.com/kiegroup/kogito-pipelines/pull/337
- https://github.com/kiegroup/kogito-runtimes/pull/1807
- https://github.com/kiegroup/optaplanner/pull/1736
- https://github.com/kiegroup/kogito-apps/pull/1169
- https://github.com/kiegroup/optaplanner-quickstarts/pull/254
- https://github.com/kiegroup/kogito-examples/pull/1047
=> Bump main Quarkus 2.6.0.Final

optaplanner-core/pom.xml, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/OptaPlannerRuleEventListener.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/holder/AbstractScoreHolder.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/AbstractRuleContext.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/buildin/AbstractScoreHolderTest.java
Related PRs:
https://github.com/kiegroup/drools/pull/4075
https://github.com/kiegroup/kogito-runtimes/pull/1805
https://github.com/kiegroup/optaplanner/pull/1735
=> [DROOLS-6707] move tms in its own module

build/optaplanner-build-parent/pom.xml
Back-port the Logback upgrade.
https://github.com/kiegroup/optaplanner-quickstarts/pull/252
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this change you can easily reproduce the …
=> [8.11.x] Upgrade Logback to 1.2.9

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/StatisticPoint.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/SubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/bestscore/BestScoreSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/bestsolutionmutation/BestSolutionMutationSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/memoryuse/MemoryUseSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/movecountperstep/MoveCountPerStepSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/scorecalculationspeed/ScoreCalculationSpeedSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/stepscore/StepScoreSubSingleStatistic.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/AbstractSubSingleStatisticTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/bestscore/BestScoreSubSingleStatisticTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/bestsolutionmutation/BestSolutionMutationSubSingleStatisticTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/memoryuse/MemoryUseSubSingleStatisticTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/movecountperstep/MoveCountPerStepSubSingleStatisticTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/scorecalculationspeed/ScoreCalculationSpeedSubSingleStatisticTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/stepscore/StepScoreSubSingleStatisticTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/subsingle/constraintmatchtotalbestscore/ConstraintMatchTotalBestScoreSubSingleStatisticTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/subsingle/constraintmatchtotalstepscore/ConstraintMatchTotalStepScoreSubSingleStatisticTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/subsingle/pickedmovetypebestscore/PickedMoveTypeBestScoreSubSingleStatisticTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/subsingle/pickedmovetypestepscore/PickedMoveTypeStepScoreSubSingleStatisticTest.java
Went looking for perf improvements, in the end I just cleaned up the code, using some modern Java.
=> Modernize and unit-test Benchmarker statistic code

.github/workflows/full-downstream.yml, .github/workflows/jenkins-tests-PR.yml, .github/workflows/jpa_integration_ci.yml, .github/workflows/pull_request.yml, .github/workflows/quarkus-snapshot.yaml, .github/workflows/sonarcloud.yml
https://issues.redhat.com/browse/PLANNER-2596
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1857
* https://github.com/kiegroup/kie-soup/pull/246
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/586
* https://github.com/kiegroup/drools/pull/4087
* https://github.com/kiegroup/optaplanner/pull/1746
* https://github.com/kiegroup/lienzo-core/pull/161
* https://github.com/kiegroup/lienzo-tests/pull/134
* https://github.com/kiegroup/appformer/pull/1225
* https://github.com/kiegroup/kie-uberfire-extensions/pull/131
* https://github.com/kiegroup/jbpm/pull/2082
* https://github.com/kiegroup/droolsjbpm-integration/pull/2676
* https://github.com/kiegroup/kie-wb-playground/pull/127
* https://github.com/kiegroup/kie-wb-common/pull/3715
* …
=> PLANNER-2596 [main] CI jobs: consistent naming

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/anchor/AnchorVariableDemand.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/CollectionInverseVariableDemand.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/SingletonInverseVariableDemand.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerNotifiable.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarSwapMoveTest.java
<details>
<summary>
</summary> …
=> Remove unused code

.ci/jenkins/Jenkinsfile.post-release.temp, .ci/jenkins/Jenkinsfile.promote
https://issues.redhat.com/browse/PLANNER-2603
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1722
Another PR will come with some testing and corrections done on `Jenkins.post-release.temp` file. For now, no other job will be created. I created this file to keep an idea of what should be done and just save the work as the file might not be that different from the temp one.
=> [8.15.x] PLANNER-2603 Extract quickstarts from promote (#1722)

.github/workflows/jpa_integration_ci.yml, .github/workflows/os_java_ci.yml, .github/workflows/pull_request.yml
https://issues.redhat.com/browse/PLANNER-2596
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1857
* https://github.com/kiegroup/kie-soup/pull/246
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/586
* https://github.com/kiegroup/drools/pull/4087
* https://github.com/kiegroup/optaplanner/pull/1746
* https://github.com/kiegroup/lienzo-core/pull/161
* https://github.com/kiegroup/lienzo-tests/pull/134
* https://github.com/kiegroup/appformer/pull/1225
* https://github.com/kiegroup/kie-uberfire-extensions/pull/131
* https://github.com/kiegroup/jbpm/pull/2082
* https://github.com/kiegroup/droolsjbpm-integration/pull/2676
* https://github.com/kiegroup/kie-wb-playground/pull/127
* https://github.com/kiegroup/kie-wb-common/pull/3715
* …
=> PLANNER-2596 CI jobs: consistent naming

.ci/jenkins/Jenkinsfile.deploy
Due to https://github.com/kiegroup/optaplanner-quickstarts/commit/3119ded80cd37068b3cad85789e6a0e4a47a0b25
cherry-pick: https://github.com/kiegroup/optaplanner/commit/1ea1f14fb52563b60af48747e9a24c4e67f32fc3
=> Corrected Jenkinsfile.deploy

.ci/jenkins/Jenkinsfile.post-release.temp, .ci/jenkins/Jenkinsfile.promote
This fix a small issue in the promote pipeline, introduced in https://github.com/kiegroup/optaplanner/commit/e93a7d4f17073f24d4bd6063790e8a28197d7949
=> Small issue in promote pipeline

.ci/jenkins/Jenkinsfile.post-release.temp, .ci/jenkins/Jenkinsfile.promote
This fix a small issue in the promote pipeline, introduced in https://github.com/kiegroup/optaplanner/commit/e93a7d4f17073f24d4bd6063790e8a28197d7949
=> [8.15.x] Small issue in promote pipeline

optaplanner-examples/src/main/java/org/optaplanner/examples/common/business/SolutionBusiness.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning_listvariable/swingui/TaskAssigningPanel.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning_listvariable/swingui/TaskOverviewPanel.java
1. Taking advantage of the possibility to iterate over each employees task.
2. Fixing bugs and unfinished UI editing features (unassigning of an assigned task and vice versa).
**I recommend to review each commit diff separately.**
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not …
=> Update TaskAssigning UI

optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning_listvariable/app/TaskAssigningApp.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning_listvariable/score/TaskAssigningConstraintProvider.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/taskassigning_listvariable/optional/benchmark/taskAssigningBenchmarkConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/taskassigning_listvariable/optional/benchmark/taskAssigningScoreDirectorBenchmarkConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/taskassigning_listvariable/optional/score/taskAssigningConstraints.drl, optaplanner-examples/src/main/resources/org/optaplanner/examples/taskassigning_listvariable/taskAssigningSolverConfig.xml, optaplanner-examples/src/test/java/org/optaplanner/examples/taskassigning_listvariable/optional/score/TaskAssigningScoreConstraintTest.java
Replicates 9ab908311b22acf121fcc340cedbc0c4c4f2b382 onto the list variable version of the Task Assigning example.
=> PLANNER-2635 Switch Task Assigning with list variable to Constraint Streams

optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/devui-integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/drl-integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/integration-test/pom.xml
https://issues.redhat.com/browse/PLANNER-2551
<details>
<summary>
</summary> …
=> PLANNER-2551 Exclude IT from coverage

optaplanner-docs/src/modules/ROOT/pages/planner-configuration/planner-configuration.adoc
<details>
<summary>
</summary> …
=> Add missing Gizmo restriction to docs

optaplanner-examples/src/main/resources/org/optaplanner/examples/examination/solver/examinationConstraints.drl
Cherry-Pick of
https://github.com/kiegroup/optaplanner/pull/1756
- [+] Documentation updated if applicable.
- [+] Upgrade recipe provided if applicable.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or …
=> PLANNER-2618 Workaround for MVEL regression (#1756)

optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java
See https://github.com/micrometer-metrics/micrometer/issues/2947.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and …
=> Disable a broken test until we upgrade to Metrics 1.7.8 (via Quarkus upgrade)

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/dsl/jobs.groovy, build/optaplanner-build-parent/pom.xml, build/release/release-procedure.adoc
Upstream PR: https://github.com/kiegroup/kogito-pipelines/pull/351
=> PLANNER-2641 OptaPlanner depends on Drools, not Kogito 

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.post-release.temp, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle
https://issues.redhat.com/browse/KOGITO-5531
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/214
- https://github.com/kiegroup/kogito-runtimes/pull/1446
- https://github.com/kiegroup/optaplanner/pull/1815
- https://github.com/kiegroup/kogito-apps/pull/942
- https://github.com/kiegroup/kogito-examples/pull/797
=> KOGITO-5531 Update Jenkins CI to Maven 3.8.1

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-6686
Related PRs:
- https://github.com/kiegroup/kogito-apps/pull/1222
- https://github.com/kiegroup/kogito-runtimes/pull/1960
- https://github.com/kiegroup/drools/pull/4173
- https://github.com/kiegroup/optaplanner/pull/1818
=> KOGITO-6686 Setup Apps PR check timeout to 210m

optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/placer/QueuedValuePlacerFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMoveSelectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarChangeMoveSelector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/SwapMoveSelectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainChangeMoveSelectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/ValueSelectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/chained/SubChainSelectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/decorator/SelectedCountLimitValueSelector.java
<details>
<summary>
</summary> …
=> Use getSimpleName() instead of hard-coded class name in strings

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java
Signed-off-by: Lukáš Petrovický <lpetrovi@redhat.com>
<details>
<summary>
</summary> …
=> PLANNER-2658 Register services unconditionally

optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/impl/IntervalTree.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/experimental/ExperimentalConstraintCollectorsTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/experimental/impl/IntervalTreeTest.java
Depends on #1852 
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with …
=> Add interval tree mutability test coverage

.ci/jenkins/dsl/jobs.groovy
- https://github.com/kiegroup/kogito-pipelines/pull/392
- https://github.com/kiegroup/kogito-runtimes/pull/2048
- https://github.com/kiegroup/optaplanner/pull/1859
=> [1.13.x] Remove kogito-apps from checks

optaplanner-docs/src/modules/ROOT/pages/repeated-planning/repeated-planning.adoc
<details>
<summary>
</summary> …
=> Mention real-time planning support in SolverManager

build/optaplanner-build-parent/pom.xml, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java
Depends on https://github.com/kiegroup/kogito-runtimes/pull/2035
=> [8.13.x] Bump Quarkus to 2.7.2

optaplanner-docs/src/modules/ROOT/pages/use-cases-and-examples/examples-overview/examples-overview.adoc, optaplanner-docs/src/modules/ROOT/pages/use-cases-and-examples/vehicle-routing/vehicle-routing.adoc, optaplanner-examples/src/main/java/org/optaplanner/examples/vehiclerouting/persistence/VehicleRoutingImporter.java
http://neo.lcc.uma.es/vrp become unavalible
<details>
<summary>
</summary> …
=> Update http://neo.lcc.uma.es/vrp to https

.ci/jenkins/dsl/jobs.groovy
- https://github.com/kiegroup/kogito-pipelines/pull/397
- https://github.com/kiegroup/kogito-runtimes/pull/2062
- https://github.com/kiegroup/optaplanner/pull/1866
- https://github.com/kiegroup/optaplanner-quickstarts/pull/300
- https://github.com/kiegroup/kogito-examples/pull/1160
- https://github.com/kiegroup/kogito-images/pull/1155
=> [8.13.x] Remove native checks

.ci/jenkins/Jenkinsfile.post-release
<details>
<summary>
</summary> …
=> [8.19.x] Correct Post Release job

optaplanner-docs/src/modules/ROOT/pages/planner-configuration/planner-configuration.adoc
<details>
<summary>
</summary> …
=> Typo fix: asSolution -> a Solution

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/io/jaxb/SolverConfigIO.java
<details>
<summary>
</summary> …
=> Improve a fail fast message

optaplanner-examples/src/main/java/org/optaplanner/examples/meetingscheduling/score/MeetingSchedulingConstraintProvider.java
- Every time `calculateOverlap(...)` is used, a non-null startingTimeGrain is required.
- Using a filtered nested stream is preferrable to using a filtering joiner.
=> Align meetingscheduling constraint provider with DRL

optaplanner-docs/src/modules/ROOT/pages/score-calculation/score-calculation.adoc
<details>
<summary>
</summary> …
=> Remove duplicated class name string in invalid score detection docs

core/optaplanner-constraint-streams/src/test/java/org/optaplanner/constraint/streams/bavet/common/index/EqualsAndComparisonIndexerTest.java, core/optaplanner-constraint-streams/src/test/java/org/optaplanner/constraint/streams/bavet/common/index/EqualsIndexerTest.java, core/optaplanner-constraint-streams/src/test/java/org/optaplanner/constraint/streams/bavet/common/index/NoneIndexerTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/config/constructionheuristic/placer/PooledEntityPlacerFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/entity/decorator/FilteringEntitySelectorTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/score/director/ScoreDirectorFactoryFactoryTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/PolymorphicScoreJaxbAdapterTest.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java
<details>
<summary>
</summary> …
=> Tests cleanup

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/director/ScoreDirectorFactoryFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/stream/JoinerSupport.java
<details>
<summary>
</summary> …
=> Improve exception message

README.adoc
due to:
* https://github.com/kiegroup/optaplanner/pull/1889
<details>
<summary>
</summary> …
=> Fix Chain Status webpage link

build/optaplanner-build-parent/pom.xml
backport of https://issues.redhat.com/browse/PLANNER-2686
<details>
<summary>
</summary> …
=> [8.13.x] backport of PLANNER-2686

optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml
https://issues.redhat.com/browse/BXMSPROD-1673
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1938
* https://github.com/kiegroup/optaplanner/pull/1916
* https://github.com/kiegroup/droolsjbpm-integration/pull/2760
<details>
<summary>
</summary>
[build-chain …
=> [7.67.x]  [BXMSPROD-1673] spring-boot to 2.6.6

optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml
https://issues.redhat.com/browse/BXMSPROD-1673
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1936
* https://github.com/kiegroup/optaplanner/pull/1915
*https://github.com/kiegroup/droolsjbpm-integration/pull/2758
<details>
<summary>
</summary>
[build-chain …
=> [7.59.x] [BXMSPROD-1673] spring-boot to 2.6.6

optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml
https://issues.redhat.com/browse/BXMSPROD-1673
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1935
* https://github.com/kiegroup/optaplanner/pull/1910
* https://github.com/kiegroup/droolsjbpm-integration/pull/2759
* https://github.com/kiegroup/optaplanner/pull/1909
* https://github.com/kiegroup/optaplanner-quickstarts/pull/317
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …
=> [7.x] BXMSPROD-1673 spring-boot to 2.6.6

core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BavetAbstractBiConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/BavetAbstractTriConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/BavetAbstractUniConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bi/BiConstraintStreamHelper.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bi/DefaultBiJoiner.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bi/InnerBiConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/common/AbstractConstraintStreamHelper.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/common/InnerConstraintFactory.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/bi/DroolsAbstractBiConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/tri/DroolsAbstractTriConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/uni/DroolsAbstractUniConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/penta/DefaultPentaJoiner.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/quad/DefaultQuadJoiner.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/tri/DefaultTriJoiner.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/tri/InnerTriConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/tri/TriConstraintStreamHelper.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/uni/InnerUniConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/uni/UniConstraintStreamHelper.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/stream/ConstraintFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/stream/bi/BiConstraintStream.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/stream/tri/TriConstraintStream.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/stream/uni/UniConstraintStream.java
<details>
<summary>
</summary> …
=> PLANNER-2688 Streamline CS join call graph

core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BavetAbstractBiConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BiScorer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/GroupBiToBiNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/GroupUniToBiNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/JoinBiNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/BavetAbstractConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/BavetTupleState.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/Tuple.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/BavetAbstractTriConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/JoinTriNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/TriScorer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/BavetAbstractUniConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/BavetIfExistsBridgeUniConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/BavetIfExistsUniConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/ForEachUniNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/IfExistsUniWithUniNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/UniScorer.java, core/optaplanner-constraint-streams/src/test/java/org/optaplanner/constraint/streams/uni/UniConstraintStreamTest.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/stream/uni/UniConstraintStream.java
=> PLANNER-2690 Uni.ifExists() (1 joiner, no filters for now)

core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/GroupBiToBiNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/GroupUniToBiNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/JoinBiNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/EqualsAndComparisonIndexer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/EqualsIndexer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/Indexer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/NoneIndexer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/JoinTriNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/IfExistsUniWithUniNode.java, core/optaplanner-constraint-streams/src/test/java/org/optaplanner/constraint/streams/bavet/common/index/AbstractIndexerTest.java, core/optaplanner-constraint-streams/src/test/java/org/optaplanner/constraint/streams/bavet/common/index/EqualsAndComparisonIndexerTest.java, core/optaplanner-constraint-streams/src/test/java/org/optaplanner/constraint/streams/bavet/common/index/EqualsIndexerTest.java, core/optaplanner-constraint-streams/src/test/java/org/optaplanner/constraint/streams/bavet/common/index/NoneIndexerTest.java
<details>
<summary>
</summary> …
=> Improve nqueens CS-B performance by further 10 %

build/optaplanner-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-6929
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/2137
- https://github.com/kiegroup/kogito-examples/pull/1215
- https://github.com/kiegroup/optaplanner/pull/1931
- https://github.com/kiegroup/kogito-apps/pull/1299
Related to https://github.com/kiegroup/kogito-runtimes/pull/2120
=> [1.11.x] KOGITO-6929 spring-boot to 2.6.6

core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/AbstractDrlScoreDirectorFactoryService.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-6036
Related PRs:
https://github.com/kiegroup/drools/pull/4311
https://github.com/kiegroup/kogito-runtimes/pull/2153
https://github.com/kiegroup/optaplanner/pull/1939
https://github.com/kiegroup/kogito-apps/pull/1306
=> [DROOLS-6036] move util classes into a separated module

core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/IfExistsUniWithUniNode.java
A 2 line change that took 2 days to figure out.
@triceo Reviewing your PR this afternoon (this won't merge conflict).
=> Fix IfExists score corruption

optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/swingui/TaskOverviewPanel.java, optaplanner-examples/src/main/java/org/optaplanner/examples/tsp/swingui/TspListPanel.java, optaplanner-examples/src/main/java/org/optaplanner/examples/tsp/swingui/TspPanel.java, optaplanner-examples/src/main/java/org/optaplanner/examples/tsp/swingui/TspWorldPanel.java
This is a partial fix but it works unless you click the map really fast.
A complete fix requires a deeper review of the existing code that wasn't
designed to work with real-time problem changes.
https://issues.redhat.com/browse/PLANNER-2687
<details>
<summary>
</summary>
[build-chain …
=> PLANNER-2687 Fix TSP problem change

core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BavetJoinBiConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/JoinBiNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/BavetJoinTriConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/JoinTriNode.java
Most of the perf loss is gone with this, but it's still slower.
I'll try a few things more, on top of this commit, maybe in a separate branch.
=> CS-B: get rid of removeAll() call

build/optaplanner-ide-config/ide-configuration.adoc
After completing the steps you should be able to organize imports by Ctrl+Shift+O
And format file by Ctrl+Shift+I
In addition to
https://issues.redhat.com/browse/PLANNER-2684
https://github.com/dupliaka/optaplanner/tree/PLANNER-2684
<details>
<summary>
</summary>
[build-chain …
=> Add VS code setup formatting

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/ConsumerSupport.java
https://issues.redhat.com/browse/PLANNER-2708
<details>
<summary>
</summary> …
=> PLANNER-2708 Dispose consumer thread after termination

optaplanner-benchmark/src/main/java/org/optaplanner/swing/impl/SwingUncaughtExceptionHandler.java
Exception stack trace can now be copied to the clipboard with a single click on the Copy button.
The difference between `NORTH` and `PAGE_START` is explained in https://docs.oracle.com/javase/tutorial/uiswing/layout/border.html.
<details>
<summary>
</summary>
[build-chain …
=> Add Copy to clipboard button to exception dialog

core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/ComparisonIndexer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/EqualsIndexer.java
This PR has no measurable effect on performance.
=> CS-B: Clean up the ComparisonIndexer

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-7100
Related PRs:
- https://github.com/kiegroup/drools/pull/4355
- https://github.com/kiegroup/optaplanner/pull/1966
- https://github.com/kiegroup/kogito-runtimes/pull/2187
- https://github.com/kiegroup/kogito-apps/pull/1330
- https://github.com/kiegroup/kogito-examples/pull/1244
- https://github.com/kiegroup/kogito-images/pull/1251
- https://github.com/kiegroup/kogito-operator/pull/1183
=> [KOGITO-7100] Jenkinsfiles: Corrected boolean env var handling

.ci/jenkins/Jenkinsfile.native, .ci/jenkins/dsl/jobs.groovy, .github/pull_request_template.md
https://issues.redhat.com/browse/KOGITO-7110
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/438
- https://github.com/kiegroup/drools/pull/4364
- https://github.com/kiegroup/kogito-runtimes/pull/2192
- https://github.com/kiegroup/kogito-apps/pull/1332
- https://github.com/kiegroup/kogito-examples/pull/1247
- https://github.com/kiegroup/kogito-images/pull/1252
- https://github.com/kiegroup/kogito-operator/pull/1184
- https://github.com/kiegroup/optaplanner/pull/1969
=> KOGITO-7110 Correct nightly DSL generation

optaplanner-examples/src/main/java/org/optaplanner/examples/vehiclerouting/swingui/VehicleRoutingPanel.java
There was a ConcurrentModificationException coming from problem changes in the vehicle routing example. 
https://issues.redhat.com/browse/PLANNER-2696
<details>
<summary>
</summary> …
=> PLANNER-2696 Fix CME in VehicleRouting

.ci/jenkins/dsl/jobs.groovy, .github/pull_request_template.md
Also see https://github.com/kiegroup/kogito-examples/pull/1258
=> [8.13.x] PLANNER-2723 OptaPlanner no longer part of kogito-examples

core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractJoinNode.java
Brings conferencescheduling from 750 to 1250.
Brings curriculumcourse from 41000 to 46000.
Other benchmarks are still running, but the benefits are already obvious.
=> PLANNER-2702 Improve CS-B join performance by not storing maps on the right

optaplanner-docs/src/modules/ROOT/pages/score-calculation/score-calculation.adoc
<details>
<summary>
</summary> …
=> Use correct ScoreManager API in docs

build/optaplanner-build-parent/pom.xml
- https://github.com/kiegroup/drools/pull/4412
- https://github.com/kiegroup/optaplanner/pull/1997
- https://github.com/kiegroup/optaplanner-quickstarts/pull/342
- https://github.com/kiegroup/kogito-runtimes/pull/2217
- https://github.com/kiegroup/kogito-examples/pull/1265
=> [8.22.x] Bump Quarkus version to 2.9.1.Final

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/entity/descriptor/EntityDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerSupport.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhaseFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/director/AbstractScoreDirector.java
https://issues.redhat.com/browse/PLANNER-2715
<details>
<summary>
</summary> …
=> PLANNER-2715 Variable listener cleanup

optaplanner-examples/src/main/java/org/optaplanner/examples/flightcrewscheduling/domain/Flight.java, optaplanner-examples/src/main/java/org/optaplanner/examples/flightcrewscheduling/domain/FlightAssignment.java
https://issues.redhat.com/browse/PLANNER-2738
<details>
<summary>
</summary> …
=> PLANNER-2738 Make FlightAssignment comparator consistent with equals

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle, .ci/jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-7356
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/485
- https://github.com/kiegroup/kogito-runtimes/pull/2255
- https://github.com/kiegroup/kogito-examples/pull/1286
- https://github.com/kiegroup/kogito-images/pull/1276
- https://github.com/kiegroup/kogito-operator/pull/1205
- https://github.com/kiegroup/optaplanner/pull/2025
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/709
- https://github.com/kiegroup/optaweb-employee-rostering/pull/827
- https://github.com/kiegroup/optaplanner-quickstarts/pull/353
=> [8.13.x-blue] KOGITO-7356 Do not use master node in pipelines (#2023)

core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/thread/OrderByMoveIndexBlockingQueueTest.java
The order of the `b1` move and the `IllegalArgumentException` in the queue might have swapped (a race condition).
<details>
<summary>
</summary> …
=> PLANNER-2733 Stabilize a randomly failing test

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/violation/ShadowVariableSnapshot.java
<details>
<summary>
</summary> …
=> Add snapshot toString() to improve debugging experience

.ci/jenkins/config/main.yaml
Dependent PR: https://github.com/kiegroup/kogito-pipelines/pull/538
Please merge this one first.
=> Pipelines DSL: harcode seed branch

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.drools, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.post-release, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.quarkus, .ci/jenkins/Jenkinsfile.turtle, .ci/jenkins/config/branch.yaml, .ci/jenkins/dsl/jobs.groovy
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/269
- https://github.com/kiegroup/drools/pull/4518
- https://github.com/kiegroup/kogito-runtimes/pull/1622
- https://github.com/kiegroup/kogito-apps/pull/1405
- https://github.com/kiegroup/kogito-examples/pull/1323
- https://github.com/kiegroup/kogito-operator/pull/1239
- https://github.com/kiegroup/optaplanner/pull/2061
=> KOGITO-5780 Set JDK and Maven tools as env vars

build/optaplanner-build-parent/pom.xml, core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/DrlScoreDirectorFactoryService.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/DroolsConstraintStreamScoreDirectorFactory.java
bumped up Drools to 8.24.0.Beta
=> bumped up Drools to 8.24.0.Beta

optaplanner-docs/src/modules/ROOT/pages/optimization-algorithms/optimization-algorithms.adoc
Based on user feedback in zulip
=> Async termination docs clean up

.ci/jenkins/Jenkinsfile.quarkus
cherry-pick: https://github.com/kiegroup/optaplanner/pull/2057
=> [8.24.x] KOGITO-7496 Update quarkus nightly to compare dependencies

.github/workflows/full-downstream.yml, .github/workflows/jpa_integration_ci.yml, .github/workflows/pull_request.yml, .github/workflows/quarkus-snapshot.yml, .github/workflows/sonarcloud.yml
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/543
- https://github.com/kiegroup/kogito-runtimes/pull/2317
- https://github.com/kiegroup/kogito-apps/pull/1407
- https://github.com/kiegroup/kogito-examples/pull/1324
- https://github.com/kiegroup/drools/pull/4525
- https://github.com/kiegroup/optaplanner/pull/2063
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/728
- https://github.com/kiegroup/optaweb-employee-rostering/pull/841
=> [KOGITO-7504] Update Maven to 3.8.6

.ci/jenkins/config/branch.yaml
<details>
<summary>
</summary> …
=> [KOGITO-7504] Update DSL Config Maven to 3.8.6

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/solver/SolverConfig.java
Make it easier to switch between Drools/Bavet in plain java (see hello world java quickstart)
=> SolverConfig.withConstraintStreamImplType(...)

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/config/branch.yaml, .ci/jenkins/dsl/jobs.groovy, .github/pull_request_template.md, build/release/release-procedure.adoc
Upstream PR: https://github.com/kiegroup/kogito-pipelines/pull/560
Downstream PR: https://github.com/kiegroup/optaplanner-website/pull/521
=> PLANNER-2753 Remove references to optaweb-employee-rostering

core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/bi/IfExistsBiWithUniNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractIfExistsNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractJoinNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/quad/IfExistsQuadWithUniNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/tri/IfExistsTriWithUniNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/uni/IfExistsUniWithUniNode.java
=> ifExists modify 

core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/bi/IfExistsBiWithUniNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractGroupNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractIfExistsNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractJoinNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/ComparisonIndexer.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/EqualsIndexer.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/IndexProperties.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/ManyIndexProperties.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/NoneIndexProperties.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/SingleIndexProperties.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/ThreeIndexProperties.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/TwoIndexProperties.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/quad/IfExistsQuadWithUniNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/tri/IfExistsTriWithUniNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/uni/IfExistsUniWithUniNode.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/MutablePair.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/MutableQuadruple.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/MutableReference.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/MutableTriple.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/Pair.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/PairImpl.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/Quadruple.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/QuadrupleImpl.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/Triple.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/TripleImpl.java
The goal of these changes is cleaner code and reduction in duplication, not more performance.
Even then, one example still shows 25 % increase in performance, with minor improvements across the board.
=> CS: Various cleanup

optaplanner-examples/src/test/java/org/optaplanner/examples/common/persistence/OpenDataFilesTest.java
Fixes concurrency issues stemming from the existence or non-existence of directories.
=> No need to use SolutionBusiness on OpenDataFilesTest

optaplanner-docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc
Companion: https://github.com/kiegroup/optaplanner-quickstarts/pull/388
=> PLANNER-2709 Document building executable app

core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/DrlScoreDirectorFactoryService.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/bendable/BendableScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/bendablebigdecimal/BendableBigDecimalScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/bendablelong/BendableLongScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoft/HardMediumSoftScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftlong/HardMediumSoftLongScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/hardsoft/HardSoftScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftlong/HardSoftLongScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/simple/SimpleScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/simplebigdecimal/SimpleBigDecimalScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/simplelong/SimpleLongScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/holder/ScoreHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java, optaplanner-docs/src/modules/ROOT/pages/drools-score-calculation/drools-score-calculation.adoc, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/AbstractScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/bendable/BendableScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/bendablebigdecimal/BendableBigDecimalScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/bendablelong/BendableLongScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/hardmediumsoft/HardMediumSoftScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/hardmediumsoftlong/HardMediumSoftLongScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/hardsoft/HardSoftScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/hardsoftlong/HardSoftLongScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/simple/SimpleScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/simplebigdecimal/SimpleBigDecimalScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/simplelong/SimpleLongScoreVerifier.java
Side effects of https://github.com/kiegroup/optaplanner-website/pull/525
=> Move drl migration guide into upgrade recipes

.ci/jenkins/config/main.yaml
This will save some disk space on Jenkins
=> DSL: Remove not needed branches

optaplanner-docs/src/modules/ROOT/pages/local-search/local-search.adoc
<details>
<summary>
</summary> …
=> Fix typo in local search acceptor docs

.ci/jenkins/config/branch.yaml
=> DSL: Update Mandrel version

.ci/jenkins/config/branch.yaml
=> [8.27.x] DSL: Update Mandrel version

.ci/jenkins/dsl/jobs.groovy
backport: https://github.com/kiegroup/optaplanner/pull/2165
=> Correct project pipelines' path

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/gizmo/GizmoSolutionClonerImplementor.java
Clone helper methods are called to get instructions on how to clone
a particular class. Special care is needed for interfaces and
abstract classes, which cannot be created directly (meaning
all instances are subclasses of the interface/abstract class).
The helper methods for interfaces and abstract base classes
call the helper method that correspond to the class of the
instance (and if it cannot find the class because it not
a planning entity, it is shallowly cloned).
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use …
=> PLANNER-2796 Add clone helper methods for interfaces and abstract classes in Gizmo

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/gizmo/GizmoSolutionClonerImplementor.java
Clone helper methods are called to get instructions on how to clone a particular class. Special care is needed for interfaces and abstract classes, which cannot be created directly (meaning all instances are subclasses of the interface/abstract class). The helper methods for interfaces and abstract base classes call the helper method that correspond to the class of the instance (and if it cannot find the class because it not a planning entity, it is shallowly cloned).
=> [8.27.x] PLANNER-2796 Add clone helper methods for interfaces and abstract classes in Gizmo (#2178)

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/violation/ShadowVariableSnapshot.java
Relates to https://stackoverflow.com/questions/73753525/optaplanner-score-corruption-with-custom-shadow-variable-calculation-based-on-ch/73769796#73769796
=> Improve error message for assertShadowVariablesAreNotStale

.ci/jenkins/project/Jenkinsfile.release
=> Corrected release pipeline

.github/workflows/pull_request.yml, optaplanner-docs/src/modules/ROOT/pages/release-notes/release-notes-8.adoc
=> PLANNER-2807 Use JDK 19 in GitHub Actions

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.init-branch, .ci/jenkins/Jenkinsfile.prod.nightly, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle, .ci/jenkins/project/Jenkinsfile.init-branch, .ci/jenkins/project/Jenkinsfile.native, .ci/jenkins/project/Jenkinsfile.nightly, .ci/jenkins/project/Jenkinsfile.post-release, .ci/jenkins/project/Jenkinsfile.release
https://issues.redhat.com/browse/KOGITO-8043
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/631
- https://github.com/kiegroup/drools/pull/4723
- https://github.com/kiegroup/kogito-runtimes/pull/2525
- https://github.com/kiegroup/kogito-apps/pull/1483
- https://github.com/kiegroup/kogito-examples/pull/1423
- https://github.com/kiegroup/kogito-images/pull/1342
- https://github.com/kiegroup/kogito-operator/pull/1293
- https://github.com/kiegroup/kogito-docs/pull/218
- https://github.com/kiegroup/kie-tools/pull/1249
- https://github.com/kiegroup/optaplanner/pull/2219
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/760
- https://github.com/kiegroup/optaplanner-quickstarts/pull/415
=> KOGITO-8043 Jenkins node master -> built-in

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.init-branch, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle, .ci/jenkins/project/Jenkinsfile.init-branch, .ci/jenkins/project/Jenkinsfile.native, .ci/jenkins/project/Jenkinsfile.nightly, .ci/jenkins/project/Jenkinsfile.post-release, .ci/jenkins/project/Jenkinsfile.release
https://issues.redhat.com/browse/KOGITO-8043
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/635
- https://github.com/kiegroup/optaplanner/pull/2220
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/761
- https://github.com/kiegroup/optaplanner-quickstarts/pull/416
=> [8.28.x] KOGITO-8043 Jenkins node master -> built-in

optaplanner-examples/src/main/java/org/optaplanner/examples/projectjobscheduling/swingui/ProjectJobSchedulingPanel.java
<details>
<summary>
</summary> …
=> Use Tango colors in Project job scheduling

build/optaplanner-build-parent/pom.xml
https://github.com/kiegroup/optaplanner/pull/2226
<details>
<summary>
</summary> …
=> Bump Spring Boot version to 2.7.4

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/ProblemBasedSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/PureSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/SubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/bestscore/BestScoreSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/bestsolutionmutation/BestSolutionMutationSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/memoryuse/MemoryUseSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/movecountperstep/MoveCountPerStepSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/scorecalculationspeed/ScoreCalculationSpeedSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/stepscore/StepScoreSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/subsingle/constraintmatchtotalbestscore/ConstraintMatchTotalBestScoreSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/subsingle/constraintmatchtotalstepscore/ConstraintMatchTotalStepScoreSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/subsingle/pickedmovetypebestscore/PickedMoveTypeBestScoreDiffSubSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/subsingle/pickedmovetypestepscore/PickedMoveTypeStepScoreDiffSubSingleStatistic.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/AbstractSubSingleStatisticTest.java
<details>
<summary>
</summary> …
=> PLANNER-2821 Fix serialization of SubSingleStatistic

build/optaplanner-build-parent/pom.xml, core/optaplanner-core-impl/pom.xml, core/optaplanner-core-impl/src/main/resources/solver.xsd, optaplanner-benchmark/pom.xml, optaplanner-benchmark/src/main/resources/benchmark.xsd
https://issues.redhat.com/browse/PLANNER-2802
<details>
<summary>
</summary> …
=> PLANNER-2802 Keep XSDs in src

optaplanner-test/pom.xml, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/AbstractConstraintVerification.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultMultiConstraintVerification.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultSingleConstraintVerification.java
<details>
<summary>
</summary> …
=> PLANNER-2810 Log a warning on suspicious use of ConstraintVerifier

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/domain/variable/AbstractVariableListener.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/domain/variable/ListVariableListener.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/domain/variable/ShadowVariable.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/calculator/IncrementalScoreCalculator.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/director/ScoreDirector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/custom/CustomShadowVariableDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/index/ExternalizedIndexVariableSupply.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/index/IndexVariableListener.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedSingletonListInverseVariableSupply.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/SingletonListInverseVariableListener.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/AbstractNotifiable.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/ElementUnassignedNotification.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/ListVariableChangedNotification.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/ListVariableListenerNotifiable.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/ListVariableNotification.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/nextprev/NextElementVariableListener.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/nextprev/PreviousElementVariableListener.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/director/AbstractScoreDirector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/director/InnerScoreDirector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/director/incremental/IncrementalScoreDirector.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testdata/domain/shadow/wrong_listener/TestdataWrongBasicShadowEntity.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/domain/solver/StartTimeUpdatingVariableListener.java, optaplanner-examples/src/main/java/org/optaplanner/examples/vehiclerouting/optional/score/VehicleRoutingIncrementalScoreCalculator.java, optaplanner-examples/src/main/java/org/optaplanner/examples/vehiclerouting/swingui/VehicleRoutingPanel.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/vehiclerouting/vehicleRoutingSolverConfig.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/DotNames.java
https://issues.redhat.com/browse/PLANNER-2711
<details>
<summary>
</summary> …
=> PLANNER-2711 Incremental score calculation for list variable

core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testutil/DisabledInProductization.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testutil/DisabledInProductizationCheck.java, core/optaplanner-core/pom.xml, core/pom.xml, optaplanner-examples/pom.xml, optaplanner-examples/src/test/java/org/optaplanner/examples/common/app/SolveAllTurtleTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/app/SolverSmokeTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/score/AbstractConstraintProviderTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorSolverPropertiesBavetTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorSolverPropertiesTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/verifier/OptaPlannerConstraintVerifierBavetStreamImplTest.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/pom.xml, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java
<details>
<summary>
</summary> …
=> PLANNER-2831 Disable CS-B in a productized profile

optaplanner-docs/src/modules/ROOT/pages/constraint-streams/constraint-streams.adoc
<details>
<summary>
</summary> …
=> CS docs: Bavet no longer experimental

core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testutil/DisabledInProductization.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testutil/DisabledInProductizationCheck.java, core/optaplanner-core/pom.xml, core/pom.xml, optaplanner-docs/src/modules/ROOT/pages/constraint-streams/constraint-streams.adoc, optaplanner-examples/pom.xml, optaplanner-examples/src/test/java/org/optaplanner/examples/common/app/SolveAllTurtleTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/app/SolverSmokeTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/score/AbstractConstraintProviderTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorSolverPropertiesBavetTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorSolverPropertiesTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/verifier/OptaPlannerConstraintVerifierBavetStreamImplTest.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/pom.xml, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java
To be merged after 8.29.0.Final is released.
=> [8.29.x] PLANNER-2831 Disable CS-B in a productized profile

.ci/jenkins/dsl/test.sh, .github/workflows/jenkins-tests-PR.yml, .github/workflows/jpa_integration_ci.yml, .github/workflows/quarkus-snapshot.yml, .github/workflows/sonarcloud.yml
https://issues.redhat.com/browse/KOGITO-8110
- https://github.com/kiegroup/kogito-pipelines/pull/646
- https://github.com/kiegroup/drools/pull/4738
- https://github.com/kiegroup/kogito-runtimes/pull/2547
- https://github.com/kiegroup/kogito-apps/pull/1489
- https://github.com/kiegroup/kogito-examples/pull/1440
- https://github.com/kiegroup/kogito-images/pull/1348
- https://github.com/kiegroup/kogito-operator/pull/1305
- https://github.com/kiegroup/kogito-docs/pull/228
- https://github.com/kiegroup/optaplanner/pull/2242
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/770
- https://github.com/kiegroup/optaplanner-quickstarts/pull/428
- https://github.com/kiegroup/kie-tools/pull/1271
=> KOGITO-8110 Correct GHA DSL checks

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/director/ScoreDirectorFactoryFactory.java
<details>
<summary>
</summary> …
=> Improve score director config fail fast

.ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh, .github/workflows/jenkins-tests-PR.yml, .github/workflows/jpa_integration_ci.yml, .github/workflows/quarkus-snapshot.yml, .github/workflows/sonarcloud.yml
cherry-picks: 
- https://github.com/kiegroup/optaplanner/pull/2251
- https://github.com/kiegroup/optaplanner/pull/2242
=> [8.29.x] Update Quarkus job: Compare dependencies (#2251)

.github/workflows/jenkins-tests-PR.yml
Related PRs:
- https://github.com/kiegroup/optaplanner/pull/2277
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/787
- https://github.com/kiegroup/optaplanner-quickstarts/pull/442
=> Correct GHA DSL check on release branch

core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/DrlScoreDirector.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/DroolsConstraintStreamScoreDirector.java
<details>
<summary>
</summary> …
=> PLANNER-2839 Don't fail fast on evicted Drools facts

core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/BavetConstraintSession.java
<details>
<summary>
</summary> …
=> CS-B: Marginally improve fact manipulation performance

build/optaplanner-build-parent/pom.xml
A cherry-pick of https://github.com/kiegroup/optaplanner/pull/2282.
https://issues.redhat.com/browse/RHBOP-22
<details>
<summary>
</summary> …
=> [8.29.x] RHBOP-22 Do not clear output directory with jaxb2:schemagen

build/optaplanner-build-parent/pom.xml
https://issues.redhat.com/browse/RHBOP-22
<details>
<summary>
</summary> …
=> RHBOP-22 Do not clear output directory with jaxb2:schemagen

build/optaplanner-build-parent/pom.xml, build/optaplanner-distribution-internal/src/main/assembly/assembly-optaplanner.xml, build/release/upload_distribution.sh, optaplanner-docs/pom.xml, optaplanner-docs/src/main/assembly/generated-docs-zip.xml
<details>
<summary>
</summary> …
=> Solve GHA OOM issues when generating docs ZIP

optaplanner-docs/src/modules/ROOT/pages/planner-configuration/planner-configuration.adoc
- Warn the user not to use list variable if any of the unsupported features are needed.
- Remove CH from the list because it's not a limitation.
- Minor improvements (active voice, consistent usage of vehicle routing, xrefs, etc.).
<details>
<summary>
</summary>
[build-chain …
=> Improve list variable documentation

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/domain/variable/PlanningVariableGraphType.java, optaplanner-docs/src/modules/ROOT/pages/benchmarking-and-tweaking/benchmarking-and-tweaking.adoc, optaplanner-docs/src/modules/ROOT/pages/constraint-streams/constraint-streams.adoc, optaplanner-docs/src/modules/ROOT/pages/design-patterns/design-patterns.adoc, optaplanner-docs/src/modules/ROOT/pages/exhaustive-search/exhaustive-search.adoc, optaplanner-docs/src/modules/ROOT/pages/local-search/local-search.adoc, optaplanner-docs/src/modules/ROOT/pages/move-and-neighborhood-selection/move-and-neighborhood-selection.adoc, optaplanner-docs/src/modules/ROOT/pages/optimization-algorithms/optimization-algorithms.adoc, optaplanner-docs/src/modules/ROOT/pages/planner-configuration/planner-configuration.adoc, optaplanner-docs/src/modules/ROOT/pages/planner-introduction/planner-introduction.adoc, optaplanner-docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc, optaplanner-docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc, optaplanner-docs/src/modules/ROOT/pages/quickstart/school-timetabling/school-timetabling-solution.adoc, optaplanner-docs/src/modules/ROOT/pages/quickstart/spring-boot/spring-boot-quickstart.adoc, optaplanner-docs/src/modules/ROOT/pages/release-notes/release-notes-8.adoc, optaplanner-docs/src/modules/ROOT/pages/score-calculation/score-calculation.adoc, optaplanner-docs/src/modules/ROOT/pages/use-cases-and-examples/cloud-balancing/cloud-balancing.adoc
<details>
<summary>
</summary> …
=> Various documentation fixes

optaplanner-persistence/optaplanner-persistence-xstream/pom.xml
From GraalVM 22.3.0 onward, the package `com.oracle.svm.core.annotate` used by the `Target_SerializableConverter` moves to `org.graalvm.sdk:graal-sdk`.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or …
=> Package com.oracle.svm.core.annotate moves to graal-sdk

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/constructionheuristic/placer/QueuedEntityPlacerConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/chained/TailChainSwapMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/entity/descriptor/EntityDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/anchor/ExternalizedAnchorVariableSupply.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/index/ExternalizedIndexVariableSupply.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedCollectionInverseVariableSupply.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedSingletonInverseVariableSupply.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedSingletonListInverseVariableSupply.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/InverseRelationShadowVariableDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverFactory.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/domain/entity/descriptor/EntityDescriptorTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/domain/solution/mutation/MutationCounterTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testdata/domain/chained/multientity/TestdataChainedBrownEntity.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testdata/domain/chained/multientity/TestdataChainedGreenEntity.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testdata/domain/chained/multientity/TestdataChainedMultiEntityAnchor.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testdata/domain/chained/multientity/TestdataChainedMultiEntityChainElement.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testdata/domain/chained/multientity/TestdataChainedMultiEntitySolution.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testdata/domain/extended/entity/TestdataExtendedEntitySolution.java, optaplanner-docs/src/modules/ROOT/pages/release-notes/release-notes-8.adoc
https://issues.redhat.com/browse/PLANNER-2798
<details>
<summary>
</summary> …
=> PLANNER-2798 Allow multiple entities with chained variables

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/valuerange/buildin/primdouble/DoubleValueRange.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/FromSolutionPropertyValueSelector.java
<details>
<summary>
</summary> …
=> Better exception when DoubleValueRange used with caching selector

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/Score.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/common/accessor/AbstractMemberAccessor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/common/accessor/gizmo/GizmoMemberDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/constraintweight/descriptor/ConstraintConfigurationDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/localsearch/decider/acceptor/tabu/AbstractTabuAcceptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/localsearch/decider/forager/AcceptedLocalSearchForager.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/domain/variable/custom/CustomVariableListenerTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/partitionedsearch/TestdataSolutionPartitioner.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/partitionedsearch/queue/PartitionQueueTest.java, optaplanner-docs/src/modules/ROOT/pages/local-search/local-search.adoc, optaplanner-examples/src/main/java/org/optaplanner/examples/examination/domain/Examination.java, optaplanner-examples/src/main/java/org/optaplanner/examples/meetingscheduling/domain/MeetingAssignment.java, optaplanner-examples/src/test/java/org/optaplanner/examples/pas/score/PatientAdmissionScheduleConstraintProviderTest.java
<details>
<summary>
</summary> …
=> Fix typos and minor code style issues

optaplanner-docs/src/modules/ROOT/pages/shadow-variable/shadow-variable.adoc
<details>
<summary>
</summary> …
=> Change @CustomShadowVariable to @ShadowVariable in "Shadow variable cloning"

optaplanner-persistence/optaplanner-persistence-jackson/src/main/java/org/optaplanner/persistence/jackson/api/OptaPlannerJacksonModule.java, optaplanner-persistence/optaplanner-persistence-jackson/src/main/java/org/optaplanner/persistence/jackson/impl/domain/solution/JacksonSolutionFileIO.java, optaplanner-persistence/optaplanner-persistence-jackson/src/main/resources/META-INF/services/com.fasterxml.jackson.databind.Module, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/integration-test/src/test/java/org/optaplanner/quarkus/jackson/it/OptaPlannerTestResourceTest.java, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/runtime/src/main/java/org/optaplanner/quarkus/jackson/OptaPlannerObjectMapperCustomizer.java
<details>
<summary>
</summary> …
=> PLANNER-2866 Make OptaPlannerJacksonModule a service

.ci/jenkins/project/Jenkinsfile.post-release
<details>
<summary>
</summary> …
=> added hash for uniqueness of branch

build/optaplanner-build-parent/pom.xml, optaplanner-examples/pom.xml, optaplanner-examples/src/main/java/org/optaplanner/examples/common/persistence/AbstractXmlSolutionExporter.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/persistence/AbstractXmlSolutionImporter.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nurserostering/persistence/NurseRosteringExporter.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nurserostering/persistence/NurseRosteringImporter.java
Especially the `jdom` version was ancient.
=> Bump dependency versions in examples

.ci/buildchain-config.yaml, .ci/buildchain-project-dependencies.yaml, .ci/chain-status-info.md, .ci/jenkins/config/branch.yaml, .github/workflows/full-downstream.yml, .github/workflows/generate_status_page_data.yaml, .github/workflows/pull_request.yml
to main optaplanner repository
https://issues.redhat.com/browse/PLANNER-2868
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/720
- https://github.com/kiegroup/optaplanner/pull/2388
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/821
- https://github.com/kiegroup/optaplanner-quickstarts/pull/462
=> PLANNER-2868 Move build-chain config

optaplanner-examples/src/main/java/org/optaplanner/examples/nurserostering/persistence/NurseRosteringImporter.java
getChildren() now returns List<Element> in JDom
=> Remove redundant casts

optaplanner-examples/src/main/resources/org/optaplanner/examples/nurserostering/optional/benchmark/nurseRosteringSprintBenchmarkConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/taskassigning/optional/benchmark/taskAssigningBenchmarkConfig.xml
These paths should have been updated when the examples were migrated from XStream to Jackson.
This PR fixes a file-not-found error when running the benchmarks using these configs.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used …
=> Update benchmark configs with JSON input files

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/config/util/ConfigUtilsTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/ProblemBenchmarksConfigTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/SolverBenchmarkFactoryTest.java
<details>
<summary>
</summary> …
=> Clean up a few tests

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/common/ReflectionHelper.java
<details>
<summary>
</summary> …
=> PLANNER-1541 Give a hint in property accessor fail-fast

.ci/jenkins/config/main.yaml
Needed to determine which is the main branch to cut-off release branches
=> Setup DSL config main branch

optaplanner-docs/src/modules/ROOT/pages/planner-configuration/planner-configuration.adoc, optaplanner-docs/src/modules/ROOT/pages/planner-introduction/planner-introduction.adoc, optaplanner-docs/src/modules/ROOT/pages/release-notes/release-notes-8.adoc, optaplanner-docs/src/modules/ROOT/pages/score-calculation/score-calculation.adoc
<details>
<summary>
</summary> …
=> Fix xref links that were broken in the single-html output

pom.xml
<details>
<summary>
</summary> …
=> Keep optaplanner-operator outside the prod profile

core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractIndexedJoinNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractJoinNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractUnindexedJoinNode.java
Makes some overdue refactors, leading to more code sharing.
No measurable impact on performance.
=> CS-B: Clean up joins

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/constructionheuristic/placer/QueuedEntityPlacerConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/constructionheuristic/placer/QueuedValuePlacerConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/entity/EntitySelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/ChangeMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/SwapMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/value/ValueSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/AbstractFromConfigFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhaseFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/placer/AbstractEntityPlacerFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/placer/QueuedValuePlacerFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhaseFactory.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/config/heuristic/selector/common/nearby/NearbySelectionConfigTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/PooledEntityPlacerFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/QueuedEntityPlacerFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/QueuedValuePlacerFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/exhaustivesearch/BlackBoxExhaustiveSearchPhaseTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/entity/EntitySelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMoveSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/SwapMoveSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/value/ValueSelectorFactoryTest.java, optaplanner-docs/src/modules/ROOT/pages/release-notes/release-notes-8.adoc
<details>
<summary>
</summary> …
=> PLANNER-2883 More with...() methods for configs

.ci/jenkins/config/branch.yaml, .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/PLANNER-2870
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/801
- https://github.com/kiegroup/optaplanner/pull/2550
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/842
- https://github.com/kiegroup/optaplanner-quickstarts/pull/505
- https://github.com/kiegroup/optaplanner-website/pull/569
- [9.x] https://github.com/kiegroup/optaplanner/pull/2558
=> PLANNER-2870 Environments should be configurable via branch config

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/common/accessor/gizmo/GizmoMemberAccessorImplementor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/gizmo/OptaPlannerGizmoClassLoaderReset.java
Fixes a bug that breaks quarkus dev mode experience, in combination with shadow variables.
Credit for the fix goes to Alexey.
https://github.com/quarkusio/quarkus/issues/30741
=> Fix Quarkus Classloader corruption in dev mode

.ci/jenkins/Jenkinsfile.setup-branch
- https://github.com/kiegroup/drools/pull/4977
- https://github.com/kiegroup/kogito-runtimes/pull/2794
- https://github.com/kiegroup/kogito-apps/pull/1623
- https://github.com/kiegroup/kogito-examples/pull/1565
- https://github.com/kiegroup/optaplanner/pull/2569
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/844
- https://github.com/kiegroup/optaplanner-quickstarts/pull/509
=> Setup Branch: Update branch before deploy

.ci/jenkins/config/branch.yaml
<details>
<summary>
</summary> …
=> Disable Quarkus native check

optaplanner-examples/src/test/java/org/optaplanner/examples/common/app/ImportDirSolveAllTurtleTest.java
<details>
<summary>
</summary> …
=> Fix broken turtle tests

.github/workflows/sonarcloud.yml
<details>
<summary>
</summary> …
=> Upgrade sonar to JDK 17

.ci/jenkins/config/branch.yaml
- https://github.com/kiegroup/kogito-pipelines/pull/860
- https://github.com/kiegroup/drools/pull/5007
- https://github.com/kiegroup/optaplanner/pull/2610
=> DSL Config: Update Git credentials

.ci/jenkins/config/main.yaml
<details>
<summary>
</summary> …
=> DSL main Config: Update Git Credentials

core/optaplanner-constraint-drl/src/test/java/org/optaplanner/constraint/drl/holder/AbstractScoreHolderTest.java
Makes OptaPlanner compatible with Drools 8.35.0-SNAPSHOT
=> Mock Drools AgendaItem instead of using AgendaItemImpl

core/optaplanner-core-impl/src/build/revapi-config.json, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/buildin/BendableBigDecimalScoreDefinition.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/buildin/BendableLongScoreDefinition.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/buildin/BendableScoreDefinition.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/buildin/HardMediumSoftBigDecimalScoreDefinition.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/buildin/HardMediumSoftLongScoreDefinition.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/buildin/HardMediumSoftScoreDefinition.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/buildin/HardSoftBigDecimalScoreDefinition.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/buildin/HardSoftLongScoreDefinition.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/buildin/HardSoftScoreDefinition.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/buildin/SimpleBigDecimalScoreDefinition.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/buildin/SimpleLongScoreDefinition.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/buildin/SimpleScoreDefinition.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/definition/ScoreDefinition.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultSingleConstraintAssertion.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/NumberEqualityUtil.java, optaplanner-test/src/test/java/org/optaplanner/test/api/score/stream/MultiConstraintAssertionTest.java, optaplanner-test/src/test/java/org/optaplanner/test/api/score/stream/SingleConstraintAssertionTest.java, optaplanner-test/src/test/java/org/optaplanner/test/api/score/stream/testdata/TestdataConstraintVerifierConstraintProvider.java, optaplanner-test/src/test/java/org/optaplanner/test/api/score/stream/testdata/TestdataConstraintVerifierEntity.java, optaplanner-test/src/test/java/org/optaplanner/test/api/score/stream/testdata/TestdataConstraintVerifierExtendedSolution.java, optaplanner-test/src/test/java/org/optaplanner/test/api/score/stream/testdata/TestdataConstraintVerifierFirstEntity.java, optaplanner-test/src/test/java/org/optaplanner/test/api/score/stream/testdata/TestdataConstraintVerifierSecondEntity.java, optaplanner-test/src/test/java/org/optaplanner/test/api/score/stream/testdata/TestdataConstraintVerifierSolution.java
<details>
<summary>
</summary> …
=> PLANNER-2905 Fix BigDecimal handling in ConstraintVerifier

build/optaplanner-build-parent/pom.xml, optaplanner-migration/pom.xml, pom.xml
<details>
<summary>
</summary> …
=> Bump OpenRewrite to latest versions

optaplanner-migration/src/main/resources/META-INF/rewrite/ToLatest9.yml
@triceo Please review the first 43 lines; the rest is a copy of the Quarkus migration recipe.
<details>
<summary>
</summary> …
=> Create a user migration recipe to OptaPlanner 9

build/optaplanner-build-parent/pom.xml, optaplanner-migration/src/main/java/org/optaplanner/migration/jakarta/JakartaHibernateMigrationRecipe.java, optaplanner-migration/src/main/java/org/optaplanner/migration/jakarta/JakartaJsonMigrationRecipe.java
<details>
<summary>
</summary> …
=> Bump rewrite-recipe-bom to 1.15.1

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-8717
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/890
- https://github.com/kiegroup/drools/pull/5034
- https://github.com/kiegroup/kogito-runtimes/pull/2822
- https://github.com/kiegroup/kogito-apps/pull/1642
- https://github.com/kiegroup/kogito-examples/pull/1583
- https://github.com/kiegroup/optaplanner/pull/2640
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/851
- https://github.com/kiegroup/optaplanner-quickstarts/pull/524
=> KOGITO-8717 Enable sonarcloud on demand

core/optaplanner-core-impl/src/build/revapi-config.json, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/common/nearby/NearbySelectionConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/list/SubListChangeMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/list/SubListSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/list/SubListSwapMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/HeuristicConfigPolicy.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/DestinationSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListChangeMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListNearbyDistanceMatrixDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/NearSubListNearbyDestinationSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/RandomSubListChangeMoveIterator.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/RandomSubListChangeMoveSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/RandomSubListSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/RandomSubListSwapMoveSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListChangeMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListNearbyDistanceMatrixDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListSwapMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/mimic/MimicRecordingSubListSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/mimic/MimicReplayingSubListSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/mimic/SubListMimicRecorder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/mimic/MimicRecordingValueSelector.java, core/optaplanner-core-impl/src/main/resources/solver.xsd, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListChangeMoveSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListChangeMoveSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListSelectorFactoryTest.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/vehiclerouting/vehicleRoutingSolverConfig.xml
<details>
<summary>
</summary> …
=> Nearby selection for SubListChangeMoveSelector

core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractIfExistsNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractIndexedIfExistsNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractUnindexedIfExistsNode.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/score/MachineReassignmentConstraintProvider.java
FilteringTracker is now static.
More code is now reused.
=> CS-B: Minor improvements to ifExists

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/decider/MultiThreadedConstructionHeuristicDecider.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/localsearch/decider/MultiThreadedLocalSearchDecider.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/director/AbstractScoreDirector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/director/InnerScoreDirector.java
https://issues.redhat.com/browse/PLANNER-1198
https://issues.redhat.com/browse/PLANNER-1370
<details>
<summary>
</summary> …
=> PLANNER-1198 Fix calculation count termination

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/DefaultSolutionManager.java
<details>
<summary>
</summary> …
=> PLANNER-1892 Throw when explained score doesn't match

core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/value/nearby/NearEntityNearbyValueSelectorTest.java
- Simplifies the test by using lifecycle simulation methods from `SelectorTestUtils`.
- Adds type parameters to generic types to reduce warning noise.
<details>
<summary>
</summary> …
=> Clean up NearEntityNearbyValueSelectorTest

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/DefaultPlannerBenchmark.java
https://issues.redhat.com/browse/PLANNER-1866
<details>
<summary>
</summary> …
=> PLANNER-1866 Exit warmup if there is a failure

build/optaplanner-bom/pom.xml
<details>
<summary>
</summary> …
=> PLANNER-2907 Docs and Distribution no longer in POM

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/EntitySelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/DestinationSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/NearSubListNearbySubListSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/RandomSubListSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListChangeMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListNearbySubListMatrixDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListSwapMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/ValueSelectorFactory.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/SelectorTestUtils.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/NearSubListNearbySubListSelectorTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/NearValueNearbyDestinationSelectorTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/TestDistanceMeter.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/TestNearbyRandom.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/value/mimic/ManualValueMimicRecorder.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/value/nearby/NearEntityNearbyValueSelectorTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testdata/domain/list/TestdataListUtils.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/vehiclerouting/vehicleRoutingSolverConfig.xml
1. The left subList is selected.
2. Its first element becomes the origin value.
3. A destination value is obtained from the distance matrix (index).
4. The right subList is randomly selected from all possible subLists beginning at the destination value's index.
- Minimum and maximum subList size configuration is honored.
**Original selection order not supported by subList move selectors!!!**
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to …
=> Nearby selection for SubListSwapMoveSelector

optaplanner-examples/src/main/java/org/optaplanner/examples/cloudbalancing/swingui/realtime/DeleteComputerProblemChange.java, optaplanner-examples/src/main/java/org/optaplanner/examples/cloudbalancing/swingui/realtime/DeleteProcessProblemChange.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/swingui/MachineReassignmentPanel.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nurserostering/swingui/NurseRosteringPanel.java, optaplanner-examples/src/main/java/org/optaplanner/examples/tsp/swingui/TspPanel.java
<details>
<summary>
</summary> …
=> PLANNER-1619 Examples: don't remove already removed entities

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/kopt/FlipSublistAction.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/kopt/KOptDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/kopt/KOptListMove.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/kopt/KOptListMoveIterator.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/kopt/KOptUtils.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/kopt/KOptListMoveTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/kopt/KOptUtilsTest.java
<details>
<summary>
</summary> …
=> Avoid unnecessary generics in the KOpt code

.github/workflows/pull_request.yml
<details>
<summary>
</summary> …
=> Github Actions: Replace JDK 19 with 20

core/optaplanner-constraint-drl/src/test/java/org/optaplanner/constraint/drl/DrlSolutionManagerTest.java, core/optaplanner-constraint-drl/src/test/resources/org/optaplanner/constraint/drl/solutionManagerDroolsConstraints.drl, core/optaplanner-constraint-streams-bavet/src/test/java/org/optaplanner/constraint/streams/bavet/BavetSolutionManagerTest.java, core/optaplanner-constraint-streams-drools/src/test/java/org/optaplanner/constraint/streams/drools/DroolsSolutionManagerTest.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/DefaultSolutionManager.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/solver/AbstractSolutionManagerTest.java
<details>
<summary>
</summary> …
=> PLANNER-2913 Set working solution before checking constraint matches

optaplanner-docs/src/modules/ROOT/pages/move-and-neighborhood-selection/move-and-neighborhood-selection.adoc
Updated the code section
Added an explanation
<details>
<summary>
</summary> …
=> Doc Update nearby distance to new VRP implementation

.ci/jenkins/config/branch.yaml
Generated by https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/8.36.x/job/tools/job/toggle-dsl-triggers/1/
=> [8.36.x] DSL triggers disabled

.ci/buildchain-config.yaml, .ci/environments/README.md, .ci/environments/common/update_quarkus.sh, .ci/environments/quarkus-branch/before.sh, .ci/environments/quarkus-lts/before.sh, .ci/environments/quarkus-main/before.sh, .ci/environments/update.sh, .ci/jenkins/config/branch.yaml
https://issues.redhat.com/browse/PLANNER-2919
Related:
- https://github.com/kiegroup/optaplanner/pull/2757
- https://github.com/kiegroup/optaplanner-quickstarts/pull/545
=> PLANNER-2919 Correct Quarkus checks

build/optaplanner-build-parent/pom.xml
=> [main] Bump Drools version to 8.37.0.Final

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/list/nearby/AbstractNearbyDestinationSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/list/nearby/NearSubListNearbyDestinationSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/list/nearby/NearValueNearbyDestinationSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/list/nearby/OriginalNearbyDestinationIterator.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/list/nearby/RandomNearbyDestinationIterator.java
<details>
<summary>
</summary> …
=> More code reuse in nearby selection

.ci/project-dependencies-rhbop.yaml
<details>
<summary>
</summary> …
=> Use QS 8.x on RHBOP main nightly

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/exhaustivesearch/decider/ExhaustiveSearchDecider.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/exhaustivesearch/scope/ExhaustiveSearchStepScope.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/phase/custom/DefaultCustomPhase.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/phase/scope/AbstractPhaseScope.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/phase/scope/AbstractStepScope.java
Some best score improvement checks were unnecessary.
Some code was unused.
=> Clean up around scopes

build/8-to-9-migration/optaplanner-quarkus3.yaml, build/optaplanner-build-parent/pom.xml, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/report/BenchmarkReport.java
Required by the Quarkus platform.
https://github.com/kiegroup/optaplanner/pull/2786
https://github.com/kiegroup/optaplanner/pull/2789
https://github.com/kiegroup/optaplanner/pull/2790
https://github.com/kiegroup/optaplanner-quickstarts/pull/556
<details>
<summary>
</summary>
[build-chain …
=> Bump Freemarker to 2.3.32

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/report/BenchmarkReport.java
Sets the compatibility version back to 2.3.31. For quickstarts/8.x, Spring Boot 2 brings that version of Freemarker.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in …
=> Set Freemarker compatibility to 2.3.31

.ci/buildchain-project-dependencies.yaml
<details>
<summary>
</summary> …
=> Change BCT repository branch mapping

.github/workflows/full-downstream.yml, .github/workflows/jenkins-tests-PR.yml, .github/workflows/optaplanner-9.yml, .github/workflows/pr-backporting.yml, .github/workflows/pull_request.yml, .github/workflows/quarkus-snapshot.yml, .github/workflows/rhbop_productized_pull_request.yml, .github/workflows/sonarcloud.yml
Related PR:
- https://github.com/kiegroup/optaplanner/pull/2837
=> Updating references to the new kie-ci actions folder.

optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml
https://issues.redhat.com/browse/RHPAM-4700
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2296
* https://github.com/kiegroup/droolsjbpm-integration/pull/2959
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on …
=> [RHPAM-4700] snakeyaml from 1.32 to 2.0

build/optaplanner-build-parent/pom.xml
- https://github.com/kiegroup/optaplanner/pull/2839
- https://github.com/kiegroup/optaplanner-quickstarts/pull/569
- https://github.com/kiegroup/optaplanner/pull/2840
=> [main] Bump Quarkus version to 2.16.7.Final

.ci/jenkins/config/branch.yaml
- https://github.com/kiegroup/optaplanner/pull/2850
- https://github.com/kiegroup/optaplanner-quickstarts/pull/572
- https://github.com/kiegroup/optaplanner/pull/2851
=> [8.38.x-prod] Bump quarkus version to 2.13.7.Final

optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml
https://issues.redhat.com/browse/RHPAM-4700
This is a backport PR of https://github.com/kiegroup/optaplanner/pull/2838 for 7.67.x
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2299
- https://github.com/kiegroup/droolsjbpm-integration/pull/2962
<details>
<summary>
</summary>
[build-chain …
=> [7.67.x] [RHPAM-4700] snakeyaml from 1.32 to 2.0 (#2838)

build/optaplanner-build-parent/pom.xml, core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/OptaPlannerRuleEventListener.java, core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/holder/AbstractScoreHolder.java, core/optaplanner-constraint-drl/src/test/java/org/optaplanner/constraint/drl/holder/AbstractScoreHolderTest.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/OptaPlannerRuleEventListener.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/common/AbstractRuleContext.java
=> [8.38.x-prod] Bump Drools version to 8.29.0.Final

.ci/jenkins/config/main.yaml
<details>
<summary>
</summary> …
=> Remove unmaintained branches

optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml
[CVE-2023-20883 spring-boot: Spring Boot Welcome Page DoS Vulnerability [rhbop-8]](https://issues.redhat.com/browse/RHBOP-53)
<details>
<summary>
</summary> …
=> Bump SpringBoot version

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.prod.nightly, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle, .ci/jenkins/project/Jenkinsfile.drools, .ci/jenkins/project/Jenkinsfile.nightly, .ci/jenkins/project/Jenkinsfile.release
https://issues.redhat.com/browse/KOGITO-9275
=> KOGITO-9275 Jenkins: Switch jobs to use RHEL8

build/optaplanner-build-parent/pom.xml
=> [main] Bump Drools version to 8.39.0.Final

build/optaplanner-build-parent/pom.xml
*Referenced Pull Requests*:
- https://github.com/kiegroup/optaplanner/pull/2870
- https://github.com/kiegroup/optaplanner-quickstarts/pull/578
=> [8.38.x-prod] Bump Quarkus version to 2.13.8.Final

build/optaplanner-build-parent/pom.xml, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/common/AbstractAccumulator.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/common/BiAccumulator.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/common/QuadAccumulator.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/common/TriAccumulator.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/common/UniAccumulator.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/common/ValueExtractor.java
due to drools-base and drools-core changes
This is just to verify CI, it shouldn't be merged as it depends on a SNAPSHOT
https://issues.redhat.com/browse/PLANNER-2927
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command …
=> PLANNER-2927 Upgrade Optaplanner to Drools 8.40.Final

optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml
- https://issues.redhat.com/browse/RHPAM-4737
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2275
<details>
<summary>
</summary> …
=> [7.67.x][CVE-2023-20860][RHPAM-4737] Bump spring-boot from 2.5.12 to 2.5.15

.ci/jenkins/config/main.yaml
<details>
<summary>
</summary> …
=> [9.x] Jenkins: Cleanup branches

.ci/jenkins/config/main.yaml
<details>
<summary>
</summary> …
=> Jenkins: Cleanup branches

.ci/jenkins/config/branch.yaml
- https://github.com/kiegroup/optaplanner/pull/2918
- https://github.com/kiegroup/optaplanner-quickstarts/pull/592
- https://github.com/kiegroup/optaplanner/pull/2919
=> [main] Bump quarkus version to 2.16.9.Final

.ci/jenkins/Jenkinsfile.deploy
<details>
<summary>
</summary> …
=> CI: Fix typo

.ci/jenkins/config/branch.yaml
Generated by https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/8.43.x/job/tools/job/toggle-dsl-triggers/1/
=> [8.43.x] DSL triggers disabled

build/optaplanner-build-parent/pom.xml
- https://issues.redhat.com/browse/RHPAM-4637
- https://issues.redhat.com/browse/RHPAM-4738
- https://github.com/kiegroup/optaplanner/pull/2473
**No PR is needed for 8.13.x-blue branch as we dont build Optaplanner for BAMOE.**
<details>
<summary>
</summary>
[build-chain …
=> [8.13.x][RHPAM-4637][RHPAM-4738] Bump xstream to 1.4.20

.ci/jenkins/config/branch.yaml
Generated by https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner/job/8.44.x/job/tools/job/toggle-dsl-triggers/1/
=> [8.44.x] DSL triggers disabled

build/optaplanner-build-parent/pom.xml
=> [main] Bump Drools version to 8.44.0.Final

.ci/jenkins/dsl/jobs.groovy
Merge apache_migration to resolve conflicts
=> Adapt kiegroup to apache

.ci/buildchain-config.yaml, .ci/buildchain-project-dependencies.yaml, .ci/environments/common/update_quarkus.sh, .ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle, .ci/jenkins/config/branch.yaml, .ci/jenkins/config/main.yaml, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh, .ci/jenkins/project/Jenkinsfile.drools, .ci/jenkins/project/Jenkinsfile.nightly, .ci/jenkins/project/Jenkinsfile.post-release, .ci/jenkins/project/Jenkinsfile.release, .github/pull_request_template.md, .github/workflows/full-downstream.yml, .github/workflows/generate_status_page.yaml, .github/workflows/generate_status_page_data.yaml, .github/workflows/jenkins-tests-PR.yml, .github/workflows/pull_request.yml
Fixes conflicts from PR https://github.com/apache/incubator-kie-optaplanner/pull/2974. If this is fine and gets merged, the original PR will be closed.
=> Update kiegroup references to apache

.ci/jenkins/Jenkinsfile
apache/incubator-kie-issues#598 
Adding a post build cleanup of workspace.
=> kie-issues#598: Add post build cleanup to PR checks

build/optaplanner-build-parent/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/deployment/pom.xml, pom.xml
- Migrate from jboss-parent to Apache parent pom.
=> Migrate from jboss-parent to apache parent pom.

.ci/jenkins/config/branch.yaml
apache/incubator-kie-issues#600
Providing specific token for buildchain configuration.
=> kie-issues#600: define token for buildchain

build/optaplanner-build-parent/pom.xml, optaplanner-examples/pom.xml, pom.xml
Changes JBoss Nexus repository to Apache Nexus.
=> [kie-issues#628] Change JBoss Nexus to Apache Nexus.

.github/workflows/jenkins-tests-PR.yml, .github/workflows/optaplanner-9.yml, .github/workflows/pr-backporting.yml, .github/workflows/pull_request.yml, .github/workflows/quarkus-snapshot.yml, .github/workflows/sonarcloud.yml
apache/incubator-kie-issues#674
Fixing references to GHA where possible.
Further changes of used actions might be still needed, but requires a repo SME to fix workflows.
apache/incubator-kie-optaplanner#3012
apache/incubator-kie-optaplanner-quickstarts#614
apache/incubator-kie-optaplanner-quickstarts#615
=> kie-issues#674: update GHA references

build/optaplanner-build-parent/pom.xml
<details>
<summary>
</summary> …
=> sonarcloud organization is Apache

.ci/jenkins/config/branch.yaml
https://github.com/apache/incubator-kie-issues/issues/732
Add credentials to enable deploying artifacts to maven
=> [incubator-kie-issues#732] Add credentials for deploying artifacts

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/config/branch.yaml, .ci/jenkins/config/main.yaml, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.post-release, .ci/jenkins/project/Jenkinsfile.setup-branch
Removes unnecessary configurations as the main become Quarkus 3 aligned.
=> [kie-issues#784] Remove unnecessary build environments and configuration.

core/.gitignore
Goal: have a clean working tree after build.
Currently:
```
$ find core/target/
core/target/
core/target/maven-shared-archive-resources
core/target/maven-shared-archive-resources/META-INF
core/target/maven-shared-archive-resources/META-INF/LICENSE
core/target/maven-shared-archive-resources/META-INF/DEPENDENCIES
core/target/maven-shared-archive-resources/META-INF/NOTICE
core/target/.plxarc
```
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to …
=> Ignore core/target directory

.ci/jenkins/Jenkinsfile.setup-branch
Fixes
* apache/incubator-kie-issues#769
Another occurrence of cleanWs() causing getCwd issues.
=> kie-issues#769: fix another case of async cleanWs

build/optaplanner-build-parent/pom.xml, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java
This is a PR to upgrade Spring Boot to version 3.2.4. 
kie-issue: https://github.com/apache/incubator-kie-issues/issues/995
Related kogito-runtimes PR: https://github.com/apache/incubator-kie-kogito-runtimes/pull/3463
Related kogito-examples PR: https://github.com/apache/incubator-kie-kogito-examples/pull/1903
Related optaplanner-quickstarts PR: https://github.com/apache/incubator-kie-optaplanner-quickstarts/pull/628
=> [kie-issues#995] Upgrade Spring Boot to 3.2.4

build/optaplanner-build-parent/pom.xml
Related: https://github.com/apache/incubator-kie-issues/issues/1197
Ensemble:
https://github.com/apache/incubator-kie-drools/pull/5934
https://github.com/apache/incubator-kie-optaplanner/pull/3085 
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3509
=> CVE-2023-6481 logback upgrade.

.ci/jenkins/Jenkinsfile.deploy
Adds gpg setup and apache-release Maven profile to the release build.
=> [NO-ISSUE] Use apache-release profile when doing a release build

build/optaplanner-build-parent/pom.xml
Fixes: https://github.com/apache/incubator-kie-issues/issues/1282
Related: https://github.com/apache/incubator-kie-kogito-runtimes/pull/3538
=> kie-issues#1282: updating spring boot version that address some important CVEs

.ci/jenkins/Jenkinsfile.weekly.deploy, .ci/jenkins/dsl/jobs.groovy
This PR fixes some issues found in the weekly deploy Jenkins job.
These changes have been tested in the following run; https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/other/job/optaplanner.weekly-deploy/9/
=> NO-ISSUE: Fix weekly deploy Jenkins job

.ci/jenkins/Jenkinsfile.deploy
After #3086 
Fixing Jenkinsfile.deploy after methods were removed and left one outdated stage.
=> kie-issues#1123: adjust Jenkinsfile.deploy after refactor

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/config/branch.yaml, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh
Depends on:
* apache/incubator-kie-kogito-pipelines#1206
Where `release` share pipeline library was added with gpg specific methods to import keys,etc.
=> NO_ISSUE: Use release share library

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/config/branch.yaml
This PR fixes the release configuration keys that was not being parsed correctly.
=> [10.0.x] NO-ISSUE: Fix release configuration keys

build/optaplanner-build-parent/pom.xml
Issue: https://github.com/apache/incubator-kie-issues/issues/1465
Alignment with latest Quarkus LTS release - 3.8.6.
Related PRs:
https://github.com/apache/incubator-kie-drools/pull/6067
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3657
https://github.com/apache/incubator-kie-kogito-apps/pull/2097
https://github.com/apache/incubator-kie-kogito-examples/pull/2008
https://github.com/apache/incubator-kie-kogito-images/pull/1801
=> [kie-issues#1465] Align with Quarkus 3.8.6.

build/optaplanner-bom/pom.xml, build/optaplanner-build-parent/pom.xml, build/optaplanner-distribution-internal/pom.xml, build/optaplanner-distribution-internal/src/main/assembly/assembly-optaplanner.xml
<details>
<summary>
</summary> …
=> NO_ISSUE: cleaning leftover from experimental operator removal

build/optaplanner-build-parent/pom.xml
Resolves https://github.com/apache/incubator-kie-issues/issues/1562
=> [kie-issues#1562] Add profile for testing a custom build using all repository tests.

.github/workflows/ci_check_license_headers.yaml, .gitignore, .rat-excludes, LICENSE, NOTICE
This is a cherrypick of:
- #3130
- #3144 
<details>
<summary>
</summary> …
=> [10.0.x]  kie-issues#1613: Add `CI :: Check license headers` GitHub Actions workflow

LICENSE, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/common/ReflectionHelper.java
This PR is to address findings of the apache/incubator-kie-issues/issues/1634:
- https://github.com/apache/incubator-kie-issues/issues/1634#issuecomment-2505325948
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line …
=> kie-issues#1634: Fix duplicated header ReflectionHelper.java

NOTICE
- https://github.com/apache/incubator-kie-issues/issues/1618
=> [incubator-kie-issues-1618] Fix NOTICE year with range

NOTICE
- https://github.com/apache/incubator-kie-issues/issues/1618
=> [10.0.x] [incubator-kie-issues-1618] Fix NOTICE year with range

NOTICE
Part of https://github.com/apache/incubator-kie-issues/issues/1747
=> kie-issues#1747: Updating the year range in the NOTICE file

build/optaplanner-build-parent/pom.xml
Fixes https://github.com/apache/incubator-kie-issues/issues/1787
Updating logback to fix the CVE
=> [kie-issues#1787] Updating Logback to 1.5.16

build/optaplanner-build-parent/pom.xml
Upgrade quarkus to 3.15.3.1
Link to key issue: https://github.com/apache/incubator-kie-issues/issues/1884
To be merged with https://github.com/apache/incubator-kie-kogito-runtimes/pull/3867 , https://github.com/apache/incubator-kie-tools/pull/3025 , https://github.com/apache/incubator-kie-drools/pull/6286
=> [kie-issues#1884] Upgrade quarkus to 3.15.3.1

build/optaplanner-build-parent/pom.xml, optaplanner-examples/pom.xml
Closes https://github.com/apache/incubator-kie-issues/issues/2047
As Java 21 is the latest Java LTS available, already for some time the code should be buildable and runnable with Java 21, while still retaining compatibility with Java 17.
<details>
<summary>
</summary>
[build-chain …
=> [incubator-kie-issues#2047]Changes for supporting JAVA21
