optaplanner-examples/src/main/java/org/optaplanner/examples/cheaptime/domain/CheapTimeSolution.java, optaplanner-examples/src/main/java/org/optaplanner/examples/cheaptime/solver/drools/IdleCost.java, optaplanner-examples/src/main/java/org/optaplanner/examples/cheaptime/solver/drools/MachinePeriodPart.java, optaplanner-examples/src/main/java/org/optaplanner/examples/cheaptime/solver/drools/Period.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/cheaptime/solver/cheapTimeScoreRules.drl, optaplanner-examples/src/main/resources/org/optaplanner/examples/cheaptime/solver/cheapTimeSolverConfig.xml
ACC = 670 with sample01.xml
Some points:
- I insert CheapTimeSolution as a fact because only it knows globalPeriodRangeFrom/globalPeriodRangeTo
- I insert Period as a fact to create MachinePeriodPart conveniently. Also it is used in rule "taskPowerCost".
- Rule "machinePeriodPart" seems to be a major bottle-neck but I have no other idea at this moment.
- Note that CheapTimeIncrementalScoreCalculator is used by default. Please uncomment scoreDrl when you test
I'm open to change anything if you suggest in review. Thanks!
=> PLANNER-275 Add Drools score rules for example CheapTime Scheduling

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/PlannerBenchmarkResult.java, optaplanner-benchmark/src/main/resources/org/optaplanner/benchmark/impl/report/benchmarkReport.html.ftl
* As SLF4J doesn't expose log level, manual resolving needs to be done
* Level resolved for the most general category (org.optaplanner), as sub-categories can define their own logging levels.
=> PLANNER-273 Benchmark report should mention logging level (because that can effect performance)

optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/SelectorTestUtils.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMoveSelectorTest.java
Created a test to understand the randomSelection flag in ChangeMoveSelector. Frankly, I still don't see the purpose of this flag, as it seems to assume that the valueSelector will produce random values (otherwise, not all possible moves can be created). You can create the same behaviour by simply supplying a random entity/value selector to a non-random ChangeMoveSelector?
=> Additional unit test + helper method.

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/SingleBenchmarkRunner.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SingleBenchmarkResult.java, optaplanner-benchmark/src/main/resources/org/optaplanner/benchmark/impl/report/benchmarkReport.html.ftl
The report now displays a red '!' in case the single benchmark best solution was uninitialized.
=> PLANNER-333: Added information about initialization of single benchmark solutions to report

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/SingleBenchmarkRunner.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SingleBenchmarkResult.java, optaplanner-benchmark/src/main/resources/org/optaplanner/benchmark/impl/report/benchmarkReport.html.ftl
**NOTE: Merge only after #105**
* Tested on Firefox and Chrome
* Works even without javascript enabled (tooltips then look like standard html tooltips)
=> PLANNER-334: Added tooltips to explain uninitialized/infeasible/failed benchmark badges in report

optaplanner-distribution/src/main/assembly/scripts/runExamples.bat, optaplanner-distribution/src/main/assembly/scripts/runExamples.sh, optaplanner-examples/pom.xml
* tested on Linux and Windows Server 2012 R2
* works even with long base directory
(tried with one that had more than 160 chars)
=> PLANNER-396: define classpath for examples using wildcards

optaplanner-examples/pom.xml
* just a suggestion. Tested locally without any test failures. 
* 4 seems like a good number given current processors have 2-4 cores. We could even use something like 2C (two threads per core). But this gets tricky when using e.g. Hyper Threading, because the number of cores visible to surefire is doubled, so in the end we have 4 threads per one "real" core.
* adding it only to `-examples` as this module takes by far the most time and contains most of the tests
* locally, the speedup is about 33% (from 3 min to 2 min)
=> examples: run tests in parallel

optaplanner-examples/src/main/java/org/optaplanner/examples/common/business/SolutionBusiness.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/swingui/SolverAndPersistenceFrame.java
Didn't find any place where the Swing UI would use an "uninitialized" score prefix, so I added it (not very cleanly with all the casts, I must admit). The colors were changed to correspond with the usage in the benchmarker.
=> PLANNER-391: Show uninitialized score in swingui

optaplanner-docs/src/main/docbook/en-US/Chapter-Benchmarking_and_tweaking/Chapter-Benchmarking_and_tweaking.xml
Not sure if we want to have 3 indented blocks in a row.
=> Added overheating warning for parallelBenchmarkCount > 1 to benchmarker docs

optaplanner-core/src/main/java/org/optaplanner/core/api/score/holder/AbstractScoreHolder.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendablebigdecimal/BendableBigDecimalScoreHolderTest.java, optaplanner-distribution/src/main/assembly/filtered-resources/UpgradeFromPreviousVersionRecipe.txt
* Creating a new Map instead of clearing it is debatable, feel free to leave that commit out.
=> PLANNER-284: Code style + performance

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/SingleBenchmarkRunner.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/aggregator/BenchmarkAggregator.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/report/BenchmarkReport.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/BenchmarkResultIO.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SingleBenchmarkResult.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/ProblemBasedSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/ProblemStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/PureSingleStatistic.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/statistic/SingleStatistic.java
* On longer benchmark runs with a large count of single statistics, the memory savings can be quite large: about 20MB per statistic per single benchmark (the number is not accurate at all). See JIRA attached screenshots.
* The toll for the memory optimization comes at the end, when generating the report: There is a ~11% slow down (about 17 seconds) in a very big benchmark (61 single benchmarks, 10min each).
=> PLANNER-259: Persist SingleStatistic point lists to save memory

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/SolverBenchmarkResult.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/result/SolverBenchmarkResultTest.java
Very sorry for breaking the build with #145. This will fix it.
=> FIX: SolverBenchmarkResult Correct failed singles handling in average score with uninitialized prefix

README.adoc
"ERROR: README.adoc: line 3: only book doctypes can contain level 0 sections"
=> Fix asciidoctor complaints in README

optaplanner-examples/src/main/java/org/optaplanner/examples/common/swingui/ConstraintMatchesDialog.java
... when constraint matches are disabled (GNOME3 doesn't render a close button). There's no way to close the dialog when that happens, except Alt+F4, which is a bad UX.
See: http://stackoverflow.com/questions/26162178/jdialog-not-showing-minimize-close-button
=> Added OK button to Constraint match dialog

optaplanner-webexamples/pom.xml
* aligns with the overall KIE platform which uses (or will use)
WildFly 10 by default
=> webexamples: run tests on WildFly 10.0.0.Final (instead of 9.0.1.Final)

pom.xml
* optaplanner now depends only on kie-third-party-bom,
drools-bom and optaplanner-bom
* before this change, the kie-parent-with-dependencies
brought in also uberfire-boms, dashbuilder-bom, errai-bom,
guvnor-bom and other BOMs which optaplanner does not need
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/184
=> [DROOLS-1137] better granularity for imported BOMs

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/SmallScalingOrderedSet.java
This change reverts performance loss of chain move selectors in some
cases.
=> PLANNER-554: Revert list size threshold to 16

optaplanner-webexamples/src/test/resources/arquillian.xml
* deprecated in JDK 8 and completely removed in JDK 9 (build fails)
=> Webexamples ARQ tests: remove no longer needed -XX:MaxPermSize

optaplanner-webexamples/pom.xml
Part of an ensemble:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/226
https://github.com/droolsjbpm/drools/pull/815
https://github.com/droolsjbpm/optaplanner/pull/200
https://github.com/droolsjbpm/jbpm/pull/487
https://github.com/droolsjbpm/droolsjbpm-integration/pull/509
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/29
https://github.com/droolsjbpm/guvnor/pull/328
https://github.com/droolsjbpm/drools-wb/pull/209
https://github.com/droolsjbpm/jbpm-designer/pull/302
https://github.com/droolsjbpm/jbpm-console-ng/pull/432
https://github.com/droolsjbpm/kie-wb-distributions/pull/303
=> [DROOLS-1216] exclude commons-logging and use jcl-over-slf4j instead

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/blueprint/SolverBenchmarkBluePrintType.java, optaplanner-core/src/main/java/org/optaplanner/core/config/constructionheuristic/ConstructionHeuristicPhaseConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/constructionheuristic/ConstructionHeuristicType.java, optaplanner-core/src/main/java/org/optaplanner/core/config/constructionheuristic/ConstructionHeuristicTypeHelper.java, optaplanner-core/src/main/java/org/optaplanner/core/config/constructionheuristic/placer/PooledEntityPlacerConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/constructionheuristic/placer/QueuedEntityPlacerConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/constructionheuristic/placer/QueuedValuePlacerConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/exhaustivesearch/ExhaustiveSearchPhaseConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/entity/EntitySelectorConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/entity/EntitySorterManner.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/entity/EntitySorterMannerHelper.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/value/ValueSelectorConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/value/ValueSorterManner.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/value/ValueSorterMannerHelper.java
This relates to reusing enums from `ConstructionHeuristicPhaseConfig` in the Workbench. As the enum methods introduced too many class dependencies, a split into enum & helper class is required.
=> PLANNER-580: Make org.optaplanner.core.api.score.Score class hierarchy JavaScript-compile friendly

optaplanner-persistence/optaplanner-persistence-jaxb/pom.xml
* fix for JDK9 which does not by default includes these
* still works on JDK8
@ge0ffrey please take a look and let me know if you have any concerns.
=> persistence-jaxb: depend explicitly on JavaEE specs

optaplanner-core/src/main/java/org/optaplanner/core/api/score/holder/AbstractScoreHolder.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/holder/ScoreHolder.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/ScoreDirector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/easy/EasyScoreDirector.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/holder/ScoreHolderTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/drools/DroolsScoreDirectorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/easy/EasyScoreDirectorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/incremental/IncrementalScoreDirectorTest.java
Contains a few minor JavaDoc fixes and makes all score directors throw
IllegalStateException from getConstraintMatchTotals() when
constraintMatchEnabled is false. Tests included.
=> Review score directors, fix getContraintMatchTotals()

optaplanner-benchmark/pom.xml, optaplanner-core/pom.xml, optaplanner-distribution/pom.xml, optaplanner-docs/pom.xml, optaplanner-examples/pom.xml, optaplanner-persistence/optaplanner-persistence-common/pom.xml, optaplanner-persistence/optaplanner-persistence-jackson/pom.xml, optaplanner-persistence/optaplanner-persistence-jaxb/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml, optaplanner-persistence/optaplanner-persistence-xstream/pom.xml, optaplanner-persistence/pom.xml, optaplanner-test/pom.xml, optaplanner-webexamples/pom.xml
There is a lot of artifacts under the `optaplanner.org` group ID but only `optaplanner` (the parent module) contains URL of www.optaplanner.org. When people search for OptaPlanner JARs they will probably look for optaplanner-core, optaplanner-benchmark etc. on mvnrepository.com where the URL is shown as a HomePage just after the artifact description. So why not providing a one-click access to www.optaplanner.org for people that possibly don't know about it? Is it a good idea?
Result:
=> Add home page URL to all POMs

optaplanner-core/src/main/java/org/optaplanner/core/api/score/AbstractScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/bendablelong/BendableLongScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoft/HardMediumSoftScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftlong/HardMediumSoftLongScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoft/HardSoftScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftdouble/HardSoftDoubleScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftlong/HardSoftLongScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/simple/SimpleScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/simplebigdecimal/SimpleBigDecimalScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/simpledouble/SimpleDoubleScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/simplelong/SimpleLongScore.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendable/BendableScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendablebigdecimal/BendableBigDecimalScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendablelong/BendableLongScoreTest.java
The PR relates to OptaPlanner Workbench. As `org.optaplanner.core.api.score.AbstractScore` uses `Class.isInstance()` method which is not supported by gwt compiler, a refactoring is required to be able to reuse the Score classes on the client-side of the WB.
=> PLANNER-580 Make org.optaplanner.core.api.score.Score class hierarchy JavaScript-compile friendly

optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/bendable/BendableScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/bendablebigdecimal/BendableBigDecimalScore.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/buildin/bendablelong/BendableLongScore.java
As the scores are value classes, custom errai mapping needs to be defined for them if they are ever to be used in Errai services. The problem with Bendable*Score types is that they don't expose hardScores & softScores variables, therefore it's not possible to marshall such value.
This PR adds getters for aforementioned variables. @ge0ffrey Are you ok with such change?
=> PLANNER-647 Workbench: Include ErraiApp.properties and score marshalling mappings in workbench-upstream-model module

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/extended/abstractsolution/TestdataExtendedAbstractSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/extended/abstractsolution/TestdataExtendedAbstractSolutionOverridenScoreAccessors.java
The changes are required to allow score getter/setter overriding in `AbstractSolution` subclass. This is used by the Workbench when working with bendable score types to define `@PlanningScore` with respective `bendable(Hard|Soft)LevelsSize` annotation values.
=> PLANNER-536 Workbench solver editor: bendable score combobox selection should allow filling in hard and soft level size

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenDroolsScoreDirector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenKieSessionEventSupport.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenKieSessionJournal.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenKieSessionListener.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenTestWriter.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenerator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenAbstractValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenEnumValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenExistingInstanceValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenListValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenMapValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenNullValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenParsedValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenPrimitiveValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenStringValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueFact.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/mutation/TestGenRemoveRandomBlockMutator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/operation/TestGenKieSessionFireAllRules.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/operation/TestGenKieSessionUpdate.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/reproducer/TestGenCorruptedScoreException.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/reproducer/TestGenCorruptedScoreReproducer.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/reproducer/TestGenDroolsExceptionReproducer.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueFactTest.java
- improve imports handling
- fix: when calculating uncorrupted score, only insert problem facts, not all objects from the working session
- consistently name Logger fields
- use diamond operator
=> TestGen fixes

optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenDroolsScoreDirector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenDroolsScoreDirectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenLegacyDroolsScoreDirectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenTestWriter.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenerator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenAbstractValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenEnumValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenExistingInstanceValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenFact.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenFactField.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenListValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenMapValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenNullFact.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenParsedValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenPrimitiveValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenSetValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueFact.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/reproducer/TestGenCorruptedScoreReproducer.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/reproducer/TestGenDroolsExceptionReproducer.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueFactTest.java
Next round of fixes and improvements, this time based on the isolation work on DROOLS-1326 and adding reproducers for DROOLS-1174 and DROOLS-1187.
* if `<scoreDrl>` is used in solver config it is now written to the reproducer
* implemented fact setup pruning -- eliminates working fact setters that are not necessary for reproducing the issue
=> TestGen fixes 2

optaplanner-core/src/test/java/org/optaplanner/core/api/domain/solution/cloner/CustomSolutionClonerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/customcloner/TestdataCorrectlyClonedSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/customcloner/TestdataEntitiesNotClonedSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/customcloner/TestdataScoreNotEqualSolution.java
While I was refactoring some tests due to the removal of `PlanningCloneable` I came across an old TODO to increase test coverage for the detection of corrupted cloning (c55f3c8980) that was implemented in [BZ-1139670](https://bugzilla.redhat.com/show_bug.cgi?id=1139670). So I resolved it.
Note for QE: when this is merged, remove `CustomSolutionClonerTest#testBadCustomSolutionCloner`.
=> BZ-1139670 Add test coverage for corrupted cloner detection

optaplanner-core/src/main/java/org/optaplanner/core/api/domain/solution/cloner/SolutionCloner.java, optaplanner-core/src/test/java/org/optaplanner/core/api/domain/solution/cloner/CustomSolutionClonerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/solution/cloner/AbstractSolutionClonerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/customcloner/TestdataCorrectlyClonedSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/customcloner/TestdataScoreNotClonedSolution.java
This PR contains various fixes and improvements in tests related to SolutionCloner.
* added the requirement for an equal score on the clone to SolutionCloner Javadoc
* added score equality check to AbstractSolutionClonerTest
* added test for the original fix for [RHBRMS-1430](https://issues.jboss.org/browse/RHBRMS-1430)
When this is merged, QE's CustomSolutionClonerTest can be removed completely.
=> SolutionCloner test updates

optaplanner-core/src/main/java/org/optaplanner/core/api/score/holder/AbstractScoreHolder.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/ReflectionHelper.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/accessor/BeanPropertyMemberAccessor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/locator/LocationStrategyResolver.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/AbstractSolution.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/FieldAccessingSolutionCloner.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/mutation/MutationCounter.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/valuerange/descriptor/AbstractFromPropertyValueRangeDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/scope/LocalSearchStepScope.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/queue/PartitionQueue.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/event/PhaseLifecycleSupport.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/XStreamXmlSolverFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/recaller/BestSolutionRecaller.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/holder/AbstractScoreHolderTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/solver/SolverFactoryTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/SelectorTestUtils.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/queue/PartitionQueueTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/util/PlannerAssert.java
Each change eliminates one "rawtypes" warning and some of them also eliminate "unchecked conversion" warnings resulting from usage of the raw type.
These are easy and safe fixes because they mostly change local variables and fields.
86 warnings eliminated in optaplanner-core (3966→3880).
=> Compiler warnings elimination - low hanging fruit

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/Score.java, optaplanner-core/src/main/java/org/optaplanner/core/api/solver/Solver.java, optaplanner-core/src/main/java/org/optaplanner/core/api/solver/event/BestSolutionChangedEvent.java, optaplanner-core/src/main/java/org/optaplanner/core/config/partitionedsearch/PartitionedSearchPhaseConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/valuerange/descriptor/EntityIndependentValueRangeDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/valuerange/descriptor/ValueRangeDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/InnerScoreDirector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/InnerScoreDirectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/easy/EasyScoreDirector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/incremental/ConstraintMatchAwareIncrementalScoreCalculator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/scope/DefaultSolverScope.java, optaplanner-examples/src/main/java/org/optaplanner/examples/meetingscheduling/domain/Meeting.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/bendable/BendableScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/bendablebigdecimal/BendableBigDecimalScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/bendablelong/BendableLongScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/hardmediumsoft/HardMediumSoftScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/hardmediumsoftlong/HardMediumSoftLongScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/hardsoft/HardSoftScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/hardsoftlong/HardSoftLongScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/simple/SimpleScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/simplebigdecimal/SimpleBigDecimalScoreVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/buildin/simplelong/SimpleLongScoreVerifier.java
Most frequent issue was broken links due to usage of `Solution_`
parameter in method references. Javadoc tool cannot handle that but when
the method reference is used without parameters, the link is generated
correctly.
Another issue was with `@value` tag. It appears to require FQCN when
referencing a different class.
Also fixes missing period at ends of first sentences and typos.
=> Fix various Javadoc issues

optaplanner-core/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/valuerange/buildin/composite/CompositeCountableValueRangeTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/util/PlannerAssert.java
Annotated methods have been checked for improper handling of the varargs
array and they appear to be safe. The varargs are always read-only and
no upcasting (e.g. to `Object[]`) takes place.
For explanation of heap pollution and when `@SafeVarargs` can be used see:
https://docs.oracle.com/javase/tutorial/java/generics/nonReifiableVarargsType.html
http://docs.oracle.com/javase/specs/jls/se7/html/jls-9.html#jls-9.6.3.7
33 warnings eliminated in optaplanner-core (3889→3856).
=> Compiler warnings - safe varargs

optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/decider/ExhaustiveSearchDecider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/move/CompositeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/move/NoChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/SwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/KOptMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainReversingChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainReversingSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/TailChainSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/DefaultLocalSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/decider/LocalSearchDecider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/decider/acceptor/tabu/MoveTabuAcceptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhase.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/QueuedEntityPlacerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/QueuedValuePlacerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/move/CompositeMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/move/DummyMove.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/move/NoChangeMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/util/PlannerAssert.java
I was reviewing https://issues.jboss.org/browse/PLANNER-731 and I found some rawtype Moves usages that could be easily fixed without side effects like changing method signatures and cascading to other parts of the code. Using the Solution_ parameter where possible also eliminated a number of unchecked warnings.
=> Eliminate some warnings related to Move<Solution_>

optaplanner-benchmark/pom.xml, optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/pom.xml, optaplanner-core/src/build/revapi-config.json
Hi, @ge0ffrey,
here is the revapi plugin for the optaplanner repo. Currently, the following is checked:
- optaplanner-benchmark - packages org.optaplanner.benchmark.api and org.optaplanner.benchmark.config
- optaplanner-core - packages org.optaplanner.core.api and org.optaplanner.core.config
Thanks,
Marian
=> Add revapi plugin

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenDroolsScoreDirector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenKieSessionEventSupport.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenKieSessionJournal.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenKieSessionListener.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/TestGenTestWriter.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenFactField.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenInlineListValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenInlineValue.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenListValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenMapValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenNullFact.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueFact.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/operation/TestGenKieSessionDelete.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/operation/TestGenKieSessionFireAllRules.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/operation/TestGenKieSessionInsert.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/operation/TestGenKieSessionUpdate.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/reproducer/TestGenCorruptedScoreReproducer.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/reproducer/TestGenCorruptedVariableListenerReproducer.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/reproducer/TestGenDroolsExceptionReproducer.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/reproducer/TestGenOriginalProblemReproducer.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueFactTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/testgen/TestdataGetterSetterTypeMismatch.java, optaplanner-examples/src/main/java/org/optaplanner/examples/coachshuttlegathering/domain/location/RoadLocationArc.java
CSG uses shadow variables (custom and inverse relationship), which lead to updates with values that are not working facts (e.g. transportTimeToHub is an Integer, transferShuttleList is an ArrayList). TestGen now handles these dynamic non-fact values using the `TestGenInlineValue`.
Another anomaly to cope with was the `Coach.destination` property whose type is `BusHub` but the getter is a supertype (`StopOrHub`).
A new "reproducer" (reproducibility decider) for corrupted variable listeners was added. It is not fully compatible with the current pruning strategy but it works when only dropping the oldest updates. FIXME comment included.
TestGen score director's logging was enhanced so that each Move updates are now visible in full detail:
```
// do move
Updating variable …
```
=> Make TestGen compatible with Coach Shuttle Gathering example

README.adoc
The public CI server is unavailable and won't be available in the near future.
@psiroky told me the idea of a public CI server was suspended due to maintenance related issues.
=> Remove build status link from Readme

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/src/build/revapi-config.json
Hi,
this PR is related to droolsjbpm/droolsjbpm-build-bootstrap#393. Revapi config JSON files were divided into filter and ignores parts.
Marian
=> Split revapi configuration into filter and ignores

optaplanner-core/src/main/java/org/optaplanner/core/config/partitionedsearch/PartitionedSearchPhaseConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/partitioner/SolutionPartitioner.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/scope/PartitionChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/scope/PartitionedSearchStepScope.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/scope/DefaultSolverScope.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/queue/PartitionQueueTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/phase/PhaseLifecycleTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/TestdataObject.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/customcloner/TestdataCorrectlyClonedSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/customcloner/TestdataScoreNotClonedSolution.java
- Fixed a few typos in Javadoc.
- Fixed implementation of `PartitionChangeMove.createUndoMove()`. It now returns null instead of throwing `UnsupportedOperationException`.
- Added thread pool shutdown when PS phase ends.
- Improved `PartitionedSearchPhaseConfig` API. Now it's possible to set custom `SolutionPartitioner`.
- Added `@PlanningId` on `TestdataObject`.
=> Add DefaultPartitionedSearchPhase test coverage

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/factory/MoveIteratorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/factory/MoveListFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/cheaptime/solver/move/factory/CheapTimePillarSlideMoveIteratorFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/investment/solver/move/factory/InvestmentBiQuantityTransferMoveIteratorFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/investment/solver/move/factory/InvestmentQuantityTransferMoveIteratorFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nqueens/solver/move/factory/RowChangeMoveFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nurserostering/solver/move/factory/EmployeeChangeMoveFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nurserostering/solver/move/factory/ShiftAssignmentPillarPartSwapMoveFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nurserostering/solver/move/factory/ShiftAssignmentSequenceSwitchLength2MoveFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nurserostering/solver/move/factory/ShiftAssignmentSequenceSwitchLength3MoveFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nurserostering/solver/move/factory/ShiftAssignmentSwapMoveFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/pas/solver/move/factory/BedDesignationPillarPartSwapMoveFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/pas/solver/move/factory/BedDesignationSwapMoveFactory.java, optaplanner-examples/src/main/java/org/optaplanner/examples/travelingtournament/solver/move/factory/MatchChainRotationsMoveFactory.java
I'm not sure if this has any benefit for the user. The "nice" thing is that you have to declare the move type as the factory type parameter. This way it is guaranteed that `MoveIteratorFactory`'s `createOriginalMoveIterator()` and `createRandomMoveIterator()` both return the same type of moves. And there is less rawtypes warnings. 😄 On the other hand, any factory implementations need to be updated.
=> Eliminate raw types in MoveListFactory and MoveIteratorFactory interfaces

optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/decider/LocalSearchDecider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/scope/LocalSearchMoveScope.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/scope/LocalSearchStepScope.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/AbstractAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/hillclimbing/HillClimbingAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/lateacceptance/LateAcceptanceAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/simulatedannealing/SimulatedAnnealingAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/stepcountinghillclimbing/StepCountingHillClimbingAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/tabu/EntityTabuAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/tabu/ValueTabuAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/forager/AcceptedForagerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/forager/finalist/StrategicOscillationByLevelFinalistPodiumTest.java
The most important change is the return type of `LocalSearchStepScope.getStep()` which makes it possible to observe steps through `PhaseLifecycleListener` so it makes sense to avoid the rawtype here.
Same changes made in `LocalSearchMoveScope` for consistency.
The changes in tests are not implied by the `LocalSearchStepScope` and `LocalSearchMoveScope` changes, they are just rawtype elimination in related code.
=> Eliminate raw Move in LS move and step scopes and some tests

optaplanner-webexamples/src/main/webapp/WEB-INF/jboss-web.xml
This allows us to use a context-root "optaplanner-webexamples", without a version number, which is a lot easier to communicate to (potential) customers when we run this demo in a cloud/container/OpenShift environment.
=> Added jboss-web.xml to set context-root.

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/src/build/revapi-config.json
Hi, @ge0ffrey,
this is only a minor change to the revapi-config.json file, since these files are no more only on master branch, but on 7.0.x as well.
Marian
P.S. I still have in plan to fine tune revapi in benchmark config classes. Sadly, there isn't time for this now, but I will try to incorporate this in the near future. Thanks for your understanding.
=> Change revapi-config.json comment to be more general

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/src/build/revapi-config.json
Hi, @ge0ffrey,
here is the promised custom config for OptaPlanner. It should check from now on only public fields + getters and setters, as you wanted.
Marian
=> Revapi: filter only public fields and getters/setters

optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/collection/TestdataArrayBasedSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/collection/TestdataSetBasedSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/extended/abstractsolution/TestdataExtendedAbstractSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/extended/abstractsolution/TestdataExtendedAbstractSolutionOverridesGetScore.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/extended/legacysolution/TestdataLegacySolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/reflect/generic/TestdataGenericSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/TestdataProblemFactPropertySolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/TestdataReadMethodProblemFactCollectionPropertySolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/autodiscover/TestdataAutoDiscoverFieldOverrideSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/autodiscover/TestdataAutoDiscoverFieldSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/autodiscover/TestdataAutoDiscoverGetterOverrideSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/autodiscover/TestdataAutoDiscoverGetterSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/autodiscover/TestdataAutoDiscoverGetterSubclassSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/autodiscover/TestdataAutoDiscoverUnannotatedEntitySolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/invalid/TestdataDuplicatePlanningEntityCollectionPropertySolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/invalid/TestdataDuplicatePlanningScorePropertySolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/invalid/TestdataDuplicateProblemFactCollectionPropertySolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/invalid/TestdataProblemFactCollectionPropertyWithArgumentSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/invalid/TestdataProblemFactIsPlanningEntityCollectionPropertySolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/invalid/TestdataUnknownFactTypeSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/invalid/TestdataUnsupportedFactTypeSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/util/TestdataCodeAssertableArrayList.java, optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
Covered use cases requested in https://issues.jboss.org/browse/PLANNER-793:
- member is a subclass of an entity class
- member is a collection of entity subclass elements
- field/getter would be autodiscovered but it uses an annotation to override the autodiscovery result
- getter is overriden and the parent was autodiscovered but the child has an explicit annotation **(broken)**
Negative test cases:
- Autodiscovery will fail with `Collection<?> getFacts()` (unsupported element type)
- Autodiscovery will fail with `MyFactCollection getFacts()` (element type is unknown)
=> PLANNER-793 Cover more autodiscovery use cases

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/reproducer/TestGenCorruptedScoreReproducer.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/reproducer/TestGenCorruptedVariableListenerReproducer.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/reproducer/TestGenDroolsExceptionReproducer.java
It appears that there is a difference in behavior of the "log4j12"
backend that causes the stack trace of exceptions to be printed, which
is not desired.
See kiegroup/optaplanner#325
=> Partially revert 8e0d114c528d3d0a47c3e6fcb179e7df0e169a4c

optaplanner-integration/optaplanner-workbench-models/optaplanner-workbench-models-datamodel-api/src/main/java/org/optaplanner/workbench/models/datamodel/util/TemplateUtils.java, optaplanner-integration/optaplanner-workbench-models/optaplanner-workbench-models-datamodel-api/src/test/java/org/optaplanner/workbench/models/datamodel/rule/ActionConstraintMatchTest.java, optaplanner-integration/optaplanner-workbench-models/optaplanner-workbench-models-datamodel-api/src/test/java/org/optaplanner/workbench/models/datamodel/util/TemplateUtilsTest.java
Related:
https://github.com/kiegroup/guvnor/pull/519
https://github.com/dashbuilder/dashbuilder/pull/372
https://github.com/kiegroup/kie-soup/pull/3
https://github.com/kiegroup/kie-wb-distributions/pull/621
https://github.com/kiegroup/droolsjbpm-tools/pull/82
https://github.com/kiegroup/optaplanner-wb/pull/218
https://github.com/kiegroup/jbpm-wb/pull/864
https://github.com/kiegroup/jbpm-designer/pull/654
https://github.com/kiegroup/drools-wb/pull/596
https://github.com/kiegroup/kie-wb-common/pull/1133
https://github.com/kiegroup/droolsjbpm-integration/pull/1163
https://github.com/kiegroup/droolsjbpm-integration/pull/1163
https://github.com/kiegroup/jbpm/pull/973
https://github.com/kiegroup/drools/pull/1444
https://github.com/kiegroup/droolsjbpm-knowledge/pull/263 …
=> AF-593: Migrate project-datamodel-* from UberFire.

optaplanner-core/pom.xml, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/termination/AbstractCompositeTermination.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/termination/ChildThreadPlumbingTermination.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/TestdataBusyEntity.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/TestdataFaultyEntity.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/TestdataSleepingEntity.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/TestdataSolutionPartitioner.java
See https://issues.jboss.org/browse/PLANNER-683.
* Added test that verifies propagation of the original exception that caused one of child partition solvers to fail.
* Child thread termination is handled by `DefaultPartitionedSearchPhase`. This piece of code is hard to test but I think it's covered by `awaitTermination()` in the test. There are no thread sleeps and the tests are quick.
As a result of the small changes accompanying the new tests, optaplanner behaves nicely and terminates all children when one of them fails or when the main thread is interrupted.
=> PLANNER-683 Add exception propagation test for Partitioned Search

optaplanner-distribution/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml
These should be last pieces to make the default `mvn clean install -Dfull` build work on JDK9.
=> JDK 9 fixes

optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhase.java
After making the semaphore fair, part threads make steps at the same rate.
<details>
<summary>Log:</summary>
```
Running org.optaplanner.core.impl.partitionedsearch.DefaultPartitionedSearchPhaseTest
17:49:00.922 [test] TRACE     Model annotations parsed for Solution TestdataSolution:
17:49:00.923 [test] TRACE         Entity TestdataEntity:
17:49:00.923 [test] TRACE             Variable value (genuine)
17:49:01.251 [test] INFO  Solving started: time spent (23), best score (0), environment mode (REPRODUCIBLE), random (JDK with seed 0).
17:49:01.269 [ad-2] TRACE                 Move index (0) not doable, ignoring move (B {0 -> 0}).
17:49:01.269 [ad-1] TRACE                 Move index (0) not doable, ignoring move (A {0 -> 0}).
17:49:01.270 [ad-3] TRACE                 Move index (0) not …
```
=> PLANNER-919 Make runnablePartThreadSemaphore fair

optaplanner-benchmark/src/main/java/org/optaplanner/swing/impl/SwingUncaughtExceptionHandler.java
- Eliminated duplicate code (`"Exception in thread " + ...`).
- Replaced complex stack trace construction with `e#printStackTrace(PrintWriter)`.
- The UI stack trace now preserves tabs in the Caused by section.
=> Simplify construction of uncaught exception message

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/BenchmarkResultIO.java
I'm working on performance report for 7.5.0.Final and I'm hitting various issues (wrong maven-exec-plugin configuration, benchmarker backward compatibility). One of them is this problem with XStream security configuration which prevents unmarshalling benchmarker reports. The fix has been backported to 7.4.x but not to 7.3.x, which is also affected.
=> PLANNER-896 Benchmark aggregator fails due to XStream security exception

optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/policy/HeuristicConfigPolicy.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/scope/PartitionChangeMove.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/queue/PartitionQueueTest.java, optaplanner-core/src/test/resources/logback-test.xml
* Bugfix: propagate logIndentation when creating phase config policy.
* Store partIndex in PartitionChangeMove and use it in toString().
* Truncate part thread name when logging to have a consistent
indentation in test logs.
=> PLANNER-910 Improve logging related to Partitioned Search

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/FieldAccessingSolutionCloner.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/util/ConcurrentCache.java
Running the most severely impacted benchmarks locally shows improvement by ~25 %. We need to run complete benchmarks to be sure this is the right fix, but all the evidence point to the `computeIfAbsent` method.
=> PLANNER-706 fix performance drop caused by using computeIfAbsent method

optaplanner-core/src/build/revapi-config.json, optaplanner-core/src/main/java/org/optaplanner/core/config/localsearch/LocalSearchPhaseConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/localsearch/decider/acceptor/AcceptorConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/localsearch/decider/forager/LocalSearchForagerConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/partitionedsearch/PartitionedSearchPhaseConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/decider/ConstructionHeuristicDecider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/scope/ConstructionHeuristicMoveScope.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/scope/ConstructionHeuristicStepScope.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/decider/ExhaustiveSearchDecider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/node/ExhaustiveSearchNode.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/DefaultLocalSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/decider/LocalSearchDecider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/decider/acceptor/Acceptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/decider/forager/AbstractLocalSearchForager.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/decider/forager/AcceptedLocalSearchForager.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/decider/forager/LocalSearchForager.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/decider/forager/finalist/FinalistPodium.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/scope/LocalSearchMoveScope.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/scope/AbstractPhaseScope.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/AbstractScoreDirector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/InnerScoreDirector.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/AbstractAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/tabu/EntityTabuAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/tabu/ValueTabuAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/forager/AcceptedLocalSearchForagerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/forager/finalist/StrategicOscillationByLevelFinalistPodiumTest.java
- Renamed Forager to LocalSearchForager
- extracted duplicated code into InnerScoreDirector.doAndProcessMove(), so multithreaded solving can reuse it too
- removed undoMove tracking (so we don't need to rebase undoMoves too in multithreaded solving)
=> Preparation for multithreaded solving

optaplanner-docs/src/main/asciidoc/Integration/Integration-chapter.adoc
I just stumbled upon the Header "16.2.4.1. JAXB: Marshalling a Score" which is a subheader of "16.2.4. JSON: Jackson" and think, it might be a typo.
=> docs: fix typo JAXB -> Jackson

optaplanner-persistence/optaplanner-persistence-jpa/src/test/filtered-resources/META-INF/persistence.xml
Relates to Narayana+DBCP integration, OptaPlanner persistence tests depend on changes introduced by https://github.com/kiegroup/drools/pull/1939.
=> PLANNER-1170 Remove unnecessary hibernate properties

optaplanner-examples/src/test/java/org/optaplanner/examples/rocktour/app/RockTourPerformanceTest.java
The test fails due to score corruption in RockTour example, which manifests with multiple move threads.
@yurloc could you please take a look?
=> [7.11.x] Skip failing test for moveThreadCount > 0

optaplanner-examples/src/test/java/org/optaplanner/examples/rocktour/app/RockTourPerformanceTest.java
The test fails due to score corruption in RockTour example, which manifests with multiple move threads.
@yurloc could you please take a look?
=> Skip failing test for moveThreadCount > 0

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/move/Move.java
javadoc should guarantee that they are only called after doMove()
=> PLANNER-1261 javadoc Move.getPlanningEntities() & getPlanningValues()

optaplanner-examples/src/main/java/org/optaplanner/examples/rocktour/domain/solver/RockShowVariableListener.java, optaplanner-examples/src/test/java/org/optaplanner/examples/rocktour/app/RockTourPerformanceTest.java
When driving seconds are over weekly budget, the budget should be
subtracted instead of putting the driving seconds to 0.
@ge0ffrey would you kindly review?
=> PLANNER-1200 subtract weekly budget from total seconds

optaplanner-docs/src/main/asciidoc/UseCasesAndExamples/ExamplesOverview/ExamplesOverview-section.adoc, optaplanner-docs/src/main/asciidoc/UseCasesAndExamples/TravellingTournament/TravellingTournament-section.adoc
Links to mat.gsia.cmu.edu give privacy errors, the fix is to change to mat.tepper.cmu.edu, it is the same website
=> fixing links that gave a privacy error

optaplanner-webexamples/pom.xml
optaplanner-webexamples overrides 'version.org.wildfly' defined in kie-parent from '14.0.1.Final' to the same version '14.0.1.Final'
This override is unnecessary and will require changes in more places when we update wildfly in the future (or will be forgotten and will cause inconsistencies).
@ge0ffrey please check and consider merging.
=> Remove useless property override

.gitignore, .travis.yml, pom.xml
- configures jacoco code coverage and reporting to sonarcloud.io
- enables travis-ci to update the sonarcloud.io with every PR
=> Configure sonarcloud and travis-ci

.travis.yml
@ge0ffrey after merging this, we should be able to see analysis on PRs like that:
https://github.com/rsynek/sonarcloud-playground/pull/2
It may require some additional settings on github side, though. Since I don't have admin privilege, I cannot check it.
=> PLANNER-1385 Enable PR code analysis by SonarCloud

optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/valuerange/buildin/bigdecimal/BigDecimalValueRangeTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/valuerange/buildin/biginteger/BigIntegerValueRangeTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/valuerange/buildin/composite/CompositeCountableValueRangeTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/valuerange/buildin/composite/NullableCountableValueRangeTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/valuerange/buildin/temporal/TemporalValueRangeTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhaseTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/acceptor/composite/CompositeAcceptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/util/PlannerAssert.java
`org.mockito.Matchers` is deprecated. Matchers are now obtained by statically importing `Mockito` which extends `ArgumentMatchers`.
`any(Class)` no longer accepts `null` -> needed to set up a few additional mocks.
=> Fixes related to Mockito upgrade

optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/persistence/ConferenceSchedulingCfpDevoxxImporter.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/swingui/ConferenceCFPImportAction.java
devoxx-cfp exposes timeslots via two endpoints:
- `/slots`: Timeslots as problem facts. It displays all available timeslots without additional data.
- `/schedules/`: The conference solution, i.e. it displays days, timeslots within each day and the talk scheduled at this timeslot.
If users choose to import data using `/slots` endpoint, they'll get an empty problem to solve from scratch, however if they choose `/schedules/`, they'll get the current schedule to either view it or continue solving.
=> Add ability to import timeslots from /slots endpoint

optaplanner-docs/src/main/asciidoc/Integration/Integration-chapter.adoc
These steps are based on https://github.com/mwkroening/optaplanner-modulepath-example/commit/e8f909250a6664b368f55b6dd503bd2cc3240824
and https://github.com/psiroky/optaplanner-cloudbalancing-jdk9
The requirement to open up the two packages to all modules is really bothering me.
When opening the domain package only to `org.optaplanner.core`, I get this message:
```bash
Exception in thread "main" java.lang.IllegalAccessError: class org.drools.base.io.github.mwkroening.optaplannermodulepathexample.domain.CloudProcess520162288$getComputer (in unnamed module @0x4d68b571) cannot access class io.github.mwkroening.optaplannermodulepathexample.domain.CloudProcess (in module io.github.mwkroening.optaplannermodulepathexample) because module io.github.mwkroening.optaplannermodulepathexample does not …
```
=> Complement JPMS requirements

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/ProblemBenchmarkResult.java, optaplanner-benchmark/src/main/resources/org/optaplanner/benchmark/impl/report/benchmarkReport.html.ftl
The issue has been sitting in the queue for quite some time. Came across huge datasets recently, where this would have been super useful.
=> PLANNER-583 Benchmarker report should mention how long it took to load a problem's inputSolutionFile

optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseTest.java
1 second timeout is too strict; it may randomly fail on Jenkins machines.
=> Increase timeouts for flaky tests

optaplanner-persistence/optaplanner-persistence-jpa/src/main/java/org/optaplanner/persistence/jpa/impl/score/AbstractScoreHibernateType.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/bendable/BendableScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/bendablebigdecimal/BendableBigDecimalScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/bendablelong/BendableLongScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/hardmediumsoft/HardMediumSoftScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/hardmediumsoftlong/HardMediumSoftLongScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/hardsoft/HardSoftScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/hardsoftdouble/HardSoftDoubleScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/hardsoftlong/HardSoftLongScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/simple/SimpleScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/simplebigdecimal/SimpleBigDecimalScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/simpledouble/SimpleDoubleScoreHibernateTypeTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/score/buildin/simplelong/SimpleLongScoreHibernateTypeTest.java
Accessing hard/soft score levels in Hibernate starts from 1 (0 is for initScore), this results in an ArrayIndexOutOfBoundsException when accessing the last score level.
=> PLANNER-1530 Fix AIOOBE when deserializnig score levels

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenDateValueProvider.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/fact/TestGenValueFact.java
This modification was necessary for me to proceed in isolation of NPE in Drools.
=> Support java.util.Date in TestGen

optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTerminationTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/UnimprovedTimeMillisSpentTerminationTest.java
- adds a new constructor taking a `Clock` instance as a parameter to enable testing
- provides unit coverage for both the `UnimprovedTimeMillisSpentTermination` and `UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination`
- fixes a bug that solving terminates despite the fact that score improved within a time limit over a given threshold
=> PLANNER-1270 Provide tests and fix for unimproved time spent score diff termination

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/pillar/DefaultPillarSelector.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/entity/pillar/DefaultPillarSelectorTest.java
@rsynek's benchmarks have shown that subpillars have actually regressed in raw Java performance. For that reason, I have gone back and [ran the new algorithm in JMH against its old implementation](https://docs.google.com/spreadsheets/d/1Szqv2bMRZaker15v7TtU7aj2q7XQ2Gs2cXttwMNFHnY/edit#gid=0) in a very wide range of circumstances.
- The new implementation (`STREAM+SHORTCUT`) is indeed better than the original loop (`ORIGINAL`) in a lot of places.
- However, this new data also shows that it is **only better in places where the code uses the shortcuts** [1]. The stream actually sucks in places where the shortcuts are not in effect. [2]
- Therefore we take the original loop, apply the same shortcuts, and we get the best results (`LOOP+SHORTCUT`).
I am submitting this PR, which implements …
=> Address subpillar performance regression (follow-up to PLANNER-1565)

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/accessor/LambdaBeanPropertyMemberAccessor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/accessor/MemberAccessorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/accessor/ReflectionBeanPropertyMemberAccessor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/accessor/ReflectionFieldMemberAccessor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/accessor/ReflectionMethodMemberAccessor.java
This gives a useful hint, but that hint may not be applicable at all times. [See here](https://stackoverflow.com/questions/57711906/redhat-decision-manager-7-3-opta-cloud-solver-example-not-working) for a situation where the hint would mislead people - therefore I am not adding the same message on setters.
=> PLANNER-1586 Mention classloader in reflection-related exceptions

optaplanner-docs/src/main/asciidoc/MoveAndNeighborhoodSelection/MoveAndNeighborhoodSelection-chapter.adoc
@ge0ffrey The `SelectionFilter` generic signature must have changed at some point. I discovered this when I was going over some code in nurse rostering.
=> Update outdated SelectionFilter doc

optaplanner-core/src/main/java/org/optaplanner/core/config/solver/termination/TerminationConfig.java, optaplanner-core/src/test/java/org/optaplanner/core/config/solver/termination/TerminationConfigTest.java, optaplanner-docs/src/main/asciidoc/OptimizationAlgorithms/OptimizationAlgorithms-chapter.adoc
Needed so we can do this in quarkus/spring-boot application.properties:
optaplanner.spentLimit=PT2M30S
=> PLANNER-1635 Termination should support java.time.Duration

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/uni/UniConstraintCollector.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/ConstraintCollectorsTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/uni/UniConstraintStreamTest.java
Some questions to answer:
- Is this kind of `min` or `max` valid on bi-streams and higher? What would it do there?
- The collectors return null when the result makes no sense. (Such as "minimum of empty stream.") My assumption is that we would never get to see those situations, since an empty stream would never call the collector in the first place. Is the assumption correct?
- Does this help to address some of the feature gaps we have in the implementation currently? If so, what examples could we improve with this?
=> PLANNER-1666 Add min() and max() UniCollector

optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/AndCompositeTerminationTest.java
The only class from the TerminationTest not yet covered in the upstream was the AndCompositeTeminationTest, which is covered in this commit.
=> PLANNER-1638 Migrate TerminationTest to upstream

optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/AndCompositeTerminationTest.java
Changed test cases that were suppose to cover corner cases but after consulting SonarCloud did not. Add negative cases of time gradient. In addition, add explaining comments, so that the choice of values is more transparent.
=> PLANNER-1674 Change values to cover more branches and add comments to AndCompositeTerminationTest

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/report/BenchmarkReport.java
Fixes regression caused by upgrading `JFreeChart` from `1.0.19` to `1.5.0` in #576
=> PLANNER-1685: Benchmark Regression Fix

optaplanner-core/src/build/revapi-config.json, optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/Joiners.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/bi/BiConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/uni/UniConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/bi/BavetAbstractBiConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/uni/BavetAbstractUniConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/bi/DroolsAbstractBiConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/bi/DroolsBiCondition.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsLogicalTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/tri/DroolsTriCondition.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/uni/DroolsAbstractUniConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/uni/DroolsUniAccumulateFunctionBridge.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/uni/DroolsUniCondition.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/uni/UniConstraintStreamTest.java, optaplanner-docs/src/main/asciidoc/ConstraintStreams/ConstraintStreams-chapter.adoc, optaplanner-examples/src/main/java/org/optaplanner/examples/cloudbalancing/optional/score/CloudBalancingConstraintProvider.java, optaplanner-examples/src/main/java/org/optaplanner/examples/conferencescheduling/optional/score/ConferenceSchedulingConstraintProvider.java, optaplanner-examples/src/main/java/org/optaplanner/examples/curriculumcourse/optional/score/CourseScheduleConstraintProvider.java, optaplanner-examples/src/main/java/org/optaplanner/examples/machinereassignment/solver/score/MachineReassignmentConstraintProvider.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nqueens/solver/score/NQueensConstraintProvider.java, optaplanner-examples/src/main/java/org/optaplanner/examples/vehiclerouting/optional/score/VehicleRoutingConstraintProvider.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/cloudbalancing/optional/benchmark/cloudBalancingScoreDirectorBenchmarkConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/nqueens/benchmark/nqueensScoreDirectorBenchmarkConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/taskassigning/benchmark/taskAssigningScoreDirectorBenchmarkConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/vehiclerouting/benchmark/vehicleRoutingScoreDirectorBenchmarkConfig.xml
The changes I've made:
- [Improved performance](https://docs.google.com/spreadsheets/d/1SP1QzVkGSiPah4WzLtlZD7Y3bk9FWcx5H0J3BY7-4ag/edit#gid=1301881863). The "friendly" examples are no longer horribly slow.
- Removed from the API methods that would throw `UnsupportedOperationException` with the Drools backend. They will be added in the future.
- Added a section of documentation discussing the two implementations.
- Removed all notions of "tech preview".
We have a meeting on Tuesday 29th to discuss if this is enough.
=> PLANNER-1689 Make Drools the default backend for Constraint Streams

optaplanner-benchmark/pom.xml, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/blueprint/SolverBenchmarkBluePrintConfigTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/report/BenchmarkReportConfigTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/DefaultPlannerBenchmarkTest.java
The tests in bxms-qe-tests in BenchmarkParallelExecutionTest were covered by the example module. In the spirit of increasing test coverage in the part that is touched by the migrating tests, I have found a few untested parts, mainly inheritance in BenchmarkReportConfig and exception message propagation in DefaultPlannerBenchmarkTest.
=> PLANNER-1639 Migrate BenchmarkParallelExecutionTest to upstream

optaplanner-core/pom.xml
[lpetrovi@sagan optaplanner]$ diff 7.29.txt 7.30.txt 
16,21c16,21
< [INFO] +- org.drools:drools-canonical-model:jar:7.30.0-SNAPSHOT:compile (optional)
< [INFO] +- org.drools:drools-model-compiler:jar:7.30.0-SNAPSHOT:compile (optional)
< [INFO] |  +- com.github.javaparser:javaparser-core:jar:3.13.10:compile (optional)
< [INFO] |  +- org.drools:drools-mvel-parser:jar:7.30.0-SNAPSHOT:compile (optional)
< [INFO] |  |  \- org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:jar:1.0.0.Final:compile (optional)
< [INFO] |  \- org.drools:drools-mvel-compiler:jar:7.30.0-SNAPSHOT:compile (optional)
---
> [INFO] +- org.drools:drools-canonical-model:jar:7.30.0-SNAPSHOT:compile
> [INFO] +- org.drools:drools-model-compiler:jar:7.30.0-SNAPSHOT:compile
> [INFO] |  +- …
=> PLANNER-1689 Drools Model JARs no longer optional

pom.xml
junit-vintage-engine currently leaks into e.g. drools-wb as the project depends on kie-server-api, which depends on optaplanner-core. Reducing the dependency scope to test is sufficient and prevents the vintage engine from leaking into other repositories.
The fact that kie-server-api depends on optaplanner-core is an issue on its own; maybe we could move the optaplanner API into a separate module in the future?
=> PLANNER-1716 Reduce scope of the junit-vintage-engine to test

optaplanner-core/src/main/java/org/optaplanner/core/config/phase/custom/CustomPhaseConfig.java, optaplanner-docs/src/main/asciidoc/OptimizationAlgorithms/OptimizationAlgorithms-chapter.adoc
Motivation: forceUpdateBestSolution was a hack, introduced before PFC probably, to use in a Santa compo once. I am not aware of anyone else actually using it.
This is not compatible with https://issues.jboss.org/browse/PLANNER-241 which allows for skipping phases if all entities are immovable.
Furthermore, it is fundamentally wrong for phases to worsen the best score.
=> Deprecate forceUpdateBestSolution

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/valuerange/descriptor/AbstractFromPropertyValueRangeDescriptor.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/reflect/generic/TestdataGenericEntity.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/reflect/generic/TestdataGenericSolution.java
I am getting following error when using kotlin data classes as PlanningEntity having a PlanningVariable with valueRangeProviderRefs to a collection of kotlin data classes. Following is the stacktrace of the error. I was able to reproduce this issue on master branch of optaplanner.
> java.lang.IllegalArgumentException: The entityClass (class org.divy.resource.planning.domain.allocation.IterationAllocation) has a PlanningVariable annotated property (employee) that refers to a ValueRangeProvider annotated member (field private java.util.List org.divy.resource.planning.domain.iteration.IterationAllocations.employeeList) that returns a parameterized Collection with an unsupported type arguments (? extends org.divy.resource.planning.domain.employee.Employee).
```
at …
```
=> PLANNER-1777 bugfix when using java generics or kotlin open classes

optaplanner-core/src/test/java/org/optaplanner/core/api/solver/SolverManagerTest.java
There has been a potential bug found: not being able to terminate a job with terminateEarly() and close() having status SOLVING_SCHEDULED
=> PLANNER-1802 Add early termination test for SolverManager

optaplanner-docs/src/main/asciidoc/UseCasesAndExamples/CheapTime/CheapTime-section.adoc, optaplanner-docs/src/main/asciidoc/UseCasesAndExamples/ExamplesOverview/ExamplesOverview-section.adoc
That page simply doesn't exist any more, but bad links are forbidden, even if we loose the URL information because of this.
=> PLANNER-1329 Links to ICON challenge in documentation do not work

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/ConstraintCollectorsTest.java, optaplanner-docs/src/main/asciidoc/ConstraintStreams/ConstraintStreams-chapter.adoc
This is a simple "last resort" collector for when our other collectors are insufficient. People can always retrieve a collection of the facts, and perform whatever operation they want on them afterwards.
WIthout providing this functionality, people would have to resort to submitting feature requests and be blocked before we implement them.
=> PLANNER-1613 toList() and toSet() constraint collectors

optaplanner-examples/src/main/java/org/optaplanner/examples/scrabble/optional/score/ScrabbleConstraintProvider.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/scrabble/solver/scrabbleSolverConfig.xml, optaplanner-examples/src/test/java/org/optaplanner/examples/scrabble/app/ScrabblePerformanceTest.java
Note: FAST_ASSERT passes, but FULL_ASSERT fails
```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.996 s <<< FAILURE! - in org.optaplanner.examples.scrabble.app.ScrabblePerformanceTest
[ERROR] solveModel[0: NONE]  Time elapsed: 7.994 s  <<< ERROR!
java.lang.IllegalStateException: 
Score corruption (4hard): the workingScore (-130init/2hard/0medium/-13soft) is not the uncorruptedScore (-130init/-2hard/0medium/-13soft) after completedAction ([ OPTAPLANNER  {HORIZONTAL -> HORIZONTAL},  OPTAPLANNER  {(1,20) -> (1,20)}]):
Score corruption analysis:
The corrupted scoreDirector has 4 ConstraintMatch(s) which are in excess (and should not be there):
org.optaplanner.examples.scrabble.domain/Character confict/[(12,20)]=1hard/0medium/0soft …
```
=> PLANNER-1829: Add a ConstraintProvider for Scrabble

optaplanner-docs/src/main/asciidoc/Integration/Integration-chapter.adoc, optaplanner-docs/src/main/asciidoc/LocalSearch/LocalSearch-chapter.adoc, optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc, optaplanner-docs/src/main/asciidoc/ScoreCalculation/ScoreCalculation-chapter.adoc
Replace `'s` (indicates a possessive form) where a plural form was actually intended.
=> Fix plural forms

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/AbstractSolution.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptorTest.java
The tests in `org.optaplanner.core.impl.domain.solution.descriptor.SolutionDescriptorTest#extendedAbstractSolutionOverridesGetScore` and `extendedAbstractSolution` causes assertion failures due to the order of the elements.
The root cause is that when executing `solutionDescriptor.getAllFacts(solution)` in `SolutionDescriptorTest.java`, it will invoke the `org.optaplanner.core.impl.domain.solution.AbstractSolution.addProblemFactsFromClass`, which calls `java.lang.Class.getDeclaredFields`. The Java8 specification about `getDeclaredFields` is that "The elements in the returned array are not sorted and are not in any particular order", with reference here: https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html. Therefore, this test may fail due to a different order.
In order to make …
=> sort fields for deterministic order

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/ConstraintCollectorsTest.java
This, I think, completes our collection of collectors. I can't think of anything else we'd need out of the box.
Introduces six kinds of methods, the end result of which is:
1. `Map<X, Set<Y>>`.
1. `Map<X, C<Y>>`, where `C` is a `Set` provided by the user. (So that they can use `TreeSet`.)
1. `Map<X, Y>` with a reducer from `Set<Y>` to `<Y>`. 
1. `SortedMap<X, Set<Y>>`.
1. `SortedMap<X, C<Y>>`, where `C` is a `Set` provided by the user. (So that they can use `TreeSet`.)
1. `SortedMap<X, Y>` with a reducer from `Set<Y>` to `<Y>`. 
Also, for consistency, I'm adding similar `toSortedSet()` methods to accompany the current `toSet()` methods.
=> PLANNER-1863: toMap() collector

optaplanner-persistence/optaplanner-persistence-jaxb/pom.xml, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/AbstractScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/bendable/BendableScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/bendablebigdecimal/BendableBigDecimalScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/bendablelong/BendableLongScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/hardmediumsoft/HardMediumSoftScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/hardmediumsoftlong/HardMediumSoftLongScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/hardsoft/HardSoftScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/hardsoftdouble/HardSoftDoubleScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/hardsoftlong/HardSoftLongScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/simple/SimpleScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/simplebigdecimal/SimpleBigDecimalScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/simpledouble/SimpleDoubleScoreJaxbXmlAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/simplelong/SimpleLongScoreJaxbXmlAdapterTest.java
Merge with: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1185
Jira: https://issues.redhat.com/browse/PLANNER-1851
- Adds the MOXy JAXB provider dependency for JSON marshalling support.
- Adds JSON score marshalling tests
=> [PLANNER-1851] Add MOXy for JAXB JSON binding in optaplanner-persistence-jaxb

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/BiTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractBiCollectingGroupByAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractGroupBy.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractGroupByAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractGroupByInvoker.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsAbstractUniCollectingGroupByAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsCondition.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/DroolsRuleStructure.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/GroupByAccumulator.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/QuadTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/TriTuple.java
- More efficient accumulate() implementation which now scales much better.
- Several small shortcuts.
This doesn't solve the larger performance problem, which I'm having trouble reproducing in controlled benchmarks.
=> Performance improvements to Drools-based Constraint Streams

.github/workflows/os_java_ci.yml
Provides testing on multiple OS and Java versions via GitHub actions.
An example of how the checks look like (please note it's not 100% in sync with this PR):
https://github.com/rsynek/optaplanner/pull/1
Most importantly, we have:
- various OS and JDK covered before merging a PR
- results publicly available (in contrast with the existing Jenkins PR check)
As a bonus, we have early feedback on OptaPlanner's compatibility with the newest Java version (thanks @triceo was suggesting that).
=> PLANNER-1968 Add OSxJava matrix PR check

optaplanner-examples/src/test/java/org/optaplanner/examples/cheaptime/persistence/CheapTimeOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/cloudbalancing/persistence/CloudBalancingOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/coachshuttlegathering/persistence/CoachShuttleGatheringOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/app/ImportDirSolveAllTurtleTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/app/SolverPerformanceTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/app/UnsolvedDirSolveAllTurtleTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/persistence/OpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/conferencescheduling/persistence/ConferenceSchedulingOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/curriculumcourse/persistence/CurriculumCourseOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/dinnerparty/persistence/DinnerPartyOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/examination/persistence/ExaminationOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/flightcrewscheduling/persistence/FlightCrewSchedulingOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/investment/persistence/InvestmentOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/machinereassignment/persistence/MachineReassignmentOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/meetingscheduling/persistence/MeetingSchedulingOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nqueens/persistence/NQueensOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nurserostering/persistence/NurseRosteringOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/pas/persistence/PatientAdmissionScheduleOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/projectjobscheduling/persistence/ProjectJobSchedulingOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/rocktour/persistence/RockTourOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/taskassigning/persistence/TaskAssigningOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/tennis/persistence/TennisOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/travelingtournament/persistence/TravelingTournamentOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/tsp/persistence/TspOpenDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/vehiclerouting/persistence/VehicleRoutingOpenDataFilesTest.java
Details that I overlooked in #764. Naming changes improve consistency with the rest of the code.
=> PLANNER-1003 Final touches (naming, visibility)

.github/workflows/jpa_integration_ci.yml, .github/workflows/os_java_ci.yml
As the 7.x branch has become another long-live branch now, we should have the same level of CI there.
=> Enable GitHub Actions for 7.x branch

optaplanner-benchmark/src/test/resources/org/optaplanner/benchmark/config/testBenchmarkConfig.xml, optaplanner-core/src/test/java/org/optaplanner/core/config/solver/SolverConfigTest.java, optaplanner-core/src/test/resources/org/optaplanner/core/config/solver/testSolverConfig.xml
Please note that JAXB changes the order of sibling elements - based on the position of corresponding fields in the class. It matters only for serialization. During deserialization, JAXB does not care about the order of sibling elements (unless told otherwise).
=> PLANNER-1921 Increase test coverage for solver configs

optaplanner-build-parent/pom.xml, optaplanner-examples/pom.xml
At least so, it says here:
https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html
If that forkCount is there and junit 4 is not in the classpath, the tests don't run.
=> Fix examples tests: JUnit 5 does not support forkCount

.github/workflows/jpa_integration_ci.yml
Jira: https://issues.redhat.com/browse/PLANNER-2049
Accounts for `optaplanner-core` api and version changes by building it before running `optaplanner-persistence-jpa` CI container tests.
=> Build optaplanner-core in optaplanner-persistence-jpa CI

optaplanner-benchmark/pom.xml, optaplanner-build-parent/pom.xml, optaplanner-core/pom.xml, optaplanner-examples/pom.xml, optaplanner-examples/src/test/java/org/optaplanner/examples/machinereassignment/solver/score/MachineReassignmentConstraintProviderTest.java, optaplanner-integration/optaplanner-spring-boot-autoconfigure/pom.xml, optaplanner-integration/optaplanner-spring-boot-starter/pom.xml, optaplanner-persistence/optaplanner-persistence-common/pom.xml, optaplanner-persistence/optaplanner-persistence-jackson/pom.xml, optaplanner-persistence/optaplanner-persistence-jsonb/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/pom.xml, optaplanner-quickstarts/quarkus-school-timetabling/src/main/java/org/acme/schooltimetabling/domain/TimeTable.java
Use maven-dependency-plugin to fail the build if any used undeclared
or unused declared dependencies are found.
The plugin is configured to ignore non-compile dependencies. This avoids
having to ignore runtime and test-runtime dependencies individually.
Explanation:
- The plugin cannot detect if a declared runtime dependency is unused.
- The plugin cannot detect if an undeclared runtime dependency is used
transitively. It is contributor's responsibility to declare runtime
dependencies even though they are provided transitively.
- Missing runtime dependencies should be detected by tests. It's
contributor's responsibility to write tests using runtime dependencies
or to document why a runtine dependency is declared in case it
cannot be covered by tests.
- The plugin will detect unused …
=> PLANNER-1996: Enable dependency check

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfig.java, optaplanner-core/pom.xml, optaplanner-core/src/main/java/org/optaplanner/core/config/solver/SolverConfig.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendable/BendableScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendablebigdecimal/BendableBigDecimalScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/bendablelong/BendableLongScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardmediumsoft/HardMediumSoftScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardmediumsoftlong/HardMediumSoftLongScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardsoft/HardSoftScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/hardsoftlong/HardSoftLongScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/simple/SimpleScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/simplebigdecimal/SimpleBigDecimalScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/buildin/simplelong/SimpleLongScoreTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/util/PlannerTestUtils.java
This PR removes the remaining usage of XStream from optaplanner-core.
It removes tests of Score (de)serialization, as these are duplicate to tests of optaplanner-persistance-xstream [1]. Test coverage measured after removing these tests shows no differences compared to coverage of the master branch.
[1] https://github.com/kiegroup/optaplanner/tree/master/optaplanner-persistence/optaplanner-persistence-xstream/src/test/java/org/optaplanner/persistence/xstream/api/score/buildin
=> Remove XStream from optaplanner-core

optaplanner-core/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/OptaPlannerBeanProvider.java
See https://github.com/quarkusio/quarkus/issues/2531 for details:
Resources inside the deployment are not on the system class path in dev mode, as we need a new class loader to enable hot deployment.
TODO:
Look for other instances of `getClass().getClassLoader()` and replace with `Thread.currentThread().getContextClassLoader()`
=> PLANNER-1960: Use Thread.currentThread().getContextClassLoader() when loading Drools for Quarkus

optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/DefaultLocalSearchPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/NoChangePhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/custom/DefaultCustomPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverFactory.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseFactoryTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/director/ScoreDirectorFactoryFactoryTest.java
Also:
- renames `resolvedActiveThreadCount` to `resolveActiveThreadCount`
- fixes error message by passing correct instance to `ConfigUtils.newInstance`.
=> Reduce raw types usage

optaplanner-build-parent/pom.xml, optaplanner-quarkus-integration/pom.xml, optaplanner-quickstarts/quarkus-facility-location/pom.xml, optaplanner-quickstarts/quarkus-school-timetabling/build.gradle, optaplanner-quickstarts/quarkus-school-timetabling/pom.xml
Do not merge before io.quarkus:quarkus-bom-deployment:1.7.0.Final is available.
Locally optaplanner-quarkus-integration tests passed with 1.7.0.Final core artifacts (and quarkus-bom-deployment:1.6.0.Final).
=> Upgrade Quarkus to 1.7.0.Final

optaplanner-examples/src/main/java/org/optaplanner/examples/examination/domain/Topic.java, optaplanner-examples/src/test/java/org/optaplanner/examples/examination/solver/score/ExaminationConstraintProviderTest.java
Prevents NPE when the test fails. Also, breaks down a single mega test into multiple smaller tests.
=> Refactor ExaminationConstraintProviderTest.mixedDurationsTest

optaplanner-core/src/build/revapi-config.json, optaplanner-core/src/main/java/org/optaplanner/core/config/constructionheuristic/ConstructionHeuristicPhaseConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/constructionheuristic/placer/PooledEntityPlacerConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/constructionheuristic/placer/QueuedEntityPlacerConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/constructionheuristic/placer/QueuedValuePlacerConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/exhaustivesearch/ExhaustiveSearchPhaseConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/move/MoveSelectorConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/move/composite/CartesianProductMoveSelectorConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/move/composite/UnionMoveSelectorConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/chained/KOptMoveSelectorConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/localsearch/LocalSearchPhaseConfig.java
**How to retest or run**:
* a pull request please add comment: regex **[.\*[j|J]enkins,?.\*(retest|test) this.\*]**
* a full downstream build please add comment: regex **[.*\[j|J]enkins,?.\*(execute|run|trigger|start|do) fdb.\*]**
* a compile downstream build please  add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) cdb.\*]**
* a full production downstream please add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) product fdb.\*]**
* an upstream build please add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) upstream.\*]**
i.e for running a full downstream build =  **Jenkins do fdb**
=> Remove KOptMoveSelector from XML configuration

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfig.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfigTest.java, optaplanner-core/src/build/revapi-config.json, optaplanner-core/src/main/java/org/optaplanner/core/config/partitionedsearch/PartitionedSearchPhaseConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/solver/SolverManagerConfig.java, optaplanner-core/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverFactory.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseFactoryTest.java, optaplanner-docs/src/main/asciidoc/BenchmarkingAndTweaking/BenchmarkingAndTweaking-chapter.adoc, optaplanner-docs/src/main/asciidoc/OptimizationAlgorithms/OptimizationAlgorithms-chapter.adoc, optaplanner-docs/src/main/asciidoc/PartitionedSearch/PartitionedSearch-chapter.adoc
Verified to work correctly on OpenJDK 15.
This will not be backported to 7.x - we'll have to use a different approach there.
=> PLANNER-2135 Remove support for JavaScript expressions from configs

optaplanner-build-parent/pom.xml
In the end, it was easier than expected: XStream fixed the illegal reflective access warnings, and all we have to do is upgrading to the latest version.
https://issues.redhat.com/browse/PLANNER-2144
backport to 7.x: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1455
<details>
<summary>
</summary>
</details>
=> PLANNER-2144 Upgrade XStream to the latest version

.github/workflows/jpa_integration_ci.yml, .github/workflows/os_java_ci.yml, .github/workflows/quarkus-snapshot.yaml
Implemented Github Actions' Maven caching mechanism. The goals:
- Maven repos are only downloaded incrementally, not the entire world every single time.
- This reduces the likelihood of Maven Central error failing the build.
- And should also speed up CI significantly.
Results once cached:
- Main CI went from 20 min to 15 min, **25 % run time improvement**.
- Persistence CI went from 7.5 min to 3.25 min, **50 % run time improvement**.
There were **no Maven Central-related failures**.
=> Improve CI performance by caching local Maven repo

optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/custom/AbstractCustomPhaseCommand.java
https://issues.redhat.com/browse/PLANNER-1362
https://github.com/kiegroup/optaplanner/pull/935
<details>
<summary>
</summary>
</details>
=> [7.x] PLANNER-1362 Deprecate AbstractCustomPhaseCommand

optaplanner-examples/src/main/java/org/optaplanner/examples/coachshuttlegathering/domain/Bus.java, optaplanner-examples/src/main/java/org/optaplanner/examples/coachshuttlegathering/domain/Coach.java, optaplanner-examples/src/main/java/org/optaplanner/examples/coachshuttlegathering/domain/Shuttle.java, optaplanner-examples/src/main/java/org/optaplanner/examples/coachshuttlegathering/domain/solver/BusPassengerCountTotalUpdatingVariableListener.java, optaplanner-examples/src/main/java/org/optaplanner/examples/coachshuttlegathering/domain/solver/CoachPassengerCountTotalUpdatingVariableListener.java, optaplanner-examples/src/main/java/org/optaplanner/examples/coachshuttlegathering/domain/solver/ShuttlePassengerCountTotalUpdatingVariableListener.java, optaplanner-examples/src/main/java/org/optaplanner/examples/coachshuttlegathering/solver/CoachShuttleGatheringConstraintProvider.java, optaplanner-examples/src/main/java/org/optaplanner/examples/coachshuttlegathering/solver/CoachShuttleGatheringEasyScoreCalculator.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/coachshuttlegathering/solver/coachShuttleGatheringConstraints.drl, optaplanner-examples/src/main/resources/org/optaplanner/examples/coachshuttlegathering/solver/coachShuttleGatheringSolverConfig.xml, optaplanner-examples/src/test/java/org/optaplanner/examples/coachshuttlegathering/solver/CoachShuttleGatheringConstraintProviderTest.java
https://issues.redhat.com/browse/PLANNER-1873
https://issues.redhat.com/browse/PLANNER-1821
<details>
<summary>
</summary>
</details>
Replaces https://github.com/kiegroup/optaplanner/pull/691 and https://github.com/kiegroup/optaplanner/pull/793
Coach Capacity was a fun one; it would be easy if we had an accumlate that …
=> PLANNER-1821 & PLANNER-1873: Add Constraint Provider for Coach Shuttle Gathering

optaplanner-quarkus-integration/pom.xml
Otherwise `optaplaner-quarkus` gives `optaplanner-core:7.36.1.Final` in the dep tree.
=> [7.x] Bump Quarkus and Kogito to fix stale optaplanner-core dep

optaplanner-core/src/test/java/org/optaplanner/core/config/heuristic/selector/common/nearby/NearbySelectionConfigTest.java, optaplanner-core/src/test/java/org/optaplanner/core/config/solver/EnvironmentModeTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/exhaustivesearch/BlackBoxExhaustiveSearchPhaseTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/io/jaxb/GenericJaxbIOTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/decider/forager/finalist/StrategicOscillationByLevelFinalistPodiumTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/business/AlphaNumericStringComparatorTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nqueens/app/NQueensAppTest.java, optaplanner-persistence/optaplanner-persistence-jackson/src/test/java/org/optaplanner/persistence/jackson/api/score/AbstractScoreJacksonRoundTripTest.java, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/AbstractScoreJaxbAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/AbstractScoreJpaTest.java, optaplanner-persistence/optaplanner-persistence-xstream/src/test/java/org/optaplanner/persistence/xstream/api/score/AbstractScoreXStreamConverterTest.java
Improve readability and consistency by using static imports for `assert*()` methods.
<details>
<summary>
</summary>
</details>
=> Use static import for assertion methods

.github/workflows/jpa_integration_ci.yml, .github/workflows/os_java_ci.yml, .gitignore, .mvn/maven.config
Puts the maven connection properties into .mvn/maven.config so that any CI can use it. The properties values have been aligned with kogito-runtimes, which uses the same approach.
<details>
<summary>
</summary>
</details>
=> Move connection properties to maven.config

optaplanner-build-parent/pom.xml, optaplanner-docs/src/main/asciidoc/BenchmarkingAndTweaking/BenchmarkingAndTweaking-chapter.adoc, optaplanner-persistence/optaplanner-persistence-jackson/pom.xml, optaplanner-persistence/optaplanner-persistence-jackson/src/main/java/org/optaplanner/persistence/jackson/impl/domain/solution/JacksonSolutionFileIO.java, optaplanner-persistence/optaplanner-persistence-jackson/src/test/java/org/optaplanner/persistence/jackson/impl/domain/solution/JacksonSolutionFileIOTest.java, optaplanner-persistence/optaplanner-persistence-jackson/src/test/java/org/optaplanner/persistence/jackson/impl/testdata/domain/JacksonTestdataValue.java
Hello,
I was working on using json formatted files as input solution files for benchmarking. I implemented a custom SolutionFileIO implementation and thought that a extendable JsonSolutionFileIO would be a good contribution.
From my understanding there are changes for benchmark configurations in the upcoming 8.0.0. 
Therefore, since `xStreamAnnotatedClass` has been removed, creating a configurable `JacksonAnnotatedClass` would not be desirable.
So, I aimed to make `JsonSolutionFileIO` **heavily** influenced by `XStreamSolutionFileIO`.
The only difference would be that the JsonSolutionFileIO lets the Jackson ObjectMapper to be created by the client in order to provide a high customizable ObjectMapper according to the clients desire.
I could provide the documentation in how to use the …
=> Implemented a JsonSolutionFileIO for benchmark input solution files

optaplanner-benchmark/pom.xml, optaplanner-build-parent/pom.xml
If there is a compilation failure it should be reported by the compiler plugin and not by the jaxb2 plugin, which was originally configured to run in an earlier phase.
<details>
<summary>
</summary>
</details>
=> Move XSD generation to a later phase

.github/workflows/jpa_integration_ci.yml, .github/workflows/os_java_ci.yml, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/DefaultPlannerBenchmark.java, optaplanner-build-parent/pom.xml
https://issues.redhat.com/browse/PLANNER-2187
https://github.com/kiegroup/optaplanner-quickstarts/pull/6
https://github.com/kiegroup/optaplanner-website/pull/285
<details>
<summary>
</summary>
</details>
=> PLANNER-2187 Use java 11 minimum for OptaPlanner 8

optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseTest.java
This measure is to prevent the DefaultPartitionedSearchPhaseTest.terminateEarly() test to stop failing occasionally.
=> Increase DefaultPartitionedSearchPhaseTest timeout to prevent flakiness

optaplanner-distribution/pom.xml, optaplanner-distribution/src/main/assembly/assembly-optaplanner.xml, optaplanner-quickstarts/quarkus-school-timetabling/pom.xml, pom.xml
A cherry-pick of https://github.com/kiegroup/optaplanner/commit/c143e1f82ac02f639595439d9055a970bdb2bdb6
https://issues.redhat.com/browse/RHPAM-3256
<details>
<summary>
</summary>
</details>
=> [7.44.x] RHPAM-3256 Fix for productized assembly with spring-boot quickstart

Jenkinsfile.deploy, Jenkinsfile.promote, optaplanner-build-parent/pom.xml, pom.xml
https://issues.redhat.com/browse/PLANNER-2142
https://github.com/kiegroup/kogito-pipelines/pull/69
https://github.com/kiegroup/kogito-examples/pull/402
<details>
<summary>
</summary>
</details>
=> PLANNER-2142 Make OptaPlanner 8 a part of kogito release pipeline

optaplanner-distribution/src/main/assembly/assembly-optaplanner.xml
The pom file for optaplanner-examples references
`../ide-configuration` to configure the automatic
code formatter. This folder was not included in the
distribution, which causes `mvn clean install` to fail
if a user try building from the `examples/sources`
folder. To remedy this, the folder was included so
builds will past.
https://issues.redhat.com/browse/PLANNER-2085
<details>
<summary>
</summary>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product …
=> [7.X] PLANNER-2085: Include ide-configuration in distribution

Jenkinsfile.deploy
Backports the https://github.com/kiegroup/optaplanner/pull/992.
<details>
<summary>
</summary>
</details>
=> [8.0.0.beta1] Add dependencies repository before mvn install

Jenkinsfile.deploy
Adds the staging repository to a `mvn install` run directly. The quarkus bootstrap maven resolver does not respect settings passed via .mvn/maven.config.
<details>
<summary>
</summary>
</details>
=> Add dependencies repository before mvn install

Jenkinsfile.deploy
Small bug correction as cleanInstall was ignored if no MAVEN_DEPENDENCIES_REPOSITORY is set
=> Deploy Pipeline executes MavenCleanInstall in all cases

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/bendable/BendableScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/bendablebigdecimal/BendableBigDecimalScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/bendablelong/BendableLongScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardmediumsoft/HardMediumSoftScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardmediumsoftlong/HardMediumSoftLongScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardsoft/HardSoftScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/hardsoftlong/HardSoftLongScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/simple/SimpleScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/simplebigdecimal/SimpleBigDecimalScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/buildin/simplelong/SimpleLongScoreHolderImpl.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/holder/AbstractScoreHolder.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/rules/AbstractRuleAssembler.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/score/buildin/AbstractScoreHolderTest.java
I know that we spoke about this before, and I'm doing something else than what we agreed on. I believe I have a good reason for why this is the best option, as it is also the only option.
Consider the following:
- The exception about wrong match weight type comes from `AbstractScoreHolder` - I can not be speaking about `penalizeBigDecimal()` there, as the user may see this in DRL as well.
- One level up, in `impactScore()` in Constraint Streams, I do not know which numeric types `AbstractScoreHolder` will or will not accept, and so I can not add that check there.
Therefore, I only have three options:
1. Modify `AbstractScoreHolder` to return the type of match weight it requires. I'd argue this is needless complexity.
1. In CS, catch the exception from `AbstractScoreHolder` and throw a new …
=> PLANNER-2212 Minimize the occurrence of match weight exceptions

build/optaplanner-build-parent/pom.xml, build/optaplanner-ide-config/pom.xml, pom.xml
Plugin dependencies, in this case the maven-formatter-plugin's dependency on optaplanner-ide-config, are resolved using pluginRepository.
<details>
<summary>
</summary>
</details>
=> Add a pluginRepository to resolve the optaplanner-ide-config artifact

build/optaplanner-build-parent/pom.xml
The version wasn't specified, which threatens build stability.
<details>
<summary>
</summary>
</details>
=> Set sonar-maven-plugin version to 3.7.0.1746

Jenkinsfile, pom.xml
The `sonar.projectKey` is overridden in the optaplanner-parent, which mistakenly propagates to optawebs. As a result, this project clashes with the optaweb-vehicle-routing on SonarCloud.
<details>
<summary>
</summary>
</details>
=> Move sonar.projectKey from pom.xml to the CI

Jenkinsfile.promote, build/release/upload_distribution.sh, optaplanner-distribution/src/main/assembly/assembly-optaplanner.xml
First step: add a script that will be called from the release pipeline. The script uploads the docs and distribution.
TODO:
- provide documentation for the release process
https://issues.redhat.com/browse/PLANNER-2217
https://github.com/kiegroup/optaplanner-website/pull/295
<details>
<summary>
</summary>
</details>
=> PLANNER-2217 Automate release of OptaPlanner documentation and distribution

Jenkinsfile.deploy
Add nightly configuration for quickstarts
- added build stage and repo for quickstarts
Tested here
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/adupliak/job/optaplanner-quickstarts-deploy/
- The quickstarts version is SNAPSHOT 1.0
- See "Test results" for surefire outcome
- Dont use  MAVEN_DEPENDENCIES_REPOSITORY 
<details>
<summary>
</summary>
* for an <b>upstream build</b> …
=> Planner 2130 nightly

Jenkinsfile, Jenkinsfile.deploy, Jenkinsfile.promote
The "fullProfile" was not properly activated in all relevant maven builds.
<details>
<summary>
</summary>
</details>
=> Activate fullProfile in all relevant builds

Jenkinsfile, Jenkinsfile.deploy, Jenkinsfile.promote
The "fullProfile" was not properly activated in all relevant maven builds.
A cherry-pick of #1026 
<details>
<summary>
</summary>
</details>
=> [8.0.x] Activate fullProfile in all relevant builds

optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/cloudbalancing/app/CloudBalancingDaemonTest.java
Tests identified as flaky:
DefaultPartitionedSearchPhaseTest.shutdownMainThreadAbruptly
CloudBalancingDaemonTest.daemon
These tests have failed sporadically in the past and need to be reviewed.
=> PLANNER-2250 Disable flaky tests

build/optaplanner-build-parent/pom.xml
Currently it's wrongly detected as 8 during Sonar Scanner execution:
[INFO] Configured Java source version (sonar.java.source): 8
According to documentation [1], sonar.java.source affects rule
activation. Using a lower version (8) might cause some Java 11 rules no
being activated.
[1] https://docs.sonarqube.org/latest/analysis/languages/java/
<details>
<summary>
</summary>
* for an <b>upstream …
=> Set sonar.java.source to 11

Jenkinsfile.deploy
Already tested with a custom job: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/rsynek/job/releasePipeline/job/optaplanner-deploy
https://issues.redhat.com/browse/PLANNER-2242
<details>
<summary>
</summary>
</details>
=> PLANNER-2242 Add optawebs to the nightly pipeline

.github/workflows/pull_request.yml, optaplanner-quickstarts/spring-boot-school-timetabling/src/test/java/com/example/schooltimetabling/solver/TimeTableControllerTest.java
The test is said to have failed a couple of times. As I cannot reproduce it locally, I am disabling the test not to harm the FDB.
FYI @mareknovotny 
https://issues.redhat.com/browse/PLANNER-2254
<details>
<summary>
</summary>
</details>
=> Disable test that failed in the 7.x FDB

optaplanner-distribution/src/main/assembly/assembly-optaplanner.xml
A cherry-pick of https://github.com/kiegroup/optaplanner/pull/986.
https://issues.redhat.com/browse/PLANNER-2085
<details>
<summary>
</summary>
</details>
=> [7.44.x] PLANNER-2085 Missing directory in optaplanner distribution zipped archives

build/optaplanner-build-parent/pom.xml
<details>
<summary>
</summary>
</details>
=> Keep jaxb-runtime version in sync with the API

build/optaplanner-build-parent/pom.xml
Quarkus 1.10.0.Final has just become publicly available. A PR to optaplanner-quickstarts and cherry-picking to 8.0.x branches will follow.
https://github.com/kiegroup/optaplanner/pull/1038
https://github.com/kiegroup/optaplanner-quickstarts/pull/24
https://github.com/kiegroup/optaplanner/pull/1039
https://github.com/kiegroup/optaplanner-quickstarts/pull/25
<details>
<summary>
</summary>
* for an …
=> Upgrade Quarkus to 1.10.0.Final

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1062
related PRs:
* https://github.com/kiegroup/kie-soup/pull/164
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/483
* https://github.com/kiegroup/drools/pull/3216
* https://github.com/kiegroup/optaplanner/pull/1013
* https://github.com/kiegroup/jbpm/pull/1795
* https://github.com/kiegroup/kie-jpmml-integration/pull/47
* https://github.com/kiegroup/droolsjbpm-integration/pull/2309
* https://github.com/kiegroup/openshift-drools-hacep/pull/104
* https://github.com/kiegroup/droolsjbpm-tools/pull/123
* https://github.com/kiegroup/lienzo-core/pull/139
* https://github.com/kiegroup/lienzo-tests/pull/112
* https://github.com/kiegroup/appformer/pull/1074
* https://github.com/kiegroup/kie-uberfire-extensions/pull/110
* …
=> BXMSPROD-1062 kiegroup/github-action-build-chain updated

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/ProblemBenchmarksConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/SolverBenchmarkConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/report/BenchmarkReportConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/DefaultPlannerBenchmarkFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ProblemBenchmarksFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/SolverBenchmarkFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/aggregator/BenchmarkAggregator.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/aggregator/swingui/BenchmarkAggregatorFrame.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/loader/ProblemProvider.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/report/BenchmarkReportFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/ProblemBenchmarkResult.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfigTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/report/BenchmarkReportConfigTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/DefaultPlannerBenchmarkFactoryTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/SolverBenchmarkFactoryTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/report/BenchmarkReportFactoryTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/result/PlannerBenchmarkResultTest.java
As we moved `build()` methods from the `SolverConfig` and its underlying classes to Factories in the past, this PR does the same thing for similar methods in the `PlannerBenchmarkConfig`.
TODO: open a PR to update the upgrade recipe.
<details>
<summary>
</summary>
</details>
=> Move deprecated build methods to Factories

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/ProblemBenchmarksConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/SolverBenchmarkConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/report/BenchmarkReportConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/DefaultPlannerBenchmarkFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ProblemBenchmarksFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/SolverBenchmarkFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/aggregator/BenchmarkAggregator.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/aggregator/swingui/BenchmarkAggregatorFrame.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/loader/ProblemProvider.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/report/BenchmarkReportFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/result/ProblemBenchmarkResult.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfigTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/report/BenchmarkReportConfigTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/DefaultPlannerBenchmarkFactoryTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/SolverBenchmarkFactoryTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/report/BenchmarkReportFactoryTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/result/PlannerBenchmarkResultTest.java
A cherry-pick of https://github.com/kiegroup/optaplanner/pull/1040.
<details>
<summary>
</summary>
</details>
=> [8.0.x] Move deprecated build methods to Factories

Jenkinsfile.promote
In previous test run for #1045, I noticed "Pipeline CPS Method Mismatches" error in the console output. The fix should be back-ported to 8.0.x.
<details>
<summary>
</summary>
</details>
=> Fix pipeline CPS Method Mismatches

Jenkinsfile.deploy, Jenkinsfile.promote
Tested with https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/rsynek/job/releasePipeline/job/kogito-release/28/.
https://issues.redhat.com/browse/PLANNER-2216
https://github.com/kiegroup/kogito-pipelines/pull/90
<details>
<summary>
</summary>
</details>
=> PLANNER-2216 Add Optawebs to the release pipeline

.github/workflows/os_java_ci.yml, build/optaplanner-build-parent/pom.xml
Plugin execution | Defined in | Decision | Comment
-- | -- | -- | --
org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:javadoc {execution: javadoc-javadoc} | optaplanner-build-parent | full profile | On 7.x it's full profile only too
org.revapi:revapi-maven-plugin:0.9.5:report {execution: report} | optaplanner-build-parent | remove | The report does not matter, only the "check" goal
org.revapi:revapi-maven-plugin:0.9.5:check {execution: check} | optaplanner-build-parent | full profile |  
net.revelc.code.formatter:formatter-maven-plugin:2.11.0:format {execution: default} | optaplanner-build-parent | keep |  
org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (all executions) | jboss-parent | keep |  
org.codehaus.mojo:jaxb2-maven-plugin:2.5.0:schemagen {execution: …
=> PLANNER-2227 A non-full build should not generate javadocs and run the enforcer rules twice

optaplanner-examples/pom.xml
Got the following error when trying to run exec:java:
```
[Message [id=1, level=ERROR, path=src/main/java/org/optaplanner/examples/tsp/solver/PAD/LambdaExtractorADBC3A59CE62AEB61CBB82A8956AE4DE.java, line=4, column=43
text=package org.optaplanner.examples.tsp.domain does not exist], Message [id=2, level=ERROR, path=src/main/java/org/optaplanner/examples/tsp/solver/PAD/LambdaExtractorADBC3A59CE62AEB61CBB82A8956AE4DE.java, line=5, column=52
text=package org.optaplanner.examples.tsp.domain.location does not exist], Message [id=3, level=ERROR, path=src/main/java/org/optaplanner/examples/tsp/solver/PAD/LambdaExtractorADBC3A59CE62AEB61CBB82A8956AE4DE.java, line=7, column=43
text=package org.optaplanner.examples.tsp.domain does not exist], Message [id=4, level=ERROR, …
```
=> Add optaplanner-examples jar to the classpath of exec:java

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/ConstraintGraph.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/ConstraintSubTree.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/rules/UniGroupBy2Map0CollectMutator.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/AdvancedGroupByConstraintStreamTest.java
Fixes a typo resulting from an unfortunate lack of type safety in this part of the code.
=> PLANNER-2270 Make CS-D GroupBy2Map0Collect return bi rule

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/bi/BavetAbstractBiConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/bi/BavetGroupBridgeBiConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/bi/BavetGroupBridgeBiNode.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/bi/BavetGroupBridgeBiTuple.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/bi/BiConstraintStreamTest.java
<details>
<summary>
This PR adds a Bavet implementation of the groupBy that has been available for Uni-Streams for the Bi-Streams. The implementation is almost the same as the existing one for Uni, with the necessary adjustments made to make it compatible with Bi streams. The test that exists for the Drools implementation passes, and testing the new implementation in use in a project was successful as well.
The existing test mentioned above is `optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/bi/BiConstraintStreamTest.java->groupBy_1Mapping1Collector_count()`
</summary>
<b>Jenkins retest this</b>
</details>
=> Added Bavet implementation of Bi-groupBy (1 Mapping, 1 Collector)

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/ConstraintCollectorsTest.java
(cherry picked from commit 200964881ef5adb4a2f84f001757a21a12775528)
=> [8.0.x] PLANNER-2271 ConstraintCollectors.toMap(): Only remove a key when no value remains (#1061)

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java, optaplanner-core/src/test/java/org/optaplanner/core/api/score/stream/ConstraintCollectorsTest.java
(cherry picked from commit 200964881ef5adb4a2f84f001757a21a12775528)
=> [7.x] RHPAM-3334 ConstraintCollectors.toMap(): Only remove a key when no value remains

optaplanner-docs/src/main/asciidoc/QuickStart/PlainJava/CloudBalancingScoreConfiguration/CloudBalancingScoreConfiguration-section.adoc
Replace `HardSoftScore.valueOf` with `HardSoftScore.of` at documentation (QuickStart / PlainJava / CloudBalancingScoreConfiguration) because HardSoftScore.valueOf has been removed from OptaPlanner 8.0.0.Final.
Seems as lost changes in #947.
Source code at repo: https://github.com/kiegroup/optaplanner/blob/e5a7d6b5a1e68bdb25a891cd70459486a29ed7c2/optaplanner-examples/src/main/java/org/optaplanner/examples/cloudbalancing/optional/score/CloudBalancingEasyScoreCalculator.java#L70
=> Docs: Replace HardSoftScore.valueOf with HardSoftScore.of

optaplanner-core/src/main/java/org/optaplanner/core/impl/io/jaxb/GenericJaxbIO.java
https://issues.redhat.com/browse/PLANNER-2297
<details>
<summary>
</summary>
</details>
=> PLANNER-2297 Fail fast if XML schema does not exist

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/GizmoMemberAccessorEntityEnhancer.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/OptaPlannerBeanProvider.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/nativeimage/Substitute_MemberAccessorFactory.java
Cherry pick of https://github.com/kiegroup/optaplanner/pull/1115
* Fix native image generation for Gizmo
* Use @ApplicationScoped for Gizmo MemberAccessors
<details>
<summary>
</summary>
</details>
=> 8.2.x - Fix native image generation for Gizmo

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/DotNames.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorInvalidTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/invalid/inverserelation/constraints/TestdataInvalidQuarkusConstraintProvider.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/invalid/inverserelation/domain/TestdataInvalidInverseRelationEntity.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/invalid/inverserelation/domain/TestdataInvalidInverseRelationSolution.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/invalid/inverserelation/domain/TestdataInvalidInverseRelationValue.java
<details>
<summary>
</summary>
</details>
=> Fail early in Quarkus build if shadow variable not on planning entity

optaplanner-quickstarts/quarkus-school-timetabling/src/test/java/org/acme/schooltimetabling/rest/TimeTableResourceTest.java, optaplanner-quickstarts/spring-boot-school-timetabling/src/test/java/com/example/schooltimetabling/solver/TimeTableControllerTest.java
Backporting the https://github.com/kiegroup/optaplanner-quickstarts/pull/48, as the flaky test was disabled on the 7.x branch.
https://issues.redhat.com/browse/PLANNER-2254
<details>
<summary>
</summary>
</details>
=> PLANNER-2254 Fix flaky TimeTableControllerTest

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/bi/BavetFilterBiTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/bi/BavetGroupBiTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/bi/BavetGroupBridgeBiTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/bi/BavetJoinBiTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/bi/BavetJoinBridgeBiTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/bi/BavetScoringBiTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/common/BavetAbstractTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/tri/BavetFilterTriTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/tri/BavetJoinTriTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/tri/BavetScoringTriTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/uni/BavetFilterUniTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/uni/BavetFromUniTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/uni/BavetGroupBridgeUniTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/uni/BavetJoinBridgeUniTuple.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/uni/BavetScoringUniTuple.java
Some tuples will only ever have 1 child.
Some tuples will mostly only have 1 expected child.
Some tuples will never have children.
The sizing of the collections should reflect that, which leads to a performance improvement of ~10 % on average.
=> PLANNER-2315 Properly size Bavet child tuple lists

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/DotNames.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorInvalidTest.java
Replaces #1127 
<details>
<summary>
</summary>
</details>
=> Fix quickstarts build: fix fail fast that triggered unneeded for a @PlanningId use of school-timetabling's Room class

optaplanner-core/src/main/java/org/optaplanner/core/impl/io/jaxb/GenericJaxbIO.java, optaplanner-core/src/test/java/org/optaplanner/core/config/solver/SolverConfigTest.java
Slightly improves the validation message as requested in https://kie.zulipchat.com/#narrow/stream/232679-optaplanner/topic/XML.20mistake.20.3D.3E.20no.20line.20number.
However, it's not possible to get the line number, as this information is available only if we use SAX as the underlying parser. In our case, we use DOM, so we get the Node where the validation error occurs.
<details>
<summary>
</summary>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product …
=> Add location to JAXB validation error

Jenkinsfile.promote
In 42e8e3374512ef45eb089aaf9caf667d20f8bfd1 I had removed the comment and during implementation of the pipeline forget to remove dependency on the comment in the matching pattern of sed.
Fixed that
<details>
<summary>
</summary>
</details>
=> Remove comment in sed path matching

build/optaplanner-build-parent/pom.xml
Motivation: run the dependency analysis in the Kogito-runtimes check, where the `fullProfile` would be an overkill.
<details>
<summary>
</summary>
</details>
=> Run dependency analysis by default

.github/workflows/jenkins-tests-PR.yml, .gitignore, .jenkins/dsl/jobs.groovy, .jenkins/dsl/test.sh, Jenkinsfile, Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-3034
https://issues.redhat.com/browse/BXMSPROD-1094
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/92
- https://github.com/kiegroup/kogito-runtimes/pull/940
- https://github.com/kiegroup/kogito-apps/pull/581
- https://github.com/kiegroup/optaplanner/pull/1085
- https://github.com/kiegroup/kogito-examples/pull/500
- https://github.com/kiegroup/kogito-images/pull/307
- https://github.com/kiegroup/kogito-cloud-operator/pull/710
**Setup DSL scripts for the different Kogito jobs.**
- Allow easy setup of jobs for own purpose (with different configuration for example)
- Moved parameters as environment
- That allows exact same configuration information for all the jobs, without having to 
- For testing, taking the getting the seed job and …
=> [KOGITO-3034][BXMSPROD-1094] Setup Jenkins DSL scripts

Jenkinsfile, Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-4501
Use shared library to clean the node used by Jenkins.
This will also allow to improve the shared lib later on without having to modify all pipelines.
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1090
- https://github.com/kiegroup/optaplanner/pull/1172
- https://github.com/kiegroup/kogito-apps/pull/665
- https://github.com/kiegroup/kogito-examples/pull/584
=> KOGITO-4501 Clean node in pipelines

build/optaplanner-build-parent/pom.xml
Upgrading the `8.3.x` branch to the same version of Quarkus that Kogito is going to use.
The Quarkus 1.11.4.Final should be available tomorrow.
https://github.com/kiegroup/optaplanner-quickstarts/pull/64
<details>
<summary>
</summary>
</details>
=> Upgrade Quarkus to 1.11.4.Final

optaplanner-docs/src/main/asciidoc/Integration/Integration-chapter.adoc, optaplanner-docs/src/main/asciidoc/Integration/config-properties.adoc
The attribute reference approach doesn't have quotes substitution
enabled by default. It can be enabled but then it breaks cross
references.
<details>
<summary>
</summary>
</details>
=> Use include directive to reuse configuration properties content

optaplanner-docs/src/main/asciidoc/Integration/config-properties.adoc
<details>
<summary>
</summary>
</details>
=> Default domain access type is different betwen Quarkus and Spring Boot

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/DotNames.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/verifier/OptaPlannerConstraintVerifierBavetStreamImplTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/verifier/OptaPlannerConstraintVerifierDroolsStreamImplTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/verifier/OptaPlannerConstraintVerifierTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/resources/org/optaplanner/quarkus/bavetSolverConfig.xml, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultConstraintVerifier.java
No new dependencies added to optaplanner-quarkus; it detects if ConstraintVerifier is on the classpath, and if so, create a Gizmo supplier of the ConstraintVerifier.
https://issues.redhat.com/browse/PLANNER-2345
<details>
<summary>
</summary>
</details>
=> PLANNER-2345: Allow @Inject ConstraintVerifier in tests in Quarkus

optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/pom.xml, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/resources/org/optaplanner/spring/boot/autoconfigure/bavetSolverConfig.xml
https://issues.redhat.com/browse/PLANNER-2345
<details>
<summary>
</summary>
</details>
=> PLANNER-2345: Add auto-configure for ConstraintVerifier in Spring Boot

Jenkinsfile.promote
Move reset task to the separate step to identify the problem faster
The problem is:
If reset falls - it fails the promote job. If promote job fails then snapshots doesn't gets updated. In this case Kogito pipeline could not proceed.
Currently in plan by  @radtriste - separate update of snapshots from the promote part and override tag if it is already exist so we can rerun promote job.
Jenkins build with passed stage for Reset Quickstarts stable branch
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/custom%2Fadupliak%2Fquickstarts-release-pipeline%2Foptaplanner-promote/detail/optaplanner-promote/49/pipeline/189
<details>
<summary>
</summary>
* for a <b>pull request build</b> please add comment: <b>Jenkins …
=>  Split Quickstarts stage to PR and tag and reset

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorXMLDefaultTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorXMLNoneTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorXMLPropertyTest.java
<details>
<summary>
</summary>
</details>
=> Set default to REFLECTION in Quarkus as a stop-gap for PLANNER-2367

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorXMLDefaultTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorXMLNoneTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorXMLPropertyTest.java
(cherry picked from commit f035eaf04efee22418a8da349b696118fd11dab1)
<details>
<summary>
</summary>
</details>
=> [8.4.x] Set default to REFLECTION in Quarkus as a stop-gap for PLANNER-2367

Jenkinsfile.promote
Part of:
https://issues.redhat.com/browse/KOGITO-4635
<details>
<summary>
</summary>
</details>
=> KOGITO-4635 Use tagLocalAndRemoteRepository to override tag if already exist

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java
Improve the warning when the `optaplanner-quarkus` extension detects there is no `PlanningSolution` nor `PlanningEntity` in the project.
<details>
<summary>
</summary>
</details>
=> Add a suggestion about missing Jandex index

Jenkinsfile.promote
In case if permissions will be changed on github.com side or if github CLI will change this job should proceed with other steps to continue release and mark the build as unstable.
In that case the step should be applied manually
Mapped .required_pull_request_reviews 
https://issues.redhat.com/browse/KOGITO-4705
<details>
<summary>
</summary>
* for an <b>upstream build</b> please add comment: …
=> Wrap gh api admin calls and mapping in try catch

.jenkins/dsl/jobs.groovy, Jenkinsfile.turtle
https://issues.redhat.com/browse/PLANNER-2363
<details>
<summary>
</summary>
</details>
=> PLANNER-2363 Re-enable the turtle tests job

.github/workflows/os_java_ci.yml, build/optaplanner-build-parent/pom.xml, optaplanner-core/src/build/revapi-config.json, optaplanner-examples/data/nurserostering/unsolved/long01.xml, optaplanner-examples/data/nurserostering/unsolved/long02.xml, optaplanner-examples/data/nurserostering/unsolved/long_hint01.xml, optaplanner-examples/data/nurserostering/unsolved/long_hint02.xml, optaplanner-examples/data/nurserostering/unsolved/medium01.xml, optaplanner-examples/data/nurserostering/unsolved/medium02.xml, optaplanner-examples/data/nurserostering/unsolved/medium03.xml, optaplanner-examples/data/nurserostering/unsolved/medium04.xml, optaplanner-examples/data/nurserostering/unsolved/medium05.xml, optaplanner-examples/data/nurserostering/unsolved/medium_hint01.xml, optaplanner-examples/data/nurserostering/unsolved/medium_hint02.xml, optaplanner-examples/data/nurserostering/unsolved/medium_hint03.xml, optaplanner-examples/data/nurserostering/unsolved/medium_late01.xml, optaplanner-examples/data/nurserostering/unsolved/medium_late01_initialized.xml, optaplanner-examples/data/nurserostering/unsolved/medium_late02.xml, optaplanner-examples/data/nurserostering/unsolved/medium_late03.xml, optaplanner-examples/data/nurserostering/unsolved/medium_late04.xml, optaplanner-examples/data/nurserostering/unsolved/medium_late05.xml, optaplanner-examples/data/nurserostering/unsolved/sprint01.xml, optaplanner-examples/data/nurserostering/unsolved/sprint02.xml, optaplanner-examples/data/nurserostering/unsolved/sprint_hint01.xml, optaplanner-examples/data/nurserostering/unsolved/sprint_hint02.xml, optaplanner-examples/src/main/java/org/optaplanner/examples/nurserostering/persistence/NurseRosteringImporter.java, optaplanner-persistence/optaplanner-persistence-xstream/src/test/java/org/optaplanner/persistence/xstream/impl/domain/solution/XStreamSolutionFileIOTest.java
XStream has issues with JDK 16. I solve them by using different collection types, which XStream can serialize just fine.
This, unfortunately, required us to regenerate some unsolved example XMLs.
=> PLANNER-2374 Add support for JDK 16

Jenkinsfile
https://issues.redhat.com/browse/KOGITO-4770
So we don't need to have the latest GraalVM on node for native building. It uses the quarkus provided docker image.
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1173
- https://github.com/kiegroup/optaplanner/pull/1232
- https://github.com/kiegroup/kogito-apps/pull/727
- https://github.com/kiegroup/kogito-examples/pull/626
=> KOGITO-4770 Corrected native PR check

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/DroolsConstraintSessionFactory.java
We can not use this because PFCs actually use different threads.
=> PLANNER-2372 Revert non-thread-safe session

build/optaplanner-build-parent/pom.xml
There is a policy in the optaplanner-parent pom to only allow SNAPSHOT versions for plugins from JBoss which has caused some issues for QE (Anna) where the maven-compiler-plugin version is taken from jboss-parent and its a jboss suffixed version only available in the JBoss repo.
<details>
<summary>
</summary>
* for a …
=> Add maven-compiler-plugin version 3.8.1

Jenkinsfile.deploy
Following on https://github.com/kiegroup/optaweb-vehicle-routing/pull/461
<details>
<summary>
</summary>
</details>
=> Fix Cypress tests disabled in nightly

optaplanner-benchmark/pom.xml, optaplanner-core/pom.xml
https://issues.redhat.com/browse/DROOLS-6257
As we plan to refactor drools-mvel, we are moving test util classes/resources from drools-mvel to drools-legacy-test-util (already copied).
In optaplanner 7.x branch, optaplanner-core and optaplanner-benchmark have drools-mvel test-jar dependency so changing it to drools-legacy-test-util test-jar dependency.
<details>
<summary>
</summary>
* for an …
=> [7.x] [DROOLS-6257] Move drools-mvel test-jar dependency

optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/lookup/LookUpStrategyImmutableTest.java
Modified all occurrences of (deprecated) calls to constructors of wrapper classes into their static valueOf() equivalent
=> Java 16 deprecations

.github/workflows/sonarcloud.yml
The new CI is supposed to run a complete analysis of the `master` branch after a PR has been merged. It's a complement to the existing analysis of open PRs, which focuses only on the changes brought by the respective PR.
TODO: delete the legacy Jenkins job after this PR is merged.
<details>
<summary>
</summary>
* for a …
=> Run SonarCloud analysis after merging a PR

.github/workflows/sonarcloud.yml
Adding the missing GITHUB_TOKEN the CI complains about.
<details>
<summary>
</summary>
</details>
=> Add GITHUB_TOKEN to sonarcloud CI

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/config/OptaPlannerBuildTimeConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/config/SolverBuildTimeConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorOverridePropertiesAtRuntimeTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/OptaPlannerBeanProvider.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/OptaPlannerRecorder.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/config/OptaPlannerRuntimeConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/config/SolverManagerRuntimeConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/config/SolverRuntimeConfig.java
https://issues.redhat.com/browse/PLANNER-2387
<details>
<summary>
</summary>
</details>
=> PLANNER-2387: Make moveThreadCount and parallelSolverCount runtime configs

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/score/descriptor/ScoreDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/score/descriptor/ScoreDescriptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/solutionproperties/invalid/TestdataMissingScorePropertySolution.java
<details>
<summary>
</summary>
</details>
=> PLANNER-2425: Move @PlanningScore annotation processing to ScoreDescriptor

.jenkins/dsl/jobs.groovy
Due to migration to CSB, with Jenkins version, direct triggers are deprecated and need to be replaced
depends on https://github.com/kiegroup/kogito-pipelines/pull/172
=> Update turtle test trigger as dsl deprecated

optaplanner-core/src/test/java/org/optaplanner/core/config/solver/SolverConfigTest.java, optaplanner-core/src/test/resources/org/optaplanner/core/config/solver/testSolverConfigWithoutNamespace.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorGeneratedGizmoSupplierTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorXMLDefaultTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorXMLNoneTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorXMLPropertyTest.java
GIZMO has been fixed for a while. The only commit content missing in master from the GIZMO_MEMBER PR is the content that adds GIZMO_MEMBER (And the GIZMO_MEMBER PR works on all of optaplanner-examples => GIZMO on master would work on all of optaplanner-examples if they were written in Quarkus). This PR change the default back to GIZMO.
Side note: `optaplanner-core/src/test/resources/org/optaplanner/core/config/solver/testSolverConfigWithoutNamespace.xml` appears to be an invalid SolverConfig; it references `TestdataAnnotatedExtendedEntity`, which references a valueRangeProvider not in the solution class `TestdataSolution`. For GIZMO, this fails the build (as it need to build a solution descriptor). In REFLECTION, the build won't fail since the SolverDescriptor is not created until a …
=> Change default domain access type to GIZMO in Quarkus

.github/workflows/quarkus-snapshot.yaml
The Ecosystem CI has been failing recently as it cannot check out the ecosystem-ci repository.
<details>
<summary>
</summary>
</details>
=> Rename master to main in Ecosystem CI

optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/lookup/LookUpStrategyImmutableTest.java
Adapted the code to avoid the compiler's complaint that there are "unnecessary boxing" occurrences.
Regression tests were run and all were successful.
=> Removed "unnecessary boxing" commit warnings

.github/pull_request_template.md, .jenkins/dsl/jobs.groovy, Jenkinsfile
https://issues.redhat.com/browse/KOGITO-5070
This will allow to run Jenkins pr check, if `multijob-pr` label is set, in separate jobs.
Also, each project check is responsible to set correct Jenkinsfile and this avoids to rewrite the commands to run in each repo for the downstream projects.
Also, this add `kogito-apps` and `kogito-examples` checks to Optaplanner (but can be removed if needed).
_For now, this does not replace the current global PR check. It is only activated with the `multijob-pr` label._
Depends on https://github.com/kiegroup/kogito-pipelines/pull/148
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1284
- https://github.com/kiegroup/optaplanner/pull/1304
- https://github.com/kiegroup/kogito-apps/pull/805
- …
=> KOGITO-5070 Setup multijob pipeline

optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/pom.xml, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/BenchmarkProperties.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerBenchmarkAutoConfiguration.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerProperties.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java
https://issues.redhat.com/browse/PLANNER-2341
<details>
<summary>
</summary>
</details>
=> PLANNER-2341: Add @Autowire support for PlannerBenchmarkFactory in Spring Boot

Jenkinsfile.promote
Cherry-pick of https://github.com/kiegroup/optaplanner/pull/1367
<details>
<summary>
</summary>
* for a <b>specific Quarkus …
=> [8.7.x] Update target location of XSD files in website

Jenkinsfile.promote
The target location of XSD files has changed from `xsd/...` to `content/xsd/...`, please see the current directory structure:
https://github.com/kiegroup/optaplanner-website/tree/master/content/xsd
<details>
<summary>
</summary>
* for an <b>upstream build</b> please add comment: …
=> Update target location of XSD files in website

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/src/build/revapi-config.json, optaplanner-persistence/optaplanner-persistence-jpa/src/build/revapi-config.json, optaplanner-test/src/build/revapi-config.json
**JIRA**: [BAQE-1904](https://issues.redhat.com/browse/BAQE-1904)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1665
=> BAQE-1904 - Change revapi to check against 7.52.0.Final

optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/test/java/org/optaplanner/benchmark/quarkus/OptaPlannerBenchmarkProcessorMissingSpentLimitTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorGeneratedGizmoSupplierTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorOverridePropertiesAtRuntimeTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/constraints/OptaPlannerProcessorConstraintProviderAndDrlTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/constraints/OptaPlannerProcessorConstraintsDrlDefaultTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/constraints/OptaPlannerProcessorConstraintsDrlTest.java
This PR is a duplicate of https://github.com/kiegroup/optaplanner/pull/1350, rebased on master. It appears the Jenkins job on it got stuck, and the actions at the time were using an outdated master.
https://issues.redhat.com/browse/PLANNER-2441
<details>
<summary>
</summary>
* for …
=> PLANNER-2441: Make tests compatiable with Quarkus 2.x

build/optaplanner-build-parent/pom.xml
- [`quarkus-hibernate-orm`](https://mvnrepository.com/artifact/io.quarkus/quarkus-hibernate-orm/2.0.0.CR3) uses Hibernate 5.5.0.Final.
- `optaplanner-persistence-jpa` uses Hibernate as well (`hibernate-core`).
- Since `optaplanner-build-parent` does not import `quarkus-bom` it has to manage Hibernate version by itself.
When Quarkus was upgraded to 2.0.0.CR3 (#1379), Hibernate version was not updated and so, `optaplanner-build-parent` effectively downgraded `hibernate-core` to 5.4.29, which is incompatible with other Hibernate 5.5.0 components used by `quarkus-orm-hibernate`. This isn't a problem in the `optaplanner` repository as none of its modules uses `quarkus-orm-hibernate` but it starts to be a problem in OptaWeb repos.
Fixes up #1379.
<details>
<summary>
How to retest this PR or …
=> Align Hibernate version with Quarkus 2.0.0.CR3

build/optaplanner-build-parent/pom.xml, optaplanner-core/pom.xml, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolver.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/util/TestMeterRegistry.java
Metrics added:
- Score Calculation Speed (calculations/seconds)
- Score Calculation Count (calculations)
https://issues.redhat.com/browse/PLANNER-2400
<details>
<summary>
</summary>
* for a <b>Native check</b> please add comment: <b>Jenkins run …
=> PLANNER-2400: Add Micrometer Metric for Solver

build/optaplanner-build-parent/pom.xml
Should fix broken build after upgrading to Quarkus 2.0.0.Final.
<details>
<summary>
</summary>
* for a <b>specific Quarkus LTS …
=> [8.8.x] Align hibernate with quarkus

optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/planningid/TestdataStringPlanningIdEntity.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/planningid/TestdataStringPlanningIdSolution.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultSingleConstraintVerification.java, optaplanner-test/src/test/java/org/optaplanner/test/api/score/stream/SingleConstraintAssertionTest.java, optaplanner-test/src/test/java/org/optaplanner/test/api/score/stream/testdata/TestdataConstraintProvider.java
https://issues.redhat.com/browse/PLANNER-2385
<details>
<summary>
</summary> …
=> (8.5.x Backport): PLANNER-2385: Do not presume Long @PlanningId in ConstraintVerifier (#1246))

build/optaplanner-build-parent/pom.xml
Should fix broken build after upgrading to Quarkus 2.0.0.Final.
<details>
<summary>
</summary>
* for a <b>specific Quarkus LTS …
=> Align Hibernate version with Quarkus

build/optaplanner-build-parent/pom.xml
Surefire was not properly finding and running tests in the `optaplanner-test` module. 
Version 2.22 doesn't play with JUnit 5 too well.
=> Bump Surefire to 3.0.0-M5 to fix some tests not launching

.ci/jenkins/Jenkinsfile, .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-5540
As Sonarqube is only Community Edition, it does not support branch analysis ...
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1453
- https://github.com/kiegroup/optaplanner/pull/1442
- https://github.com/kiegroup/kogito-apps/pull/948
<details>
<summary>
</summary>
* for a <b>full production downstream build</b> please …
=> KOGITO-5540 Disable Sonarcloud on release branches

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/SolverConfigBuildStep.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/resources/dev-templates/constraints.html, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/resources/dev-templates/embedded.html, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/resources/dev-templates/model.html, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/resources/dev-templates/solverConfig.html, optaplanner-quarkus-integration/optaplanner-quarkus/devui-integration-test/.gitignore, optaplanner-quarkus-integration/optaplanner-quarkus/devui-integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/devui-integration-test/src/main/java/org/optaplanner/quarkus/it/devui/OptaPlannerTestResource.java, optaplanner-quarkus-integration/optaplanner-quarkus/devui-integration-test/src/main/java/org/optaplanner/quarkus/it/devui/domain/StringLengthVariableListener.java, optaplanner-quarkus-integration/optaplanner-quarkus/devui-integration-test/src/main/java/org/optaplanner/quarkus/it/devui/domain/TestdataStringLengthShadowEntity.java, optaplanner-quarkus-integration/optaplanner-quarkus/devui-integration-test/src/main/java/org/optaplanner/quarkus/it/devui/domain/TestdataStringLengthShadowSolution.java, optaplanner-quarkus-integration/optaplanner-quarkus/devui-integration-test/src/main/java/org/optaplanner/quarkus/it/devui/solver/TestdataStringLengthConstraintProvider.java, optaplanner-quarkus-integration/optaplanner-quarkus/devui-integration-test/src/main/resources/application.properties, optaplanner-quarkus-integration/optaplanner-quarkus/devui-integration-test/src/test/java/org/optaplanner/quarkus/it/devui/OptaPlannerDevUITest.java, optaplanner-quarkus-integration/optaplanner-quarkus/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/devui/OptaPlannerDevUIProperties.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/devui/OptaPlannerDevUIPropertiesSupplier.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/devui/OptaPlannerModelProperties.java
Don't know how to test this, since in order to verify it works, we need to visit the Dev UI pages.
https://issues.redhat.com/browse/PLANNER-2411
<details>
<summary>
</summary>
* for a <b>Quarkus LTS …
=> PLANNER-2411: Add solver config, constraint list, and model to Quarkus Dev UI

.ci/jenkins/dsl/jobs.groovy
Small issue coming from https://github.com/kiegroup/optaplanner/pull/1372
<details>
<summary>
</summary>
* for a <b>specific …
=> Fix DSL generation

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/move/AbstractMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainReversingSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/chained/SubChain.java
Improves TSP GREECE 9882 score calculation count 80 times, assuming only subchain swap moves are enabled.
=> PLANNER-2476 Improve performance of SubChainSwapMove

optaplanner-examples/src/main/resources/org/optaplanner/examples/pas/solver/patientAdmissionScheduleConstraints.drl
Fixing a few typos I came across.
<details>
<summary>
</summary>
* for a <b>specific Quarkus LTS check</b> please add comment: …
=> Fix typos in PAS constraints

optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/variable/inverserelation/CollectionInverseVariableListenerTest.java
Cleaning up unnatural assertion API usages that are a result of semi-automated migration from JUnit to AssertJ.
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> please add comment: …
=> Use isEmpty() instead of contains() with no arguments

optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/stream/BavetConstraintStreamScoreDirectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/stream/DroolsConstraintStreamScoreDirectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/bavet/BavetConstraintFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/common/AbstractConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/DroolsConstraintFactory.java
Eliminates a few compiler warnings.
<details>
<summary>
</summary>
* for a <b>specific Quarkus LTS check</b> please add …
=> Fix compiler warnings

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/dsl/jobs.groovy, .gitignore
https://issues.redhat.com/browse/KOGITO-5597
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1482
- https://github.com/kiegroup/optaplanner/pull/1472
- https://github.com/kiegroup/kogito-apps/pull/965
- https://github.com/kiegroup/kogito-examples/pull/818
<details>
<summary>
</summary>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins …
=> KOGITO-5597 Separate native checks

build/optaplanner-build-parent/pom.xml, optaplanner-examples/pom.xml, optaplanner-persistence/pom.xml, optaplanner-spring-integration/pom.xml
Decentralizes the `dependencyManagement` as a temporary solution until https://github.com/quarkusio/quarkus-platform-bom-generator/issues/64 is implemented. By removing redundant dependencies versions, we can use the `optaplanner-build-parent` as an input to the Quarkus Platform BOM generation tool.
FYI: @aloubyansky 
https://issues.redhat.com/browse/PLANNER-2439
https://github.com/quarkusio/quarkus-platform/pull/279 depends on this PR.
<details>
<summary>
</summary>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run …
=> PLANNER-2439 decentralize dependencyManagement

optaplanner-quarkus-integration/optaplanner-quarkus/integration-test/src/main/java/org/optaplanner/quarkus/it/OptaPlannerTestResource.java
See https://sonarcloud.io/project/issues?id=org.optaplanner%3Aoptaplanner&resolved=false&severities=MAJOR&types=BUG
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> please add comment: …
=> Re-interrupt a thread (SonarCloud suggestion)

optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/TestdataEntity.java
Same as #1295. I just missed `TestdataEntity` in the original PR.
<details>
<summary>
</summary>
* for a <b>specific Quarkus …
=> Simplify TestdataEntity build methods

.ci/jenkins/Jenkinsfile.native, .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-5635
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/229
- https://github.com/kiegroup/kogito-runtimes/pull/1491
- https://github.com/kiegroup/optaplanner/pull/1483
- https://github.com/kiegroup/kogito-apps/pull/973
- https://github.com/kiegroup/kogito-examples/pull/827
<details>
<summary>
</summary>
* for a <b>full …
=> KOGITO-5635 Added native LTS check

build/optaplanner-build-parent/pom.xml
Despite that jacoco does not generate coverage report part for swing ui anymore, the sonar needs to be specified with exclusion property as it done here https://github.com/search?q=org%3Akiegroup+sonar.coverage.exclusions&type=code
<details>
<summary>
</summary>
* for an …
=> Add specific property for sonar exclusion

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/accessor/gizmo/GizmoMemberDescriptor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/GizmoMemberAccessorEntityEnhancer.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/gizmo/PrivateNoArgsConstructorEntity.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/gizmo/PrivateNoArgsConstructorSolution.java
https://issues.redhat.com/browse/PLANNER-2504
<details>
<summary>
</summary> …
=> PLANNER-2504: GIZMO - Make final fields non-final in Quarkus; fail fast in plain java

pom.xml
<details>
<summary>
</summary> …
=> Make JBoss Java Release profiles not active by default

optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/entity/pillar/DefaultPillarSelectorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarChangeMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarSwapMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/KOptMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainChangeMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainReversingChangeMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainReversingSwapMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainSwapMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/value/chained/DefaultSubChainSelectorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/util/CodeAssertable.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/util/PlannerAssert.java
- Remove unused methods.
- Reduce code duplication.
- More specific assertions for better messages.
- And most importantly...
A SwapMoveSelector that produces `"a<->b", "a<->c", "a<->d", "b<->c", "b<->d", "c<->d"` moves.
And an intentionally modified assertion with three modifications:
```java
assertAllCodesOfMoveSelector(moveSelector, "a<->b", "a<->b", "a<->d", "c<->b", "b<->d", "c<->d", "xxxxx");
//                                                   ^mod1             ^mod2                      ^mod3
```
```
expected: "a<->b"
but was: "a<->c"
```
Only describes the first error in the sequence. It's not clear whether the problem is with the first element or with the second one.
```
Expecting actual:
["a<->b", "a<->c", "a<->d", "b<->c", "b<->d", "c<->d"]
to contain exactly (and in same …
```
=> Simplify PlannerAssert

optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/ExperimentalConstraintCollectors.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/impl/ConsecutiveSetTree.java
Issues addressed:
* `[WARNING] /home/jlocker/src/github.com/kiegroup/optaplanner/optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/ExperimentalConstraintCollectors.java:299: warning - invalid usage of tag {@link Duration#between)`
* `[WARNING] /home/jlocker/src/github.com/kiegroup/optaplanner/optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/impl/ConsecutiveSetTree.java:34: warning - invalid usage of tag <`
* `[WARNING] /home/jlocker/src/github.com/kiegroup/optaplanner/optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/impl/ConsecutiveSetTree.java:34: warning - invalid usage of tag <`
* `[WARNING] /home/jlocker/src/github.com/kiegroup/optaplanner/optaplanner-examples/src/main/java/org/optaplanner/examp …
=> Fix Javadoc issues

.github/workflows/pull_request.yml
build chain changes:
-  https://github.com/kiegroup/github-action-build-chain/pull/169
upgrades:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1729
* https://github.com/kiegroup/kie-soup/pull/225
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/545
* https://github.com/kiegroup/drools/pull/3791
* https://github.com/kiegroup/optaplanner/pull/1515
* https://github.com/kiegroup/lienzo-core/pull/151
* https://github.com/kiegroup/lienzo-tests/pull/125
* https://github.com/kiegroup/appformer/pull/1189
* https://github.com/kiegroup/kie-uberfire-extensions/pull/123
* https://github.com/kiegroup/jbpm/pull/2000
* https://github.com/kiegroup/kie-jpmml-integration/pull/63
* https://github.com/kiegroup/droolsjbpm-integration/pull/2573
* …
=> upgrade build-chain @v2.6.8

optaplanner-core/src/main/java/org/optaplanner/core/impl/AbstractFromConfigFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/placer/PooledEntityPlacerFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/placer/QueuedEntityPlacerFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/entity/descriptor/EntityDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/mutation/MutationCounter.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerSupport.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMoveSelectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/scope/PartitionChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/AbstractPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/stream/DroolsConstraintStreamScoreDirectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/common/AbstractRuleContext.java
Improves performance of checking for disabled constraints by caching the constraint ID.
Improves performance of checking if an entity is initialized, by using a `List` instead of `Map.values()`.
The latter change has the potential to speed up many other parts of OptaPlanner as well, although that was not benchmarked.
=> Improve performance of Constraint Streams on select use cases

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java
https://issues.redhat.com/browse/PLANNER-2512
<details>
<summary>
</summary> …
=> PLANNER-2512 Make SolverFactory unremovable

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/resources/dev-templates/constraints.html, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/resources/dev-templates/model.html, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/resources/dev-templates/solverConfig.html, optaplanner-quarkus-integration/optaplanner-quarkus/devui-integration-test/src/test/java/org/optaplanner/quarkus/it/devui/OptaPlannerDevUITest.java
Should close https://github.com/quarkusio/quarkus/issues/11563
Made the selectors looks for particular id instead of path, so changes to the dev ui base template should not affect this test.
<details>
<summary>
</summary>
* for a <b>full production downstream build</b> please add comment: …
=> Make Dev UI tests use id selectors

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorEmptyAppWithInjectionTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/bean/DefaultOptaPlannerBeanProvider.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/bean/UnavailableOptaPlannerBeanProvider.java
If OptaPlanner beans cannot be injected, the exception should clearly suggest what the cause is.
https://issues.redhat.com/browse/PLANNER-2498
<details>
<summary>
</summary>
* for an …
=> PLANNER-2498 Improve the error message for Quarkus

optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
<details>
<summary>
</summary>
* for …
=> Fix inconsistency in the docs; made examples clearer

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle, build/optaplanner-build-parent/pom.xml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
After the following backport the Kogito runtimes Maven version has been enforced to be `3.6.3`. https://github.com/kiegroup/kogito-runtimes/pull/1568
The Jenkinsfile in this repository branch needs to use at least this version to execute downstream builds for Kogito runtimes.
=> [8.11.x] Upgrade Jenkinsfile Maven version to 3.6.3

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessorTest.java
https://issues.redhat.com/browse/PLANNER-2485
<details>
<summary>
</summary> …
=> PLANNER-2485: Fail fast if KieBase properties are set in Quarkus

optaplanner-docs/src/main/asciidoc/QuickStart/HelloWorld/HelloWorldQuickStart-chapter.adoc, optaplanner-docs/src/main/asciidoc/QuickStart/SchoolTimetabling/SchoolTimetablingModel-section.adoc
<details>
<summary>
</summary>
* for …
=> BXMSDOC-8130: PLANNER: Edit hello world java in community docs

optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/api/Break.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/api/Sequence.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/impl/ConsecutiveSetTree.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/impl/SequenceImpl.java, optaplanner-examples/src/main/java/org/optaplanner/examples/nurserostering/score/NurseRosteringConstraintProvider.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nurserostering/score/NurseRosteringConstraintProviderTest.java
<details>
<summary>
</summary> …
=> Combine the first/last/consecutiveFreeDays constraints to improve performance

optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolver.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java, optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
Wait for backport JIRA before Merging
Motivation: optaplanner.solver.solve-length does not follow Micrometer naming
Convention (https://micrometer.io/docs/concepts#_naming_meters) which causes it
to look arkward in some monitoring systems (ex: optaplannerSolverSolve-length).
Cherry-picked from 95d0864c8d
https://issues.redhat.com/browse/RHDM-1818
<details>
<summary>
</summary>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run …
=> [8.11.x - under triage] Change optaplanner.solver.solve-length to optaplanner.solver.solve.duration

optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolver.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java, optaplanner-docs/src/main/asciidoc/PlannerConfiguration/PlannerConfiguration-chapter.adoc
Motivation: optaplanner.solver.solve-length does not follow Micrometer naming
Convention (https://micrometer.io/docs/concepts#_naming_meters) which causes it
to look arkward in some monitoring systems (ex: optaplannerSolverSolve-length).
<details>
<summary>
</summary>
* for a <b>full production …
=> Change optaplanner.solver.solve-length to optaplanner.solver.solve.duration

.github/workflows/sonarcloud.yml
This should fix the branch analysis triggered by either pushing directly or by merging a PR.
https://issues.redhat.com/browse/PLANNER-2527
<details>
<summary>
</summary>
* for an <b>upstream …
=> PLANNER-2527 Pass sonar.login property to maven build

optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/impl/ConsecutiveIntervalInfoImpl.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/impl/IntervalTree.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/experimental/impl/IntervalTreeTest.java
https://issues.redhat.com/browse/PLANNER-2528
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> …
=> PLANNER-2528: Update break when interval cluster start changes

optaplanner-core/src/main/java/org/optaplanner/core/config/solver/monitoring/SolverMetric.java, optaplanner-docs/src/modules/ROOT/pages/planner-configuration/planner-configuration.adoc
I noticed I missed all the new metrics when fixing `solver-length`, so I fixed those to follow micrometer naming conventions. 
<details>
<summary>
</summary>
* for an <b>upstream build</b> …
=> Add docs for mointoring; use Micrometer naming convenctions for metrics

.github/workflows/sonarcloud.yml
Removes SonarCloud warning about missing history. Potentially, it could also fix the PR analysis, see https://community.sonarsource.com/t/pr-scans-not-detecting-code-changes-that-branch-scans-do/47714.
<details>
<summary>
</summary>
* for a <b>full production downstream build</b> please add …
=> Fetch entire git history for Sonar

.github/pull_request_template.md, .github/workflows/full-downstream.yml
<details>
<summary>
</summary>
* for …
=> execute full downstream build by label

optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolver.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/util/TestMeterRegistry.java
This is an alternative fix for the Micrometer bug; the other is #1586 .
This changes the order the event listeners are added, resulted
in the meters being the last meters (thus a test needed to be rewritten).
<details>
<summary>
</summary>
* for a <b>full downstream build</b> 
* for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
* for <b>github actions</b> job: add the label `run_fdb`
* for a <b>compile downstream build</b> please add …
=> Move meters inside the solve calls to address registration and unregistration issues

optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolver.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java
<details>
<summary>
</summary>
* for a <b>full downstream build</b> 
* for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
* for <b>github actions</b> job: add the label `run_fdb`
* for an <b>upstream build</b> please add comment: <b>Jenkins run …
=> Remove tags for solve.duration and error.count

optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/runtime/graal/OptaPlannerFeature.java
Closes https://github.com/quarkusio/quarkus/issues/20491
A simple way to fix the issue is to make `KieModuleMarshaller` run-time initialized.
@Sanne mentioned [here](https://github.com/quarkusio/quarkus/issues/11563#issuecomment-926479069):
> I had a quick look at java.awt.datatransfer.DataFlavor.. I could be wrong but it looks like a perfect candidate to be optimized via build time initialization.
Not sure exactly what he means, but at a first glance, everything awt related/dependant should really be runtime initialized to start with. Then, you can always optimize further things as needed/required.
=> Make KieModuleMarshaller run time initialized

build/optaplanner-build-parent/pom.xml
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1634
- https://github.com/kiegroup/optaplanner/pull/1593
- https://github.com/kiegroup/kogito-apps/pull/1044
- https://github.com/kiegroup/kogito-examples/pull/909
- https://github.com/kiegroup/optaplanner-quickstarts/pull/190
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/570
<details>
<summary>
</summary>
* for a <b>full downstream build</b> 
* for <b>jenkins</b> job: please …
=> Bump Quarkus 2.3.0.Final

.ci/jenkins/dsl/jobs.groovy, .github/workflows/full-downstream.yml
https://issues.redhat.com/browse/KOGITO-5280
https://github.com/kiegroup/kogito-apps/pull/1033
https://github.com/kiegroup/kogito-examples/pull/897
https://github.com/kiegroup/kogito-pipelines/pull/271
https://github.com/kiegroup/kogito-apps/pull/1049
https://github.com/kiegroup/optaplanner-quickstarts/pull/191
<details>
<summary>
</summary>
* for a <b>full downstream build</b> 
* for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
* for …
=> KOGITO-5280 Setup downstream profiles for kogito checks

optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseTest.java
Disable flaky test. It fails only on jdk8
https://issues.redhat.com/browse/PLANNER-2563
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this change you can easily reproduce the same …
=> Disable abrupt shutdown test for Partitioned search

optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/runtime/graal/OptaPlannerFeature.java
A workaround for the failing Quarkus Ecosystem CI:
https://github.com/quarkusio/quarkus/issues/11563
This comes from Drools and is tracked under:
https://issues.redhat.com/browse/DROOLS-6643
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, …
=> DROOLS-6643 add a workaround for runtime init

optaplanner-docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc
These were my mistake.
Antora exposed these broken links on the website, and the sixtrix SEO report complained about it.
Interestingly enough, these mistakes were around for a while.
=> Fix broken links in quarkus docs

.ci/jenkins/Jenkinsfile.deploy
user group in notification
<details>
<summary>
</summary> …
=> Deploy pipeline: Added optaplanner-team

.ci/jenkins/Jenkinsfile.promote
Make sure the changes made to `antora-playbook.yml` during a release are committed to the `optaplanner-website` repository.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this …
=> Git add antora-playbook.yml during a release

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessorTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/drl-integration-test/pom.xml
A temporary workaround for https://issues.redhat.com/browse/KOGITO-6236.
In short, we fail fast if the dependency that the Kogito extension needs is not there with a clear message and a suggestion. This way, we don't drag the dependency on the classpath unnecessarily when the user is not using the DRL.
https://issues.redhat.com/browse/PLANNER-2572
<details>
<summary>
</summary>
We do "simple" maven builds, they are just basically maven commands, but just because we have multiple repositories related between them and one change could affect several of those projects by multiple pull requests, we use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest …
=> KOGITO-6236 Add a workaround for DRL support in Quarkus

optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessorTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/drl-integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/resources/application.properties
https://issues.redhat.com/browse/KOGITO-6236
- https://github.com/kiegroup/kogito-runtimes/pull/1703
- https://github.com/kiegroup/optaplanner/pull/1662
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull …
=> [KOGITO-6236] Introducing Capability definition for OptaPlanner extensions

optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/resources/META-INF/quarkus-extension.yaml
=> OptaPlanner on code.quarkus.io should just be called "OptaPlanner"

optaplanner-core/src/test/java/org/optaplanner/core/config/heuristic/selector/common/nearby/NearbySelectionConfigTest.java
<details>
<summary>
</summary> …
=> Replace depreacted isEqualToComparingFieldByField()

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/common/accessor/gizmo/GizmoMemberAccessorImplementor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/gizmo/GizmoSolutionClonerImplementor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/common/AbstractConstraintStream.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolver.java, optaplanner-core/src/test/java/org/optaplanner/core/config/util/ConfigUtilsTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/common/accessor/gizmo/GizmoMemberAccessorFactoryTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/solution/cloner/GizmoSolutionClonerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/comparable/TestdataCodeComparator.java, optaplanner-examples/src/main/java/org/optaplanner/examples/batchscheduling/optional/score/BatchSchedulingEasyScoreCalculator.java, optaplanner-examples/src/main/java/org/optaplanner/examples/batchscheduling/score/BatchSchedulingIncrementalScoreCalculator.java, optaplanner-examples/src/main/java/org/optaplanner/examples/batchscheduling/swingui/BatchSchedulingPanel.java, optaplanner-examples/src/main/java/org/optaplanner/examples/meetingscheduling/persistence/MeetingSchedulingXlsxFileIO.java
<details>
<summary>
</summary> …
=> Add missing `@Override` annotations

optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java
Removes needless reference indirection and with it, some extra calls.
=> Optimize ConstraintCollectors.count*()

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessorTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/drl-integration-test/pom.xml
Re-applying a workaround as the ecosystem CI got again broken.
Should be properly fixed by https://github.com/kiegroup/kogito-runtimes/pull/1731, which brings the `quarkus-resteasy-jackson` dependency transitively.
https://issues.redhat.com/browse/PLANNER-2572
<details>
<summary>
</summary>
[build-chain …
=> PLANNER-2572 fix Quarkus ecosystem CI

optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/HeuristicConfigPolicy.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/DefaultLocalSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/localsearch/DefaultLocalSearchPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/AbstractPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/AbstractPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/NoChangePhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/NoChangePhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/custom/DefaultCustomPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/custom/DefaultCustomPhaseFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverFactory.java, optaplanner-core/src/test/java/org/optaplanner/core/config/constructionheuristic/placer/PooledEntityPlacerFactoryTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhaseTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/QueuedEntityPlacerFactoryTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/QueuedValuePlacerFactoryTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhaseTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/AbstractSelectorFactoryTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/DefaultLocalSearchPhaseTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/phase/NoChangePhaseTest.java
The goal of this PR is to make it easier to understand and reason about the Phases code. Declaring fields `final` and eliminating the corresponding setters reduces the effort of searching for the places from where the field can be changed. With `final`, the intention is clear: the value is determined during object construction and then never changes.
The Builder pattern is taken from Item 2, Effective Java. In this case it solves the problem with optional assertion flags. The Builder has a named setter method for each optional argument, so instead of something like
```java
XyPhase phase;
if (environment.isLevelA() && environment.isLevelB()) {
phase = new XyPhase(requiredArgs, true, true);
}
if (environment.isLevelA()) {
phase = new XyPhase(requiredArgs, true);
}
// etc.
```
and multiple …
=> Reduce mutability in Phase related code

optaplanner-docs/src/modules/ROOT/pages/integration/config-properties.adoc, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/main/java/org/optaplanner/benchmark/quarkus/deployment/OptaPlannerBenchmarkBuildTimeConfig.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerBenchmarkAutoConfiguration.java
Note: Spring reuses the Solver Termination Config while Quarkus does not, meaning Spring technically has `best-score-limit` and `unimproved-time-spent` properties for benchmarker whereas Quarkus does not.
https://issues.redhat.com/browse/PLANNER-2583
<details>
<summary>
</summary>
[build-chain …
=> PLANNER-2583: Add docs for Benchmarker properties

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/BXMSPROD-1546
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/328
- https://github.com/kiegroup/optaplanner/pull/1686
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted …
=> BXMSPROD-1546 updated native PR checks

optaplanner-docs/pom.xml, optaplanner-docs/src/antora-template.yml, optaplanner-docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc, optaplanner-docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc, optaplanner-docs/src/modules/ROOT/pages/quickstart/spring-boot/spring-boot-quickstart.adoc
[PLANNER-2570](https://issues.redhat.com/browse/PLANNER-2570)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this change you can easily reproduce the same build by executing it …
=> Replace {project-version} to {optaplanner-version} in docs

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/AbstractSolver.java
It's unnecessary to count all movable entities when it's enough to find any and quit early.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this change you can easily reproduce the …
=> Simplify SolutionDescriptor.getMovableEntityCount()

optaplanner-benchmark/src/main/resources/org/optaplanner/benchmark/impl/report/twitterbootstrap/js/jquery.js
See the https://issues.redhat.com/browse/BAPL-1990 initiative
Replaces #1697.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this change you can easily reproduce the same build by …
=> Remove non-inclusive word master from twitterbootstap

optaplanner-benchmark/src/main/resources/org/optaplanner/benchmark/impl/report/twitterbootstrap/js/jquery.js, optaplanner-core/src/main/java/org/optaplanner/core/api/domain/variable/InverseRelationShadowVariable.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/InverseRelationShadowVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/mutation/TestGenRemoveRandomBlockMutator.java, optaplanner-docs/src/main/asciidoc/BenchmarkingAndTweaking/BenchmarkingAndTweaking-chapter.adoc, optaplanner-docs/src/main/asciidoc/ShadowVariable/ShadowVariable-chapter.adoc
Cherry-pick https://github.com/kiegroup/optaplanner/pull/1708
Update optaplanner-core/src/main/java/org/optaplanner/core/impl/score/director/drools/testgen/mutation/TestGenRemoveRandomBlockMutator.java
PR feedback
Remove non-inclusive words from 7.x
Replaced non-inclusive words according to changes in main
<details>
<summary>
</summary> …
=> Remove non-inclusive words from 7.12

.ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle
https://issues.redhat.com/browse/KOGITO-6241
<details>
<summary>
</summary> …
=> KOGITO-6241 Add optaplanner-team mention to notif

build/optaplanner-build-parent/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/drl-integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/pom.xml
`optaplanner-quarkus` now depends on pure Drools, except for where DRL is necessary, at which point `kogito-rules` is brought in. We can not go any further until we have a Drools Quarkus extension. Mario is aware, but at the moment there are no plans to do that.
Downstream PRs: 
- https://github.com/kiegroup/optaplanner-quickstarts/pull/240
- https://github.com/kiegroup/kogito-apps/pull/1155
=> PLANNER-2598 Simplify how we depend on Kogito

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle
https://issues.redhat.com/browse/KOGITO-6398
<details>
<summary>
</summary> …
=> KOGITO-6398 Remove Maven Download outputs

build/optaplanner-build-parent/pom.xml
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1717
PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1799
- https://github.com/kiegroup/optaplanner/pull/1730
- https://github.com/kiegroup/kogito-apps/pull/1167
- https://github.com/kiegroup/kogito-examples/pull/1043
- https://github.com/kiegroup/optaplanner-quickstarts/pull/246
=> [1.15.x] Bump Quarkus version to 2.6.0.final

optaplanner-docs/src/modules/ROOT/pages/_attributes.adoc, optaplanner-docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc, optaplanner-docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc, optaplanner-docs/src/modules/ROOT/pages/quickstart/spring-boot/spring-boot-quickstart.adoc
Moving quickstarts-related attributes to a single .adoc file.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with this change you can easily reproduce the same build by executing it …
=> Single source asciidoc attributes

optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverJob.java
There was a race condition where a SolverJob can cancel
the completition of a different SolverJob with the same
problem id. In particular, the old code did not have any locking
on SolverStatus changes, which allowed the following sequence
of operations on three threads (T1, T2, T3):
Preconditions:
solverManager.getSolverStatus(1L) == SOLVING_SCHEDULED
```
---
T1: solverManager.terminateEarly(1L)
T2: solverManager.terminateEarly(1L)
T3: solverJob = solverManager.solve(1L, problem)
---
T1: solvingTerminated() (in SolverJob.terminateEarly, under SOLVING_SCHEDULED)
T2: solvingTerminated() (in SolverJob.terminateEarly, under SOLVING_SCHEDULED)
T3: solverJob = solverManager.solve(1L, problem) (No Action Yet)
---
T1: Thread Ended (the old SolverJob was removed from SolverManager)
T2: …
```
=> PLANNER-2611: Fix rare race condition in DefaultSolverJob terminateEarly

optaplanner-docs/src/modules/ROOT/pages/constraint-streams/constraint-streams.adoc, optaplanner-docs/src/modules/ROOT/pages/optimization-algorithms/optimization-algorithms.adoc, optaplanner-docs/src/modules/ROOT/pages/use-cases-and-examples/cloud-balancing/cloud-balancing.adoc
[skip ci]
<details>
<summary>
</summary> …
=> Adjust column widths to avoid line breaks in tables

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListAssignMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListUnassignMove.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListAssignMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListChangeMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListSwapMoveTest.java
https://issues.redhat.com/browse/PLANNER-2593
<details>
<summary>
</summary> …
=> PLANNER-2593 Implement list moves' getPlanningEntities(), getPlanningValues(), equals(), hashCode() and rebase()

.ci/jenkins/Jenkinsfile.post-release.temp, .ci/jenkins/Jenkinsfile.promote
https://issues.redhat.com/browse/PLANNER-2603
Another PR will come with some testing and corrections done on `Jenkins.post-release.temp` file. For now, no other job will be created. I created this file to keep an idea of what should be done and just save the work as the file might not be that different from the temp one.
<details>
<summary>
</summary>
We do "simple" maven builds, they are just basically maven commands, but just because we have multiple repositories related between them and one change could affect several of those projects by multiple pull requests, we use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each …
=> PLANNER-2603 Extract quickstarts from promote

.ci/jenkins/Jenkinsfile.deploy
Due to https://github.com/kiegroup/optaplanner-quickstarts/commit/3119ded80cd37068b3cad85789e6a0e4a47a0b25
Tested locally with:
```bash
git clone https://github.com/kiegroup/optaplanner
git checkout upstream/8.15.x
mvn -fae -N -e versions:set -Dfull -DnewVersion=8.15.0.Final -DallowSnapshots=false -DgenerateBackupPoms=false
mvn -fae -e versions:set-property -Dfull -Dproperty=version.org.kie.kogito -DnewVersion=1.15.0.Final -DallowSnapshots=true -DgenerateBackupPoms=false
mvn -fae -U -pl org.optaplanner:optaplanner-build-parent,org.optaplanner:optaplanner-bom -am clean install -Dfull -DskipTests=true
git clone https://github.com/kiegroup/optaplanner-quickstarts
git checkout upstream/8.15.x
mvn -fae -N -e versions:update-parent -Dfull '-DparentVersion=[8.15.0.Final]' -DallowSnapshots=false …
```
=> [8.15.x] Corrected Jenkinsfile.deploy

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/index/ExternalizedIndexVariableSupply.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/index/IndexVariableDemand.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/index/IndexVariableListener.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedSingletonListInverseVariableSupply.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/SingletonListInverseVariableListener.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/variable/index/ExternalizedIndexVariableSupplyTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/localsearch/DefaultLocalSearchPhaseTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/list/externalized/TestdataListEntityExternalized.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/list/externalized/TestdataListSolutionExternalized.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/list/externalized/TestdataListValueExternalized.java
I paid a lot of attention to keep high level of code style consistency between external supplies and listeners and with the existing code. Some changes on the older code (before this PR) reflect that.
Can we afford to require unique entity events in the inverse/index listeners/supplies? It has a performance cost but is necessary to make the strict checks work.
Alternatively, I can eliminate<sup>:monkey:</sup> the redundant before/after variable changed notifications in list moves if they happen on the same entity. I could then lift the requirement for unique events but that would open the door to breaking the checks for users that implement custom moves on a list variable.
Finally, I can do :monkey: even if the requirement for unique events is kept. Simply because it makes sense.
- Pros: …
=> PLANNER-2508 Add externalized index supply

optaplanner-core/src/main/java/org/optaplanner/core/api/domain/variable/IndexShadowVariable.java, optaplanner-core/src/main/java/org/optaplanner/core/api/domain/variable/PlanningListVariable.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/entity/descriptor/EntityDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/descriptor/GenuineVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/descriptor/ListVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/index/IndexShadowVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/index/IndexVariableSupply.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/InverseRelationShadowVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/SingletonInverseVariableSupply.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/SwapMoveSelectorFactory.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListSwapMove.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/list/TestdataListEntity.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/list/externalized/TestdataListEntityExternalized.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/list/mixed/TestdataMixedVariablesEntity.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/list/valuerange/TestdataListEntityWithArrayValueRange.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning_listvariable/domain/Employee.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/DotNames.java
Changing the annotation name to `@PlanningListVariable` as agreed in the **List variable naming, part 2** discussion on October 14.
=> Rename the annotation to `@PlanningListVariable`

optaplanner-core/src/main/java/org/optaplanner/core/config/solver/termination/TerminationConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/test/java/org/optaplanner/benchmark/quarkus/OptaPlannerBenchmarkProcessorMissingSpentLimitPerBenchmarkTest.java, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/test/java/org/optaplanner/benchmark/quarkus/OptaPlannerBenchmarkProcessorSpentLimitConfiguredPerBenchmarkTest.java, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/test/resources/solverBenchmarkConfigSpentLimitPerBenchmark.xml, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/test/resources/solverBenchmarkConfigSpentLimitPerBenchmarkNoTermination.xml, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/runtime/src/main/java/org/optaplanner/benchmark/quarkus/OptaPlannerBenchmarkRecorder.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerBenchmarkAutoConfiguration.java
https://issues.redhat.com/browse/PLANNER-2625
<details>
<summary>
</summary> …
=> PLANNER-2625: Do not fail fast if termination is configured per benchmark

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/entity/descriptor/EntityDescriptor.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptorTest.java
https://issues.redhat.com/browse/PLANNER-2303
The formula is `v^2 / e + v`. It's designed so that it gives the same problem scale with the list variable as with the chained basic variable. I can't see any good meaning behind it. Nevertheless, I can live with this being merged provided that we replace the "problem size" metric with solution space as proposed in https://issues.redhat.com/browse/PLANNER-2623.
=> PLANNER-2303 Fix problem scale for list variable

optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/AbstractPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/scope/SolverScope.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java
Before, the step score map was configured to a phase-lifetime object.
This is fine when there is only one phase, but there is typically
many phases. Thus, when a new phase is started, the step score map
that the gauge tracks is never updated (since it linked to the old,
forgotten, phase). The step score map now lives in SolverScope, so
it should work across the entire solver run.
Maybe should be backported.
https://issues.redhat.com/browse/PLANNER-2627
<details>
<summary>
</summary> …
=> PLANNER-2627: Move step score map to solve-lifetime scope

.ci/jenkins/Jenkinsfile.post-release, .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-6527
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1776
<details>
<summary>
</summary> …
=> [8.16.x] [KOGITO-6527] Updated post release job (#1776)

optaplanner-core/src/main/java/org/optaplanner/core/api/domain/variable/PlanningListVariable.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/descriptor/GenuineVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/descriptor/ListVariableDescriptor.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/domain/Employee.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/domain/Task.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/domain/solver/TaskDifficultyComparator.java, optaplanner-examples/src/test/java/org/optaplanner/examples/taskassigning/domain/solver/TaskDifficultyComparatorTest.java
According to **raw meeting notes vrp simplification merging phase 1** (Dec 10)
Goal:
- merge vrp simplification to main
- **do not expose non-future-proof API's yet**
- do expose the ones we're sure off
@PlanningListVariable: naming (will be) OK
- behaviour: OK to write in stone.
- **strengthComparatorClass: leave OUT**
Add "// TODO" for task assignment
- strengthWeightFactoryClass: leave OUT
=> Remove strengthComparatorClass because the API is not yet stable

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/move/AbstractMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainReversingSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainSwapMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/chained/SubChain.java
Backports the fix of https://issues.redhat.com/browse/PLANNER-2476 to the `7.x` branch.
https://issues.redhat.com/browse/PLANNER-2476
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action tool but a CLI one, so in case you posted multiple pull requests related with …
=> [7.x] PLANNER-2476 Improve performance of SubChainSwapMove

optaplanner-core/src/main/java/org/optaplanner/core/config/solver/termination/TerminationConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/main/java/org/optaplanner/benchmark/quarkus/deployment/OptaPlannerBenchmarkProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/test/java/org/optaplanner/benchmark/quarkus/OptaPlannerBenchmarkProcessorInheritedSolverBenchmarkTest.java, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/test/java/org/optaplanner/benchmark/quarkus/OptaPlannerBenchmarkProcessorOnlySolverConfigTest.java, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/test/java/org/optaplanner/benchmark/quarkus/OptaPlannerBenchmarkProcessorPhasesTest.java, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/test/java/org/optaplanner/benchmark/quarkus/testdata/normal/domain/TestdataQuarkusOtherEntity.java, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/test/resources/solverBenchmarkConfigWithInheritedSolverBenchmark.xml, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/test/resources/solverBenchmarkConfigWithPhases.xml, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/src/test/resources/solverConfigWithPhases.xml, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/runtime/src/main/java/org/optaplanner/benchmark/quarkus/OptaPlannerBenchmarkRecorder.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerBenchmarkAutoConfiguration.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/config/OptaPlannerProperties.java
https://issues.redhat.com/browse/PLANNER-2624
https://issues.redhat.com/browse/PLANNER-2626
<details>
<summary>
</summary> …
=> PLANNER-2626, PLANNER-2624: Fix inherited benchmark config

optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/ConsumerSupport.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverJob.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverManager.java, optaplanner-core/src/test/java/org/optaplanner/core/api/solver/SolverManagerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/ConsumerSupportTest.java
https://issues.redhat.com/browse/PLANNER-2628
<details>
<summary>
</summary> …
=> PLANNER-2628 Implement consumer threads

optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/AbstractPhase.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/phase/scope/AbstractPhaseScope.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/BestScoreFeasibleTerminationTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/BestScoreTerminationTest.java
Simple internal API cleanup.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests …
=> AbstractPhaseScope doesn't need ScoreDefinition

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/variable/custom/CustomShadowVariableDescriptor.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListSwapMove.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/domain/Task.java, optaplanner-examples/src/main/java/org/optaplanner/examples/taskassigning/domain/solver/StartTimeUpdatingVariableListener.java
As agreed previously, let's fail fast if a custom shadow variable is sourced on a `@PlanningListVariable`. In the near future this will be possible but the variable listener class will have to implement `ListVariableListener`, which is a new API that we currently don't have. Will be designed in the next phase, see https://issues.redhat.com/browse/PLANNER-2582.
=> Fail fast if a custom shadow variable listener is sourced on a list variable

build/optaplanner-build-parent/pom.xml
Quarkus has removed this dependency from the quarkus-bom. This PR fixes the ecosystem CI.
<details>
<summary>
</summary> …
=> Add assertj to dependencyManagement

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.post-release, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle
https://issues.redhat.com/browse/KOGITO-5531
This is to harmonize all Jenkins CIs.
PR checks are already using the Maven 3.8.x
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/375
- https://github.com/kiegroup/drools/pull/4169
- https://github.com/kiegroup/kogito-runtimes/pull/1954
- https://github.com/kiegroup/optaplanner/pull/1814
- https://github.com/kiegroup/kogito-apps/pull/1220
- https://github.com/kiegroup/kogito-examples/pull/1105
- https://github.com/kiegroup/kogito-apps/pull/1220
- https://github.com/kiegroup/kogito-examples/pull/1105
=> [8.16.x] KOGITO-5531 Update Jenkins CI to 3.8.1

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle
https://issues.redhat.com/browse/KOGITO-5531
Required by Quarkus 2.2 branch.
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1961
- https://github.com/kiegroup/optaplanner/pull/1819
- https://github.com/kiegroup/kogito-apps/pull/1223
- https://github.com/kiegroup/kogito-examples/pull/1108
- https://github.com/kiegroup/kogito-operator/pull/1124
=> [8.11.x] KOGITO-5531 Updated to Maven 3.8.1 (#1815)

.ci/jenkins/Jenkinsfile.post-release, .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-6527
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1776
<details>
<summary>
</summary> …
=> [KOGITO-6527] Updated post release job (#1776)

build/optaplanner-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-6682
Related PRs:
- https://github.com/kiegroup/drools/pull/4174
- https://github.com/kiegroup/kogito-runtimes/pull/1962
- https://github.com/kiegroup/optaplanner/pull/1820
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/647
- https://github.com/kiegroup/optaplanner-quickstarts/pull/277
- https://github.com/kiegroup/kogito-apps/pull/1227
- https://github.com/kiegroup/kogito-examples/pull/1109
=> KOGITO-6682 Force maven version to 3.8.1+

optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/change/DefaultProblemChangeDirector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/change/ProblemChangeAdapter.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/solver/scope/SolverScope.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/change/DefaultProblemChangeDirectorTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/solver/termination/BasicPlumbingTerminationTest.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/business/SolutionBusiness.java
1. Fixes a bug in the examples.
2. Improves the internal problem change API so that a problem fact change can be applied easily without having to explicitly trigger variable listeners.
https://issues.redhat.com/browse/PLANNER-2659
Could replace https://github.com/kiegroup/optaplanner/pull/1821.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each …
=> PLANNER-2659 Improve internal ProblemChangeDirector API

optaplanner-core/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/DeepCloningUtils.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/domain/solution/cloner/AbstractSolutionClonerTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/list/externalized/TestdataListEntityExternalized.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/testdata/domain/list/externalized/TestdataListSolutionExternalized.java
This fixes a bug where planning list variables are not deep planning
cloned if their element type is not a Planning Entity or Planning Deep
Cloned.
Fields on test domain object were made public to allow the test to work on Gizmo
https://issues.redhat.com/browse/PLANNER-2661
<details>
<summary>
</summary>
[build-chain …
=> PLANNER-2661: Add check for @PlanningListVariable to isFieldDeepCloned check

.github/workflows/full-downstream.yml, .github/workflows/jenkins-tests-PR.yml, .github/workflows/jpa_integration_ci.yml, .github/workflows/pull_request.yml, .github/workflows/quarkus-snapshot.yml, .github/workflows/sonarcloud.yml
That makes no sense. I often start with a draft PR. I polish it
incrementally and make sure all checks are green. Then I mark it as
ready for review. At that point I want the review to see a ready PR that
can be merged immediatelly if no issues are found. But unexpectedly,
workflows are restarted without any change in the code. That is a waste
of time (both human and machine).
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross …
=> Do not re-run GHA workflows when PR is marked as ready for review

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote
For a release, optaplanner and drools are not similar. So if you set the optaplanner version before the drools version, it will fail when wanting to update the drools version as that one won't exist.
We need to set first the released drools version and then the optaplanner version
<details>
<summary>
</summary> …
=> [8.17.x] Corrected Jenkinsfile.deploy and Jenkinsfile.promote

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote
<details>
<summary>
</summary> …
=> Corrected Jenkinsfile.deploy and Jenkinsfile.promote

optaplanner-core/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/util/ThreadDumpExtension.java, optaplanner-examples/src/test/java/org/optaplanner/examples/cloudbalancing/app/CloudBalancingDaemonTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/util/ThreadDumpExtension.java
Show tread dump for
- DefaultPartitionedSearchPhaseTest
- CloudBalancingDaemonTest
Cherry-pick [7.59.x] PLANNER-2563 Improve partition search tests stability (#1695)
https://issues.redhat.com/browse/PLANNER-2563
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is not only a github-action …
=> PLANNER-2563 Show thread dump of a failed test

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/pillar/DefaultPillarSelector.java
The same check is already done in the loop above.
<details>
<summary>
</summary> …
=> Do not check variableDescriptor.isChained() twice

optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMove.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMoveSelector.java, optaplanner-core/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/ChainedChangeMove.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/move/CompositeMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMoveTest.java, optaplanner-core/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/ChainedChangeMoveTest.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/business/SolutionBusiness.java
VariableDescriptor always goes first.
I assume that built-in moves are an internal API and so we can afford changing the constructor signature. This would only affect users whose custom move extends `ChangeMove` or `ChainedChangeMove` or create their instances themselves like we do in `SolutionBusiness`:
https://github.com/kiegroup/optaplanner/blob/5a7dd41fc0272be847bc0ff4654fe3f7dee5fa74/optaplanner-examples/src/main/java/org/optaplanner/examples/common/business/SolutionBusiness.java#L385-L395
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those …
=> Improve ChangeMove constructor consistency with other moves

core/.gitignore, core/optaplanner-constraint-drl/pom.xml, core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/testgen/operation/TestGenKieSessionUpdate.java, core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/testgen/reproducer/TestGenCorruptedScoreReproducer.java
<details>
<summary>
</summary> …
=> Core split cleanup

build/optaplanner-javadoc/pom.xml, core/pom.xml
See commit messages for details.
<details>
<summary>
</summary> …
=> Fix optaplanner-javadoc to include optaplanner-core-impl and optaplanner-constraint-drl

.ci/jenkins/dsl/jobs.groovy
Signed-off-by: Lukáš Petrovický <lpetrovi@redhat.com>
<details>
<summary>
</summary> …
=> Don't run Optawebs in OptaPlanner native tests

optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/ProblemBenchmarksConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/statistic/ProblemStatisticType.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/ProblemBenchmarksFactory.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/SolverBenchmarkFactory.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/ProblemBenchmarksConfigTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/SolverBenchmarkFactoryTest.java
How are defaults handled? If `problemStatisticType` are provided in `problemBenchmarks` config, and `BEST_SCORE` is not included, is it added to the list, or is it presumed not included? (from https://www.optaplanner.org/docs/optaplanner/latest/benchmarking-and-tweaking/benchmarking-and-tweaking.html#enableAProblemStatistic ; to disable all statistics, `problemStatisticEnabled` must be set to false)
https://issues.redhat.com/browse/PLANNER-2665
<details>
<summary>
</summary> …
=> PLANNER-2665: Make BEST_SCORE statistic enabled by default in benchmarker

core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/AbstractLeftHandSide.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/AbstractPatternVariable.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/BiLeftHandSide.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/BiTuple.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/DetachedPatternVariable.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/DirectPatternVariable.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/IndirectPatternVariable.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/QuadLeftHandSide.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/QuadTuple.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/TriLeftHandSide.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/TriTuple.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/UniLeftHandSide.java
This is a pure refactor. `DirectPatternVariable` and `IndirectPatternVariable` were nearly carbon copies. I extracted the common logic into `AbstractPatternVariable`, significantly reducing code duplication.
=> Reuse code between CS direct and indirect variables

optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/ExperimentalConstraintCollectors.java, optaplanner-examples/src/main/java/org/optaplanner/examples/common/experimental/impl/ConsecutiveSetTree.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/experimental/ExperimentalConstraintCollectorsTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/experimental/impl/ConsecutiveSetTreeTest.java
There was a bug where the consecutive collector gets corrupted
if its index function depends on planning variable. This is due
to how score calculation works:
1. A move is performed
2. calculateScore is called
3. The undo move is performed
Since calculateScore is not called for undo, when
the entity is later removed by the next move, its index
would have change, corrupting the consecutive collector.
To fix consecutive, the index of the value is cached on add, and
the cached index is used during remove.
https://issues.redhat.com/browse/PLANNER-2667
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or …
=> PLANNER-2667: Fix consecutive collector getting corrupted on data that depends on planning variables

build/optaplanner-build-parent/pom.xml
Signed-off-by: Lukáš Petrovický <lpetrovi@redhat.com>
<details>
<summary>
</summary> …
=> [8.13.x] Switch to Drools 7

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/AbstractFromConfigFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhaseFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/placer/PooledEntityPlacerFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/placer/QueuedEntityPlacerFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverFactory.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java, optaplanner-examples/src/main/java/org/optaplanner/examples/meetingscheduling/score/MeetingSchedulingConstraintProvider.java
Before, all problems get the phase list [ConstructionHeuristic, LocalSearch] if
the phase list was not configured in the SolverConfig. This poses an issue for
problems with multiple genuine entities:
AbstractFromConfigFactory.deduceEntityDescriptor (which is used for
ConstructionHeuristic with a null entity placer config) throws an
exception if there are multiple genuine planning entities. As a result,
if you had a problem with multiple genuine planning entities, you are
forced to specify the phase list manually.
Now, all problems get the phase list
[
ConstructionHeuristic(defaultEntityPlacer(genuineEntity1)),
ConstructionHeuristic(defaultEntityPlacer(genuineEntity2)),
...
ConstructionHeuristic(defaultEntityPlacer(genuineEntityN)),
LocalSearch
]
if the phase list was not configured in the …
=> Set default phase list for problems with multiple genuine entities

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/solver/SolverJob.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverJob.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/solver/SolverManagerTest.java
https://issues.redhat.com/browse/PLANNER-2670
<details>
<summary>
</summary> …
=> PLANNER-2670 SolverJob returns best solution after terminateEarly

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/common/iterator/UpcomingSelectionListIterator.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/decorator/FilteringEntitySelector.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/entity/decorator/FilteringEntitySelectorTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testdata/util/PlannerAssert.java
Hello 👋 
I ran into difficulties benchmarking with a dataset that included pinned entities, and came to learn the cause was I couldn't run `VARIABLE_NEIGHBORHOOD_DESCENT` with pinned entities, because [FilteringEntitySelector#listIterator](https://github.com/kiegroup/optaplanner/blob/32b4fb0ad0ccc13f72ac940a9709c15db1bdd9e0/core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/decorator/FilteringEntitySelector.java#L123-L126) had not yet been implemented.
I was interested in the internals so had a stab at doing this by extending the existing [UpcomingSelectionIterator](https://github.com/kiegroup/optaplanner/blob/32b4fb0ad0ccc13f72ac940a9709c15db1bdd9e0/core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/common/iterat …
=> Enable FilteringEntitySelector to support list iterator

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/PLANNER-2669
https://github.com/kiegroup/optaplanner/pull/1871
https://github.com/kiegroup/optaplanner-quickstarts/pull/302
https://github.com/kiegroup/drools/pull/4245
https://github.com/kiegroup/kogito-pipelines/pull/399
<details>
<summary>
</summary>
[build-chain …
=> PLANNER-2669 Disable full profile for GHA

optaplanner-examples/src/main/java/org/optaplanner/examples/cloudbalancing/swingui/CloudBalancingPanel.java, optaplanner-examples/src/main/java/org/optaplanner/examples/cloudbalancing/swingui/CloudComputerPanel.java
Colors are now assigned based on process labels (and cached) by the `TangoColorFactory` instead of their order on a computer. It's now easier to track process movement during solving on small data sets.
Code-wise, using the factory eliminates `colorIndex` calculations.
Potential downside: similar or identical colors might appear next to each other with large data sets. If this is a problem, I can easily restore the original behavior but still use the factory to avoid `colorIndex` calculations.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories …
=> Make cloud balancing process colors stable

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/src/build/revapi-config.json, optaplanner-persistence/optaplanner-persistence-jpa/src/build/revapi-config.json, optaplanner-test/src/build/revapi-config.json
**JIRA:** [BAQE-2254](https://issues.redhat.com/browse/BAQE-2254)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1923
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …
=> BAQE-2254 - Change revapi to check against 7.67.0.Final

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhaseFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/descriptor/SolutionDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverFactory.java
- The domain model never changes so it's possible and more efficient to find list variable descriptors at the end of the solution descriptor build procedure and store them in a list for future reference.
- With the list of list variable descriptors available, it is now easy to use a `for` loop instead of a stream, which should be more efficient (given that there is typically zero or one list variable).
<details>
<summary>
</summary> …
=> Find list variable descriptors once and store them

optaplanner-examples/src/main/resources/org/optaplanner/examples/batchscheduling/batchSchedulingSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/cheaptime/cheapTimeSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/cloudbalancing/cloudBalancingSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/coachshuttlegathering/coachShuttleGatheringSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/conferencescheduling/conferenceSchedulingSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/curriculumcourse/curriculumCourseSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/examination/examinationSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/flightcrewscheduling/flightCrewSchedulingSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/investment/investmentSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/machinereassignment/machineReassignmentSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/meetingscheduling/meetingSchedulingSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/nqueens/nqueensSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/nurserostering/nurseRosteringSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/pas/patientAdmissionScheduleSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/projectjobscheduling/projectJobSchedulingSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/rocktour/rockTourSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/taskassigning/taskAssigningSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/tennis/tennisSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/travelingtournament/travelingTournamentSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/tsp/tspSolverConfig.xml, optaplanner-examples/src/main/resources/org/optaplanner/examples/vehiclerouting/vehicleRoutingSolverConfig.xml
This PR makes it possible to turn on full assert mode in one step. Just hit the keyboard shortcut for _Comment with Line Comment_ on the line with ``.
Before this PR, it took 3 steps because it was necessary to first move `` on a separate line to prevent it from being uncommented as well. That would make the solver config XML invalid.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use …
=> Turn FULL_ASSERT on and off in one step

optaplanner-benchmark/src/build/revapi-config.json, optaplanner-core/src/build/revapi-config.json, optaplanner-persistence/optaplanner-persistence-jpa/src/build/revapi-config.json, optaplanner-test/src/build/revapi-config.json
**JIRA**: [BAQE-2253](https://issues.redhat.com/browse/BAQE-2253)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1925
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …
=> [7.67.x] BAQE-2253 - Change revapi to check against 7.59.0.Final

core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BavetFilterBiConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BavetGroupBiConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BavetGroupBridgeBiConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BavetJoinBiConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BavetJoinBridgeBiConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BavetScoringBiConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BiScorer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BiTuple.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/GroupBiToBiNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/GroupUniToBiNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/bi/JoinBiNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/BavetAbstractConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/NodeBuildHelper.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/BavetFilterTriConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/BavetJoinTriConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/BavetScoringTriConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/JoinTriNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/TriScorer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/tri/TriTuple.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/BavetFilterUniConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/BavetForEachUniConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/BavetGroupBridgeUniConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/BavetJoinBridgeUniConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/BavetScoringUniConstraintStream.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/ForEachUniNode.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/UniScorer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/uni/UniTuple.java, core/optaplanner-constraint-streams/src/test/java/org/optaplanner/constraint/streams/bavet/common/index/EqualsAndComparisonIndexerTest.java, core/optaplanner-constraint-streams/src/test/java/org/optaplanner/constraint/streams/bavet/common/index/EqualsIndexerTest.java, core/optaplanner-constraint-streams/src/test/java/org/optaplanner/constraint/streams/bavet/common/index/NoneIndexerTest.java
Trade off alternative advancement of https://github.com/kiegroup/optaplanner/pull/1895
Negative:
- More casting
- 
Positive:
- Less arrays created, so at least least 2 less instances per tuple (lower memory consumption)
- Maybe more CPU cache friendly
- Closer to what "burn" will do.
=> PLANNER-2675  CS-B: Stores instead of maps WITH unified store

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/solver/SolverJob.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/solver/SolverManager.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/BestSolutionContainingProblemChanges.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/BestSolutionHolder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/ConsumerSupport.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverJob.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverManager.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/solver/SolverManagerTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/solver/BestSolutionHolderTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/solver/ConsumerSupportTest.java, optaplanner-docs/src/modules/ROOT/pages/repeated-planning/repeated-planning.adoc
TODO:
https://issues.redhat.com/browse/PLANNER-2672
https://github.com/kiegroup/optaplanner-website/pull/485
<details>
<summary>
</summary> …
=> PLANNER-2672 Return CompletableFuture for a problem change

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/anchor/ExternalizedAnchorVariableSupply.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/index/ExternalizedIndexVariableSupply.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedCollectionInverseVariableSupply.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedSingletonInverseVariableSupply.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/ExternalizedSingletonListInverseVariableSupply.java
Nice improvement from the closed #1876.
<details>
<summary>
</summary> …
=> Improve externalized supplies' reset

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/solver/Solver.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/solver/SolverJob.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/solver/SolverManager.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/solver/change/ProblemChange.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/solver/change/ProblemChangeDirector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/director/AbstractScoreDirector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/DefaultSolver.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/change/ProblemChangeAdapter.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/recaller/BestSolutionRecaller.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/solver/termination/BasicPlumbingTerminationTest.java
Focuses on various small improvements and enhancing Javadoc after revealing that https://issues.redhat.com/browse/PLANNER-2681 is not doable following the original plan.
https://issues.redhat.com/browse/PLANNER-2681
<details>
<summary>
</summary>
[build-chain …
=> PLANNER-2681 - Small improvements to problem changes

build/optaplanner-build-parent/pom.xml
- https://github.com/kiegroup/optaplanner/pull/1919
- https://github.com/kiegroup/optaplanner-quickstarts/pull/318
<details>
<summary>
</summary> …
=> [main] Bump Quarkus version to 2.8.0.Final

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/custom/CustomShadowVariableDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/descriptor/ShadowVariableDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/listener/support/VariableListenerSupport.java
Removing the unused `scoreDirector` parameter enables a method reference and makes the stream even more concise.
<details>
<summary>
</summary> …
=> Simplify ShadowVariableDescriptor.hasVariableListener()

build/release/upload_distribution.sh
Updates the upload server for OptaPlanner docs. Similar change as for the website: https://github.com/kiegroup/optaplanner-website/pull/487.
Tested by running the script with `--dry-run` added to `rsync`.
https://github.com/kiegroup/optaplanner-quickstarts/pull/319
<details>
<summary>
</summary>
[build-chain …
=> Change the upload server for docs

build/release/upload_distribution.sh
https://github.com/kiegroup/optaplanner/pull/1937
https://github.com/kiegroup/optaplanner-quickstarts/pull/323
<details>
<summary>
</summary> …
=> [8.20.x] Change the upload server for docs (#1923)

build/optaplanner-build-parent/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/src/test/filtered-resources/datasource.properties
Depends on https://github.com/kiegroup/drools/pull/4300.
The Quarkus ecosystem CI has failed due to a new H2 version, which changed the default behavior: a new database is no longer created when the H2 server starts.
https://github.com/quarkusio/quarkus/issues/11563
H2 introduced a new argument `-ifNotExists` that allows the creation of a new database as before.
https://github.com/kiegroup/drools/pull/4300
<details>
<summary>
</summary> …
=> Create H2 database before tests

.github/workflows/generate_status_page.yaml, .github/workflows/generate_status_page_data.yaml
<details>
<summary>
</summary> …
=> Execute GHA generate status only on kiegroup

.ci/jenkins/dsl/jobs.groovy
<details>
<summary>
</summary> …
=> Correct Run BDD Runtimes

core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/ComparisonIndexer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/EqualsIndexer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/Indexer.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/NoneIndexer.java
There was a level of indirection in `visit(...)` that used to be necessary.
With the recent refactoring, it no longer is.
=> CS-B: Remove unnecessary indirection

optaplanner-quarkus-integration/optaplanner-quarkus/integration-test/pom.xml
Since native is not supported in 7.x
<details>
<summary>
</summary> …
=> Remove native profile from integration tests

build/optaplanner-build-parent/pom.xml
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1941
Related PRs:
- https://github.com/kiegroup/drools/pull/4342
- https://github.com/kiegroup/optaplanner/pull/1958
- https://github.com/kiegroup/optaplanner-quickstarts/pull/327
- https://github.com/kiegroup/kogito-runtimes/pull/2174
- https://github.com/kiegroup/kogito-apps/pull/1315
- https://github.com/kiegroup/kogito-examples/pull/1238
=> [8.21.x] Bump Quarkus version to 2.8.2.Final (#1941)

README.adoc
Change of contribution section + add some related badges + replace link to an OptaPlanner image
Contribution section is a quickest way how to commit changes to OptaPlanner for community.
@emmurphy1 Could I ask you to check it as well, please?
https://issues.redhat.com/browse/PLANNER-2684
<details>
<summary>
</summary> …
=> Updating Contributing to OptaPlanner section in README

build/optaplanner-build-parent/pom.xml
cherry-pick: https://github.com/kiegroup/optaplanner/pull/1961
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/437
- https://github.com/kiegroup/drools/pull/4357
- https://github.com/kiegroup/kogito-runtimes/pull/2188
- https://github.com/kiegroup/optaplanner/pull/1967
- https://github.com/kiegroup/optaplanner-quickstarts/pull/330
- https://github.com/kiegroup/kogito-apps/pull/1331
- https://github.com/kiegroup/kogito-examples/pull/1245
=> [1.21.x] Bump Quarkus version to 2.9.0.Final

core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/holder/AbstractScoreHolder.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/AbstractAccumulator.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/BiAccumulator.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/QuadAccumulator.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/TriAccumulator.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/UniAccumulator.java, core/optaplanner-constraint-streams/src/main/java/org/optaplanner/constraint/streams/drools/common/ValueExtractor.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-6942
Related PRs:
- https://github.com/kiegroup/drools/pull/4359
- https://github.com/kiegroup/kogito-runtimes/pull/2193
- https://github.com/kiegroup/optaplanner/pull/1970
=> [DROOLS-6942] remove useless interfaces from spi package

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/composite/UniformRandomUnionMoveIterator.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/composite/UnionMoveSelectorTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/vehiclerouting/app/VehicleRoutingPerformanceTest.java
Otherwise .next() can produce a null move.
Identified by `kogito-apps` CI.
=> PLANNER-2716 Ignore empty iterators

optaplanner-docs/src/modules/ROOT/pages/constraint-streams/constraint-streams.adoc
To make it clear that it is a custom type that the user needs to bring.
=> Replace Tuple with MyTuple

optaplanner-examples/src/main/java/org/optaplanner/examples/tsp/swingui/TspPanel.java, optaplanner-examples/src/main/java/org/optaplanner/examples/vehiclerouting/swingui/VehicleRoutingPanel.java
TSP was also affected.
I also updated the comment to explain why shallow cloning is needed. I reused an existing comment for consistency with other PCs.
https://issues.redhat.com/browse/PLANNER-2696
Amends #1977.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) …
=> PLANNER-2696 Fix CME in TSP

.ci/jenkins/Jenkinsfile.turtle, .ci/jenkins/dsl/jobs.groovy, optaplanner-examples/src/test/java/org/optaplanner/examples/cheaptime/app/CheapTimeSolveAllTurtleTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/TestSystemProperties.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/app/SolveAllTurtleTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nurserostering/app/NurseRosteringSolveAllTurtleTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/projectjobscheduling/app/ProjectJobSchedulingSolveAllTurtleTest.java
The goal is to have two turtle test jobs: one with ConstraintStreams-Drools and the other one with ConstraintStreams-Bavet.
https://issues.redhat.com/browse/PLANNER-2730
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command …
=> PLANNER-2730 Create a turtle test job with CS-B

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.post-release, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle
with this PR we prevent pipelines running on master and also the cancel on update is defined directly in pipelines 
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in …
=> prevented multiple starts of a PR & pipelines won't run on master

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/GizmoMemberAccessorEntityEnhancer.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorInterfaceEntityTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/interfaceentity/constraints/TestdataInterfaceEntityConstraintProvider.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/interfaceentity/domain/TestdataInterfaceEntity.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/interfaceentity/domain/TestdataInterfaceEntityImplementation.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/interfaceentity/domain/TestdataInterfaceEntitySolution.java
IndexView.getAllKnownSubclasses() does not get implementations for
interfaces, causing a bug in the generated SolutionCloner where implementations
of an interface PlanningEntity were not cloned. To fix it,
IndexView.getAllKnownImplementors() need to be used instead for
interfaces.
https://issues.redhat.com/browse/PLANNER-2734
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest …
=> PLANNER-2734: Make Solution Cloner clone implementations of entity interfaces

optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/model/OptaPlannerSolver.java
The "kind" of the custom resource should be capitalized.
<details>
<summary>
</summary> …
=> Make OptaPlannerSolver kind capitalized

build/optaplanner-build-parent/pom.xml, optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/OptaPlannerSolverReconciler.java, optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/model/messaging/KafkaTopicDependentResource.java, optaplanner-operator/src/test/java/org/optaplanner/operator/impl/solver/OptaPlannerSolverReconcilerTest.java, pom.xml
Upgrading the Java Operator SDK to the latest final version requires upgrading also the `io.quarkiverse.operatorsdk:quarkus-operator-sdk`. Unfortunately, there is no compatible final version yet (hopefully there will be one very soon).
Although we are trading one non-final version for another, it's still a step forward.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version …
=> Upgrade Java Operator SDK

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle, .ci/jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-7356
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/484
- https://github.com/kiegroup/drools/pull/4446
- https://github.com/kiegroup/kogito-runtimes/pull/2252
- https://github.com/kiegroup/kogito-apps/pull/1375
- https://github.com/kiegroup/kogito-examples/pull/1285
- https://github.com/kiegroup/kogito-images/pull/1275
- https://github.com/kiegroup/kogito-operator/pull/1204
- https://github.com/kiegroup/optaplanner/pull/2023
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/708
- https://github.com/kiegroup/optaweb-employee-rostering/pull/826
- https://github.com/kiegroup/optaplanner-quickstarts/pull/352
=> [8.13.x] KOGITO-7356 Do not use master node in pipelines

optaplanner-examples/src/main/java/org/optaplanner/examples/flightcrewscheduling/score/FlightCrewSchedulingConstraintProvider.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/flightcrewscheduling/optional/score/flightCrewSchedulingConstraints.drl
1. Variable names (change `fa` to `flightAssignment`).
2. In my opinion it helps understand the constraints if the constraint name _consistently_ either A) describes the condition it penalizes or B) describes the goal it maximizes by penalizing its negation. When this is used consistently it's easy to guess what the constraint does without looking at the implementation. I choose `A` because in this case it's a natural language description of the filtering condition.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use …
=> Improve Flight Crew Scheduling constraints consistency

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.drools, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.post-release, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.quarkus, .ci/jenkins/dsl/jobs.groovy, .github/pull_request_template.md, build/optaplanner-build-parent/pom.xml
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/464
- https://github.com/kiegroup/drools/pull/4437
- https://github.com/kiegroup/kogito-runtimes/pull/2243
- https://github.com/kiegroup/optaplanner/pull/2014
- https://github.com/kiegroup/kogito-apps/pull/1366
Jobs to test:
=> [PLANNER-2727] Optaplanner depends on released version of Drools

build/optaplanner-ide-config/ide-configuration.adoc
<details>
<summary>
</summary> …
=> Fix minor issues in IDE configuration instructions

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhase.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/decider/ConstructionHeuristicDecider.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/decider/MultiThreadedConstructionHeuristicDecider.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/localsearch/DefaultLocalSearchPhase.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/localsearch/decider/LocalSearchDecider.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/localsearch/decider/MultiThreadedLocalSearchDecider.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/phase/event/PhaseLifecycleSupport.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/AbstractSolver.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/DefaultSolver.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/event/SolverLifecycleListener.java
Move threads were not properly disposed of in case of an exception during solving.
https://issues.redhat.com/browse/PLANNER-2742
<details>
<summary>
</summary> …
=> PLANNER-2742 Shutdown move threads after exception

build/optaplanner-build-parent/pom.xml
A temporary fix to https://github.com/quarkusio/quarkus/issues/6588, which breaks the Quarkus ecosystem CI
<details>
<summary>
</summary> …
=> Override com.github.javaparser version

.ci/jenkins/Jenkinsfile.nightly, .ci/jenkins/Jenkinsfile.release, .ci/jenkins/config/branch.yaml, .ci/jenkins/config/main.yaml, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh, .github/workflows/jenkins-tests-PR.yml
Extract OptaPlanner DSL config and move specific pipelines to OptaPlanner repository.
That way OptaPlanner will benefit from its own release branch and setup.
There is way for optimization, for example nightly/release jobs calling only one deploy job. But ideally, optawebs and optaplanner-quickstarts should have their own deploy/promote jobs.
This will come later in another enhancement and should not impact yet the jobs.
Tests:
=> [PLANNER-2728] Extract optaplanner release from Kogito

.ci/jenkins/config/branch.yaml
<details>
<summary>
</summary> …
=> Fallback branch config to 8.24.x

.ci/jenkins/config/main.yaml
depends on https://github.com/kiegroup/optaplanner/pull/2054
`optaplanner-8.24.x` is causing issues in nightly pipelines so falling back to simple `8.24.x`
=> Fallback config to branch 8.24.x

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/phase/custom/CustomPhaseConfig.java
Trivial two-line bug fix.
CustomPhaseConfig.withCustomProperties(Map) was void. Now returns the
instance after setting the property.
There is no issue for this, as far as I know.
=> Fix void with-method

.ci/jenkins/Jenkinsfile.quarkus
Make sure the pipeline updates the dependencies before running the build&tests
https://issues.redhat.com/browse/KOGITO-7496
- https://github.com/kiegroup/kogito-pipelines/pull/532
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/209
- https://github.com/kiegroup/kogito-runtimes/pull/2310
- https://github.com/kiegroup/optaplanner/pull/2057
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be …
=> KOGITO-7496 Update quarkus nightly to compare dependencies

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/Score.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/bendable/BendableScore.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/bendablebigdecimal/BendableBigDecimalScore.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/bendablelong/BendableLongScore.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoft/HardMediumSoftScore.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScore.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/hardmediumsoftlong/HardMediumSoftLongScore.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/hardsoft/HardSoftScore.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScore.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/hardsoftlong/HardSoftLongScore.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/simple/SimpleScore.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/simplebigdecimal/SimpleBigDecimalScore.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/buildin/simplelong/SimpleLongScore.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/localsearch/decider/acceptor/greatdeluge/GreatDelugeAcceptor.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/buildin/bendable/BendableScoreTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/buildin/bendablebigdecimal/BendableBigDecimalScoreTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/buildin/bendablelong/BendableLongScoreTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/buildin/hardmediumsoft/HardMediumSoftScoreTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/buildin/hardmediumsoftlong/HardMediumSoftLongScoreTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/buildin/hardsoft/HardSoftScoreTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScoreTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/buildin/hardsoftlong/HardSoftLongScoreTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/buildin/simple/SimpleScoreTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/buildin/simplebigdecimal/SimpleBigDecimalScoreTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/buildin/simplelong/SimpleLongScoreTest.java
Hi there,
I noticed one tiny problem in the great deluge algorithm. In the end of each step, the current water level will be updated by a certain amount. It works well when the configuration is set to be increasing by a fixed score. However, if I set the increment as a ratio (Using ratio is a brilliant idea by the way), then the algorithm will only work when the starting water level is negative. In fact, to make sure the water level keep increasing, every increment of water level should be positive. But it will be negative when the starting water level is positive. So .negate() is not suitable for all scenarios, for example, when someone has more reward score than penalty score. Maybe taking absolute value is a better idea. I add an abs.() function for the score so that the certain amount …
=> Add Score.abs() for GreatDelugeAlgorithm.

.ci/jenkins/Jenkinsfile.drools
<details>
<summary>
</summary> …
=> Pipeline: Add drools team notif to Drools nightly

README.adoc
<details>
<summary>
</summary> …
=> Update Readme with CI info

core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/BavetConstraintSessionFactory.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/BavetConstraintStreamScoreDirectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/stream/JoinerSupport.java, optaplanner-docs/src/modules/ROOT/pages/integration/integration.adoc
Android unfortunately supports only a subset of the current JDK API. This has so far not been a problem for OptaPlanner, but after some recent changes OptaPlanner apparently started using some of the unsupported APIs, causing runtime crashes.
[ServiceLoader.findFirst()](https://developer.android.com/reference/java/util/ServiceLoader) is not currently supported by Android. `Collection.toArray(IntFunction<T[]>)` [is available as of Android API Level 33](https://developer.android.com/reference/java/util/Collection#toArray(java.util.function.IntFunction%3CT[]%3E)) but [is not available as a "desugared" API yet](https://developer.android.com/studio/write/java8-support-table), which means it can not be used in apps that want to maintain backwards compatibility.
Fortunately, this is easily …
=> Desugared use of APIs incompatible with Android

build/optaplanner-build-parent/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/src/test/filtered-resources/datasource.properties, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/AbstractScoreJpaTest.java
Creates the H2 test database before starting the H2 server. The previous solution relied on a property that allowed automatic creation of the database on connection, but that works only with newer H2 versions. As the H2 version comes from the `quarkus-bom` and we test with multiple Quarkus versions, the test setup must be backward-compatible.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …
=> Make H2 setup compatible with older versions

optaplanner-docs/src/modules/ROOT/pages/benchmarking-and-tweaking/benchmarking-and-tweaking.adoc
Change the key for the sifting appender to subSingleBenchmark.name in the documentation as referenced in the code at https://github.com/kiegroup/optaplanner/blob/5e36aecfa6b18b6f36e4e019fed5b70449176fea/optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/impl/SubSingleBenchmarkRunner.java#L28
=> Fix key in documentation for log separation

core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/ComparisonIndexer.java, optaplanner-examples/src/main/java/org/optaplanner/examples/cheaptime/score/CheapTimeConstraintProvider.java, optaplanner-examples/src/main/java/org/optaplanner/examples/pas/score/PatientAdmissionScheduleConstraintProvider.java
TreeMap's headMap() and tailMap() are relatively inefficient. The new algorithm iterates over the entire map and stops when it reaches the key that is no longer of interest.
At the same time, we update some constraint providers to use the API effectively.
=> CS-B: Improve performance of ComparisonIndexer

core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/DrlScoreDirectorFactoryService.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/BavetConstraintStreamScoreDirectorFactoryService.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/DroolsConstraintStreamScoreDirectorFactoryService.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/director/ScoreDirectorFactoryFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/score/director/ScoreDirectorFactoryService.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/verifier/OptaPlannerConstraintVerifierTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/resources/org/optaplanner/quarkus/verifier/droolsSolverConfig.xml, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/pom.xml, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/resources/org/optaplanner/spring/boot/autoconfigure/droolsSolverConfig.xml, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultConstraintVerifier.java
If they explicitly specify a constraintStreamImplType, then it should fail fast if it's not on the classpath
Otherwise if only one is on the classpath, use that one.
If both are on the classpath, use - for now - drools.
=> PLANNER-2757 Use the CS impl that is available

optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4449
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2008
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2010
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2009
* https://github.com/kiegroup/optaplanner/pull/2089
* https://github.com/kiegroup/optaplanner/pull/2090
* https://github.com/kiegroup/optaplanner/pull/2091
<details>
<summary>
</summary> …
=> [RHPAM-4449] spring-boot downgraded to 2.5.12

optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4449
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2008
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2010
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2009
* https://github.com/kiegroup/optaplanner/pull/2089
* https://github.com/kiegroup/optaplanner/pull/2090
* https://github.com/kiegroup/optaplanner/pull/2091
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those …
=> [7.67.x][RHPAM-4449] spring-boot downgraded to 2.5.12

optaplanner-quickstarts/spring-boot-school-timetabling/pom.xml
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4449
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2008
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2010
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2009
* https://github.com/kiegroup/optaplanner/pull/2089
* https://github.com/kiegroup/optaplanner/pull/2090
* https://github.com/kiegroup/optaplanner/pull/2091
<details>
<summary>
</summary> …
=> [7.67.x-blue][RHPAM-4449] spring-boot downgraded to 2.5.12

core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/DrlScoreDirectorFactoryService.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/DroolsConstraintStreamScoreDirectorFactoryService.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/score/director/ScoreDirectorFactoryConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java
Due to a Quarkus recorder bug https://github.com/quarkusio/quarkus/issues/26889,
the droolsAlphaNetworkCompilationEnabled (DANCE) is never actual set (i.e. it is always
null) in Quarkus, meaning we need to use isDroolsAlphaNetworkCompilationEnabled(), which is computed,
instead of getDroolsAlphaNetworkCompilationEnabled(), which just returns
droolsAlphaNetworkCompilationEnabled.
This fixes the native build, which was broken because DANCE was always
null, causing it to be enabled in native mode, which DANCE is not
compatiable with.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method …
=> Handle null case in OptaPlanner processor; replace usages of getDANCE with isDANCE

.ci/jenkins/dsl/jobs.groovy
This reverts commit c467f93b465580314e9996a1b8bcdfbaaca65d6f.
<details>
<summary>
</summary> …
=> [8.13.x] Revert "[8.13.x] Remove native checks"

core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractFlattenLastNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractGroupNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractIfExistsNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractJoinNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractScorer.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractTuple.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/Group.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/Tuple.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/SingleIndexProperties.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/ThreeIndexProperties.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/index/TwoIndexProperties.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/package-info.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/MutablePairImpl.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/MutableQuadrupleImpl.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/MutableTripleImpl.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/PairImpl.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/QuadrupleImpl.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/util/TripleImpl.java
Brings a couple percentage points in constraint provider performance due to not allocating certain structures on the hot path.
=> CS-B: Reduce memory churn

build/optaplanner-build-parent/pom.xml, core/optaplanner-constraint-streams-common/src/test/java/org/optaplanner/constraint/streams/common/AbstractConstraintStreamTest.java, core/optaplanner-core-impl/src/test/resources/junit-platform.properties, optaplanner-examples/pom.xml, optaplanner-examples/src/test/java/org/optaplanner/examples/common/TurtleTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/app/AbstractBenchmarkConfigTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/app/AbstractPhaseTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/app/SolverPerformanceTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/persistence/ImportDataFilesTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/persistence/OpenDataFilesTest.java
Reduced the run time of optaplanner-examples from 9min13s to 7min16s on my quad-core machine. (A reduction in run time of ~20 %.)
However, the biggest benefit of this change will come with turtle tests, which (when run on a powerful machine) will no longer take days, rather hours.
This is unlikely to make any impact on GHA, as those machines have 2 cores and this is configured to use 50 % of available cores.
=> Execute some OP tests in parallel

build/optaplanner-build-parent/pom.xml, core/optaplanner-constraint-drl/pom.xml, core/optaplanner-constraint-streams-bavet/pom.xml, core/optaplanner-constraint-streams-common/pom.xml, core/optaplanner-core-impl/pom.xml, core/optaplanner-core/pom.xml, optaplanner-persistence/pom.xml
Add android-api-compatibility-check profile that checks signature of optaplanner-core-impl if it is compatible with the current android version
https://issues.redhat.com/browse/PLANNER-2752
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which …
=> PLANNER-2752 Check Jar/Class-Files for compliance with Android

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/AbstractFromConfigFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/placer/PooledEntityPlacerFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/placer/QueuedEntityPlacerFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/placer/QueuedValuePlacerFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/EntitySelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/pillar/PillarSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/composite/AbstractCompositeMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarChangeMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarSwapMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/SwapMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/KOptMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainChangeMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/SubChainSwapMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/chained/TailChainSwapMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/ValueSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/chained/SubChainSelectorFactory.java
I made some improvements to the code that builds selectors from configs. It should be now easier to understand because it's slightly less code and its structure is more consistent across all factories.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build …
=> Clean up selector factories' build methods

build/optaplanner-build-parent/pom.xml
1. Plugin management shouldn't be conditional if the plugin is used
unconditionally in some modules. That results in a warning about
using a plugin without specifying its version.
2. The general approach is: run everything by default, use `-Dquickly` if
you want to build faster.
Example of the mentioned warning:
> [WARNING] Some problems were encountered while building the effective model for org.optaplanner:optaplanner-core:jar:8.26.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:animal-sniffer-maven-plugin is missing. @ line 56, column 15
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and …
=> Fix Animal Sniffer plugin management

core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java
Previously, before each test, only Metrics.globalRegistry.clear()
was called. This removes all meters, but does not remove
meter registries. Each test create it own meter registry.
This leads to a leak where the Metrics.globalRegistry keep glowing,
slowing down repeated test execution. Leak does not affect
core.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the …
=> Remove leak of test meter registries

optaplanner-docs/src/modules/ROOT/pages/integration/config-properties.adoc, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/config/SolverBuildTimeConfig.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorSolverPropertiesTest.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfiguration.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/main/java/org/optaplanner/spring/boot/autoconfigure/config/SolverProperties.java, optaplanner-spring-integration/optaplanner-spring-boot-autoconfigure/src/test/java/org/optaplanner/spring/boot/autoconfigure/OptaPlannerAutoConfigurationTest.java
https://issues.redhat.com/browse/PLANNER-2756
<details>
<summary>
</summary> …
=> PLANNER-2756: Add constraint stream type property for Quarkus and Spring Boot

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/AbstractConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/AbstractSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/pillar/PillarSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/SwapMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/chained/SubChainSelectorFactory.java
The "from config" factories should use `config` in exception messages instead of `this` because they (factories) do not override `toString()` but configs do. This PR fixes the few case which break the rule.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a …
=> Fix typos and improve selector factories' error messages

.ci/jenkins/Jenkinsfile.post-release
once optaplanner was released and the artifacts/binaries are on Maven Central the job optaplanner-post-release runs.
Here was added the automatic bumping up of of kie-benchmarks SNAPSHOT version. This was done until now 100% manually and now it is automatted. 
i.e. when optaplanner gets released to 8.25.0.Final the next SNAPSHOT version of kie-benchmarks will be 8.26.0-SNAPSHOT.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross …
=> added step for upgrading kie-benchmarks

.ci/jenkins/Jenkinsfile.post-release
In kiegroup/kie-benchmarks will be upgraded the OptaPlanner version to the next SNAPSHOT instead of Final version. 
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in …
=> OptaPlanner version upgraded to next SNAPSHOT version

build/optaplanner-build-parent/pom.xml, optaplanner-operator/pom.xml, optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/model/ConfigMapDependentResource.java, optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/model/DeploymentDependentResource.java, optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/model/keda/ScaledObjectDependentResource.java, optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/model/keda/TriggerAuthenticationDependentResource.java, optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/model/messaging/ArtemisQueueDependentResource.java, pom.xml
The `io.quarkiverse:quarkus-operator-sdk` released a stable version, which means we no longer have to override the `javaoperatorsdk` version or exclude the `optaplanner-operator` from the build.
https://issues.redhat.com/browse/PLANNER-2768
<details>
<summary>
</summary>
[build-chain …
=> PLANNER-2768 Use a final version of quarkus-operator-sdk

pom.xml
Disables the `optaplanner-operator` due to an upstream issue that makes it incompatible with Quarkus 2.7.
See https://github.com/quarkiverse/quarkus-operator-sdk/pull/390 for more details.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can …
=> Disable optaplanner-operator module

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/DefaultSolver.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/recaller/BestSolutionRecaller.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/partitionedsearch/DefaultPartitionedSearchPhaseTest.java
https://issues.redhat.com/browse/PLANNER-2778
<details>
<summary>
</summary> …
=> PLANNER-2778 Partitioned search does not emit BSE after a ProblemChange

optaplanner-docs/src/modules/ROOT/pages/constraint-streams/constraint-streams.adoc
I've had a lot of hair pulling with what should have been common sense from my side (don't assume everything is thread safe), but i think a warning can help some people because the errors it causes really do not make any sense.
See the conversation on zulipchat where all the hair pulling happened: https://kie.zulipchat.com/#narrow/stream/232679-optaplanner/topic/NoClassDefFound.20error
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle …
=> Add warning ConstraintVerifier not thread safe

core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/BavetConstraintStreamScoreDirectorFactoryService.java, core/optaplanner-constraint-streams-common/src/main/java/org/optaplanner/constraint/streams/common/AbstractConstraintStreamScoreDirectorFactory.java, core/optaplanner-constraint-streams-common/src/main/java/org/optaplanner/constraint/streams/common/AbstractConstraintStreamScoreDirectorFactoryService.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/DroolsConstraintStreamScoreDirectorFactory.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/DroolsConstraintStreamScoreDirectorFactoryService.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/util/ConfigUtils.java, optaplanner-docs/src/modules/ROOT/pages/constraint-streams/constraint-streams.adoc, optaplanner-examples/src/test/java/org/optaplanner/examples/cheaptime/score/CheapTimeConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/cloudbalancing/score/CloudBalancingConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/coachshuttlegathering/score/CoachShuttleGatheringConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/score/AbstractConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/score/ConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/common/score/SimplifiedTestNameGenerator.java, optaplanner-examples/src/test/java/org/optaplanner/examples/conferencescheduling/score/ConferenceSchedulingConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/curriculumcourse/score/CurriculumCourseConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/examination/score/ExaminationConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/machinereassignment/score/MachineReassignmentConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/meetingscheduling/score/MeetingSchedulingConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nqueens/score/NQueensConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nurserostering/score/NurseRosteringConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/pas/score/PatientAdmissionScheduleConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/tennis/score/TennisConstraintProviderTest.java, optaplanner-examples/src/test/java/org/optaplanner/examples/vehiclerouting/score/VehicleRoutingConstraintProviderTest.java, optaplanner-test/src/main/java/org/optaplanner/test/api/score/stream/ConstraintVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/ConfiguredConstraintVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultConstraintVerifier.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultMultiConstraintAssertion.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultMultiConstraintVerification.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultSingleConstraintVerification.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/ScoreDirectorFactoryCache.java
Makes ConstraintVerifier thread-safe by using ServiceLoader in a ThreadLocal.
Also caches ScoreDirectorFactories, speeding up tests.
Finally switches constraint provider tests in examples to use concurrency, to dogfood the new feature.
=> PLANNER-2781 Thread-safe ConstraintVerifier

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/BooleanFieldCloner.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/ByteFieldCloner.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/CharFieldCloner.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/DeepCloningFieldCloner.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/DoubleFieldCloner.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/FieldAccessingSolutionCloner.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/FieldCloner.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/FloatFieldCloner.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/IntFieldCloner.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/LongFieldCloner.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/ShallowCloningFieldCloner.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/ShortFieldCloner.java
The FieldCloner class doesn't need to be generic. The type parameter is
only needed in the clone() method to ensure that the `instanceClass`,
`original` and `clone` are all of the same type.
This change makes the code simpler by removing the type parameter where
it's not needed, and resolves several unchecked and rawtype warnings.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use …
=> Resolve unchecked and rawtype warnings in field cloners

build/release/release-procedure.adoc
<details>
<summary>
</summary> …
=> re-edited OptaPlanner release procedure

.ci/jenkins/config/branch.yaml, .ci/jenkins/config/main.yaml
<details>
<summary>
</summary> …
=> test config

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/solver/SolverJob.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/solver/SolverManager.java
The relation between `terminateEarly()` and the `finalBestSolutionConsumer` was not clear enough, as illustrated by https://stackoverflow.com/questions/73557560/optaplanner-solvermanagersolveandlisten-synchronization-locking-bug.
<details>
<summary>
</summary>
[build-chain …
=> Clarify terminateEarly() Javadoc

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/decider/forager/ConstructionHeuristicForagerFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhaseFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/exhaustivesearch/node/bounder/TrendBasedScoreBounder.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/HeuristicConfigPolicy.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/DefaultSolverFactory.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/config/constructionheuristic/placer/PooledEntityPlacerFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/PlacementAssertions.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/PooledEntityPlacerFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/PooledEntityPlacerTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/QueuedEntityPlacerFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/QueuedEntityPlacerTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/QueuedValuePlacerFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/constructionheuristic/placer/entity/QueuedValuePlacerTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/HeuristicConfigPolicyTestUtils.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/AbstractSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/entity/EntitySelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/MoveSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMoveSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/SwapMoveSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/value/ValueSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/score/buildin/AbstractScoreDefinitionTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/score/buildin/HardSoftScoreDefinitionTest.java
Benefits:
- ScoreDirectorFactory cannot leak from the policy object.
- Callers looking for the InitializingScoreTrend do not have to traverse through the SDF.
- Easier to create a HeuristicConfigPolicy instance because SDF is no longer needed (tests do not have to create an SDF mock).
<details>
<summary>
</summary> …
=> Decouple HeuristicConfigPolicy and ScoreDirectorFactory plus related tests cleanup

optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/OptaPlannerSolverReconciler.java, optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/model/ConfigMapDependentResource.java, optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/model/OptaPlannerSolver.java, optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/model/OptaPlannerSolverStatus.java, optaplanner-operator/src/test/java/org/optaplanner/operator/impl/solver/OptaPlannerSolverReconcilerTest.java
Based on https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties.
https://issues.redhat.com/browse/PLANNER-2767
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can …
=> PLANNER-2767 Implement the operator status API

optaplanner-operator/src/k8s/openshift.yml
Adds missing permissions to the operator deployment template to allow working with the ActiveMQ address resources.
<details>
<summary>
</summary> …
=> Set permissions on the activemq resource

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/solver/termination/TerminationFactory.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/solver/termination/TerminationFactoryTest.java
https://issues.redhat.com/browse/PLANNER-2800
<details>
<summary>
</summary> …
=> PLANNER-2800 Avoid NegativeArraySizeException when zero feasible levels

optaplanner-examples/src/main/java/org/optaplanner/examples/nurserostering/domain/contract/Contract.java, optaplanner-examples/src/test/java/org/optaplanner/examples/nurserostering/score/NurseRosteringConstraintProviderTest.java, optaplanner-test/src/main/java/org/optaplanner/test/impl/score/stream/DefaultSingleConstraintAssertion.java
The other change in DefaultSingleConstraintAssertion is there just to clean up the code while I was investigating it. 
It has no relation to the bug, which is solely in the test.
=> PLANNER-2801 Fix flaky test by not sharing maps across threads

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.init-branch, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.turtle, .ci/jenkins/project/Jenkinsfile.drools, .ci/jenkins/project/Jenkinsfile.init-branch, .ci/jenkins/project/Jenkinsfile.native, .ci/jenkins/project/Jenkinsfile.nightly, .ci/jenkins/project/Jenkinsfile.post-release, .ci/jenkins/project/Jenkinsfile.quarkus, .ci/jenkins/project/Jenkinsfile.release
https://issues.redhat.com/browse/PLANNER-2795
- All failed builds (regardless of branch/job name/etc) go to the CI failures topic in optaplanner-dev.
- All success build (regardless of branch/job name/etc) go to the CI success topic in optaplanner-dev.
<details>
<summary>
</summary>
[build-chain …
=> PLANNER-2795 Reduce CI verbosity

.ci/jenkins/config/branch.yaml
<details>
<summary>
</summary> …
=> [8.27.x] Disable triggers as branch not maintained anymore

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/pom.xml
This PR replaces the usage of `ClassInfo.annotations()` with `ClassInfo.annotationsMap()`, because `annotations()` have different meaning between Jandex 2 and 3 (while `annotationsMap()`, added in Jandex 2.4.3, has the same meaning in Jandex 3.0).
Also, this PR removes the dependency on `org.jboss:jandex` from the `runtime` module of the Quarkus extension, because that seems completely unnecessary. Jandex is almost never required at runtime in Quarkus applications, and I couldn't find any evidence of OptaPlanner using Jandex (besides the `deployment` part of the Quarkus extension, of course).
Sorry if I'm submitting this PR incorrectly, I never contributed to OptaPlanner before. I'm happy to do any adjustments necessary.
None
N/A
<details>
<summary>
How to replicate CI configuration …
=> Compatibility with Jandex 3

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java
This PR partially reverts https://github.com/kiegroup/optaplanner/pull/2193.
I believe the change to `ClassInfo#annotationsMap()` arrived too early. The CI checking compatibility with Quarkus 2.7 has failed due to `java.lang.NoSuchMethodError: 'java.util.Map org.jboss.jandex.ClassInfo.annotationsMap()'`.
The latest version in that stream is the 2.7.6.Final, which depends on Jandex 2.4.2.Final. However, the `annotationsMap()` method has been backported [1] only to 2.4.3.Final.
[1] https://github.com/smallrye/jandex/commit/cd7fa5fd648eaa8b890babe0b090102932406ee3
@Ladicek please let me know if I am missing something.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the …
=> Keep compatibility with Quarkus 2.7

.github/jandex_3.patch, .github/quarkus-ecosystem-test
A temporary fix of the Quarkus Ecosystem CI. Applies a patch to make OptaPlanner compatible with Jandex 3.0.
Remove after creating the 8.29.x branch.
<details>
<summary>
</summary> …
=> Patch the ecosystem CI to enable testing with Jandex 3.0

.github/pull_request_template.md, .github/workflows/full-downstream.yml, .github/workflows/pull_request.yml
JIRA:
- https://issues.redhat.com/browse/BXMSPROD-1770
referenced Pull Requests:
- https://github.com/kiegroup/kogito-pipelines/pull/590
Added OS preparation step.
If we agree on this solution I'll revert the commit [9346bcd](https://github.com/kiegroup/optaplanner/pull/2146/commits/9346bcd1616013541c5f8ed4613030ced630c875) and propagate the same fix on all other kogito-related projects.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle …
=> [BXMSPROD-1770] Added OS preparation step

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, build/optaplanner-distribution-internal/pom.xml, build/optaplanner-distribution-internal/src/main/assembly/assembly-optaplanner.xml, optaplanner-docs/src/modules/ROOT/pages/release-notes/release-notes-8.adoc, pom.xml
Temporarily disable the operator from the default build as it's incompatible with Quarkus 2.7.
<details>
<summary>
</summary> …
=> Exclude the operator from the default build

optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorGizmoKitchenSinkTest.java
Follows up on af2579924259f552ce73a578afdabc8b845068d1.
<details>
<summary>
</summary> …
=> Assert same scoreDirectorFactory in solverFactory and scoreManager

.ci/jenkins/Jenkinsfile.prod.nightly
- https://issues.redhat.com/browse/BXMSPROD-1826
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1327
<details>
<summary>
</summary> …
=> [RHBOP] [BXMSPROD-1826] Added nightly jenkins pipeline

.ci/jenkins/Jenkinsfile.prod.nightly
- https://issues.redhat.com/browse/BXMSPROD-1826
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1327
- https://github.com/kiegroup/optaplanner/pull/2214
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1328
<details>
<summary>
</summary>
[build-chain …
=> Fix RHBOP nightly pipeline

.ci/jenkins/config/main.yaml
<details>
<summary>
</summary> …
=> DSL: Remove OP 8.27.x jobs

.ci/jenkins/Jenkinsfile.prod.nightly, pom.xml
- https://issues.redhat.com/browse/BXMSPROD-1826
- https://github.com/kiegroup/optaplanner-quickstarts/pull/421
- https://github.com/jboss-integration/rhbop-optaplanner/pull/1
- https://github.com/kiegroup/optaplanner/pull/2214
- https://github.com/kiegroup/optaplanner/pull/2223
Changes:
- Rename optaweb sources folder name 
- Remove the following quickstarts examples from sources generation:
- technology
- python
- kubernetes
<details>
<summary>
</summary> …
=> [RHBOP] Nightly sources generation fix

.ci/jenkins/Jenkinsfile.prod.nightly
- https://issues.redhat.com/browse/BXMSPROD-1826
- https://github.com/kiegroup/optaplanner-quickstarts/pull/423
<details>
<summary>
</summary> …
=> [RHBOP] [BXMSPROD-1826] Use quickstarts development branch for main nightly

core/optaplanner-core-impl/pom.xml, optaplanner-benchmark/pom.xml
Fail the CI if XSD changes during the build. This happens when XSD changes have not been committed with the PR that introduces them.
<details>
<summary>
</summary> …
=> Fail the CI if XSDs change

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/thread/OrderByMoveIndexBlockingQueue.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/localsearch/decider/MultiThreadedLocalSearchDecider.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java
https://issues.redhat.com/browse/PLANNER-2811
<details>
<summary>
</summary> …
=> PLANNER-2811 Stop MT solving if there are no moves

core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BavetAbstractBiConstraintStream.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/bi/BavetJoinBiConstraintStream.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/bi/IndexedJoinBiNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/bi/UnindexedJoinBiNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractConditionalTupleLifecycle.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractFlattenLastNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractGroupNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractIndexedIfExistsNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractIndexedJoinNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractJoinNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractMapNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractTuple.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractUnindexedIfExistsNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AbstractUnindexedJoinNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/AggregatedTupleLifecycle.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/LeftTupleLifecycleImpl.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/RightTupleLifecycleImpl.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/Tuple.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/common/collection/TupleListEntry.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/quad/BavetJoinQuadConstraintStream.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/quad/IndexedJoinQuadNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/quad/UnindexedJoinQuadNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/tri/BavetAbstractTriConstraintStream.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/tri/BavetJoinTriConstraintStream.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/tri/IndexedJoinTriNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/tri/UnindexedJoinTriNode.java, core/optaplanner-constraint-streams-bavet/src/main/java/org/optaplanner/constraint/streams/bavet/uni/BavetAbstractUniConstraintStream.java
POC shows big speed gain in specific cases.
=> PLANNER-2818 Bavet join must not create out tuple if filtering returns false

.ci/jenkins/config/main.yaml
<details>
<summary>
</summary> …
=> DSL: Remove Jenkins jobs on branch 8.28.x

.ci/jenkins/dsl/jobs.groovy
- https://github.com/kiegroup/optaplanner/pull/2251
- https://github.com/kiegroup/optaplanner-quickstarts/pull/430
<details>
<summary>
</summary> …
=> Update Quarkus job: Compare dependencies

build/optaplanner-build-parent/pom.xml, optaplanner-operator/pom.xml, pom.xml
<details>
<summary>
</summary> …
=> Enable the optaplanner-operator module

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, build/optaplanner-distribution-internal/pom.xml, build/optaplanner-distribution-internal/src/main/assembly/assembly-optaplanner.xml, optaplanner-docs/src/modules/ROOT/pages/release-notes/release-notes-8.adoc
This is a leftover from https://github.com/kiegroup/optaplanner/pull/2246.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple …
=> Enable optaplanner-operator in the release pipeline

.ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.setup-branch
So we can call it also on main branch to update the version
The renaming of the job/jenkinsfile is done as it is a more logical name for the job.
https://issues.redhat.com/browse/PLANNER-2829
- https://github.com/kiegroup/kogito-pipelines/pull/658
- https://github.com/kiegroup/optaplanner/pull/2255
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/774
- https://github.com/kiegroup/optaplanner-quickstarts/pull/437
<details>
<summary>
</summary> …
=> PLANNER-2829 Init branch becomes Setup branch

.ci/jenkins/Jenkinsfile.turtle
I noticed the turtle tests haven't sent any email for a while; in the logs, there is: 
`[2022-10-14T21:30:43.661Z] Sending email to: null@redhat.com`
<details>
<summary>
</summary> …
=> Set OPTAPLANNER_CI_EMAIL_TO env variable in turtle tests

.ci/jenkins/project/Jenkinsfile.nightly
<details>
<summary>
</summary> …
=> Correct issue on unsuccessful project nightly

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-8168
After this merge, there will be:
- only on message on Zulip with all PRs in there
- each PR is updated with all the related PRs
- default reviewers are assigned
- https://github.com/kiegroup/kogito-pipelines/pull/661
- https://github.com/kiegroup/optaplanner/pull/2264
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the …
=> KOGITO-8168 Update Quarkus job: Centralize PR links

optaplanner-docs/src/modules/ROOT/pages/release-notes/release-notes-8.adoc
This improvement is possible because release notes have been moved into the docs module.
- Works better during development (local builds of the docs have links back to the local build).
- IDE support (code completion and navigation).
<details>
<summary>
</summary>
[build-chain …
=> Replace documentation URLs in release notes with xref

optaplanner-docs/src/modules/ROOT/pages/planner-configuration/planner-configuration.adoc, optaplanner-docs/src/modules/ROOT/pages/release-notes/release-notes-8.adoc, optaplanner-docs/src/modules/ROOT/pages/shadow-variable/shadow-variable.adoc
<details>
<summary>
</summary> …
=> Add list variable to 8.29.0 release notes

.ci/jenkins/config/branch.yaml
The CI is currently configured to push the operator image to the `kiegroup` organization, which is wrong.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need …
=> Push operator image to optaplanner organization

.ci/jenkins/config/branch.yaml, .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/PLANNER-2856
Meant to automate the update of Optaplanner on Quarkus platform
Example created PR (with also Kogito): https://github.com/radtriste/quarkus-platform/pull/3
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/683
- https://github.com/kiegroup/optaplanner/pull/2300
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of …
=> [PLANNER-2856] Setup Quarkus platform job

.ci/jenkins/config/branch.yaml
https://issues.redhat.com/browse/PLANNER-2855
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/685
- https://github.com/kiegroup/optaplanner/pull/2301
- https://github.com/kiegroup/optaplanner-website/pull/547
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1360
<details>
<summary>
</summary> …
=> Added optaplanner-website

.ci/jenkins/Jenkinsfile.prod.nightly
- https://github.com/kiegroup/optaplanner/pull/2304
- https://github.com/kiegroup/optaplanner/pull/2305
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need …
=> [8.29.x] [RHBOP] Using env.LOCAL_NEXUS_IP for RHBOP nightly

.ci/jenkins/Jenkinsfile.prod.nightly
- https://github.com/kiegroup/optaplanner/pull/2304
- https://github.com/kiegroup/optaplanner/pull/2305
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need …
=> [RHBOP] Using env.LOCAL_NEXUS_IP for RHBOP nightly

.ci/jenkins/config/main.yaml
<details>
<summary>
</summary> …
=> DSL: Remove 8.30.x jobs

.ci/pull-request-config-rhbop.yaml
As long as optaplanner refers to a `8.30.0.Final` version of `Drools` [1] the actual build-chain tool for RHBOP product is correctly building drools from scratch with `productized` profile (using the main snapshot version) - but then, the result is not used in the `optaplanner` build as it will look for the `8.30.0.Final`.
[1] https://github.com/kiegroup/optaplanner/blob/main/build/optaplanner-build-parent/pom.xml#L23
Taking inspiration from https://github.com/kiegroup/optaplanner/blob/main/.ci/jenkins/project/Jenkinsfile.drools#L61 my idea was to retrieve the Drools version once its build is completed and export it, after that override `version.org.drools` in the optaplanner build.
*JIRA*:
- https://issues.redhat.com/browse/BXMSPROD-1861
*Referenced Pull Requests*:
- …
=> [RHBOP] Fix drools version when building projects for PR CI checks

optaplanner-examples/src/main/java/org/optaplanner/examples/cloudbalancing/swingui/realtime/AddComputerProblemChange.java
https://issues.redhat.com/browse/PLANNER-2854
<details>
<summary>
</summary> …
=> PLANNER-2854 Fix adding computers to CloudBalance

.ci/project-dependencies-rhbop.yaml, .ci/pull-request-config-rhbop.yaml, .github/workflows/rhbop_productized_pull_request.yml
- https://issues.redhat.com/browse/BXMSPROD-1861
- https://github.com/kiegroup/optaplanner/pull/2275 (main)
- https://github.com/kiegroup/optaplanner/pull/2294
- https://github.com/kiegroup/optaplanner-quickstarts/pull/448
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/791
- https://github.com/kiegroup/drools/pull/4796
Backport on `8.29.x` branch
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be …
=> [8.29.x] [BXMSPROD-1861] Added PR CI workflow for productized rhbop

core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/SelectorTestUtils.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/ChangeMoveSelectorTest.java
https://issues.redhat.com/browse/PLANNER-2857
<details>
<summary>
</summary> …
=> PLANNER-2857 ChangeMoveSelector must not skip not doable moves

optaplanner-docs/src/modules/ROOT/pages/repeated-planning/repeated-planning.adoc
Based on https://kie.zulipchat.com/#narrow/stream/232679-optaplanner/topic/.60ProblemChange.60.20to.20change.20entities.3F .
<details>
<summary>
</summary> …
=> Mention that ProblemChange covers also entities

.ci/jenkins/Jenkinsfile.prod.nightly
Backporting for `8.29.x`
https://issues.redhat.com/browse/BXMSPROD-1876
https://issues.redhat.com/browse/BXMSPROD-1884
- https://github.com/kiegroup/optaplanner/pull/2318
- https://github.com/kiegroup/optaplanner/pull/2319
<details>
<summary>
</summary>
[build-chain …
=> [8.29.x] [BXMSPROD-1876-1884] Fix UMB msg for nightly

.ci/jenkins/Jenkinsfile.prod.nightly
Introduced fixes:
- Added in UMB msg the `optaplanner` and `platform.quarkus.bom` versions in order to keep it coherent with the release process.
- Fixed the archive url in the UMB msg from `...8.29.x-nightly` to `...8.29-nightly`
https://issues.redhat.com/browse/BXMSPROD-1876
https://issues.redhat.com/browse/BXMSPROD-1884
- https://github.com/kiegroup/optaplanner/pull/2318
- https://github.com/kiegroup/optaplanner/pull/2319
<details>
<summary>
</summary> …
=> [BXMSPROD-1876-1884] Fix UMB msg for nightly

build/optaplanner-build-parent/pom.xml
<details>
<summary>
</summary> …
=> upgraded drools version

optaplanner-migration/pom.xml
Fixes the Quarkus main branch compatibility CI check.
<details>
<summary>
</summary> …
=> Make OptaPlanner compatible with Quarkus 2.15

optaplanner-quarkus-integration/optaplanner-quarkus/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/reflection-integration-test/.gitignore, optaplanner-quarkus-integration/optaplanner-quarkus/reflection-integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/reflection-integration-test/src/main/java/org/optaplanner/quarkus/it/reflection/OptaPlannerTestResource.java, optaplanner-quarkus-integration/optaplanner-quarkus/reflection-integration-test/src/main/java/org/optaplanner/quarkus/it/reflection/domain/TestdataReflectionEntity.java, optaplanner-quarkus-integration/optaplanner-quarkus/reflection-integration-test/src/main/java/org/optaplanner/quarkus/it/reflection/domain/TestdataReflectionSolution.java, optaplanner-quarkus-integration/optaplanner-quarkus/reflection-integration-test/src/main/java/org/optaplanner/quarkus/it/reflection/solver/TestdataStringLengthConstraintProvider.java, optaplanner-quarkus-integration/optaplanner-quarkus/reflection-integration-test/src/main/resources/application.properties, optaplanner-quarkus-integration/optaplanner-quarkus/reflection-integration-test/src/test/java/org/optaplanner/quarkus/it/reflection/OptaPlannerTestResourceIT.java, optaplanner-quarkus-integration/optaplanner-quarkus/reflection-integration-test/src/test/java/org/optaplanner/quarkus/it/reflection/OptaPlannerTestResourceTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/src/main/java/org/optaplanner/quarkus/nativeimage/Substitute_LambdaBeanPropertyMemberAccessor.java
The missing context for why Substitute_MemberAccessorFactory was created: LambdaBeanPropertyMemberAccessor generate classes at runtime (via LambdaMetafactory), which is not supported by GraalVM. Thus, if a getter method is annotated for member access, a
LambdaBeanPropertyMemberAccessor is created, which will try to create a new class, and GraalVM will throw an unsupported feature exception at runtime when run in native mode.
The Substitute_MemberAccessorFactory "fixed" it by removing the code path that leads to LambdaBeanPropertyMemberAccessor. However, that is more work to maintain and requires knowledge of why LambdaBeanPropertyMemberAccessor should not be used. What this commit does instead, is substitute LambdaBeanPropertyMemberAccessor, keeping the original MemberAccessorFactory …
=> PLANNER-2002: Add Substitute_LambdaBeanPropertyMemberAccessor

.ci/jenkins/project/Jenkinsfile.post-release
(cherry picked from commit 0806c9c7548dc56cdb88371279a005832765f2e1)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and …
=> [8.31.x] added hash for uniqueness of branch (#2384)

.github/dependabot.yml
Replaces https://github.com/kiegroup/optaplanner/pull/2403.
<details>
<summary>
</summary> …
=> Enable version updates on main

.ci/jenkins/project/Jenkinsfile.post-release
<details>
<summary>
</summary> …
=> Correct post release pipeline

build/optaplanner-build-parent/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml
<details>
<summary>
</summary> …
=> Remove Jandex override

.github/workflows/pull_request.yml
In order to save resources, run GHA on PRs only.
Rationale:
The `on push` trigger runs the GHA checks when a PR is merged to the target branch. Such a check is redundant, as the PR has been already tested and there is also a nightly build making sure the branch is in the correct state.
<details>
<summary>
</summary> …
=> Do not run GHA on push

.github/workflows/pull_request.yml, .github/workflows/rhbop_productized_pull_request.yml
<details>
<summary>
</summary> …
=> Simplify CI and make it less flaky

core/optaplanner-core-impl/src/test/java/org/optaplanner/core/config/solver/SolverConfigTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/io/jaxb/GenericJaxbIOTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfigTest.java
Tests now don't rely on exception messages that are subject to locale.
https://issues.redhat.com/browse/PLANNER-2881 -->
-none-
<details>
<summary>
</summary> …
=>  PLANNER-2881 - fix tests when build runs in non-english locale

build/optaplanner-build-parent/pom.xml, optaplanner-operator/pom.xml, optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/OptaPlannerSolverReconciler.java, optaplanner-operator/src/main/java/org/optaplanner/operator/impl/solver/model/messaging/ArtemisQueueDependentResource.java, optaplanner-operator/src/test/java/org/optaplanner/operator/impl/solver/OptaPlannerSolverReconcilerTest.java
Replaces https://github.com/kiegroup/optaplanner/pull/2463.
Bumps quarkus-operator-sdk from 4.0.5 to 5.0.0.
---
updated-dependencies:
- dependency-name: io.quarkiverse.operatorsdk:quarkus-operator-sdk dependency-type: direct:production update-type: version-update:semver-major ...
Signed-off-by: dependabot[bot] <support@github.com>
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use …
=> Bump quarkus-operator-sdk from 4.0.5 to 5.0.0

build/optaplanner-build-parent/pom.xml, optaplanner-persistence/optaplanner-persistence-jaxb/pom.xml, optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/AbstractScoreJaxbAdapterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/AbstractScoreJpaTest.java, optaplanner-persistence/pom.xml
Related to https://issues.redhat.com/browse/PLANNER-2875.
<details>
<summary>
</summary> …
=> PLANNER-2875 Another pre-migration cleanup

build/optaplanner-distribution-internal/pom.xml, build/optaplanner-distribution-internal/src/main/assembly/assembly-optaplanner-productized.xml, pom.xml
Excludes the `optaplanner-operator` (experimental) module from the productization profile.
<details>
<summary>
</summary> …
=> Disable operator in the productized profile

.ci/jenkins/Jenkinsfile.prod.nightly
https://issues.redhat.com/browse/BXMSPROD-1945
- https://github.com/kiegroup/optaplanner/pull/2503
- https://github.com/kiegroup/kie-ci/pull/1408
Retrieve the product version to be used in nightlies from the original `main` pom.xml, if `PRODUCT_VERSION` and/or `DROOLS_PRODUCT_VERSION` are not provided. In this wai we don't need to maintain these two variables https://github.com/kiegroup/kie-ci/blob/main/job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy#L46 and https://github.com/kiegroup/kie-ci/blob/main/job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy#L48
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other …
=> [BXMSPROD-1945] Fetch main nightly product version from main pom.xml

core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testutil/TestRandom.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfigTest.java, optaplanner-benchmark/src/test/java/org/optaplanner/benchmark/impl/statistic/AbstractSubSingleStatisticTest.java
<details>
<summary>
</summary> …
=> Use AssertJ assertions instead of JUnit

.ci/jenkins/Jenkinsfile.prod.nightly
https://issues.redhat.com/browse/BXMSPROD-1945
- https://github.com/kiegroup/optaplanner/pull/2503
- https://github.com/kiegroup/kie-ci/pull/1408
Export versions fetched from pom because they are needed in the "uploading sources" stage.
<details>
<summary>
</summary>
[build-chain …
=> [BXMSPROD-1945] Export versions fetched from pom

.ci/jenkins/config/main.yaml
No more maintained
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with …
=> Remove branches 8.31.x and 8.32.x

build/optaplanner-build-parent/pom.xml
cherry-pick: https://github.com/kiegroup/optaplanner/pull/2496
Co-authored-by: Jenkins CI <noreply@redhat.com>
<details>
<summary>
</summary> …
=> [8.33.x] [PLANNER-2887] Bump Quarkus version to 2.16.0.Final (#2496)

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.release
https://issues.redhat.com/browse/PLANNER-2889
This will help to release OptaPlanner at the same time as Kogito and Drools in case we don't have the time to release one after the other.
All artifacts will so be staged to JBoss Nexus and then release altogether.
NOTE: This remains an optional parameter
=> PLANNER-2889 Allow to set Drools version in release

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.release
https://issues.redhat.com/browse/PLANNER-2889
This will help to release OptaPlanner at the same time as Kogito and Drools in case we don't have the time to release one after the other.
All artifacts will so be staged to JBoss Nexus and then release altogether.
NOTE: This remains an optional parameter
=> PLANNER-2889 Allow to set Drools version in release (#2516)

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/solution/cloner/FieldAccessingSolutionCloner.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/domain/solution/cloner/AbstractSolutionClonerTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testdata/domain/clone/deepcloning/field/TestdataFieldAnnotatedDeepCloningEntity.java
<details>
<summary>
</summary> …
=> PLANNER-2891 Deep clone support for null in collection-typed map keys

.ci/jenkins/config/main.yaml
<details>
<summary>
</summary> …
=> DSL: remove branch 8.29.x

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/anchor/AnchorVariableDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/index/IndexVariableDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/CollectionInverseVariableDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/SingletonInverseVariableDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/SingletonListInverseVariableDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/supply/AbstractVariableDescriptorBasedDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/common/nearby/NearbyDistanceMatrixDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/PillarDemand.java
`Objects.hashCode(...)` is a varargs method, which means it creates an array of arguments every time it is called. 
This is typically not a problem, but in the case of `Demand` implementations, this actually shows up on the hot path.
This change significantly reduces the number of `Object[]` arrays getting allocated.
=> Reduce memory churn in Demand hashCode

.ci/jenkins/Jenkinsfile.prod.nightly
https://issues.redhat.com/browse/BXMSPROD-1960
- https://github.com/kiegroup/kie-ci/pull/1421
Since Quarkus 2.13.x, core and platform artifacts could be not aligned, in terms of productized builds, for this reason we split versions in:
- `platform.quarkus.bom`
- `quarkus.bom`
<details>
<summary>
</summary> …
=> [BXMSPROD-1960] RHBOP nightly: split quarkus core and platform version

.ci/jenkins/Jenkinsfile.prod.nightly, .ci/jenkins/config/branch.yaml, .github/workflows/full-downstream.yml, .github/workflows/pull_request.yml, .github/workflows/quarkus-snapshot.yml, .github/workflows/rhbop_productized_pull_request.yml, .github/workflows/sonarcloud.yml
https://issues.redhat.com/browse/PLANNER-2892
Related:
- https://github.com/kiegroup/optaplanner/pull/2530
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/840
- https://github.com/kiegroup/optaplanner-quickstarts/pull/497
=> PLANNER-2892 Update default Maven to 3.8.7

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/custom/CustomShadowVariableDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/custom/LegacyCustomShadowVariableDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/custom/PiggybackShadowVariableDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/variable/inverserelation/InverseRelationShadowVariableDescriptor.java
https://issues.redhat.com/browse/PLANNER-2888
<details>
<summary>
</summary> …
=> PLANNER-2888 Add suggestions to fail-fast messages

build/optaplanner-build-parent/pom.xml, optaplanner-examples/pom.xml, optaplanner-persistence/optaplanner-persistence-jackson/pom.xml, optaplanner-test/pom.xml
<details>
<summary>
</summary> …
=> Bump Maven plugin versions

core/optaplanner-core-impl/src/build/revapi-config.json, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/api/score/stream/ConstraintCollectors.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/score/stream/ConstraintCollectorsTest.java
<details>
<summary>
</summary> …
=> PLANNER-2898 Use PECS principle in Constraint Collectors

.ci/jenkins/config/branch.yaml
`main` has to switch to JDK 17 too, as later, quickstarts and the optaweb will migrate to OptaPlanner 9.
https://issues.redhat.com/browse/PLANNER-2880
https://github.com/kiegroup/optaplanner/pull/2542
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build …
=>  PLANNER-2880 Build OptaPlanner with JDK 17

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.nightly, .ci/jenkins/project/Jenkinsfile.post-release, build/8-to-9-migration/migrate.sh
OptaPlanner will release the "8" stream from the `main` branch and the "9" stream from the `9.x` branch.
Optaweb vehicle routing and quickstarts exist only in the "9" stream; the `main`, resp. `development` branch of these repositories depend on OptaPlanner 9.
https://issues.redhat.com/browse/PLANNER-2877
Depends on https://github.com/kiegroup/optaplanner/pull/2542 if the next build of 9.x should not fail.
<details>
<summary>
</summary> …
=> PLANNER-2877 Support 9.x in the CI

build/8-to-9-migration/optaplanner-quarkus3.yaml
There is Alpha3 already; locally the migration still works and tests passed.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple …
=> Upgrade to Quarkus Alpha3 in migration recipe

.github/workflows/optaplanner-9.yml, build/8-to-9-migration/migrate.sh
A simple PR check that migrates to OptaPlanner 9 and tests if everything works after migration. Downstream builds will be handled by the existing checks after quickstarts and the optaweb will have been migrated to 9.
<details>
<summary>
</summary>
[build-chain …
=> Create a migration PR check

.github/workflows/optaplanner-9.yml
<details>
<summary>
</summary> …
=> Rename the optaplanner 9 check

.ci/jenkins/config/branch.yaml
https://issues.redhat.com/browse/PLANNER-2870
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/801
- https://github.com/kiegroup/optaplanner/pull/2550
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/842
- https://github.com/kiegroup/optaplanner-quickstarts/pull/505
- https://github.com/kiegroup/optaplanner-website/pull/569
- [9.x] https://github.com/kiegroup/optaplanner/pull/2558
=> [9.x-dsl-config] PLANNER-2870 Environments should be configurable via branch config

.github/workflows/jenkins-tests-PR.yml
<details>
<summary>
</summary> …
=> DSL check: Ignore branch 9.x

.ci/jenkins/Jenkinsfile.prod.nightly, .ci/project-dependencies-rhbop.yaml, build/optaplanner-build-parent/pom.xml
As required by RHBQ integration: downgrading Drools version to `8.29.0.Final`
- https://issues.redhat.com/browse/RHBOP-38
- https://github.com/kiegroup/drools/pull/4963
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command …
=> [8.33.x] RHBOP-38: Downgrade Drools to 8.29.0.Final

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/config/branch.yaml, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.nightly, .ci/jenkins/project/Jenkinsfile.post-release, build/8-to-9-migration/migrate.sh
https://github.com/kiegroup/optaplanner/pull/2523
https://github.com/kiegroup/optaplanner/pull/2550
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to …
=> [9.x] Backport the CI changes

.ci/jenkins/project/Jenkinsfile.nightly, build/8-to-9-migration/migrate.sh
<details>
<summary>
</summary> …
=> Fix nightly pipeline

.ci/jenkins/config/branch.yaml
Now that quarkus main is Quarkus 3
<details>
<summary>
</summary> …
=> [9.x-dsl-config] Enable Quarkus Main

.ci/buildchain-config.yaml
<details>
<summary>
</summary> …
=> Build Chain Config: Remove clone configuration

build/8-to-9-migration/migrate.sh
<details>
<summary>
</summary> …
=> Fix the migration script

.ci/jenkins/config/branch.yaml
<details>
<summary>
</summary> …
=> Disable quickstarts and optaweb on 9.x

.github/workflows/pull_request.yml
<details>
<summary>
</summary> …
=> Enable GHA on 9.* branches

.ci/jenkins/config/branch.yaml
Backporting https://github.com/kiegroup/optaplanner/pull/2543.
<details>
<summary>
</summary> …
=> [9.x] KOGITO-8377 Merge native and mandrel checks

.ci/jenkins/config/branch.yaml
Due to https://github.com/quarkusio/quarkus/pull/30860
- https://github.com/kiegroup/kogito-pipelines/pull/830
- https://github.com/kiegroup/drools/pull/4982
- https://github.com/kiegroup/optaplanner/pull/2578
=> DSL: Quarkus branch should have version env

.ci/jenkins/Jenkinsfile.setup-branch
<details>
<summary>
</summary> …
=> set optaplanner version in kie-benchmarks

.ci/jenkins/config/branch.yaml
Backporting https://github.com/kiegroup/optaplanner/pull/2578.
<details>
<summary>
</summary> …
=> [8.34.x] DSL: Quarkus branch should have version env

.ci/jenkins/config/branch.yaml
A suppose this should be the version: https://github.com/quarkusio/quarkus/blob/3.0/pom.xml#L16
<details>
<summary>
</summary> …
=> [9.x] DSL: Quarkus branch should have version env

.ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.drools
<details>
<summary>
</summary> …
=> Fix the drools snapshot check

.ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.drools
Backports https://github.com/kiegroup/optaplanner/pull/2584 to `9.x` to see the result in the next nightlies.
<details>
<summary>
</summary> …
=> [9.x] Fix the drools snapshot check

.ci/buildchain-config.yaml
Backports https://github.com/kiegroup/optaplanner/pull/2568.
<details>
<summary>
</summary> …
=> [8.33.x] Build Chain Config: Remove clone configuration

.ci/jenkins/config/branch.yaml
Backporting https://github.com/kiegroup/optaplanner/pull/2575 to fix the seed job and retry the `9.34.0` release.
<details>
<summary>
</summary> …
=> [9.34.x] Disable quickstarts and optaweb on 9.x

.ci/jenkins/Jenkinsfile.deploy
Issue with jdk17 ...
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related …
=> Deploy pipeline: Stage artifacts need jdk11

.ci/jenkins/config/branch.yaml
This should limit the rate limit issues.
Each project (Drools, Kogito. OptaPlanner) will have its own token.
=> DSL: Update GH token credentials id

optaplanner-docs/src/modules/ROOT/pages/planner-introduction/planner-introduction.adoc
The default Java Eclipse IDE doesn't need any extra steps to run the examples anymore.
https://issues.redhat.com/browse/PLANNER-1707
<details>
<summary>
</summary> …
=> PLANNER-1707 Simplify setup for Eclipse

.ci/jenkins/config/branch.yaml
<details>
<summary>
</summary> …
=> DSL branch Config: Revert quarkus credentials

.ci/jenkins/config/branch.yaml
Will be activated again once the GH rate limit issue has been solved
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and …
=> Deactivate quarkus-lts as default PR check

optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/devui-integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/drl-integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/integration-test/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/reflection-integration-test/pom.xml, optaplanner-quarkus-integration/pom.xml
It is not possible to use Javadoc plugin with Quarkus in its current form.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple …
=> Disable Javadoc on everything Quarkus

.ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/project/Jenkinsfile.setup-branch
<details>
<summary>
</summary> …
=> Setup branch job to be stream (8.x/9.x) aware

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/list/kopt/KOptListMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/kopt/KOptListMoveIterator.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/kopt/KOptListMoveSelector.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/kopt/KOptListMoveTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/kopt/TwoOptListMoveTest.java
Most of the PR eliminates the boilerplate test code that calls index variable listener just to initialize the index shadow variables. The `TestdataListEntity.createWithValues()` already does that in a way that does not depend on internal API.
<details>
<summary>
</summary>
[build-chain …
=> Clean up parts of the KOpt related code

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListSwapMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/ListValueNearbyDistanceMatrixDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/NearValueNearbyValueSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/ValueSelectorFactory.java, optaplanner-examples/src/main/resources/org/optaplanner/examples/vehiclerouting/vehicleRoutingSolverConfig.xml
The nearby selector and demand are copies of the existing variants for the list change move. These two new classes need:
- better names
- tests
- deduplication
but all of that will be addressed in the last step when there are all four variants for list change, swap, sublist change and swap move selectors when it's clear what parts of the code are common and what the differences are.
Another significant change is the value selector factory, which now has to handle two different cases when applying nearby selection config.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect …
=> Nearby selection for ListSwapMoveSelector

build/optaplanner-bom/pom.xml
Remove javadoc dependencies from OptaPlanner BOM
https://issues.redhat.com/browse/RHBOP-42
<details>
<summary>
</summary> …
=> [RHBOP-42] Remove javadoc deps references from BOM

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/AbstractConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/constructionheuristic/decider/forager/ConstructionHeuristicForagerConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/constructionheuristic/placer/PooledEntityPlacerConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/exhaustivesearch/ExhaustiveSearchPhaseConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/entity/pillar/PillarSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/MoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/factory/MoveIteratorFactoryConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/factory/MoveListFactoryConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/AbstractPillarMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/PillarChangeMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/PillarSwapMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/chained/KOptMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/chained/SubChainChangeMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/chained/SubChainSwapMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/list/SubListChangeMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/list/SubListSwapMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/value/chained/SubChainSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/partitionedsearch/PartitionedSearchPhaseConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/phase/PhaseConfig.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/config/heuristic/selector/move/generic/PillarSwapMoveSelectorConfigTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/config/localsearch/LocalSearchPhaseConfigTest.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/PlannerBenchmarkConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/ProblemBenchmarksConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/SolverBenchmarkConfig.java, optaplanner-benchmark/src/main/java/org/optaplanner/benchmark/config/report/BenchmarkReportConfig.java
- adds the missing `with()` methods
- enables proper `with()` method chaining on the `Config` classes hierarchy
https://issues.redhat.com/browse/PLANNER-2161
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line …
=> PLANNER-2161 Add missing with methods

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhase.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/constructionheuristic/DefaultConstructionHeuristicPhaseTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/solver/DefaultSolverTest.java
https://issues.redhat.com/browse/PLANNER-1538
<details>
<summary>
</summary> …
=> PLANNER-1538 Update solution only if CH changed it

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/common/accessor/gizmo/GizmoFieldHandler.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/common/accessor/gizmo/GizmoMemberDescriptor.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/common/accessor/gizmo/GizmoMemberHandler.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/domain/common/accessor/gizmo/GizmoMethodHandler.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/domain/solution/cloner/GizmoSolutionClonerTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/GizmoMemberAccessorEntityEnhancer.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/main/java/org/optaplanner/quarkus/deployment/OptaPlannerProcessor.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/OptaPlannerProcessorPrivateConstructorTest.java, optaplanner-quarkus-integration/optaplanner-quarkus/deployment/src/test/java/org/optaplanner/quarkus/testdata/gizmo/PrivateNoArgsConstructorSolution.java
This PR cleans up the logic in Gizmo accessors,
removing instanceof checks during read and write operations.
This should make the code read better.
=> Clean up Gizmo accessors

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/common/nearby/NearbySelectionConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/entity/EntitySelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/DestinationSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/ValueSelectorFactory.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/config/heuristic/selector/common/nearby/NearbySelectionConfigTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/entity/EntitySelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/DestinationSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/value/ValueSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/testdata/domain/list/TestdataListUtils.java
I wanted to explore the possibility to introduce entity/value/subList/destination factory-tailored nearby config classes to simplify the validation. Unfortunately, there is no backward-compatible way to do it due to how `@XmlType(propOrder)` behaves (too complicated to describe here).
So I reverted to the current approach with only `NearbySelectionConfig` having all possible origin selector properties and I completed exception messages and added coverage.
=> Nearby config tests

optaplanner-examples/src/main/resources/org/optaplanner/examples/vehiclerouting/optional/benchmark/vehicleRoutingBenchmarkConfig.xml
This is still not identical to the benchmark config before the list variable because we don't have a replacement for the TailChainSwapMoveSelector but it's getting close.
I think we can either:
- A) introduce ListTailSwapMoveSelector
- B) add nearby selection support to KOptListMoveSelector and replace TailChainSwapMoveSelector with a combination of sublist swap and k-opt moves (with nearby selection).
=> Enable nearby selection in VRP benchmark config

build/optaplanner-build-parent/pom.xml, optaplanner-operator/pom.xml, optaplanner-quarkus-integration/pom.xml
It's better to deploy javadoc jars to Maven Central for optaplanner-quarkus too than to skip it.
Workaround for MJAVADOC-747.
=> Generate Javadoc jars for optaplanner-quarkus etc too

optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/integration-test/src/test/java/org/optaplanner/quarkus/benchmark/it/OptaPlannerBenchmarkTestResourceIT.java, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/integration-test/src/test/java/org/optaplanner/quarkus/jackson/it/OptaPlannerTestResourceIT.java, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/integration-test/src/test/java/org/optaplanner/quarkus/jsonb/it/OptaPlannerTestResourceIT.java, optaplanner-quarkus-integration/optaplanner-quarkus/drl-integration-test/src/test/java/org/optaplanner/quarkus/drl/it/OptaPlannerTestResourceIT.java, optaplanner-quarkus-integration/optaplanner-quarkus/integration-test/src/test/java/org/optaplanner/quarkus/it/OptaPlannerTestResourceIT.java, optaplanner-quarkus-integration/optaplanner-quarkus/reflection-integration-test/src/test/java/org/optaplanner/quarkus/it/reflection/OptaPlannerTestResourceIT.java
This annotation has been already replaced in quickstarts.
<details>
<summary>
</summary> …
=> Replace the deprecated NativeImageTest

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/list/SubListChangeMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/list/SubListSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/config/heuristic/selector/move/generic/list/SubListSwapMoveSelectorConfig.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/RandomSubListChangeMoveSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/RandomSubListSwapMoveSelector.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListChangeMoveSelectorFactory.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListConfigUtil.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListSwapMoveSelectorFactory.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListChangeMoveSelectorFactoryTest.java, core/optaplanner-core-impl/src/test/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/SubListSwapMoveSelectorFactoryTest.java
See `SubListConfigUtil` Javadoc.
=> Deprecate minimumSubListSize and maximumSubListSize on move selector configs

build/optaplanner-build-parent/pom.xml, core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/OptaPlannerRuleEventListener.java, core/optaplanner-constraint-drl/src/main/java/org/optaplanner/constraint/drl/holder/AbstractScoreHolder.java, core/optaplanner-constraint-drl/src/test/java/org/optaplanner/constraint/drl/holder/AbstractScoreHolderTest.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/OptaPlannerRuleEventListener.java, core/optaplanner-constraint-streams-drools/src/main/java/org/optaplanner/constraint/streams/drools/common/AbstractRuleContext.java
Cherry-pick the https://github.com/kiegroup/optaplanner/commit/e83266718d52052ebd967ddab3d5efd95d49c65b.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need …
=> DROOLS-7347 Adapt to changes in Drools internals (#2679)

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/move/generic/list/kopt/TwoOptListMove.java, optaplanner-docs/src/modules/ROOT/pages/move-and-neighborhood-selection/move-and-neighborhood-selection.adoc
<details>
<summary>
</summary> …
=> Add k-opt move to overview and fix a typo in toString()

.ci/jenkins/Jenkinsfile.prod.nightly
Fixes nightly updated in https://github.com/kiegroup/optaplanner/pull/2717 double escaping the `$` sign in the file definition in order to let it ignored by jenkins.
https://issues.redhat.com/browse/BXMSPROD-1983
- https://github.com/kiegroup/optaplanner/pull/2717
<details>
<summary>
</summary>
[build-chain …
=> [BXMSPROD-1983] double escape dollar sign

core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/common/nearby/NearbyDistanceMatrixDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/list/nearby/ListNearbyDistanceMatrixDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/list/nearby/SubListNearbyDistanceMatrixDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/list/nearby/SubListNearbySubListMatrixDemand.java, core/optaplanner-core-impl/src/main/java/org/optaplanner/core/impl/heuristic/selector/value/nearby/ListValueNearbyDistanceMatrixDemand.java
Expand distance matrix demand Javadoc and clarify what demands have in common and how they differ.
There are 4 kinds of distance matrices classified by the types of the origins and destinations they contain:
- (1) `Entity->Entities`: supplied to `NearbyDistanceMatrixDemand` with child entity selector
- (2) `Entity->Values`: supplied to `NearbyDistanceMatrixDemand` with child value selector
- (3) `Value->mix of Entities and Values`: supplied to:
- `ListNearbyDistanceMatrixDemand` used by `NearValueNearbyDestinationSelector` to produce nearby enabled `ListChangeMove`s.
- `SubListNearbyDistanceMatrixDemand` used by `NearSubListNearbyDestinationSelector` to produce nearby enabled `SubListChangeMove`s.
- (4) `Value->Values`: supplied to:
- `ListValueNearbyDistanceMatrixDemand` used by …
=> Improved distance matrix demand Javadoc

.ci/jenkins/Jenkinsfile.prod.nightly, .ci/nightly-build-config.yaml, .ci/nightly-project-dependencies.yaml, .ci/project-dependencies-rhbop.yaml
This PR aims to fix two bugs in the nightly that have been introduced by the build-chain migration (https://github.com/kiegroup/optaplanner/pull/2717).
- Moved Quarkus bom dependencies alignment for Drools here, in this way we can keep the pnc build config as close as possible to the prod one.
- Exported project versions during the Jenkins pipeline (needed additional PR https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/269) since those exported from build-chain were not visible outside.
- Added `; set -o pipefail` on every command in order to ensure that the script returns failure when mvn command fails - this was not true before as the exit code was the one returned by `tee` cmd.
- When building `main` branch, Drools must be `main-integration-quarkus-lts` as there are …
=> Fix RHBOP Nightly

build/8-to-9-migration/optaplanner-quarkus3.yaml, optaplanner-migration/src/main/resources/META-INF/rewrite/ToLatest9.yml, optaplanner-quarkus-integration/optaplanner-quarkus-benchmark/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jackson/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus-jsonb/runtime/pom.xml, optaplanner-quarkus-integration/optaplanner-quarkus/runtime/pom.xml, optaplanner-quarkus-integration/pom.xml
The `quarkus-extension-maven-plugin` replaces the `quarkus-bootstrap-maven-plugin` and is available since Quarkus `2.10.1.Final`; see https://central.sonatype.com/artifact/io.quarkus/quarkus-extension-maven-plugin/3.0.0.CR1.
https://issues.redhat.com/browse/PLANNER-2918
<details>
<summary>
</summary>
[build-chain …
=> PLANNER-2918 - Upgrade Quarkus 3 to 3.0.0.CR1

.ci/jenkins/Jenkinsfile.prod.nightly
###JIRA: https://issues.redhat.com/browse/BXMSPROD-2011
Migrate to `rhba-prod` service account with custom keytab.
###Referenced pull requests:
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/270 (provide additional `withKerberos` method)
- https://github.com/kiegroup/kogito-pipelines/pull/931
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of …
=> [BXMSPROD-2011] Migrate to rhba-prod service account

.ci/jenkins/config/branch.yaml
<details>
<summary>
</summary> …
=> [8.37.x] Disable `quarkus-branch` checks

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/config/branch.yaml, .ci/jenkins/project/Jenkinsfile.post-release, .ci/jenkins/project/Jenkinsfile.setup-branch
https://issues.redhat.com/browse/PLANNER-2902
https://github.com/kiegroup/optaplanner/pull/2765
https://github.com/kiegroup/optaplanner-quickstarts/pull/549
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally …
=> PLANNER-2902 Migrate quickstarts to OptaPlanner 9

.ci/jenkins/config/branch.yaml
https://issues.redhat.com/browse/PLANNER-2902
https://github.com/kiegroup/optaplanner/pull/2766
https://github.com/kiegroup/optaplanner-quickstarts/pull/549
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally …
=> [9.x-dsl-config] PLANNER-2902 Migrate quickstarts to OptaPlanner 9

.ci/buildchain-config.yaml, .ci/jenkins/dsl/jobs.groovy
Merge only after quickstarts are migrated to Quarkus 3.
https://issues.redhat.com/browse/PLANNER-2896
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to …
=> PLANNER-2896 Migrate in upstream build

.ci/buildchain-config.yaml, .ci/jenkins/dsl/jobs.groovy
Backporting https://github.com/kiegroup/optaplanner/pull/2548.
<details>
<summary>
</summary> …
=> [9.x] PLANNER-2896 Migrate in upstream build

.ci/jenkins/dsl/jobs.groovy
<details>
<summary>
</summary> …
=> Migrate for a non-release branch

.ci/jenkins/dsl/jobs.groovy
<details>
<summary>
</summary> …
=> [9.x] update migration condition

.ci/buildchain-config.yaml, .github/workflows/optaplanner-9.yml, build/8-to-9-migration/migrate.sh
Allows to skip git commit in CI where it's not needed or even wanted.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and …
=> Fine-tune the migration scipt

.ci/jenkins/Jenkinsfile.deploy
A quick fix to exclude the kubernetes quickstart from version upgrade checks.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple …
=> Exclude the kubernetes directory from assertions

build/8-to-9-migration/optaplanner-quarkus3.yaml, build/optaplanner-build-parent/pom.xml
Backports https://github.com/kiegroup/optaplanner/pull/2786. The build-parent changes are what the updated recipe would do over night.
https://github.com/kiegroup/optaplanner/pull/2786
https://github.com/kiegroup/optaplanner/pull/2789
https://github.com/kiegroup/optaplanner/pull/2790
https://github.com/kiegroup/optaplanner-quickstarts/pull/556
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …
=> [9.x] Bump Freemarker and Spring Boot

build/8-to-9-migration/optaplanner-quarkus3.yaml, build/optaplanner-build-parent/pom.xml
Backports https://github.com/kiegroup/optaplanner/pull/2786. The build-parent changes are what the updated recipe would do over night.
https://github.com/kiegroup/optaplanner/pull/2786
https://github.com/kiegroup/optaplanner/pull/2789
https://github.com/kiegroup/optaplanner/pull/2790
https://github.com/kiegroup/optaplanner-quickstarts/pull/556
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …
=> [9.37.x] Bump Freemarker and Spring Boot

.ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/config/branch.yaml, .ci/jenkins/config/main.yaml
[KOGITO-8994](https://issues.redhat.com/browse/KOGITO-8994)
[kie-benchmarks](https://github.com/kiegroup/kie-benchmarks/pull/231)
[optaplanner](https://github.com/kiegroup/optaplanner/pull/2782)
[drools](https://github.com/kiegroup/drools/pull/5183)
<details>
<summary>
</summary>
[build-chain …
=> KOGITO-8994: optaplanner version update in kie-benchmarks

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/config/branch.yaml, .ci/jenkins/project/Jenkinsfile.post-release, .ci/jenkins/project/Jenkinsfile.setup-branch
Version 8 quickstarts need to keep being released for the purpose of product releases.
For every 8.? release of OptaPlanner:
- there has to be the same release branch for quickstarts, too
- the OptaPlanner distribution (finalized here in quickstarts) has to be uploaded
- the OptaPlanner version on the `optaplanner-quickstarts/8.x` branch has to be upgraded
Effectively, we maintain two release streams for quickstart: from the `development` branch and from the `8.x` branch with the following differences:
- the `stable` branch will ever point only to the latest `9.?.x` release branch
- there is no sync-up between `development` and `8.x`; the `8.x` branch will not receive further changes apart from the newer versions of OptaPlanner and related necessary adjustments …
=> PLANNER-2922 Enable quickstarts 8.x release

.ci/jenkins/project/Jenkinsfile.post-release
<details>
<summary>
</summary> …
=> Correct post-release job for Stream 8

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, build/8-to-9-migration/migrate.sh, build/8-to-9-migration/optaplanner-quarkus3.yaml
Enables the optaplanner-operator in the migration and release automation.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories …
=> Migrate the operator to Quarkus 3

.ci/jenkins/config/branch.yaml, .ci/jenkins/config/main.yaml
- https://issues.redhat.com/browse/BXMSPROD-2019
- https://github.com/kiegroup/kogito-pipelines/pull/967
- https://github.com/kiegroup/optaplanner/pull/2845
- https://github.com/kiegroup/drools/pull/5209
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build …
=> [BXMSPROD-2019] Setup automated prod branch creation

.ci/jenkins/config/branch.yaml
…king
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you …
=> Include optaplanner-website in prod repos to keep seed job working

.ci/nightly-project-dependencies.yaml, .ci/project-dependencies-rhbop.yaml
https://issues.redhat.com/browse/BXMSPROD-2056
* https://github.com/kiegroup/kie-ci/pull/1508
* https://github.com/kiegroup/optaplanner/pull/2852
<details>
<summary>
</summary> …
=> [RHBOP] Mapping OP 8.38 to Drools 8.29

.github/workflows/pull_request.yml
Thank you for submitting this pull request
JIRA:
https://issues.redhat.com/browse/BXMSPROD-2067
<details>
<summary>
</summary> …
=> [7.67.x][BXMSPROD-2067] Fix PR workflow concurrency group (#2882)

.ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.setup-branch
Needed to allow invoking setup-branch without deploying artifacts on Nexus
- https://issues.redhat.com/browse/BXMSPROD-2019
- https://github.com/kiegroup/kogito-pipelines/pull/967
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used …
=> Made deploy artifacts on setup-branch configurable

.ci/jenkins/project/Jenkinsfile.setup-branch
<details>
<summary>
</summary> …
=> [BXMSPROD-2019] fix setup branch when condition

.ci/jenkins/Jenkinsfile.prod.nightly
I noticed that `main` nightly occasionally failed in the last runs because it is started in jenkins nodes where `podman` is installed and `docker` is not - this fix ensure to start the nightly on a node that has `docker` correctly installed in it.
<details>
<summary>
</summary>
[build-chain …
=> nightly: ensure docker exists in the jenkins node

.ci/jenkins/Jenkinsfile.promote, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.release, .ci/jenkins/project/Jenkinsfile.setup-branch
https://issues.redhat.com/browse/KOGITO-9676
=> KOGITO-9676 Promote calls setup-branch

.ci/jenkins/config/branch.yaml
JIRA: [BXMSPROD-2104](https://issues.redhat.com/browse/BXMSPROD-2104)
related URLs:
* https://github.com/kiegroup/kogito-pipelines/pull/1038
* https://github.com/kiegroup/drools/pull/5468
* https://github.com/kiegroup/optaplanner/pull/2935
<details>
<summary>
</summary>
[build-chain …
=> BXMSPROD-2104: new parameter for JDK version in SonarCloud  analysis

.ci/jenkins/dsl/jobs.groovy, build/optaplanner-build-parent/pom.xml
https://github.com/kiegroup/kie-issues/issues/522
- https://github.com/kiegroup/optaplanner-quickstarts/pull/596
- https://github.com/kiegroup/optaplanner/pull/2943
=> [main] [kie-issues#522] Bump Quarkus version to 2.16.10.Final

optaplanner-test/src/main/java/org/optaplanner/test/api/solver/change/MockProblemChangeDirector.java
- NPE when using lookUpWorkingObject for non-registered object.
- Believe intention is that this should return Optional.empty(), which isn't working without ofNullable.
- Change to Optional.ofNullable since lookUpTable shouldn't contain object.
=> fix NPE for Optional lookup in MockProblemChangeDirector

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/Jenkinsfile.turtle, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.drools, .ci/jenkins/project/Jenkinsfile.nightly, .ci/jenkins/project/Jenkinsfile.post-release, .ci/jenkins/project/Jenkinsfile.release, .ci/jenkins/project/Jenkinsfile.setup-branch
- https://github.com/kiegroup/kogito-runtimes/pull/3206
- https://github.com/kiegroup/kogito-apps/pull/1876
- https://github.com/kiegroup/kogito-examples/pull/1790
- https://github.com/kiegroup/kogito-images/pull/1697
- https://github.com/kiegroup/kogito-operator/pull/1527
- https://github.com/kiegroup/kogito-serverless-operator/pull/249
- https://github.com/kiegroup/drools/pull/5518
- https://github.com/asf-transfer/optaplanner/pull/2967
=> [apache_migration] Update pipelines

.ci/jenkins/Jenkinsfile, .ci/jenkins/dsl/jobs.groovy
Enabling a simplified PR check, which repeatedly (each 5 minutes) polls for new PRs coming from both the origin itself and forks.
Full ensemble:
https://github.com/kiegroup/kogito-runtimes/pull/3224
https://github.com/kiegroup/kogito-apps/pull/1879
https://github.com/kiegroup/kogito-examples/pull/1808
https://github.com/kiegroup/drools/pull/5523
https://github.com/kiegroup/kogito-images/pull/1700
https://github.com/kiegroup/optaplanner-quickstarts/pull/602
https://github.com/apache/incubator-kie-optaplanner/pull/2975
=> PR multibranchPipelineJob

.ci/jenkins/config/branch.yaml
Removing older branch override, because changes are currently  in apache_migration branches only.
=> Remove branch override for quickstarts from branch config

.ci/jenkins/Jenkinsfile
kiegroup/kie-issues#587
Aborting previous builds when new one is triggered (PR branch push or target branch push).
Full ensemble:
apache/incubator-kie-drools#5535
apache/incubator-kie-kogito-runtimes#3237
apache/incubator-kie-kogito-apps#1887
apache/incubator-kie-kogito-examples#1812
apache/incubator-kie-optaplanner#2988
apache/incubator-kie-optaplanner-quickstarts#608
=> kie-issues#587 abort stale builds

.ci/buildchain-config-pr-cdb.yaml, .ci/jenkins/Jenkinsfile
apache/incubator-kie-issues#593
Adding an extra Compile Downstream build-chain configuration for PRs, which is a copy of existing + definition of downstream scripts.
Reason is not to break existing configuration of other pipelines that use the original build-chain configuration - needs to be reviewed when I have better grasp of all affected places, scoping to jenkins PR check for now.
=> kie-issues#593: switch to compile downstream in Jenkins

.ci/buildchain-config-pr-cdb.yaml
apache/incubator-kie-issues#593
For the chain to successfully complete, the maven builds should invoke install goal instead of compile.
This is needed due to dependent projects down the chain that would miss the artifacts if they were not installed.
=> kie-issues#593: use install goal for downstream projects

.ci/jenkins/Jenkinsfile
First task in regards to apache/incubator-kie-issues#599
Disabling sonar checks, as it currently breaks the build due to bug and misconfiguration.
=> kie-issues#599: disable sonar in PR checks

.ci/jenkins/config/branch.yaml
apache/incubator-kie-issues#641
Enabling triggers for jenkins pipelines.
Together with that disabling deploy, so that nightly builds (now being triggered) don't fail due to non-configured nexus deployment.
=> kie-issues#641: enable triggers for jenkins pipelines

.ci/buildchain-project-dependencies.yaml
apache/incubator-kie-issues#654
Simplifying build-chain project configuration, so that there's a direct mapping between matching branches in optaplanner and optaplanner-quickstarts.
Does remove the need for MIGRATE_TO_9 env variable and handling.
Should be considered as unblocking the non-working PR checks at the moment, with assumption this logic would be brought back when needed.
=> kie-issues#654: simplify buildchain configuration

build/optaplanner-build-parent/pom.xml, core/optaplanner-core-impl/pom.xml, optaplanner-benchmark/pom.xml, optaplanner-docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc, optaplanner-examples/pom.xml
See https://cwiki.apache.org/confluence/display/MAVEN/Maven+3.x+Compatibility+Notes#Maven3.xCompatibilityNotes-AutomaticPluginVersionResolution
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …
=> Remove warning for missing plugin version

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/dsl/jobs.groovy
apache/incubator-kie-issues#655
Fixing Jenkinsfile.deploy for use in ASF Jenkins.
Main issue was with the shared jenkins library, where used Groovy methods need allowing in script security. To unblock, rewriting using different "path" in library code which is not affected.
Also adjusting to reflect DISABLE_DEPLOY configuration property - to be able to run nightly job without actual push to repos.
Also introducing distinction between repository and folder names in Jenkinsfile, for better readability.
=> kie-issues#655: fix Jenkinsfile.deploy

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/Jenkinsfile.turtle, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.drools, .ci/jenkins/project/Jenkinsfile.post-release, .ci/jenkins/project/Jenkinsfile.release
After #3009 
apache/incubator-kie-issues#667
Fixing cleanup and settings.xml pipeline configuration to work correctly in ASF Jenkins.
* Deferred wipeout was causing issues when invoked in early stages
* Docker cleanup can't be done since the overall build is in docker container that uses the docker.sock from the host - it would attempt to erase itself.
* withSettingsXmlId shared library method does imply usage of a prohibited groovy method, thus replacing with explicit configFileProvider and passing as withSettingsXmlFile goes around that part of code. 
Complete list:
apache/incubator-kie-kogito-pipelines#1113
apache/incubator-kie-kogito-runtimes#3272
apache/incubator-kie-kogito-apps#1909
apache/incubator-kie-kogito-examples#1820
apache/incubator-kie-drools#5572 …
=> kie-issues#667: fix cleanup and settingsXml handling

.ci/jenkins/config/branch.yaml
apache/incubator-kie-issues#710
In preparation for switching the kogito-ci-build to ubuntu based, setting explicitly the tag of the most recent tag before the switch.
This will allow to separate change of image dockerfile and necessary change of docker arguments for the new image into 2 separate PRs without introducing a CI disruption.
apache/incubator-kie-kogito-pipelines#1124
apache/incubator-kie-drools#5588
apache/incubator-kie-optaplanner#3023
=> kie-issues#710: freeze kogito-ci-build image tag

.ci/jenkins/config/branch.yaml
apache/incubator-kie-issues#710
Switching configuration to use docker in docker image variant now available under main-latest tag.
Follows-up on: apache/incubator-kie-kogito-pipelines#1125
Part of ensemble:
apache/incubator-kie-kogito-pipelines#1127
apache/incubator-kie-drools#5593
apache/incubator-kie-optaplanner#3026
=> kie-issues#710: configure dind image

.ci/jenkins/project/Jenkinsfile.nightly
https://github.com/apache/incubator-kie-issues/issues/655
adjust mapping of optaplanner-quickstarts branches to the upstream ones so the correct one is used.
=> [incubator-kie-issues#655] Build optaplanner quickstarts from correct branch

build/optaplanner-build-parent/pom.xml
Fixes:
* apache/incubator-kie-issues#742
To have all projects in sync, upgrading jacoco maven plugin, even though it does not have problems on JDK17, unlike the rest of our projects.
=> kie-issues#742: upgrade jacoco maven plugin to 0.8.11

build/optaplanner-build-parent/pom.xml
<details>
<summary>
</summary> …
=> Optaplanner depends on Drools 999-SNAPSHOT

pom.xml
addded timestamp
added maven-artifact-plugin
Still failing with
`mvn artifact:check-buildplan`
See
https://github.com/mojohaus/jaxb2-maven-plugin/issues/296#issuecomment-1907439163
https://github.com/mojohaus/jaxb2-maven-plugin/pull/243
<details>
<summary>
</summary>
[build-chain …
=> Reproducible build

core/optaplanner-core-impl/src/test/java/org/optaplanner/core/api/solver/SolverManagerTest.java
Fixes a flaky test detected in #3058.
<details>
<summary>
</summary> …
=> Fix flaky SolverManagerTest

build/optaplanner-build-parent/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/pom.xml, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/api/score/buildin/bendable/BendableScoreConverterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/api/score/buildin/bendablebigdecimal/BendableBigDecimalScoreConverterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/api/score/buildin/bendablelong/BendableLongScoreConverterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/api/score/buildin/hardmediumsoft/HardMediumSoftScoreConverterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/api/score/buildin/hardmediumsoftbigdecimal/HardMediumSoftBigDecimalScoreConverterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/api/score/buildin/hardmediumsoftlong/HardMediumSoftLongScoreConverterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/api/score/buildin/hardsoft/HardSoftScoreConverterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/api/score/buildin/hardsoftbigdecimal/HardSoftBigDecimalScoreConverterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/api/score/buildin/hardsoftlong/HardSoftLongScoreConverterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/api/score/buildin/simple/SimpleScoreConverterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/api/score/buildin/simplebigdecimal/SimpleBigDecimalScoreConverterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/api/score/buildin/simplelong/SimpleLongScoreConverterTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/java/org/optaplanner/persistence/jpa/impl/AbstractScoreJpaTest.java, optaplanner-persistence/optaplanner-persistence-jpa/src/test/resources/META-INF/persistence.xml
Same as https://github.com/apache/incubator-kie-drools/pull/5764 but for OptaPlanner. The goal is to get rid of a transitive dependency on Hibernate, which is now licensed under LGPL 2.1, which is unwanted for ASF releases.
<details>
<summary>
</summary>
[build-chain …
=> Replace QuarkusTest and Hibernate with OpenJPA

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/dsl/jobs.groovy
Finalize
* apache/incubator-kie-issues#1123
Part of PR group (not dependent):
* apache/incubator-kie-kogito-pipelines#1195
* apache/incubator-kie-drools#5942
* apache/incubator-kie-kogito-runtimes#3517
* apache/incubator-kie-kogito-apps#2051
* apache/incubator-kie-kogito-examples#1919
* apache/incubator-kie-optaplanner#3086
=> [kie-issues#1123] adjust deploy operation

.ci/jenkins/project/Jenkinsfile.setup-branch
Part of
* apache/incubator-kie-issues#1237
Adjusts the snapshot version changes to happen only in new branch when branching, not in main.
Ensemble:
* apache/incubator-kie-kogito-pipelines#1201
* apache/incubator-kie-drools#5967
* apache/incubator-kie-optaplanner#3089
* apache/incubator-kie-kogito-runtimes#3527
* apache/incubator-kie-kogito-apps#2059
* apache/incubator-kie-kogito-examples#1925
* apache/incubator-kie-optaplanner-quickstarts#630
=> kie-issues#1237: stay on x.y.999-SNAPSHOT in release branches

.ci/jenkins/config/main.yaml
To properly fix
* apache/incubator-kie-issues#1255
Adding jenkins agent docker configuration to .ci/config/main.yaml
Also in:
* apache/incubator-kie-kogito-pipelines#1205
* apache/incubator-kie-drools#5971
* apache/incubator-kie-optaplanner#3094
There are jobs already in main pipeline (either root folder or defined in dsl/seed_job_branch.groovy file), which didn't have access to jenkins agent docker image and args configuration from branch.yaml - because that one is loaded only in Jenkinsfile.seed.branch - which did not make it possible to reference these values already in dsl/seed_job_branch.groovy.
So adding the agent docker configuration into main.yaml and loading already in Jenkinsfile.seed.main, so that all DSL jobs are able to use this value loaded from particular branch (except …
=> kie-issues#1255: agent docker config in main pipeline

.ci/jenkins/Jenkinsfile.promote, .ci/jenkins/config/branch.yaml, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/scripts/imageUtils.groovy
Fixes:
* apache/incubator-kie-issues#1213
Depends on `docker.io/apache/incubator-kie-kogito-ci-build:main-latest` being released first (after #1197 is merged and pipeline execution succeeds).
Part of PR group:
* apache/incubator-kie-kogito-pipelines#1198
* apache/incubator-kie-drools#5952
* apache/incubator-kie-optaplanner#3087
=> kie-issues#1213: configure for dockerhub registry

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/config/branch.yaml, .ci/jenkins/config/main.yaml
Part of: https://github.com/apache/incubator-kie-issues/issues/1387
=> kie-issues#1387: Adjust pipelines to use the gpg key provided by Apache to sign the artifacts

.ci/buildchain-project-dependencies.yaml, .ci/jenkins/config/branch.yaml, .ci/jenkins/project/Jenkinsfile.nightly
<details>
<summary>
</summary> …
=> Change buildchain project dependencies

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.release
Part of: https://github.com/apache/incubator-kie-issues/issues/1397
=> [10.0.x] kie-issues#1397: Adjust release pipelines for the Apache 10 release

.ci/jenkins/Jenkinsfile.deploy
This PR adds the `productized` property to the build command during a release to ensure reproducible builds.
=> [10.0.x] Add productized maven property to the build command for the release job

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/config/branch.yaml, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/project/Jenkinsfile.release, optaplanner-operator/pom.xml
Cherry-pick of the changes we made in the 10.0.x branch for the Apache 10 release:
- 9a378d84b1211fa39c67ba43b43c2f6fbaa30a95
- aa73f300292c17a3e173b9c9f534bac822f44488
- 83c7027b863349e493bc778c127e94735db11bf9
- d5e15d6ea30b05d40b01bc6267d7a4889d3a3c43
- 509f4ef0e76784651c77c136112f04f76b6746e7
- 4f7456a1479380bc7c4a0685bb6e78d2597d967f
Depends on: https://github.com/apache/incubator-kie-kogito-pipelines/pull/1245
=> NO-ISSUE: Jenkins jobs updates and fixes for Apache 10 release

.ci/jenkins/config/branch.yaml, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh
Adjusting branch.yaml configuration to split maven related configurations for nightly and release.
Part of ensemble:
- apache/incubator-kie-kogito-pipelines#1254
- apache/incubator-kie-drools#6130
- apache/incubator-kie-optaplanner#3133
- apache/incubator-kie-optaplanner-quickstarts#634
- apache/incubator-kie-kogito-runtimes#3737
- apache/incubator-kie-kogito-apps#2119
- apache/incubator-kie-kogito-examples#2025
The scope of changes:
- maven settings.xml reference (config file id pointing at pre-defined config file in jenkins)
- artifacts upload repository
- url - mostly informational, should not be needed for deploy itself (inheriting that configuration from apache parent)
- credentials-id - the important part, allowing to configure different credentials for nightly and release.
Notes:
- …
=> [10.0.x] CI duplicate maven configuration entries

.ci/jenkins/config/branch.yaml, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh
Adjusting branch.yaml configuration to split maven related configurations for nightly and release.
Part of ensemble:
- apache/incubator-kie-kogito-pipelines#1259
- apache/incubator-kie-drools#6132
- apache/incubator-kie-optaplanner#3135
- apache/incubator-kie-optaplanner-quickstarts#635
- apache/incubator-kie-kogito-runtimes#3738
- apache/incubator-kie-kogito-apps#2121
- apache/incubator-kie-kogito-examples#2026
The scope of changes:
- maven settings.xml reference (config file id pointing at pre-defined config file in jenkins)
- artifacts upload repository
- url - mostly informational, should not be needed for deploy itself (inheriting that configuration from apache parent)
- credentials-id - the important part, allowing to configure different credentials for nightly and release.
Notes:
- …
=> CI duplicate maven configuration entries

build/optaplanner-build-parent/pom.xml, core/optaplanner-core/pom.xml, core/pom.xml
Resolves https://github.com/apache/incubator-kie-issues/issues/1561
After discussion with Luca, we decided to remove the productized profile, as it is not needed anymore at the place where the optaplanner-constraint-streams-bavet is handled with it.
=> [kie-issues#1561] Remove productized profile for filtering out optaplanner-constraint-streams-bavet module.

build/optaplanner-build-parent/pom.xml
Unify netty-handler and netty-common versions to 4.1.118-Final
Relates to https://github.com/apache/incubator-kie-tools/pull/2947
<details>
<summary>
</summary> …
=> [NO_ISSUE] Fix netty-related CVE. Unify versions to 4.1.118.Final

build/optaplanner-build-parent/pom.xml
Update the version of apache poi to fix the [CVE-2025-31672](https://github.com/advisories/GHSA-gmg8-593g-7mv3)
=> [NO-ISSUE] Bump apache POI
